from django.urls import path

from apps.content.views import (
    AreaListView,
    LevelCreateView,
    LevelDeleteView,
    LevelListView,
    LevelUpdateView,
    ModuleCreateView,
    ModuleDeleteView,
    ModuleListView,
    ModuleUpdateView,
    ResourceCreateView,
    ResourceDeleteView,
    ResourceDetailView,
    ResourceListView,
    ResourceUpdateView,
    SubjectCreateView,
    SubjectDeleteView,
    SubjectListView,
    SubjectUpdateView,
    TopicCreateView,
    TopicDeleteView,
    TopicListView,
    TopicUpdateView,
    module_resource_add,
    module_resource_list,
    module_resource_remove,
    resource_options,
    topic_options_by_subject,
)

urlpatterns = [
    path("areas/", AreaListView.as_view()),
    path("levels/", LevelListView.as_view()),
    path("levels/create/", LevelCreateView.as_view()),
    path("levels/<int:pk>/edit/", LevelUpdateView.as_view()),
    path("levels/<int:pk>/delete/", LevelDeleteView.as_view()),
    path("modules/", ModuleListView.as_view()),
    path("modules/create/", ModuleCreateView.as_view()),
    path("modules/<int:pk>/edit/", ModuleUpdateView.as_view()),
    path("modules/<int:pk>/delete/", ModuleDeleteView.as_view()),
    path("modules/<int:module_id>/resources/", module_resource_list),
    path("modules/<int:module_id>/resources/add/", module_resource_add),
    path("modules/<int:module_id>/resources/remove/", module_resource_remove),
    path("resources/", ResourceListView.as_view()),
    path("resources/create/", ResourceCreateView.as_view()),
    path("resources/<int:pk>/", ResourceDetailView.as_view()),
    path("resources/<int:pk>/edit/", ResourceUpdateView.as_view()),
    path("resources/<int:pk>/delete/", ResourceDeleteView.as_view()),
    path("resources/options/", resource_options),
    path("subjects/", SubjectListView.as_view()),
    path("subjects/create/", SubjectCreateView.as_view()),
    path("subjects/<int:pk>/edit/", SubjectUpdateView.as_view()),
    path("subjects/<int:pk>/delete/", SubjectDeleteView.as_view()),
    path("topics/", TopicListView.as_view()),
    path("topics/create/", TopicCreateView.as_view()),
    path("topics/<int:pk>/edit/", TopicUpdateView.as_view()),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view()),
    path("topics/options/", topic_options_by_subject),
]
