from django.urls import path
from django.views.generic import RedirectView

from apps.content.views.legacy_redirects import (
    legacy_level_detail_redirect,
    legacy_level_delete_redirect,
    legacy_level_update_redirect,
    legacy_module_delete_redirect,
    legacy_module_resource_add_redirect,
    legacy_module_resource_remove_redirect,
    legacy_module_resources_redirect,
    legacy_module_update_redirect,
    legacy_resource_delete_redirect,
    legacy_resource_detail_redirect,
    legacy_resource_update_redirect,
    legacy_subject_delete_redirect,
    legacy_subject_detail_redirect,
    legacy_subject_update_redirect,
    legacy_topic_delete_redirect,
    legacy_topic_update_redirect,
)

urlpatterns = [
    path("areas/", RedirectView.as_view(pattern_name="content:area_list", permanent=True)),
    path("levels/", RedirectView.as_view(pattern_name="content:level_list", permanent=True)),
    path("levels/create/", RedirectView.as_view(pattern_name="content:level_create", permanent=True)),
    path("levels/<int:pk>/", legacy_level_detail_redirect),
    path("levels/<int:pk>/edit/", legacy_level_update_redirect),
    path("levels/<int:pk>/delete/", legacy_level_delete_redirect),
    path("modules/", RedirectView.as_view(pattern_name="content:module_list", permanent=True)),
    path("modules/create/", RedirectView.as_view(pattern_name="content:module_create", permanent=True)),
    path("modules/<int:pk>/edit/", legacy_module_update_redirect),
    path("modules/<int:pk>/delete/", legacy_module_delete_redirect),
    path("modules/<int:module_id>/resources/", legacy_module_resources_redirect),
    path("modules/<int:module_id>/resources/add/", legacy_module_resource_add_redirect),
    path("modules/<int:module_id>/resources/remove/", legacy_module_resource_remove_redirect),
    path("resources/", RedirectView.as_view(pattern_name="content:resource_list", permanent=True)),
    path("resources/create/", RedirectView.as_view(pattern_name="content:resource_create", permanent=True)),
    path("resources/<int:pk>/", legacy_resource_detail_redirect),
    path("resources/<int:pk>/edit/", legacy_resource_update_redirect),
    path("resources/<int:pk>/delete/", legacy_resource_delete_redirect),
    path("resources/options/", RedirectView.as_view(pattern_name="content:resource_options", permanent=True)),
    path("subjects/", RedirectView.as_view(pattern_name="content:subject_list", permanent=True)),
    path("subjects/create/", RedirectView.as_view(pattern_name="content:subject_create", permanent=True)),
    path("subjects/<int:pk>/", legacy_subject_detail_redirect),
    path("subjects/<int:pk>/edit/", legacy_subject_update_redirect),
    path("subjects/<int:pk>/delete/", legacy_subject_delete_redirect),
    path("topics/", RedirectView.as_view(pattern_name="content:topic_list", permanent=True)),
    path("topics/create/", RedirectView.as_view(pattern_name="content:topic_create", permanent=True)),
    path("topics/<int:pk>/edit/", legacy_topic_update_redirect),
    path("topics/<int:pk>/delete/", legacy_topic_delete_redirect),
    path("topics/options/", RedirectView.as_view(pattern_name="content:topic_options", permanent=True)),
]
