from django.urls import path
from apps.content.views import (
    ResourceCreateView,
    ResourceDeleteView,
    ResourceDetailView,
    resource_infographic,
    ResourceListView,
    ResourceUpdateView,
    resource_options,
    create_resource_from_video,
    publication_item_editorial_package,
    publication_item_status,
    upload_publication_infographic,
    upload_resource_infographic,
    refresh_direct_resource_editorial,
    repair_direct_resource_editorial_text,
    confirm_publication_item,
    toggle_resource_completion,
    quiz_start,
    quiz_submit,
    quiz_status,
    quiz_recover,
    report_error,
)

urlpatterns = [
    path("recursos/", ResourceListView.as_view(), name="resource_list"),
    path("recursos/crear/", ResourceCreateView.as_view(), name="resource_create"),
    path("recursos/opciones/", resource_options, name="resource_options"),
    path("recursos/<slug:slug>/infografia/", resource_infographic, name="resource_infographic"),
    path("recursos/<slug:slug>/", ResourceDetailView.as_view(), name="resource_detail"),
    path("recursos/<slug:slug>/completar/", toggle_resource_completion, name="resource_toggle_completion"),
    path("recursos/<int:pk>/editar/", ResourceUpdateView.as_view(), name="resource_update"),
    path("recursos/<int:pk>/eliminar/", ResourceDeleteView.as_view(), name="resource_delete"),
    path("api/recursos/crear-video/", create_resource_from_video, name="api_create_resource_from_video"),
    path("api/recursos/<int:resource_id>/infografia/", upload_resource_infographic, name="api_resource_infographic_upload"),
    path(
        "api/recursos/slug/<slug:slug>/infografia/",
        upload_resource_infographic,
        name="api_resource_infographic_upload_by_slug",
    ),
    path(
        "api/recursos/slug/<slug:slug>/paquete-editorial/",
        refresh_direct_resource_editorial,
        name="api_resource_editorial_refresh_by_slug",
    ),
    path(
        "api/recursos/slug/<slug:slug>/reparar-texto/",
        repair_direct_resource_editorial_text,
        name="api_resource_editorial_repair_by_slug",
    ),
    path(
        "api/publicacion/<int:item_id>/",
        publication_item_status,
        name="api_publication_item_status",
    ),
    path(
        "api/publicacion/<int:item_id>/confirmar/",
        confirm_publication_item,
        name="api_confirm_publication_item",
    ),
    path(
        "api/publicacion/<int:item_id>/paquete-editorial/",
        publication_item_editorial_package,
        name="api_publication_item_editorial_package",
    ),
    path(
        "api/publicacion/<int:item_id>/infografia/",
        upload_publication_infographic,
        name="api_publication_infographic_upload",
    ),
    # Evaluación gamificada
    path("recursos/<slug:slug>/quiz/<int:level>/<str:mode>/", quiz_start, name="quiz_start"),
    path("recursos/<slug:slug>/quiz/<int:level>/<str:mode>/enviar/", quiz_submit, name="quiz_submit"),
    path("recursos/<slug:slug>/quiz/estado/", quiz_status, name="quiz_status"),
    path("recursos/<slug:slug>/quiz/<int:level>/recuperar/", quiz_recover, name="quiz_recover"),
    path("recursos/quiz/reportar/<int:question_id>/", report_error, name="quiz_report_error"),
]
