"""Tests de F1 — KnowledgeNode + import_knowledge_tree."""

import tempfile
from pathlib import Path

from django.core.management import call_command
from django.db import IntegrityError
from django.test import TestCase

from apps.content.models import KnowledgeNode

# YAML mínimo en formato atómico (EE.BB.TT.RR), igual estructura que numeros-enteros.yaml.
ATOMIC_YAML = """\
rama: Números
codigo: "02"
abreviatura: NUM
bloque: "Enteros"
bloque_codigo: "02.01"
temas:
  - codigo: "02.01.01"
    id: MAT.NUM.ENTEROS_CONJUNTO
    nombre: El conjunto de los números enteros y orden
    competencia: M1
    recursos:
      - { cod: "02.01.01.01", id: MAT.NUM.ENTEROS_CONJUNTO.NATURALES, nombre: "Números naturales", dificultad: basica, cursos: [7B] }
      - { cod: "02.01.01.02", id: MAT.NUM.ENTEROS_CONJUNTO.CARDINALES, nombre: "Números cardinales", dificultad: basica, cursos: [7B] }
  - codigo: "02.01.02"
    id: MAT.NUM.ENTEROS_OPERATORIA
    nombre: Operatoria en enteros
    competencia: M1
    recursos:
      - { cod: "02.01.02.01", id: MAT.NUM.ENTEROS_OPERATORIA.ADICION, nombre: "Adición de enteros", dificultad: basica, cursos: [7B] }
"""

# YAML legacy de resumen (sin codigo/bloque_codigo, recursos sin id) → debe omitirse.
LEGACY_YAML = """\
rama: Números (Aritmética)
abreviatura: NUM
temas:
  - id: MAT.NUM.CONJUNTOS
    nombre: Conjuntos numéricos
    competencia: M1
    recursos:
      - { n: "01", nombre: "Cadena de inclusión", dificultad: basica }
"""


class KnowledgeNodeModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        node = KnowledgeNode.objects.create(
            semantic_id="MAT",
            code="MAT",
            node_type=KnowledgeNode.NODE_ASIGNATURA,
            subject_abbr="MAT",
            name="Matemáticas",
        )
        self.assertEqual(node.slug, "matematicas")

    def test_is_leaf_property(self):
        asign = KnowledgeNode.objects.create(
            semantic_id="MAT",
            code="MAT",
            node_type=KnowledgeNode.NODE_ASIGNATURA,
            subject_abbr="MAT",
            name="Matemáticas",
        )
        leaf = KnowledgeNode.objects.create(
            semantic_id="MAT.NUM.X.Y",
            code="02.01.01.01",
            node_type=KnowledgeNode.NODE_RECURSO,
            subject_abbr="MAT",
            name="Una hoja",
            parent=asign,
        )
        self.assertFalse(asign.is_leaf)
        self.assertTrue(leaf.is_leaf)

    def test_semantic_id_is_globally_unique(self):
        KnowledgeNode.objects.create(
            semantic_id="MAT",
            code="MAT",
            node_type=KnowledgeNode.NODE_ASIGNATURA,
            subject_abbr="MAT",
            name="Matemáticas",
        )
        with self.assertRaises(IntegrityError):
            KnowledgeNode.objects.create(
                semantic_id="MAT",
                code="OTRO",
                node_type=KnowledgeNode.NODE_ASIGNATURA,
                subject_abbr="MAT",
                name="Duplicado",
            )

    def test_code_unique_per_subject_not_global(self):
        KnowledgeNode.objects.create(
            semantic_id="MAT.NUM",
            code="02",
            node_type=KnowledgeNode.NODE_EJE,
            subject_abbr="MAT",
            name="Números",
        )
        # Mismo code en otra asignatura: permitido.
        KnowledgeNode.objects.create(
            semantic_id="FIS.MEC",
            code="02",
            node_type=KnowledgeNode.NODE_EJE,
            subject_abbr="FIS",
            name="Mecánica",
        )
        # Mismo code en la misma asignatura: prohibido.
        with self.assertRaises(IntegrityError):
            KnowledgeNode.objects.create(
                semantic_id="MAT.ALG",
                code="02",
                node_type=KnowledgeNode.NODE_EJE,
                subject_abbr="MAT",
                name="Álgebra",
            )


class ImportKnowledgeTreeTests(TestCase):
    def _write(self, dirpath, name, content):
        path = Path(dirpath) / name
        path.write_text(content, encoding="utf-8")
        return path

    def test_import_builds_tree_and_skips_legacy(self):
        with tempfile.TemporaryDirectory() as d:
            self._write(d, "numeros-enteros.yaml", ATOMIC_YAML)
            self._write(d, "numeros.yaml", LEGACY_YAML)
            call_command("import_knowledge_tree", dir=d, verbosity=0)

        # asignatura + eje + bloque + 2 temas + 3 recursos = 8 nodos.
        self.assertEqual(KnowledgeNode.objects.count(), 8)
        self.assertTrue(
            KnowledgeNode.objects.filter(
                semantic_id="MAT", node_type="asignatura", parent__isnull=True
            ).exists()
        )
        self.assertTrue(
            KnowledgeNode.objects.filter(semantic_id="MAT.NUM", node_type="eje").exists()
        )
        self.assertTrue(
            KnowledgeNode.objects.filter(
                semantic_id="MAT.NUM.B0201", node_type="bloque"
            ).exists()
        )
        # El archivo legacy no aporta nodos.
        self.assertFalse(
            KnowledgeNode.objects.filter(semantic_id="MAT.NUM.CONJUNTOS").exists()
        )

    def test_leaf_fields_and_parentage(self):
        with tempfile.TemporaryDirectory() as d:
            self._write(d, "numeros-enteros.yaml", ATOMIC_YAML)
            call_command("import_knowledge_tree", dir=d, verbosity=0)

        leaf = KnowledgeNode.objects.get(
            semantic_id="MAT.NUM.ENTEROS_CONJUNTO.NATURALES"
        )
        self.assertEqual(leaf.node_type, "recurso")
        self.assertEqual(leaf.code, "02.01.01.01")
        self.assertEqual(leaf.competencia, "M1")  # heredada del tema
        self.assertEqual(leaf.dificultad, "basica")
        self.assertEqual(leaf.cursos, ["7B"])
        self.assertEqual(leaf.subject_abbr, "MAT")
        self.assertEqual(leaf.axis_abbr, "NUM")
        self.assertEqual(leaf.parent.semantic_id, "MAT.NUM.ENTEROS_CONJUNTO")
        # Cadena completa hasta la raíz.
        self.assertEqual(leaf.parent.parent.node_type, "bloque")
        self.assertEqual(leaf.parent.parent.parent.node_type, "eje")
        self.assertEqual(leaf.parent.parent.parent.parent.node_type, "asignatura")

    def test_import_is_idempotent(self):
        with tempfile.TemporaryDirectory() as d:
            self._write(d, "numeros-enteros.yaml", ATOMIC_YAML)
            call_command("import_knowledge_tree", dir=d, verbosity=0)
            count1 = KnowledgeNode.objects.count()
            slug_before = KnowledgeNode.objects.get(
                semantic_id="MAT.NUM.ENTEROS_CONJUNTO.NATURALES"
            ).slug

            call_command("import_knowledge_tree", dir=d, verbosity=0)
            count2 = KnowledgeNode.objects.count()
            slug_after = KnowledgeNode.objects.get(
                semantic_id="MAT.NUM.ENTEROS_CONJUNTO.NATURALES"
            ).slug

        self.assertEqual(count1, count2)  # no duplica
        self.assertEqual(slug_before, slug_after)  # slug estable entre corridas

    def test_single_file_option(self):
        with tempfile.TemporaryDirectory() as d:
            path = self._write(d, "numeros-enteros.yaml", ATOMIC_YAML)
            call_command("import_knowledge_tree", file=str(path), verbosity=0)
        self.assertEqual(KnowledgeNode.objects.count(), 8)
