# Generated by Django 6.0.3 on 2026-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('text', 'Texto'), ('video', 'Video'), ('document', 'Documento'), ('link', 'Enlace')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
