# Generated by Django 6.0.3 on 2026-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_level_subject_resource_content_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='modules', through='content.ModuleResource', to='content.resource', verbose_name='recursos'),
        ),
    ]
