# Generated by Django 6.0.3 on 2026-03-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_module_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='resources',
        ),
    ]
