# Generated by Django 6.0.3 on 2026-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_topic_resource_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'nivel',
                'verbose_name_plural': 'niveles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='resources', to='content.level', verbose_name='niveles'),
        ),
    ]
