# Generated by Django 6.0.3 on 2026-03-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_level_resource_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('objective', models.TextField(blank=True, verbose_name='objetivo de aprendizaje')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('levels', models.ManyToManyField(blank=True, related_name='modules', to='content.level', verbose_name='niveles')),
                ('resources', models.ManyToManyField(blank=True, related_name='modules', to='content.resource', verbose_name='recursos')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.subject', verbose_name='asignatura')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='content.topic', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['subject__name', 'order', 'title'],
            },
        ),
    ]
