# Generated by Django 6.0.3 on 2026-03-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_module_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content_body',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción breve'),
        ),
    ]
