# Generated by Django 6.0.3 on 2026-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_area_subject_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='archivo descargable'),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video de YouTube'),
        ),
    ]
