# Generated by Django 6.0.3 on 2026-05-26 03:40

import apps.content.models.resource
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_resource_file_resource_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden manual'),
        ),
        migrations.AddField(
            model_name='topic',
            name='resource_ordering_method',
            field=models.CharField(choices=[('level', 'Nivel educativo (básico a avanzado)'), ('alphabetical', 'Alfabético-numérico por título'), ('created_asc', 'Fecha de creación (antiguo primero)'), ('created_desc', 'Fecha de creación (reciente primero)'), ('manual', 'Orden manual (por índice de orden)')], default='level', max_length=20, verbose_name='método de ordenación de recursos'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'png', 'jpg', 'jpeg', 'zip']), apps.content.models.resource.validate_file_size, apps.content.models.resource.validate_file_mime], verbose_name='archivo descargable'),
        ),
    ]
