# Generated by Django 6.0.3 on 2026-05-30 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_add_mechanics_forces_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='content.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurso completado',
                'verbose_name_plural': 'recursos completados',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'resource'), name='unique_user_resource_completion')],
            },
        ),
    ]
