# Generated by Django 6.0.5 on 2026-05-31 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_resourcecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurso visto',
                'verbose_name_plural': 'recursos vistos',
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'resource'), name='unique_user_resource_view')],
            },
        ),
    ]
