# Generated by Django 6.0.5 on 2026-05-31 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_resourceview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1 — Definición'), (2, 'Nivel 2 — Ejercicios simples'), (3, 'Nivel 3 — Problemas de aplicación')], verbose_name='nivel')),
                ('mode', models.CharField(choices=[('preparacion', 'Preparación'), ('evaluacion', 'Evaluación'), ('ambas', 'Ambas')], default='ambas', max_length=15, verbose_name='modo')),
                ('text', models.TextField(verbose_name='enunciado')),
                ('explanation', models.TextField(blank=True, help_text='Explicación breve que se muestra tras responder.', verbose_name='explicación')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=10, verbose_name='estado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['resource', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='es correcta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.question', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='1=Definición, 2=Ejercicios simples, 3=Problemas de aplicación', verbose_name='nivel')),
                ('mode', models.CharField(choices=[('preparacion', 'Preparación'), ('evaluacion', 'Evaluación')], max_length=15, verbose_name='modo')),
                ('score', models.PositiveSmallIntegerField(help_text='Número de respuestas correctas.', verbose_name='aciertos')),
                ('total', models.PositiveSmallIntegerField(help_text='Total de preguntas en el intento.', verbose_name='total de preguntas')),
                ('passed', models.BooleanField(verbose_name='aprobado')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='nº de intento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='content.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento de evaluación',
                'verbose_name_plural': 'intentos de evaluación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('respuesta_incorrecta', 'Respuesta correcta equivocada'), ('enunciado_confuso', 'Enunciado confuso'), ('alternativas_ambiguas', 'Alternativas ambiguas'), ('error_redaccion', 'Error de redacción/formato'), ('explicacion_insuficiente', 'Explicación insuficiente')], max_length=30, verbose_name='motivo')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('revisando', 'Revisando'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='nuevo', max_length=12, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_error_reports', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to='content.quizattempt')),
            ],
            options={
                'verbose_name': 'reporte de error',
                'verbose_name_plural': 'reportes de error',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='es correcta')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='content.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='content.choice')),
            ],
            options={
                'verbose_name': 'respuesta de intento',
                'verbose_name_plural': 'respuestas de intento',
            },
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('user', 'resource', 'level', 'mode', 'attempt_number'), name='unique_quiz_attempt'),
        ),
    ]
