# Generated by Django 6.0.5 on 2026-05-31 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_evaluacion_gamificada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEvaluationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Número de respuestas correctas.', verbose_name='aciertos')),
                ('total', models.PositiveSmallIntegerField(verbose_name='total de preguntas')),
                ('percentage', models.PositiveSmallIntegerField(help_text='Porcentaje de acierto (0-100).', verbose_name='porcentaje')),
                ('passed', models.BooleanField(verbose_name='aprobado')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='nº de intento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_attempts', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_eval_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento de evaluación de tema',
                'verbose_name_plural': 'intentos de evaluación de tema',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic', 'attempt_number'), name='unique_topic_eval_attempt')],
            },
        ),
    ]
