# Generated by Django 6.0.5 on 2026-06-01 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_topicevaluationattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveSmallIntegerField(default=0)),
                ('longest_count', models.PositiveSmallIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'racha de aprendizaje',
                'verbose_name_plural': 'rachas de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('practice', 'Practica'), ('resource_level_pass', 'Nivel de recurso aprobado'), ('topic_exam_pass', 'Evaluacion final de tema aprobada'), ('skill_unlock', 'Skill desbloqueada'), ('streak_bonus', 'Bonus de racha')], max_length=30)),
                ('amount', models.PositiveSmallIntegerField()),
                ('event_key', models.CharField(help_text='Clave idempotente para no duplicar XP por refrescos o reenvios.', max_length=160, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='content.quizattempt')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='content.resource')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='content.topic')),
                ('topic_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='content.topicevaluationattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de XP',
                'verbose_name_plural': 'eventos de XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_skills', to='content.topic')),
                ('unlocked_by_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_skills', to='content.topicevaluationattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill desbloqueada',
                'verbose_name_plural': 'skills desbloqueadas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_skill_per_user_topic')],
            },
        ),
    ]
