# Generated by Django 6.0.5 on 2026-06-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_userstreak_xpevent_userskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='content.area', verbose_name='área'),
        ),
    ]
