# Generated by Django 6.0.5 on 2026-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_seed_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='content.level', verbose_name='niveles'),
        ),
        migrations.AddField(
            model_name='topic',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='topics', to='content.level', verbose_name='niveles'),
        ),
    ]
