# Generated by Django 6.0.5 on 2026-06-13 17:04

import apps.content.models.resource_quiz_config
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_seed_fluid_mechanics_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceQuizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField(default=apps.content.models.resource_quiz_config.default_quiz_counts, help_text='Configuración de pool y mostradas por nivel y modo.', verbose_name='matriz de preguntas')),
                ('pass_threshold', models.FloatField(default=1.0, help_text='Porcentaje mínimo de respuestas correctas para aprobar (1.0 = 100%).', verbose_name='umbral de aprobación')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Número máximo de intentos permitidos para la evaluación del nivel.', verbose_name='intentos máximos')),
                ('recovery_rule', models.CharField(choices=[('practice_5_5', 'Práctica perfecta 5/5'), ('none', 'Ninguna')], default='practice_5_5', help_text='Regla que permite recuperar un intento de evaluación.', max_length=20, verbose_name='regla de recuperación')),
                ('allow_retake_passed', models.BooleanField(default=True, help_text='Permite al alumno volver a rendir la evaluación si ya está aprobada (sin volver a dar estrellas/XP).', verbose_name='permitir repetir aprobado')),
                ('autopublish', models.BooleanField(default=False, help_text='Si está activo, las preguntas generadas por IA se publican directamente en vez de guardarse en borrador.', verbose_name='autopublicar al generar')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_config', to='content.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'configuración de quiz de recurso',
                'verbose_name_plural': 'configuraciones de quiz de recurso',
            },
        ),
    ]
