# Generated by Django 6.0.5 on 2026-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_topic_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descripción')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='archivo de origen')),
                ('content_text', models.TextField(help_text='Texto limpio y compacto extraído del material; es lo que lee la IA.', verbose_name='texto normalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='quiz_guides', to='content.resource', verbose_name='recursos')),
                ('subjects', models.ManyToManyField(blank=True, related_name='quiz_guides', to='content.subject', verbose_name='asignaturas')),
                ('topics', models.ManyToManyField(blank=True, related_name='quiz_guides', to='content.topic', verbose_name='temas')),
            ],
            options={
                'verbose_name': 'guía de referencia',
                'verbose_name_plural': 'guías de referencia',
                'ordering': ['title'],
            },
        ),
    ]
