# Generated by Django 6.0.5 on 2026-06-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_quizguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='transcript',
            field=models.TextField(blank=True, default='', help_text='Texto hablado del video (se baja aparte y se guarda aquí). Lo usa la generación de preguntas; no se muestra al público.', verbose_name='Transcripción del video'),
        ),
    ]
