# Generated by Django 6.0.5 on 2026-06-19 00:27

import math
import random
from django.db import migrations

def save_questions(Choice, Question, resource, level, mode, questions_data):
    created_questions = []
    last_order = Question.objects.filter(resource=resource, level=level).count()

    for item in questions_data:
        text = item.get("text")
        explanation = item.get("explanation", "")
        choices = item.get("choices")

        if not text or not choices:
            continue

        question = Question.objects.create(
            resource=resource,
            level=level,
            mode=mode,
            text=text,
            explanation=explanation,
            status="publicada",
            order=last_order + 1
        )
        last_order += 1

        choice_objs = []
        for idx, choice_data in enumerate(choices):
            c_text = choice_data.get("text")
            c_correct = choice_data.get("is_correct", False)

            choice_objs.append(
                Choice(
                    question=question,
                    text=c_text,
                    is_correct=bool(c_correct),
                    order=idx + 1
                )
            )

        Choice.objects.bulk_create(choice_objs)
        created_questions.append(question)

    return created_questions

# Generadores dinámicos idénticos al generador local para el seed

def gen_conjuntos_numericos():
    questions = []
    questions.append({
        "text": "¿Cuál de las siguientes afirmaciones describe mejor al conjunto de los números enteros (ℤ)?",
        "explanation": "El conjunto de los números enteros (ℤ) incluye los números naturales (enteros positivos), el cero y los enteros negativos. Por lo tanto, incluye positivos, negativos y el cero.",
        "choices": [
            {"text": "Está formado por los enteros positivos, los enteros negativos y el cero.", "is_correct": True},
            {"text": "Solo contiene los números positivos que sirven para contar y el cero.", "is_correct": False},
            {"text": "Incluye a todas las fracciones y números decimales infinitos.", "is_correct": False},
            {"text": "Está compuesto únicamente por números impares menores a 100.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "¿Cuál es la principal diferencia entre el conjunto de los números naturales (ℕ) y los números enteros (ℤ)?",
        "explanation": "Los números naturales (ℕ) solo contemplan cantidades positivas (y a veces el cero), mientras que los enteros (ℤ) amplían este conjunto agregando los números negativos para representar deudas, temperaturas bajo cero, etc.",
        "choices": [
            {"text": "Los enteros contienen números negativos, a diferencia de los naturales.", "is_correct": True},
            {"text": "Los naturales contienen números negativos y los enteros no.", "is_correct": False},
            {"text": "Los naturales incluyen fracciones y los enteros solo números con coma.", "is_correct": False},
            {"text": "No hay ninguna diferencia; son exactamente el mismo conjunto.", "is_correct": False}
        ]
    })
    for num in [-15, -8, -42, -5, -31]:
        questions.append({
            "text": f"¿A qué conjuntos numéricos pertenece el número {num}?",
            "explanation": f"El número {num} es un número entero negativo. Por lo tanto, pertenece al conjunto de los números enteros (ℤ), pero NO pertenece al conjunto de los números naturales (ℕ) que solo tiene positivos.",
            "choices": [
                {"text": f"Pertenece a los enteros (ℤ) pero no a los naturales (ℕ).", "is_correct": True},
                {"text": f"Pertenece a los naturales (ℕ) pero no a los enteros (ℤ).", "is_correct": False},
                {"text": "Pertenece a ambos conjuntos (ℕ y ℤ).", "is_correct": False},
                {"text": "No pertenece a ninguno de los dos conjuntos.", "is_correct": False}
            ]
        })
    contexts = [
        {"desc": "un termómetro marca una temperatura de 4 grados bajo cero", "val": -4},
        {"desc": "un submarino navega a una profundidad de 150 metros bajo el nivel del mar", "val": -150},
        {"desc": "un cliente de un banco tiene una deuda de $12.000 en su cuenta", "val": -12000},
        {"desc": "un ascensor se encuentra en el tercer piso del subterráneo (-3)", "val": -3}
    ]
    for ctx in contexts:
        questions.append({
            "text": f"Si representamos la siguiente situación con un número entero: '{ctx['desc']}', ¿cuál es el número entero correspondiente?",
            "explanation": f"Las situaciones que indican 'bajo cero', 'bajo el nivel del mar', 'subterráneo' o 'deuda/saldo en contra' se representan matemáticamente con números enteros negativos. En este caso corresponde a {ctx['val']}.",
            "choices": [
                {"text": f"{ctx['val']}", "is_correct": True},
                {"text": f"{abs(ctx['val'])}", "is_correct": False},
                {"text": "0", "is_correct": False},
                {"text": f"{ctx['val'] * 2}", "is_correct": False}
            ]
        })
    for num in [7, 24, 88, 9]:
        questions.append({
            "text": f"¿Cómo se clasifica el número natural positivo {num} en el conjunto de los enteros?",
            "explanation": f"Todo número natural ({num}) es también un número entero positivo. Por ende, pertenece a ambos conjuntos.",
            "choices": [
                {"text": "Pertenece tanto a los naturales (ℕ) como a los enteros (ℤ).", "is_correct": True},
                {"text": "Solo pertenece a los naturales (ℕ).", "is_correct": False},
                {"text": "Solo pertenece a los enteros (ℤ).", "is_correct": False},
                {"text": "Es un entero negativo.", "is_correct": False}
            ]
        })
    return questions

def gen_relaciones_orden():
    questions = []
    questions.append({
        "text": "En la recta numérica, ¿cómo se determina si un número entero es mayor que otro?",
        "explanation": "En la recta numérica, el número que se ubica más a la derecha siempre es el mayor, y el que está más a la izquierda es el menor.",
        "choices": [
            {"text": "El número que está más a la derecha siempre es el mayor.", "is_correct": True},
            {"text": "El número que tiene más cifras siempre es el menor.", "is_correct": False},
            {"text": "El número que está más cerca del cero siempre es el mayor.", "is_correct": False},
            {"text": "Los números negativos siempre son mayores que los positivos.", "is_correct": False}
        ]
    })
    comparisons = [
        (-15, 2), (-30, -5), (-8, -1), (-25, 0), (-12, 4), (-4, -3), (-20, -10)
    ]
    for n1, n2 in comparisons:
        questions.append({
            "text": f"¿Cuál de las siguientes relaciones de comparación es correcta para los números {n1} y {n2}?",
            "explanation": f"En la recta numérica, {n2} está a la derecha de {n1}. Por tanto, {n2} > {n1} (o {n1} < {n2}).",
            "choices": [
                {"text": f"{n1} < {n2}", "is_correct": True},
                {"text": f"{n1} > {n2}", "is_correct": False},
                {"text": f"{n1} = {n2}", "is_correct": False},
                {"text": "Ninguna relación es correcta", "is_correct": False}
            ]
        })
    temps = [
        (-8, -2), (-12, 1), (-5, -1), (-15, -4), (-9, 2), (-6, 0), (-3, 3)
    ]
    for temp1, temp2 in temps:
        questions.append({
            "text": f"Una ciudad A registra una temperatura de {temp1}°C y una ciudad B registra {temp2}°C. ¿Cuál ciudad tiene la temperatura más fría y por qué?",
            "explanation": f"La temperatura más fría corresponde al número menor en la escala. Como {temp1} es menor que {temp2} ({temp1} < {temp2}), la ciudad A es la más fría.",
            "choices": [
                {"text": f"La ciudad A es la más fría, porque {temp1} es menor que {temp2}.", "is_correct": True},
                {"text": f"La ciudad B es la más fría, porque {temp2} es menor que {temp1}.", "is_correct": False},
                {"text": "Ambas ciudades tienen el mismo nivel de frío.", "is_correct": False},
                {"text": "La ciudad A es la más cálida, por estar más lejos del cero.", "is_correct": False}
            ]
        })
    return questions

def gen_valor_absoluto():
    questions = []
    questions.append({
        "text": "@Qué representa el valor absoluto de un número entero?",
        "explanation": "El valor absoluto de un número representa su distancia al cero en la recta numérica. Dado que las distancias siempre son positivas o cero, el valor absoluto nunca puede ser negativo.",
        "choices": [
            {"text": "La distancia del número al cero en la recta numérica.", "is_correct": True},
            {"text": "El número con el signo contrario.", "is_correct": False},
            {"text": "La suma del número consigo mismo.", "is_correct": False},
            {"text": "La distancia entre el número y su opuesto.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "¿Cuál es el valor absoluto de un número negativo?",
        "explanation": "El valor absoluto de cualquier número distinto de cero es siempre positivo, ya que representa una distancia.",
        "choices": [
            {"text": "Es el mismo número pero con signo positivo.", "is_correct": True},
            {"text": "Es el mismo número pero con signo negativo.", "is_correct": False},
            {"text": "Siempre es cero.", "is_correct": False},
            {"text": "Es el número multiplicado por -1.", "is_correct": False}
        ]
    })
    for val in [-12, -25, -5, -8, -50, -18, -33]:
        questions.append({
            "text": f"¿Cuál es el valor de |{val}|?",
            "explanation": f"El valor absoluto de {val}, escrito como |{val}|, es la distancia de {val} al cero en la recta numérica, lo cual es {abs(val)} unidades.",
            "choices": [
                {"text": f"{abs(val)}", "is_correct": True},
                {"text": f"{val}", "is_correct": False},
                {"text": "0", "is_correct": False},
                {"text": f"{-val - 5}", "is_correct": False}
            ]
        })
    questions.append({
        "text": "Un buzo está a -15 metros bajo el nivel del mar y un ave vuela a 15 metros de altura sobre el nivel del mar. ¿Quién está a mayor distancia del nivel del mar (cero)?",
        "explanation": "El buzo está a |-15| = 15 metros del nivel del mar. El ave está a |15| = 15 metros del nivel del mar. Por lo tanto, ambos están exactamente a la misma distancia (15 metros) del cero.",
        "choices": [
            {"text": "Ambos están a la misma distancia del nivel del mar.", "is_correct": True},
            {"text": "El buzo está más lejos porque -15 es menor que 15.", "is_correct": False},
            {"text": "El ave está más lejos porque 15 es un número positivo.", "is_correct": False},
            {"text": "El buzo está más cerca porque está bajo el agua.", "is_correct": False}
        ]
    })
    depths = [
        (-25, 5), (-35, 10), (-18, 3), (-40, 8), (-15, 4)
    ]
    for d1, d2 in depths:
        questions.append({
            "text": f"Un pez se encuentra a {d1} metros de profundidad y un cangrejo a {d1 + d2} metros de profundidad. ¿Cuál de los dos está más cerca del nivel del mar (cero) y por qué?",
            "explanation": f"El pez está a |{d1}| = {abs(d1)} metros del cero. El cangrejo está a |{d1 + d2}| = {abs(d1 + d2)} metros del cero. Como {abs(d1 + d2)} es menor que {abs(d1)}, el cangrejo está más cerca del nivel del mar.",
            "choices": [
                {"text": f"El cangrejo, porque su valor absoluto ({abs(d1 + d2)}) es menor que el del pez ({abs(d1)}).", "is_correct": True},
                {"text": f"El pez, porque su valor absoluto ({abs(d1)}) es mayor que el del cangrejo ({abs(d1 + d2)}).", "is_correct": False},
                {"text": "Ambos están a la misma distancia.", "is_correct": False},
                {"text": f"El pez, porque está a mayor profundidad.", "is_correct": False}
            ]
        })
    return questions

def gen_sumas_restas():
    questions = []
    questions.append({
        "text": "Al sumar dos números enteros con el mismo signo, ¿cuál es la regla a seguir?",
        "explanation": "La regla para sumar números de igual signo es: se suman sus valores absolutos y se conserva el signo común.",
        "choices": [
            {"text": "Se suman sus valores absolutos y se mantiene el signo común.", "is_correct": True},
            {"text": "Se restan sus valores absolutos y se pone el signo del mayor.", "is_correct": False},
            {"text": "El resultado siempre es un número positivo.", "is_correct": False},
            {"text": "El resultado siempre es cero.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "Al sumar dos números enteros con signos diferentes (uno positivo y uno negativo), ¿cuál es la regla?",
        "explanation": "La regla para sumar enteros de distinto signo es: se restan sus valores absolutos (el mayor menos el menor) y se conserva el signo del número con mayor valor absoluto.",
        "choices": [
            {"text": "Se restan sus valores absolutos y se conserva el signo del que tiene mayor valor absoluto.", "is_correct": True},
            {"text": "Se suman sus valores absolutos y se coloca signo positivo.", "is_correct": False},
            {"text": "Se restan sus valores absolutos y el signo del resultado siempre es negativo.", "is_correct": False},
            {"text": "Se multiplican sus signos y se suman los números.", "is_correct": False}
        ]
    })
    ops = [
        (-15, -8), (-12, 5), (-8, 12), (-20, -10), (-25, 15), (-4, -9), (-18, 22)
    ]
    for n1, n2 in ops:
        ans = n1 + n2
        questions.append({
            "text": f"Resuelve la siguiente operación: {n1} + ({n2})",
            "explanation": f"Para resolver {n1} + ({n2}): si tienen igual signo se suman y conserva el signo; si tienen distinto signo se restan y conserva el signo del mayor absoluto. El resultado es {ans}.",
            "choices": [
                {"text": f"{ans}", "is_correct": True},
                {"text": f"{ans + 5}", "is_correct": False},
                {"text": f"{ans - 10}", "is_correct": False},
                {"text": f"{n1 - n2}", "is_correct": False}
            ]
        })
    saldos = [
        (-5000, 12000), (-8000, 5000), (-15000, 20000), (-3000, 8000), (-25000, 30000), (-12000, 15000)
    ]
    for saldo, deposito in saldos:
        ans = saldo + deposito
        questions.append({
            "text": f"Una cuenta bancaria tiene un saldo de {saldo} pesos (en contra). Si el dueño realiza un depósito de {deposito} pesos, ¿cuál es el nuevo saldo de la cuenta?",
            "explanation": f"El saldo inicial es de {saldo} (negativo). Al depositar {deposito} (positivo), calculamos la suma: {saldo} + {deposito} = {ans} pesos.",
            "choices": [
                {"text": f"{ans} pesos", "is_correct": True},
                {"text": f"{saldo - deposito} pesos", "is_correct": False},
                {"text": f"{deposito} pesos", "is_correct": False},
                {"text": f"{ans - 2000} pesos", "is_correct": False}
            ]
        })
    return questions

def gen_mult_div():
    questions = []
    questions.append({
        "text": "¿Cuál es el signo del resultado al multiplicar dos números enteros con signos diferentes (un positivo por un negativo)?",
        "explanation": "La ley de signos para la multiplicación establece que más por menos es menos (+ · - = -). Por lo tanto, el resultado es siempre negativo.",
        "choices": [
            {"text": "Negativo", "is_correct": True},
            {"text": "Positivo", "is_correct": False},
            {"text": "Depende de cuál número sea mayor en valor absoluto.", "is_correct": False},
            {"text": "Siempre es cero.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "¿Cuál es el signo del resultado al dividir dos números enteros negativos?",
        "explanation": "La ley de signos para la división establece que menos dividido por menos es más (- / - = +). Por lo tanto, el resultado es siempre positivo.",
        "choices": [
            {"text": "Positivo", "is_correct": True},
            {"text": "Negativo", "is_correct": False},
            {"text": "Depende de la distancia al cero.", "is_correct": False},
            {"text": "Es indeterminado.", "is_correct": False}
        ]
    })
    ops = [
        (-5, -6), (-4, 8), (-8, -3), (6, -4), (-9, 3), (7, 5), (-12, -2)
    ]
    for n1, n2 in ops:
        ans = n1 * n2
        questions.append({
            "text": f"Resuelve la siguiente multiplicación: {n1} · ({n2})",
            "explanation": f"Multiplicamos los valores absolutos: {abs(n1)} · {abs(n2)} = {abs(ans)}. Luego aplicamos la ley de signos: si los signos son iguales el resultado es positivo; si son diferentes es negativo. Por tanto, el resultado es {ans}.",
            "choices": [
                {"text": f"{ans}", "is_correct": True},
                {"text": f"{-ans}", "is_correct": False},
                {"text": f"{ans + n1}", "is_correct": False},
                {"text": f"{abs(ans) + 2}", "is_correct": False}
            ]
        })
    descensos = [
        (3, 5), (4, 6), (2, 8), (5, 4), (6, 3), (3, 7)
    ]
    for desc, tiempo in descensos:
        total = -desc * tiempo
        questions.append({
            "text": f"Un globo aerostático desciende {desc} metros por cada minuto que transcurre. Si mantiene este ritmo constante durante {tiempo} minutos, ¿cuál es la variación total en su altura?",
            "explanation": f"El descenso se representa como un número negativo: -{desc} metros por minuto. Multiplicado por los {tiempo} minutos de trayecto: -{desc} · {tiempo} = {total} metros de variación (es decir, descendió {abs(total)} metros en total).",
            "choices": [
                {"text": f"{total} metros", "is_correct": True},
                {"text": f"{abs(total)} metros", "is_correct": False},
                {"text": f"-{desc + tiempo} metros", "is_correct": False},
                {"text": "0 metros", "is_correct": False}
            ]
        })
    return questions

def gen_prioridad():
    questions = []
    questions.append({
        "text": "Al resolver operaciones combinadas sin paréntesis, ¿cuál es el orden correcto de prioridad?",
        "explanation": "El orden estándar de prioridad de operaciones (conocido en Chile como PAPOMUDAS) dicta que primero se resuelven Paréntesis, luego Potencias, después Multiplicaciones y Divisiones de izquierda a derecha, y finalmente Sumas y Restas de izquierda a derecha.",
        "choices": [
            {"text": "Primero multiplicaciones y divisiones, luego sumas y restas.", "is_correct": True},
            {"text": "Primero sumas y restas, luego multiplicaciones y divisiones.", "is_correct": False},
            {"text": "Siempre de izquierda a derecha sin importar el tipo de operación.", "is_correct": False},
            {"text": "Primero las sumas y divisiones, luego restas y multiplicaciones.", "is_correct": False}
        ]
    })
    ops = [
        (5, 3, -2), (8, 4, -3), (12, 2, -5), (4, 5, -2), (10, 3, -4), (15, 6, -2), (2, 4, -3)
    ]
    for n1, n2, n3 in ops:
        ans = n1 + n2 * n3
        questions.append({
            "text": f"Calcula el resultado de la siguiente expresión: {n1} + {n2} · ({n3})",
            "explanation": f"Primero resolvemos la multiplicación por prioridad: {n2} · ({n3}) = {n2 * n3}. Luego sumamos el resultado: {n1} + ({n2 * n3}) = {ans}.",
            "choices": [
                {"text": f"{ans}", "is_correct": True},
                {"text": f"{(n1 + n2) * n3}", "is_correct": False},
                {"text": f"{ans + 5}", "is_correct": False},
                {"text": f"{ans - 5}", "is_correct": False}
            ]
        })
    problems = [
        (15, 3, 5, 2), (20, 4, 6, 3), (10, 5, 4, 4), (25, 2, 8, 5), (30, 4, 5, 6), (12, 3, 6, 2), (18, 5, 5, 3)
    ]
    for base, cajas, cant, perdidas in problems:
        ans = base + cajas * cant - perdidas
        questions.append({
            "text": f"Un almacén tiene {base} manzanas. Recibe {cajas} cajas con {cant} manzanas cada una. Si al final del día se botan {perdidas} manzanas que estaban en mal estado, ¿cuántas manzanas quedan?",
            "explanation": f"Escribimos la expresión matemática: {base} + {cajas} · {cant} - {perdidas}. Resolvemos la multiplicación primero: {cajas} · {cant} = {cajas * cant}. Luego sumamos y restamos: {base} + {cajas * cant} - {perdidas} = {ans} manzanas.",
            "choices": [
                {"text": f"{ans} manzanas", "is_correct": True},
                {"text": f"{(base + cajas) * cant - perdidas} manzanas", "is_correct": False},
                {"text": f"{base + cajas * (cant - perdidas)} manzanas", "is_correct": False},
                {"text": f"{ans - 10} manzanas", "is_correct": False}
            ]
        })
    return questions

def gen_primos():
    questions = []
    questions.append({
        "text": "¿Qué define a un número primo?",
        "explanation": "Un número primo es un número entero mayor que 1 que tiene exactamente dos divisores distintos: el 1 y él mismo.",
        "choices": [
            {"text": "Es un número mayor que 1 que solo se puede dividir por 1 y por sí mismo.", "is_correct": True},
            {"text": "Es cualquier número impar.", "is_correct": False},
            {"text": "Es un número que termina en 1, 3, 7 o 9.", "is_correct": False},
            {"text": "Es cualquier número que tenga más de dos divisores.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "¿Cuál es el único número par que también es un número primo?",
        "explanation": "El número 2 es el único número primo par, ya que sus únicos divisores son el 1 y el 2. Todos los demás números pares mayores son compuestos (divisibles por 2).",
        "choices": [
            {"text": "El número 2", "is_correct": True},
            {"text": "El número 4", "is_correct": False},
            {"text": "El número 0", "is_correct": False},
            {"text": "No existen números primos pares.", "is_correct": False}
        ]
    })
    nums = [9, 12, 15, 18, 20, 21, 25]
    for num in nums:
        divs = [d for d in range(1, num + 1) if num % d == 0]
        questions.append({
            "text": f"¿Cuáles son todos los divisores del número {num}?",
            "explanation": f"Los divisores de {num} son los números enteros que lo dividen de forma exacta (con residuo cero). Para {num}, estos son: {', '.join(map(str, divs))}.",
            "choices": [
                {"text": f"{', '.join(map(str, divs))}", "is_correct": True},
                {"text": f"1, {num}", "is_correct": False},
                {"text": f"{', '.join(map(str, divs[:-1]))}", "is_correct": False},
                {"text": "Ninguna de las anteriores", "is_correct": False}
            ]
        })
    groups = [
        (12, 3), (18, 6), (24, 8), (30, 5), (16, 4), (20, 5)
    ]
    for alumnos, opt in groups:
        questions.append({
            "text": f"Un profesor quiere organizar a sus {alumnos} alumnos en grupos de igual tamaño. ¿Cuál de los siguientes tamaños de grupo es posible sin que sobre ningún alumno?",
            "explanation": f"Para organizar a los {alumnos} alumnos de forma exacta, el tamaño del grupo debe ser un divisor de {alumnos}. Entre las opciones, {opt} es divisor de {alumnos}.",
            "choices": [
                {"text": f"Grupos de {opt} alumnos.", "is_correct": True},
                {"text": f"Grupos de {opt + 1} alumnos.", "is_correct": False},
                {"text": f"Grupos de {alumnos - 1} alumnos.", "is_correct": False},
                {"text": "No es posible organizarlos en grupos iguales.", "is_correct": False}
            ]
        })
    return questions

def gen_mcm_mcd():
    questions = []
    questions.append({
        "text": "¿Qué representa el Mínimo Común Múltiplo (MCM) de dos números?",
        "explanation": "El Mínimo Común Múltiplo (MCM) de dos o más números es el número más pequeño (distinto de cero) que es múltiplo común de todos ellos.",
        "choices": [
            {"text": "El múltiplo más pequeño que tienen en común ambos números.", "is_correct": True},
            {"text": "El divisor más grande que tienen en común ambos números.", "is_correct": False},
            {"text": "La suma de los múltiplos de ambos números.", "is_correct": False},
            {"text": "El producto de ambos números dividido por dos.", "is_correct": False}
        ]
    })
    questions.append({
        "text": "¿Qué representa el Máximo Común Divisor (MCD) de dos números?",
        "explanation": "El Máximo Común Divisor (MCD) es el número entero más grande que divide de forma exacta a todos los números del grupo.",
        "choices": [
            {"text": "El divisor más grande que tienen en común ambos números.", "is_correct": True},
            {"text": "El múltiplo más pequeño que tienen en común ambos números.", "is_correct": False},
            {"text": "El número primo más pequeño de los divisores comunes.", "is_correct": False},
            {"text": "La diferencia entre los divisores comunes.", "is_correct": False}
        ]
    })
    pairs = [
        (4, 3, 12), (6, 5, 30), (8, 6, 24), (10, 4, 20), (6, 9, 18), (8, 5, 40), (12, 8, 24)
    ]
    for a, b, mcm in pairs:
        mcd = math.gcd(a, b)
        questions.append({
            "text": f"Calcula el Mínimo Común Múltiplo (MCM) de los números {a} y {b}.",
            "explanation": f"Los múltiplos de {a} son: {a}, {a*2}, {a*3}... y los de {b} son: {b}, {b*2}, {b*3}... El primer múltiplo común más pequeño que encontramos es {mcm}.",
            "choices": [
                {"text": f"{mcm}", "is_correct": True},
                {"text": f"{mcd}", "is_correct": False},
                {"text": f"{a * b}", "is_correct": False},
                {"text": f"{mcm + a}", "is_correct": False}
            ]
        })
    bus_problems = [
        (4, 3, 12), (6, 5, 30), (8, 3, 24), (5, 4, 20), (6, 4, 12), (8, 5, 40)
    ]
    for t1, t2, mcm in bus_problems:
        mcd = math.gcd(t1, t2)
        questions.append({
            "text": f"Dos buses salen al mismo tiempo del terminal. El bus A pasa por un paradero cada {t1} minutos y el bus B pasa por el mismo paradero cada {t2} minutos. ¿En cuántos minutos volverán a coincidir en el paradero?",
            "explanation": f"Este problema se resuelve calculando el Mínimo Común Múltiplo (MCM) de los intervalos de tiempo {t1} y {t2}. El MCM({t1}, {t2}) es {mcm} minutos.",
            "choices": [
                {"text": f"En {mcm} minutos.", "is_correct": True},
                {"text": f"En {t1 + t2} minutos.", "is_correct": False},
                {"text": f"En {t1 * t2 * 2} minutos.", "is_correct": False},
                {"text": f"En {mcd} minutos.", "is_correct": False}
            ]
        })
    return questions

def run_seed_migration(apps, schema_editor):
    Resource = apps.get_model('content', 'Resource')
    Question = apps.get_model('content', 'Question')
    Choice = apps.get_model('content', 'Choice')

    # Mapeo de slugs a sus generadores
    GENERATORS = {
        '12-conjuntos-numericos': gen_conjuntos_numericos,
        '13-numeros-enteros-relaciones-de-orden-mayor-menor-e-igual': gen_relaciones_orden,
        '14-valor-absoluto-relaciones-de-orden': gen_valor_absoluto,
        '15-regla-de-signos-para-sumasrestas': gen_sumas_restas,
        '15a-ejercicios-de-sumas-y-restas-aplicacion-de-regla-de-los-signos': gen_sumas_restas,
        '16-regla-de-los-signos-en-multiplicaciondivision-ejemplos': gen_mult_div,
        '17-prioridad-de-operaciones-sumarestamultiplicaciondivision-combinadas': gen_prioridad,
        '18-numeros-primos-multiplos-y-divisores': gen_primos,
        '19-minimo-comun-multiplo-maximo-comun-divisor': gen_mcm_mcd,
        '19a-ejercicios-minimo-comun-multiplo': gen_mcm_mcd
    }

    for slug, generator_fn in GENERATORS.items():
        try:
            resource = Resource.objects.get(slug=slug)
        except Resource.DoesNotExist:
            continue

        questions_data = generator_fn()

        # Guardar en base de datos vinculando a los tres niveles
        save_questions(Choice, Question, resource, level=1, mode="ambas", questions_data=questions_data[0:5])
        save_questions(Choice, Question, resource, level=2, mode="ambas", questions_data=questions_data[5:10])
        save_questions(Choice, Question, resource, level=3, mode="ambas", questions_data=questions_data[10:15])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_resource_transcript'),
    ]

    operations = [
        migrations.RunPython(run_seed_migration, reverse_code=migrations.RunPython.noop),
    ]
