# Generated by Django 6.0.5 on 2026-06-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_resource_editorial_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.CharField(blank=True, choices=[('escolar', 'Escolar (hasta 13 años)'), ('media', 'Media preuniversitaria (14-17 años)'), ('universitaria', 'Universitaria (18+)')], default='', help_text='Nivel por defecto que heredan los temas/recursos sin nivel propio.', max_length=20, verbose_name='nivel educativo'),
        ),
    ]
