# Generated by Django 6.0.5 on 2026-06-22 04:11

import apps.content.models.topic_bank_config
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_clean_resource_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_tolerance',
            field=models.FloatField(blank=True, null=True, verbose_name='tolerancia'),
        ),
        migrations.AddField(
            model_name='question',
            name='canonical_answer',
            field=models.TextField(blank=True, verbose_name='respuesta canónica'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('basica', 'Básica'), ('intermedia', 'Intermedia'), ('avanzada', 'Avanzada'), ('desafio', 'Desafío')], default='', max_length=12, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='question',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='minutos estimados'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, verbose_name='pista'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='puntaje'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('alternativa', 'Alternativa'), ('numerica', 'Numérica'), ('algebraica', 'Algebraica')], default='alternativa', max_length=12, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='question',
            name='scope',
            field=models.CharField(blank=True, choices=[('banco_visible', 'Banco visible'), ('evaluacion_nivel', 'Evaluación de nivel'), ('prueba_final', 'Prueba final')], default='', help_text='Vacío = sin clasificar; no entra al sistema nuevo.', max_length=20, verbose_name='ámbito'),
        ),
        migrations.AddField(
            model_name='quizattemptanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Respuesta escrita en preguntas numéricas/algebraicas.', verbose_name='texto ingresado'),
        ),
        migrations.AddField(
            model_name='topic',
            name='structured_bank_enabled',
            field=models.BooleanField(default=False, help_text='Si está apagado, el tema usa el sistema de evaluación actual.', verbose_name='banco estandarizado activado'),
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('evaluacion_nivel', 'Evaluación por nivel'), ('prueba_final', 'Prueba final')], max_length=20, verbose_name='tipo')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='nivel')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='nº de intento')),
                ('started_at', models.DateTimeField(verbose_name='inicio')),
                ('expires_at', models.DateTimeField(verbose_name='vencimiento')),
                ('status', models.CharField(choices=[('en_curso', 'En curso'), ('enviada', 'Enviada'), ('vencida', 'Vencida')], default='en_curso', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, help_text='Solo para evaluaciones por nivel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='content.resource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de evaluación',
                'verbose_name_plural': 'sesiones de evaluación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='content.evaluationsession')),
            ],
            options={
                'verbose_name': 'pregunta de sesión',
                'verbose_name_plural': 'preguntas de sesión',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='questions',
            field=models.ManyToManyField(related_name='evaluation_sessions', through='content.EvaluationSessionQuestion', to='content.question', verbose_name='preguntas seleccionadas'),
        ),
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1 — Definición'), (2, 'Nivel 2 — Ejercicios simples'), (3, 'Nivel 3 — Problemas de aplicación')], verbose_name='nivel')),
                ('difficulty', models.CharField(blank=True, choices=[('basica', 'Básica'), ('intermedia', 'Intermedia'), ('avanzada', 'Avanzada'), ('desafio', 'Desafío')], default='', max_length=12, verbose_name='dificultad')),
                ('objective', models.TextField(verbose_name='objetivo')),
                ('recommendation', models.TextField(blank=True, verbose_name='recomendación')),
                ('common_errors', models.TextField(blank=True, verbose_name='errores frecuentes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('status', models.CharField(choices=[('propuesto', 'Propuesto'), ('aprobado', 'Aprobado'), ('archivado', 'Archivado')], default='propuesto', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_items', to='content.topic', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'ítem de aprendizaje',
                'verbose_name_plural': 'ítems de aprendizaje',
                'ordering': ['topic', 'level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='exercise_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.exerciseitem', verbose_name='ítem'),
        ),
        migrations.CreateModel(
            name='LearningGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('structured_content', models.JSONField(blank=True, default=dict, help_text='Intro, resumen, fórmulas, ejemplos resueltos, ejercicios por ítem/dificultad, desafíos y solucionario.', verbose_name='contenido estructurado')),
                ('visibility', models.CharField(choices=[('interna', 'Interna'), ('publica', 'Pública')], default='interna', max_length=10, verbose_name='visibilidad')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_sources', models.ManyToManyField(blank=True, related_name='derived_guides', to='content.quizguide', verbose_name='fuentes privadas utilizadas')),
                ('resources', models.ManyToManyField(blank=True, related_name='learning_guides', to='content.resource', verbose_name='recursos')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_guides', to='content.topic', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'guía ProfeOnline',
                'verbose_name_plural': 'guías ProfeOnline',
                'ordering': ['topic', 'title'],
            },
        ),
        migrations.AddField(
            model_name='exerciseitem',
            name='learning_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content.learningguide', verbose_name='guía de origen'),
        ),
        migrations.AddField(
            model_name='question',
            name='learning_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='content.learningguide', verbose_name='guía de origen'),
        ),
        migrations.CreateModel(
            name='ResourceExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_quota', models.PositiveSmallIntegerField(default=0, verbose_name='cuota de práctica')),
                ('evaluation_quota', models.PositiveSmallIntegerField(default=0, verbose_name='cuota de evaluación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('exercise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='content.exerciseitem')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_item_links', to='content.resource')),
            ],
            options={
                'verbose_name': 'ítem por recurso',
                'verbose_name_plural': 'ítems por recurso',
                'ordering': ['exercise_item', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopicBankConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_eval_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='minutos por evaluación de nivel')),
                ('level_eval_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='intentos por evaluación de nivel')),
                ('final_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='minutos de la prueba final')),
                ('final_attempts', models.PositiveSmallIntegerField(default=2, verbose_name='intentos de la prueba final')),
                ('final_distribution', models.JSONField(default=apps.content.models.topic_bank_config.default_final_distribution, verbose_name='distribución de la prueba final')),
                ('network_tolerance_seconds', models.PositiveSmallIntegerField(default=15, verbose_name='tolerancia de red (s)')),
                ('duration_tolerance_pct', models.PositiveSmallIntegerField(default=10, verbose_name='tolerancia de duración (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_config', to='content.topic', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'configuración de banco por tema',
                'verbose_name_plural': 'configuraciones de banco por tema',
            },
        ),
        migrations.CreateModel(
            name='EvaluationSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='texto ingresado')),
                ('is_correct', models.BooleanField(default=False, verbose_name='es correcta')),
                ('points_awarded', models.FloatField(default=0, verbose_name='puntaje otorgado')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_session_answers', to='content.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.evaluationsession')),
            ],
            options={
                'verbose_name': 'respuesta de sesión de evaluación',
                'verbose_name_plural': 'respuestas de sesión de evaluación',
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='unique_session_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsession',
            constraint=models.UniqueConstraint(fields=('user', 'topic', 'kind', 'level', 'attempt_number'), name='unique_evaluation_session'),
        ),
        migrations.AddConstraint(
            model_name='resourceexerciseitem',
            constraint=models.UniqueConstraint(fields=('exercise_item', 'resource'), name='unique_item_resource'),
        ),
    ]
