# Generated by Django 6.0.5 on 2026-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_question_answer_tolerance_question_canonical_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseitem',
            name='detected_exercise_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de ejercicios de este ítem detectados por la IA en la guía de origen.', verbose_name='ejercicios detectados'),
        ),
    ]
