# Generated by Django 6.0.5 on 2026-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_exerciseitem_detected_exercise_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningguide',
            name='originality_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación de originalidad'),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='originality_content_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash de contenido validado'),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='originality_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='informe de originalidad'),
        ),
        migrations.AlterField(
            model_name='learningguide',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=10, verbose_name='estado'),
        ),
        migrations.AddConstraint(
            model_name='learningguide',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'publicada')), fields=('topic',), name='unique_active_published_guide_per_topic'),
        ),
    ]
