# Generated by Django 6.0.5 on 2026-06-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_topic_structured_bank_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_id', models.CharField(help_text='Llave eterna y única global. Ej: MAT.NUM.ENTEROS_CONJUNTO.NATURALES', max_length=120, unique=True, verbose_name='id semántico')),
                ('code', models.CharField(help_text='EE.BB.TT.RR para mostrar/ordenar. Único por asignatura.', max_length=20, verbose_name='código')),
                ('node_type', models.CharField(choices=[('asignatura', 'Asignatura'), ('eje', 'Eje'), ('bloque', 'Bloque'), ('tema', 'Tema'), ('recurso', 'Recurso')], max_length=12, verbose_name='tipo de nodo')),
                ('subject_abbr', models.CharField(help_text='MAT | FIS | QUI', max_length=10, verbose_name='asignatura (abrev.)')),
                ('axis_abbr', models.CharField(blank=True, help_text='NUM | ALG | GEO | EST | FUND (vacío en asignatura)', max_length=10, verbose_name='eje (abrev.)')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('competencia', models.CharField(blank=True, choices=[('M1', 'M1 — PAES obligatoria'), ('M2', 'M2 — PAES electiva'), ('U', 'U — Universitario / fuera de foco PAES')], max_length=2, verbose_name='competencia')),
                ('dificultad', models.CharField(blank=True, choices=[('basica', 'Básica'), ('media', 'Media'), ('avanzada', 'Avanzada')], max_length=10, verbose_name='dificultad')),
                ('cursos', models.JSONField(blank=True, default=list, verbose_name='cursos')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.knowledgenode', verbose_name='padre')),
            ],
            options={
                'verbose_name': 'nodo de conocimiento',
                'verbose_name_plural': 'nodos de conocimiento',
                'ordering': ['subject_abbr', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NodePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('requerido', 'Requerido'), ('recomendado', 'Recomendado')], default='requerido', max_length=12, verbose_name='tipo')),
                ('min_mastery', models.FloatField(default=0.75, verbose_name='dominio mínimo')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='content.knowledgenode', verbose_name='nodo')),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='content.knowledgenode', verbose_name='requiere')),
            ],
            options={
                'verbose_name': 'prerrequisito',
                'verbose_name_plural': 'prerrequisitos',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['node_type'], name='content_kno_node_ty_0ce6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['subject_abbr', 'axis_abbr'], name='content_kno_subject_9f89d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenode',
            constraint=models.UniqueConstraint(fields=('subject_abbr', 'code'), name='unique_code_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='nodeprerequisite',
            constraint=models.UniqueConstraint(fields=('node', 'requires'), name='unique_node_prerequisite'),
        ),
    ]
