# Generated by Django 6.0.5 on 2026-06-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_knowledgenode_nodeprerequisite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField(blank=True, verbose_name='objetivo')),
                ('explicacion', models.TextField(blank=True, verbose_name='explicación')),
                ('procedimiento', models.JSONField(blank=True, default=list, verbose_name='procedimiento')),
                ('ejemplos', models.JSONField(blank=True, default=list, verbose_name='ejemplos')),
                ('errores_frecuentes', models.JSONField(blank=True, default=list, verbose_name='errores frecuentes')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=12, verbose_name='estado')),
                ('fuente', models.TextField(blank=True, verbose_name='fuente')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.knowledgenode', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'contenido del nodo',
                'verbose_name_plural': 'contenidos de nodos',
            },
        ),
        migrations.CreateModel(
            name='NodeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('video_youtube', 'Video de YouTube'), ('file', 'Archivo'), ('external', 'Enlace externo')], max_length=16, verbose_name='tipo')),
                ('video_kind', models.CharField(blank=True, choices=[('explicacion', 'Explicación'), ('ejercicios_resueltos', 'Ejercicios resueltos'), ('complementario', 'Complementario')], max_length=20, verbose_name='subtipo de video')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to='node_media/', verbose_name='archivo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.knowledgenode', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'media del nodo',
                'verbose_name_plural': 'medias del nodo',
                'ordering': ['order'],
            },
        ),
    ]
