# Generated by Django 6.0.5 on 2026-06-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_nodecontent_nodemedia_f2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('purpose', models.TextField(blank=True, verbose_name='propósito')),
                ('level', models.CharField(choices=[('comprender', 'Comprender'), ('reconocer', 'Reconocer'), ('resolver', 'Resolver'), ('variar', 'Variar'), ('aplicar', 'Aplicar'), ('evaluar', 'Evaluar')], max_length=12, verbose_name='nivel')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('required_for_mastery', models.BooleanField(default=False, verbose_name='requerido para dominio')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='content.knowledgenode', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'grupo de ítems',
                'verbose_name_plural': 'grupos de ítems',
                'ordering': ['node', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NodeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(blank=True, default='', help_text='Llave idempotente para reimportar sin duplicar.', max_length=120, verbose_name='id estable')),
                ('kind', models.CharField(choices=[('item', 'Ejercicio concreto'), ('template', 'Patrón / generador')], default='item', max_length=10, verbose_name='tipo')),
                ('format', models.CharField(choices=[('multiple_choice', 'Selección múltiple'), ('open_answer', 'Respuesta abierta'), ('true_false', 'Verdadero / Falso'), ('matching', 'Términos pareados'), ('completion', 'Completación'), ('development', 'Desarrollo')], default='multiple_choice', max_length=20, verbose_name='formato')),
                ('difficulty', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('avanzada', 'Avanzada')], default='basica', max_length=10, verbose_name='dificultad')),
                ('competencia', models.CharField(blank=True, choices=[('M1', 'M1 — PAES obligatoria'), ('M2', 'M2 — PAES electiva'), ('U', 'U — Universitario / fuera de foco PAES')], max_length=2, verbose_name='competencia')),
                ('prompt', models.TextField(verbose_name='enunciado')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='alternativas')),
                ('correct_answer', models.TextField(blank=True, verbose_name='respuesta correcta')),
                ('solution_steps', models.TextField(blank=True, verbose_name='solución paso a paso')),
                ('explanation', models.TextField(blank=True, verbose_name='explicación')),
                ('conceptual_checks', models.JSONField(blank=True, default=list, verbose_name='chequeos conceptuales')),
                ('prerequisites', models.JSONField(blank=True, default=list, verbose_name='prerrequisitos detectados')),
                ('pattern', models.JSONField(blank=True, default=dict, help_text='Variables/restricciones cuando kind=template. Vacío en ejercicios concretos.', verbose_name='patrón generador')),
                ('paes_style', models.BooleanField(default=False, verbose_name='estilo PAES')),
                ('source_title', models.CharField(blank=True, max_length=200, verbose_name='fuente (título)')),
                ('source_location', models.CharField(blank=True, max_length=200, verbose_name='fuente (ubicación)')),
                ('source_reference', models.TextField(blank=True, verbose_name='fuente (referencia)')),
                ('source_kind', models.CharField(choices=[('notebooklm_extraction', 'Extracción NotebookLM'), ('manual', 'Manual'), ('generated', 'Generado'), ('rewritten', 'Reescrito')], default='manual', max_length=24, verbose_name='origen')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo'), ('review_required', 'Requiere revisión'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=16, verbose_name='estado')),
                ('legal_review', models.BooleanField(default=False, verbose_name='revisión legal')),
                ('rewrite_required', models.BooleanField(default=False, verbose_name='requiere reescritura')),
                ('duplicate_candidate', models.BooleanField(default=False, verbose_name='posible duplicado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.itemgroup', verbose_name='grupo de ítems')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.knowledgenode', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'ejercicio del nodo',
                'verbose_name_plural': 'ejercicios del nodo',
                'ordering': ['item_group', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemgroup',
            constraint=models.UniqueConstraint(fields=('node', 'code'), name='unique_item_group_per_node'),
        ),
        migrations.AddIndex(
            model_name='nodeexercise',
            index=models.Index(fields=['node', 'status'], name='content_nod_node_id_1ba36c_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexercise',
            index=models.Index(fields=['item_group', 'order'], name='content_nod_item_gr_070257_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodeexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('stable_id', ''), _negated=True), fields=('stable_id',), name='unique_node_exercise_stable_id'),
        ),
    ]
