# Generated by Django 6.0.5 on 2026-06-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_itemgroup_nodeexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado el'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
