# Generated by Django 6.0.5 on 2026-06-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_nodecontent_created_at_nodecontent_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='resumen',
            field=models.TextField(blank=True, verbose_name='resumen (IA)'),
        ),
    ]
