# Generated by Django 6.0.5 on 2026-06-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_nodecontent_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='introduccion',
            field=models.TextField(blank=True, verbose_name='introducción'),
        ),
    ]
