# Generated by Django 6.0.5 on 2026-07-02 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_add_introduccion_to_nodecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='manual_edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='editado manualmente el'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='manual_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_edited_node_contents', to=settings.AUTH_USER_MODEL, verbose_name='editado manualmente por'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Impide que load_node_content reemplace esta edición sin --force-manual.', verbose_name='protegido de importaciones'),
        ),
    ]
