# Generated by Django 6.0.5 on 2026-07-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_add_introduccion_to_nodecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='nivel')),
                ('score', models.PositiveSmallIntegerField(verbose_name='aciertos')),
                ('total', models.PositiveSmallIntegerField(verbose_name='total de preguntas')),
                ('passed', models.BooleanField(verbose_name='aprobado')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='número de intento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='content.knowledgenode', verbose_name='nodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_assessment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'intento de evaluación de nodo',
                'verbose_name_plural': 'intentos de evaluación de nodos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Definición'), (2, 'Ejercicios simples'), (3, 'Problemas de aplicación')], verbose_name='nivel')),
                ('text', models.TextField(verbose_name='enunciado')),
                ('explanation', models.TextField(blank=True, verbose_name='explicación')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=12, verbose_name='estado')),
                ('generation_key', models.CharField(blank=True, max_length=64, verbose_name='llave de generación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='content.knowledgenode', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'pregunta de evaluación de nodo',
                'verbose_name_plural': 'preguntas de evaluación de nodos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NodeAssessmentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='es correcta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.nodeassessmentquestion', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'alternativa de evaluación',
                'verbose_name_plural': 'alternativas de evaluación',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NodeAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='es correcta')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.nodeassessmentattempt', verbose_name='intento')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.nodeassessmentchoice', verbose_name='alternativa seleccionada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='content.nodeassessmentquestion', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'respuesta de intento de evaluación',
                'verbose_name_plural': 'respuestas de intentos de evaluación',
            },
        ),
        migrations.AddConstraint(
            model_name='nodeassessmentattempt',
            constraint=models.UniqueConstraint(fields=('user', 'node', 'level', 'attempt_number'), name='unique_user_node_level_attempt'),
        ),
    ]
