# Generated by Django 6.0.5 on 2026-07-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_nodeassessmentattempt_nodeassessmentquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceNodeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sugerido', 'Sugerido'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado'), ('sin_bloque', 'Sin bloque encontrado')], default='sugerido', max_length=12, verbose_name='estado')),
                ('origen', models.CharField(blank=True, choices=[('ia', 'IA'), ('manual', 'Manual')], max_length=8, verbose_name='origen')),
                ('ai_rationale', models.TextField(blank=True, verbose_name='razón de la IA')),
                ('ai_corrigio', models.BooleanField(default=False, verbose_name='la IA corrigió el candidato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_suggestions', to='content.knowledgenode', verbose_name='nodo')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_suggestion', to='content.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'sugerencia de nodo para recurso',
                'verbose_name_plural': 'sugerencias de nodo para recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
