# Generated by Django 6.0.5 on 2026-07-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_resourcenodesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_node',
            field=models.ForeignKey(blank=True, help_text='Bloque/Tema del árbol nuevo (/aprender/) al que corresponde este Tema legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_topics', to='content.knowledgenode', verbose_name='nodo de conocimiento vinculado'),
        ),
        migrations.DeleteModel(
            name='ResourceNodeSuggestion',
        ),
    ]
