# Generated by Django 6.0.5 on 2026-07-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_topic_related_node_delete_resourcenodesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='related_node',
            field=models.ForeignKey(blank=True, help_text='Vínculo puntual a un nodo específico, cuando el Tema completo no es suficientemente preciso para este video. Tiene prioridad sobre el vínculo del Tema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_resources', to='content.knowledgenode', verbose_name='nodo de conocimiento vinculado directamente'),
        ),
    ]
