# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0046_resource_related_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="infographic_alt_text",
            field=models.CharField(blank=True, default="", max_length=240, verbose_name="texto alternativo de infografía"),
        ),
        migrations.AddField(
            model_name="resource",
            name="infographic_key",
            field=models.CharField(blank=True, default="", help_text="Objeto privado en Railway Storage Bucket, servido por ProfeOnline.", max_length=320, verbose_name="clave de infografía editorial"),
        ),
    ]
