# Generated by Django 6.0.5 on 2026-07-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_resource_infographic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='concept_image_alt_text',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='texto alternativo de imagen conceptual'),
        ),
        migrations.AddField(
            model_name='resource',
            name='concept_image_key',
            field=models.CharField(blank=True, default='', help_text='Ilustración conceptual generada con IA y almacenada en Railway Storage Bucket.', max_length=320, verbose_name='clave de imagen conceptual'),
        ),
    ]
