# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0048_resource_concept_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="reading_checkpoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Tres preguntas formativas no calificadas, insertadas dentro de "
                    "la guía sin formar parte del banco de práctica y evaluación."
                ),
                verbose_name="comprobaciones durante la lectura",
            ),
        ),
    ]
