# Generated by Django 6.0.5 on 2026-08-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_resource_reading_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='al_terminar_debes_poder',
            field=models.TextField(blank=True, verbose_name='al terminar debes poder'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='checkpoints',
            field=models.JSONField(blank=True, default=list, help_text="Exactamente 2 checkpoints ('Comprueba tu avance'), validados por node_checkpoint_service.", verbose_name='comprobaciones intermedias'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='definiciones_clave',
            field=models.TextField(blank=True, verbose_name='definiciones clave'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='ejemplo_guiado',
            field=models.JSONField(blank=True, default=dict, help_text='Forma: {"enunciado": str, "pasos": [str, ...]}', verbose_name='ejemplo guiado'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='errores_correccion',
            field=models.TextField(blank=True, help_text='Texto explicativo; no reemplaza errores_frecuentes (fuente del V/F).', verbose_name='errores frecuentes y cómo corregirlos'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='explicacion_formal',
            field=models.TextField(blank=True, verbose_name='explicación formal'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='explicacion_simple',
            field=models.TextField(blank=True, verbose_name='explicación en palabras simples'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='propiedades_relaciones',
            field=models.TextField(blank=True, verbose_name='propiedades y relaciones importantes'),
        ),
        migrations.AddField(
            model_name='nodecontent',
            name='resumen_inicial',
            field=models.TextField(blank=True, verbose_name='resumen inicial'),
        ),
    ]
