# Generated by Django 6.0.5 on 2026-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_nodecontent_al_terminar_debes_poder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecontent',
            name='afirmaciones_verdaderas',
            field=models.JSONField(blank=True, default=list, help_text='Enunciados ciertos sobre el tema, usados para mezclar con errores_frecuentes en la sección Verdadero/Falso.', verbose_name='afirmaciones verdaderas'),
        ),
    ]
