from django.db import migrations


class Migration(migrations.Migration):
    """Colapsa 96 migraciones de carga de contenido (0052-0147) en un no-op.

    Todas eran RunPython idempotentes que reparseaban docs/conocimiento/ y llamaban
    load_node_content / load_exercise_bank / sync. Ese trabajo ahora lo hace el
    preDeployCommand de railway.json en cada deploy (ver railway.json). Mantener
    ~100 RunPython en el grafo solo inflaba el build de la BD de test en CI sin
    aportar esquema. `replaces` deja que Django trate esto como ya-aplicado en la
    BD de produccion (que ya paso por las 96) y como no-op en BDs nuevas/test.
    """

    replaces = [
        ("content", "0052_load_node_02_04_content"),
        ("content", "0053_load_node_02_05_content"),
        ("content", "0054_load_all_fixed_node_contents"),
        ("content", "0055_load_node_02_06_content"),
        ("content", "0056_load_node_03_01_content"),
        ("content", "0057_load_node_03_02_content"),
        ("content", "0058_load_node_03_03_content"),
        ("content", "0059_load_node_03_04_content"),
        ("content", "0060_load_node_03_05_content"),
        ("content", "0061_load_node_03_06_content"),
        ("content", "0062_load_node_03_07_content"),
        ("content", "0063_load_node_03_08_content"),
        ("content", "0064_load_node_03_09_content"),
        ("content", "0065_load_node_03_10_content"),
        ("content", "0066_load_node_03_11_content"),
        ("content", "0067_load_node_03_12_content"),
        ("content", "0068_load_node_03_13_content"),
        ("content", "0069_load_node_03_14_content"),
        ("content", "0070_load_node_03_15_content"),
        ("content", "0071_load_node_04_geometria_content"),
        ("content", "0072_load_node_02_06_content"),
        ("content", "0073_load_node_02_05_batch1_content"),
        ("content", "0074_load_node_02_05_batch2_content"),
        ("content", "0075_load_node_02_04_batch1_content"),
        ("content", "0076_load_node_02_04_content"),
        ("content", "0077_load_logica_basica_and_master_nodes"),
        ("content", "0078_load_logica_basica_svg_trilogy"),
        ("content", "0079_load_interactive_ejemplos"),
        ("content", "0080_load_conectivos_logicos_update"),
        ("content", "0081_load_tablas_verdad_update"),
        ("content", "0082_load_razonamiento_logico_update"),
        ("content", "0083_load_cuantificadores_update"),
        ("content", "0084_load_definicion_conjunto_update"),
        ("content", "0085_load_conjuntos_basicos_update"),
        ("content", "0086_load_relaciones_conjuntos_update"),
        ("content", "0087_load_diagramas_venn_update"),
        ("content", "0088_load_operaciones_conjuntos_update"),
        ("content", "0089_load_propiedades_conjuntos_update"),
        ("content", "0090_load_cardinalidad_conteo_update"),
        ("content", "0091_load_producto_cartesiano_update"),
        ("content", "0092_load_enteros_orden_update"),
        ("content", "0093_load_operatoria_enteros_update"),
        ("content", "0094_load_divisibilidad_update"),
        ("content", "0095_load_numeros_primos_update"),
        ("content", "0096_load_factorizacion_prima_update"),
        ("content", "0097_load_mcm_update"),
        ("content", "0098_load_mcd_update"),
        ("content", "0099_load_aplicaciones_mcm_mcd_update"),
        ("content", "0100_load_numeros_racionales_update"),
        ("content", "0101_load_fracciones_update"),
        ("content", "0102_load_clasificacion_fracciones_update"),
        ("content", "0103_load_equivalencia_fracciones_update"),
        ("content", "0104_load_comparacion_fracciones_update"),
        ("content", "0105_load_operatoria_fracciones_update"),
        ("content", "0106_load_propiedades_q_update"),
        ("content", "0107_load_clasificacion_decimales_update"),
        ("content", "0108_load_operatoria_decimales_update"),
        ("content", "0109_load_conversion_fraccion_decimal_update"),
        ("content", "0110_load_conversion_decimal_fraccion_update"),
        ("content", "0111_load_aproximaciones_update"),
        ("content", "0112_load_error_numerico_update"),
        ("content", "0113_load_numeros_irracionales_update"),
        ("content", "0114_load_numeros_reales_update"),
        ("content", "0115_load_potencias_update"),
        ("content", "0116_load_propiedades_potencias_update"),
        ("content", "0117_load_notacion_cientifica_update"),
        ("content", "0118_load_raices_reales_update"),
        ("content", "0119_load_propiedades_raices_update"),
        ("content", "0120_load_racionalizacion_update"),
        ("content", "0121_load_logaritmos_update"),
        ("content", "0122_load_propiedades_logaritmos_update"),
        ("content", "0123_load_numeros_imaginarios_update"),
        ("content", "0124_load_numeros_complejos_update"),
        ("content", "0125_load_razones_update"),
        ("content", "0126_load_proporciones_update"),
        ("content", "0127_load_proporcionalidad_directa_update"),
        ("content", "0128_load_proporcionalidad_inversa_update"),
        ("content", "0129_load_proporcionalidad_compuesta_update"),
        ("content", "0130_load_reparto_proporcional_escalas_update"),
        ("content", "0131_load_porcentajes_update"),
        ("content", "0132_load_variaciones_porcentuales_finanzas_update"),
        ("content", "0133_load_interes_simple_update"),
        ("content", "0134_load_interes_compuesto_update"),
        ("content", "0135_load_sucesiones_base_update"),
        ("content", "0136_load_progresion_aritmetica_update"),
        ("content", "0137_load_progresion_geometrica_update"),
        ("content", "0138_load_serie_geometrica_update"),
        ("content", "0139_load_progresiones_comparacion_update"),
        ("content", "0140_load_fundamentos_algebra_update"),
        ("content", "0141_load_termino_algebraico_update"),
        ("content", "0142_load_polinomios_basicos_update"),
        ("content", "0143_load_grado_ordenamiento_update"),
        ("content", "0144_load_clasificacion_tecnica_update"),
        ("content", "0145_sync_all_node_content_yamls"),
        ("content", "0146_sync_all_node_content_yamls_update"),
        ("content", "0147_load_all_node_content_canonical_update"),
    ]

    dependencies = [
        ("content", "0051_nodecontent_afirmaciones_verdaderas"),
    ]

    operations = []
