# Generated by Django 6.0.5 on 2026-09-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_squash_content_loads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSyncState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estado de sincronización de contenido',
                'verbose_name_plural': 'estados de sincronización de contenido',
            },
        ),
    ]
