# Generated by Django 6.0.3 on 2026-05-23 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_city_profile_education_level_and_more'),
        ('content', '0007_area_subject_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.level', verbose_name='nivel educativo'),
        ),
    ]
