# Generated by Django 6.0.5 on 2026-06-03 03:11

from django.db import migrations

def verify_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    # Obtenemos el modelo EmailAddress de allauth de forma dinámica
    try:
        EmailAddress = apps.get_model('account', 'EmailAddress')
    except LookupError:
        # Si por alguna razón la app de allauth no está cargada (por ejemplo en tests limitados)
        return

    for user in User.objects.all():
        if user.email:
            EmailAddress.objects.update_or_create(
                user=user,
                email=user.email,
                defaults={
                    'verified': True,
                    'primary': True
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_education_level'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(verify_existing_users),
    ]
