# Generated by Django 6.0.5 on 2026-06-03 03:11

from django.db import migrations

def verify_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    # Obtenemos el modelo EmailAddress de allauth de forma dinámica
    try:
        EmailAddress = apps.get_model('account', 'EmailAddress')
    except LookupError:
        # Si por alguna razón la app de allauth no está cargada (por ejemplo en tests limitados)
        return

    seen_emails = set()
    for user in User.objects.all().order_by('id'):
        if user.email:
            email_lower = user.email.lower().strip()
            if email_lower in seen_emails:
                continue

            existing_email = EmailAddress.objects.filter(email__iexact=email_lower).first()
            if existing_email:
                if existing_email.user == user:
                    existing_email.verified = True
                    existing_email.primary = True
                    existing_email.save()
                seen_emails.add(email_lower)
                continue

            try:
                EmailAddress.objects.create(
                    user=user,
                    email=user.email,
                    verified=True,
                    primary=True
                )
            except Exception:
                pass
            seen_emails.add(email_lower)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_education_level'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(verify_existing_users),
    ]
