from .resource_list import ResourceListView
from .resource_detail import ResourceDetailView
from .resource_create import ResourceCreateView
from .resource_update import ResourceUpdateView
from .resource_delete import ResourceDeleteView
from .subject_list import SubjectListView
from .subject_create import SubjectCreateView
from .subject_update import SubjectUpdateView
from .subject_delete import SubjectDeleteView
from .topic_list import TopicListView
from .topic_create import TopicCreateView
from .topic_update import TopicUpdateView
from .topic_delete import TopicDeleteView
from .topic_options import topic_options_by_subject
from .level_list import LevelListView
from .level_create import LevelCreateView
from .level_update import LevelUpdateView
from .level_delete import LevelDeleteView
from .module_list import ModuleListView
from .module_create import ModuleCreateView
from .module_update import ModuleUpdateView
from .module_delete import ModuleDeleteView