# scratch/build_alg_b0301_t7.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 16. EXPRESION_ENTERA
sid16 = "MAT.ALG.CLASIFICACION_TECNICA.EXPRESION_ENTERA"
RECURSOS.append({
    "semantic_id": sid16, "objetivo": "Reconocer expresiones algebraicas enteras por la ausencia de variables en sus denominadores.",
    "introduccion": "En el mundo de las expresiones algebraicas, no todo es lo que parece. A veces, ver una fracción no significa que la expresión esté 'rota'. Depende de quién esté en el sótano.",
    "resumen": "Una **Expresión Algebraica Entera** es aquella en la cual **no hay variables (letras) en ningún denominador** ni afectadas por exponentes negativos.",
    "explicacion": "Una expresión es 'entera' respecto a las letras, no respecto a los números.\n- $5x^2 + 3x$ es entera.\n- $\\frac{x}{2} + y$ es entera. ¡Sí, es entera! Aunque hay una fracción (división por 2), el número de abajo es una constante. La 'x' está arriba, segura.\n- $\\frac{5}{x} + 2$ NO es entera. Aquí la variable 'x' bajó al denominador. Esto la convierte en una expresión fraccionaria.\n\nRecuerda la ley de exponentes: un exponente negativo equivale a estar en el denominador ($x^{-2} = \\frac{1}{x^2}$). Por tanto, expresiones con exponentes literales negativos tampoco son enteras.",
    "procedimiento": ["Paso 1: Revisa visualmente todos los denominadores (la parte de abajo de cualquier fracción).", "Paso 2: Revisa también si hay alguna letra con un exponente negativo.", "Paso 3: Si no encuentras letras en denominadores ni con exponentes negativos, la expresión es Entera. (No importa si hay fracciones numéricas)."],
    "ejemplos": [
        {"titulo": "Falsas alarmas", "enunciado": "Determina si la expresión (x^2 + 5)/4 - y/3 es entera o no.", "solucion_pasos": ["Revisamos los denominadores: hay un 4 y un 3.", "Revisamos los exponentes de las letras: x tiene 2 (positivo), y tiene 1 (positivo).", "Como no hay letras abajo ni exponentes negativos, la expresión es Entera."]}
    ],
    "errores_frecuentes": ["Creer que la presencia de cualquier línea fraccionaria (como en $\\frac{x}{5}$) convierte automáticamente a la expresión en no-entera.", "Olvidar que $x^{-1}$ es matemáticamente igual a tener la $x$ en un denominador."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EENT-CONC-{i}", "semantic_id": sid16, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Bajo qué criterio técnico se clasifica a una expresión algebraica como 'Entera'? (v{i})", "choices": ["A) Cuando ninguna de sus variables (letras) se encuentra ubicada en un denominador, ni posee exponentes negativos.", "B) Cuando no existe absolutamente ninguna fracción en toda la expresión, ni siquiera numérica.", "C) Cuando todos los exponentes de las variables son números pares.", "D) Cuando carece de raíces cuadradas numéricas."], "correct_answer": "A) Cuando ninguna de sus variables (letras) se encuentra ubicada en un denominador, ni posee exponentes negativos.", "solution_steps": "La clasificación de entera se enfoca exclusivamente en la posición de las variables. Fracciones numéricas (como $\\frac{1}{2}$) son permitidas.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"EENT-REC-1", "semantic_id": sid16, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de las siguientes opciones corresponde a una Expresión Algebraica Entera.", "choices": ["A) $\\frac{x^2 - 4}{5} + x$", "B) $3x^2 + \\frac{5}{x}$", "C) $x^3 - x^{-2}$", "D) $\\frac{1}{a+b}$"], "correct_answer": "A) $\\frac{x^2 - 4}{5} + x$", "solution_steps": "En A, la x está en el numerador. En B, la x está en el denominador. En C, hay exponente negativo. En D, variables en el denominador.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EENT-PROC-{i}", "semantic_id": sid16, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $\\frac{3}{4}x^2 - \\frac{1}{2}x$ deja de ser entera debido a la presencia de las fracciones numéricas $\\frac{3}{4}$ y $\\frac{1}{2}$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Las fracciones numéricas son solo coeficientes racionales. Como las variables 'x' no están abajo dividiendo, la expresión sigue siendo estructuralmente entera respecto a las letras.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EENT-PAES-{i}", "semantic_id": sid16, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un programa de cálculo diferencial requiere que se ingresen exclusivamente 'Expresiones Algebraicas Enteras' para garantizar que el dominio sea todos los números reales (sin riesgo de división por cero). ¿Cuál de las siguientes fórmulas escritas por un usuario será aceptada por el programa? (v{i})", "choices": ["A) $P(t) = \\frac{t^3 - 5t}{100} + 4$", "B) $V(r) = \\frac{100}{r^2}$", "C) $F(x) = 5x^2 + 3x^{-1}$", "D) $G(y) = \\frac{y+2}{y-2}$"], "correct_answer": "A) $P(t) = \\frac{t^3 - 5t}{100} + 4$", "solution_steps": "Solo la opción A tiene a la variable (t) libre de denominadores y de exponentes negativos. Las demás poseen riesgo de división por cero en sus variables.", "paes_style": True})

# 17. EXPRESION_FRACCIONARIA
sid17 = "MAT.ALG.CLASIFICACION_TECNICA.EXPRESION_FRACCIONARIA"
RECURSOS.append({
    "semantic_id": sid17, "objetivo": "Reconocer expresiones algebraicas fraccionarias por la presencia de variables en el denominador.",
    "introduccion": "Cuando la letra principal de la historia se hunde en el sótano de una fracción, las reglas del juego cambian. La expresión ya no es 'entera'.",
    "resumen": "Una **Expresión Algebraica Fraccionaria** es aquella que tiene **al menos una variable (letra) figurando en un denominador**, o equivalentemente, que posee al menos una variable con un exponente negativo.",
    "explicacion": "A diferencia de las expresiones enteras (donde los números pueden estar abajo, pero las letras no), en las fraccionarias las letras son el divisor.\n- $\\frac{5}{x}$ es fraccionaria (la 'x' está dividiendo).\n- $x^2 + \\frac{1}{y}$ es fraccionaria (basta con que una variable esté en un denominador para contagiar a toda la expresión).\n- $3x^{-4}$ es fraccionaria, porque matemáticamente es igual a $\\frac{3}{x^4}$.\n\nEl gran problema de las expresiones fraccionarias es que su dominio ya no es infinito. Debemos tener cuidado de que esa letra en el denominador jamás tome el valor cero (porque la división por cero no está definida).",
    "procedimiento": ["Paso 1: Examina toda la expresión buscando divisiones (líneas fraccionarias).", "Paso 2: Si debajo de alguna línea fraccionaria hay una letra, la expresión es fraccionaria.", "Paso 3: Examina si alguna letra tiene exponente negativo. Si es así, también es fraccionaria."],
    "ejemplos": [
        {"titulo": "El infiltrado en el sótano", "enunciado": "Clasifica la expresión x^3/5 + 2/x + y.", "solucion_pasos": ["El primer término (x^3/5) es entero, la x está arriba.", "El segundo término (2/x) tiene a la variable x en el denominador.", "Al haber al menos una letra en el denominador, toda la expresión se clasifica como Fraccionaria."]}
    ],
    "errores_frecuentes": ["Confundir una fracción de números (como $\\frac{1}{2}x$) con una expresión fraccionaria. Recuerda: lo que hace fraccionaria a la expresión es la letra, no el número.", "Olvidar que las variables con exponentes negativos son fracciones disfrazadas."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EFRA-CONC-{i}", "semantic_id": sid17, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué elemento es el detonante exclusivo para que una expresión deje de ser entera y pase a clasificarse formalmente como una 'Expresión Algebraica Fraccionaria'? (v{i})", "choices": ["A) La presencia de al menos una variable (incógnita o letra) ubicada en el denominador de la expresión o con un exponente negativo.", "B) La existencia de cualquier fracción, incluso si solo involucra números como coeficientes.", "C) La presencia de una raíz cuadrada aplicada a un número.", "D) Que el grado absoluto de la expresión sea un número fraccionario."], "correct_answer": "A) La presencia de al menos una variable (incógnita o letra) ubicada en el denominador de la expresión o con un exponente negativo.", "solution_steps": "La posición de la variable en el divisor (abajo) es lo que define a las expresiones fraccionarias.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"EFRA-REC-1", "semantic_id": sid17, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de las siguientes expresiones se clasifica correctamente como Expresión Algebraica Fraccionaria.", "choices": ["A) $4x^2 + 5x^{-3}$", "B) $\\frac{x^2 - 1}{4}$", "C) $0.25x^3 - 0.5x$", "D) $\\frac{1}{2}x + \\frac{3}{4}y$"], "correct_answer": "A) $4x^2 + 5x^{-3}$", "solution_steps": "El exponente negativo $x^{-3}$ es equivalente a $\\frac{1}{x^3}$. Al bajar la variable al denominador, la expresión se vuelve fraccionaria.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EFRA-PROC-{i}", "semantic_id": sid17, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $P(x) = \\frac{5}{x+2}$ es fraccionaria, lo que implica matemáticamente que la variable $x$ no podrá tomar el valor $-2$ para evitar la división por cero?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Al ser fraccionaria (la variable está en el denominador), se deben restringir los valores que hacen cero el denominador ($x+2=0 \\rightarrow x=-2$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EFRA-PAES-{i}", "semantic_id": sid17, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una tarea de clasificación de dominios, se pide separar las funciones que tienen dominio real infinito de las que tienen restricciones. El profesor escribe $M = \\frac{{a+b}}{{100}}$ y $N = 100(a+b)^{{-1}}$. ¿Cómo debe clasificarlas el estudiante? (v{i})", "choices": ["A) M es una expresión entera (dominio infinito) y N es una expresión fraccionaria (dominio con restricciones).", "B) Ambas son expresiones fraccionarias porque las dos representan divisiones de alguna forma.", "C) Ambas son expresiones enteras porque ninguna usa el símbolo de fracción explícito con una letra abajo.", "D) M es fraccionaria y N es entera."], "correct_answer": "A) M es una expresión entera (dominio infinito) y N es una expresión fraccionaria (dominio con restricciones).", "solution_steps": "M tiene un denominador numérico fijo (100), es Entera. N tiene exponente -1 afectando a las variables, lo que es igual a $100/(a+b)$, es Fraccionaria.", "paes_style": True})

# 18. EXPRESION_RACIONAL
sid18 = "MAT.ALG.CLASIFICACION_TECNICA.EXPRESION_RACIONAL"
RECURSOS.append({
    "semantic_id": sid18, "objetivo": "Englobar las expresiones enteras y fraccionarias bajo el concepto general de Expresión Racional, excluyendo a las irracionales.",
    "introduccion": "En el reino animal, tanto los leones como los tigres son felinos. En el álgebra, tanto las expresiones enteras como las fraccionarias pertenecen a una misma gran familia: Las Racionales.",
    "resumen": "Una **Expresión Algebraica Racional** es el conjunto mayor que engloba tanto a las expresiones enteras como a las fraccionarias. Su característica definitoria es que **ninguna de sus variables está bajo el signo de una raíz (radical)** ni afectada por exponentes fraccionarios.",
    "explicacion": "La palabra 'racional' en matemáticas suele estar asociada a la idea de proporción o fracción sin componentes infinitos no periódicos. \n- $3x^2 + 5$ es racional (y además, entera).\n- $\\frac{2}{x}$ es racional (y además, fraccionaria).\n- $\\sqrt{5} \\cdot x$ es racional. (Ojo: ¡La raíz afecta al número 5, no a la 'x'!).\n\n¿Quién no entra a la fiesta? Las expresiones donde la *variable* está atrapada dentro de un radical, como $\\sqrt{x}$. Esas son la otra gran familia (Irracionales).",
    "procedimiento": ["Paso 1: Revisa toda la expresión buscando símbolos de raíz (cuadrada, cúbica, etc.) o exponentes en forma de fracción (ej. x^(1/2)).", "Paso 2: Si ves alguna raíz, fíjate qué hay adentro.", "Paso 3: Si dentro de la raíz SOLO hay números, y ninguna letra, la expresión sigue siendo Racional.", "Paso 4: Si no hay raíces afectando letras, puedes clasificarla con seguridad como Racional."],
    "ejemplos": [
        {"titulo": "El club racional", "enunciado": "Verifica si la expresión x^2 + 3/x - √7 es racional.", "solucion_pasos": ["El primer término no tiene raíz. Es racional.", "El segundo tiene una fracción (letra en denominador), pero no tiene raíz. Es racional.", "El tercero es √7. Es una raíz, pero adentro solo hay un número (el 7). No afecta a las variables.", "Conclusión: La expresión completa es Racional."]}
    ],
    "errores_frecuentes": ["Creer que la presencia de un número irracional (como $\\sqrt{2}$ o $\\pi$) vuelve a la expresión algebraica irracional. La clasificación depende del estado de las *variables*, no de las constantes numéricas.", "Pensar que una expresión no puede ser simultáneamente 'Fraccionaria' y 'Racional'. (Fraccionaria es un subtipo de Racional)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ERAC-CONC-{i}", "semantic_id": sid18, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué macro-clasificación engloba conjuntamente a las 'Expresiones Algebraicas Enteras' y a las 'Expresiones Algebraicas Fraccionarias', exigiendo únicamente que las variables no estén dentro de una raíz? (v{i})", "choices": ["A) Expresiones Algebraicas Racionales.", "B) Expresiones Algebraicas Irracionales.", "C) Polinomios Homogéneos.", "D) Ecuaciones Lineales."], "correct_answer": "A) Expresiones Algebraicas Racionales.", "solution_steps": "Las racionales son la gran familia matriz que acepta divisiones por letras, pero prohíbe las raíces sobre las letras.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ERAC-REC-1", "semantic_id": sid18, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Teniendo en cuenta que las constantes irracionales no afectan la clasificación de la variable, ¿cuál de las siguientes es una Expresión Algebraica Racional?", "choices": ["A) $\\sqrt{3} \\cdot x^2 + \\frac{5}{x}$", "B) $3\\sqrt{x} + 5$", "C) $x^{1/2} + 4$", "D) $\\frac{x}{\\sqrt{y}}$"], "correct_answer": "A) $\\sqrt{3} \\cdot x^2 + \\frac{5}{x}$", "solution_steps": "En A, la raíz solo envuelve al número 3, las x están libres de radicales. En B, C y D, las variables están afectadas por raíces (o exponentes fraccionarios que equivalen a raíces).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ERAC-PROC-{i}", "semantic_id": sid18, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si una expresión es 'Entera', entonces por definición teórica también pertenece a la familia de las expresiones 'Racionales'?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Las expresiones enteras son un subconjunto de las racionales. Si no tiene letras abajo (entera) tampoco tiene letras en raíces, por lo que cumple con ser racional.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ERAC-PAES-{i}", "semantic_id": sid18, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un sistema de cálculo pide que solo se ingresen 'Expresiones Racionales' (permitiendo tanto enteras como fraccionarias) porque no tiene el módulo para procesar raíces variables. Si un usuario ingresa la fórmula física del periodo del péndulo $T = 2\\pi \\sqrt{{\\frac{{L}}{{g}}}}$ (donde $L$ y $g$ son variables), ¿qué hará el sistema? (v{i})", "choices": ["A) La rechazará, porque las variables $L$ y $g$ están dentro de un radical, convirtiendo la expresión en Irracional.", "B) La aceptará, porque es una expresión fraccionaria ($L/g$).", "C) La aceptará, porque el número $2$ y $\\pi$ están fuera de la raíz.", "D) La rechazará exclusivamente por tener la letra $\\pi$."], "correct_answer": "A) La rechazará, porque las variables $L$ y $g$ están dentro de un radical, convirtiendo la expresión en Irracional.", "solution_steps": "Las variables $L$ y $g$ están bajo el techo de la raíz cuadrada. Esto la expulsa automáticamente de la familia Racional.", "paes_style": True})

# 19. EXPRESION_IRRACIONAL
sid19 = "MAT.ALG.CLASIFICACION_TECNICA.EXPRESION_IRRACIONAL"
RECURSOS.append({
    "semantic_id": sid19, "objetivo": "Identificar expresiones algebraicas irracionales por la presencia de variables dentro de un radical.",
    "introduccion": "A veces, las variables se quedan atrapadas bajo un techo del cual no pueden salir fácilmente. Ese 'techo' es el símbolo de la raíz.",
    "resumen": "Una **Expresión Algebraica Irracional** es aquella en la que **al menos una de sus variables (letras) se encuentra dentro del signo de una raíz (radical)**, o bien, está elevada a un exponente fraccionario.",
    "explicacion": "El término 'irracional' aquí significa que no se puede escribir como una simple razón (fracción) de polinomios ordinarios.\n- $\\sqrt{x}$ es una expresión irracional pura.\n- $5x^2 + \\sqrt[3]{y} - 2$ es irracional. (El polinomio entero $5x^2$ se 'contagia' de irracionalidad con la sola presencia de $\\sqrt[3]{y}$).\n- $z^{1/2}$ es irracional, porque un exponente fraccionario es la forma moderna de escribir una raíz ($z^{1/2} = \\sqrt{z}$).\n\nEl desafío con las expresiones irracionales de índice par (como la raíz cuadrada) es que su dominio está severamente restringido: lo que está dentro de la raíz no puede ser negativo en los números reales.",
    "procedimiento": ["Paso 1: Escanea la expresión en busca del símbolo radical ($\\sqrt{}$).", "Paso 2: Observa el interior del radical (el radicando).", "Paso 3: Si encuentras al menos una letra en el radicando, la expresión completa se clasifica como Irracional.", "Paso 4: También busca exponentes fraccionarios sobre letras (ej. $x^{2/3}$); si los hay, también es Irracional."],
    "ejemplos": [
        {"titulo": "Bajo techo", "enunciado": "Verifica la clasificación de la expresión 4x + √(xy) - 8.", "solucion_pasos": ["El primer término es entero (4x).", "El segundo término tiene el símbolo radical.", "Dentro del radical están las letras 'x' e 'y'.", "Por la presencia de este segundo término, la expresión total es Irracional."]}
    ],
    "errores_frecuentes": ["Clasificar como irracional a una expresión que tiene un número irracional, pero letras normales (ej. $\\sqrt{5} \\cdot x$). La irracionalidad algebraica requiere *variables* en la raíz.", "No reconocer que una letra elevada a una fracción (ej. $a^{3/4}$) es una expresión irracional oculta."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EIRR-CONC-{i}", "semantic_id": sid19, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué característica técnica obliga a que una expresión algebraica sea clasificada inmediatamente como 'Irracional'? (v{i})", "choices": ["A) La presencia de al menos una variable (letra) situada bajo el signo de un radical o afectada por un exponente fraccionario.", "B) La presencia de números infinitos no periódicos como $\\pi$ o $e$ multiplicando a las variables.", "C) La presencia de variables elevadas a exponentes negativos.", "D) El hecho de que la expresión no se pueda factorizar."], "correct_answer": "A) La presencia de al menos una variable (letra) situada bajo el signo de un radical o afectada por un exponente fraccionario.", "solution_steps": "La irracionalidad se define por el confinamiento de la incógnita dentro de una raíz.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"EIRR-REC-1", "semantic_id": sid19, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Identifica cuál de las siguientes es verdaderamente una Expresión Algebraica Irracional, diferenciándola de los distractores numéricos.", "choices": ["A) $x^2 - 3x + \\sqrt{2x}$", "B) $\\sqrt{3}x - \\sqrt{5}y$", "C) $\\frac{x^2}{\\sqrt{2}}$", "D) $x^{-2} + y^{-2}$"], "correct_answer": "A) $x^2 - 3x + \\sqrt{2x}$", "solution_steps": "En A, la variable x está dentro del radical $\\sqrt{2x}$. En B y C, las raíces solo encierran números. D es una expresión fraccionaria.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EIRR-PROC-{i}", "semantic_id": sid19, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión matemática $V = s^{1/3}$ es una expresión irracional porque su exponente fraccionario equivale a la raíz cúbica de la variable ($V = \\sqrt[3]{s}$)?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Todo exponente fraccionario es simplemente otra notación para escribir un radical. Al afectar a la variable, convierte la expresión en Irracional.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EIRR-PAES-{i}", "semantic_id": sid19, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Al analizar el modelo matemático del tiempo de caída de un objeto $t(h) = \\sqrt{{\\frac{{2h}}{{g}}}}$, donde $h$ (altura) es la única variable independiente del experimento y $g$ es una constante, un equipo debe clasificar la función. ¿Cuál es la clasificación técnica correcta de la expresión con respecto a $h$? (v{i})", "choices": ["A) Es una expresión Irracional, porque la variable $h$ se encuentra operando desde dentro de un signo radical.", "B) Es una expresión Racional Entera, porque $h$ está en el numerador de la fracción interna.", "C) Es una expresión Racional Fraccionaria, porque hay una división.", "D) Es un polinomio de primer grado."], "correct_answer": "A) Es una expresión Irracional, porque la variable $h$ se encuentra operando desde dentro de un signo radical.", "solution_steps": "Al margen de que sea una fracción ($2h/g$), todo el bloque está atrapado dentro de una gran raíz cuadrada. Al estar la variable bajo ese techo, la expresión principal es Irracional.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 7 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 7 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-7", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-7.jsonl con 40 ejercicios.")

if __name__ == "__main__":
    generate_all()
