# scratch/build_b0206_t3.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. DIFERENCIA_COMUN
sid1 = "MAT.NUM.PROG_ARITMETICA.DIFERENCIA_COMUN"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Calcular correctamente la diferencia común (d) de una progresión aritmética a partir de términos consecutivos.",
    "introduccion": "Si la Progresión Aritmética es un vehículo, la Diferencia Común 'd' es su motor. Nos dice a qué velocidad avanza la fila de números y, lo más importante, si va hacia adelante o en reversa.",
    "resumen": "La diferencia común se calcula siempre restando a un término cualquiera su término inmediatamente anterior: $d = a_n - a_{n-1}$. Un error en el signo de 'd' arruinará todos los cálculos posteriores.",
    "explicacion": "El cálculo de la diferencia **$d$** es matemáticamente muy sencillo, pero es la principal causa de error en las pruebas por descuidos con los signos.\n\n**Regla de Oro:** Siempre toma el término de la DERECHA y réstale el de la IZQUIERDA. NUNCA al revés.\n- P.A: $12, 17, 22\\dots$ $\\rightarrow$ $d = 17 - 12 = 5$.\n- P.A: $8, 5, 2\\dots$ $\\rightarrow$ $d = 5 - 8 = -3$. (¡Es negativo!)\n- P.A con negativos: $-10, -6, -2\\dots$ $\\rightarrow$ $d = -6 - (-10) = -6 + 10 = 4$.\n\nEs recomendable hacer la resta con dos pares de números distintos (ej. $a_2 - a_1$ y luego $a_3 - a_2$) para comprobar que no te hayas equivocado en una resta básica.",
    "procedimiento": ["Paso 1: Identifica dos números consecutivos en la progresión (ojalá los más fáciles, sin fracciones o números grandes si es posible).", "Paso 2: Al número que está más a la derecha, réstale el número que está a su izquierda.", "Paso 3: Respeta la ley de los signos si el número de la izquierda es negativo (terminarás sumando).", "Paso 4: El resultado de esa resta es 'd'."],
    "ejemplos": [
        {"titulo": "Cuidado con los negativos", "enunciado": "Calcula la diferencia de la P.A: 5, 1, -3, -7...", "solucion_pasos": ["Tomamos a2=1 y a1=5. Restamos: 1 - 5 = -4.", "Comprobamos con a3=-3 y a2=1. Restamos: -3 - 1 = -4.", "Comprobamos con a4=-7 y a3=-3. Restamos: -7 - (-3) = -7 + 3 = -4.", "La diferencia d es -4."]}
    ],
    "errores_frecuentes": ["Restar el número mayor menos el menor, sin importar su orden (ej. en 10, 8, 6, restar 10-8=2 en lugar de 8-10=-2).", "Olvidar los paréntesis al restar un número negativo, transformando $5 - (-2)$ en $5 - 2$."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFCOM-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes fórmulas describe el cálculo correcto e infalible para hallar la diferencia '$d$' en una progresión aritmética? (v{i})", "choices": [r"A) $d = a_n - a_{n-1}$", r"B) $d = a_{n-1} - a_n$", r"C) $d = a_n + a_{n-1}$", r"D) $d = a_n / a_{n-1}$"], "correct_answer": r"A) $d = a_n - a_{n-1}$", "solution_steps": "La resta siempre es: (término actual) menos (término anterior).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DIFCOM-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en una progresión aritmética calculas $a_2 - a_1$ y obtienes $+4$, y luego calculas $a_3 - a_2$ y obtienes $-4$, ¿qué puedes concluir?", "choices": ["A) Que la lista de números no corresponde realmente a una progresión aritmética.", "B) Que la diferencia 'd' es cero.", "C) Que debes sumar ambos resultados para obtener 'd'.", "D) Que la progresión es primero creciente y luego decreciente."], "correct_answer": "A) Que la lista de números no corresponde realmente a una progresión aritmética.", "solution_steps": "En una P.A. real, la diferencia debe ser siempre constante. Si varía, no es aritmética.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFCOM-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La diferencia de la progresión aritmética $-8, -12, -16, -20$ es igual a $4$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Restamos a2 - a1: $-12 - (-8) = -12 + 8 = -4$. La diferencia es $-4$, no $+4$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFCOM-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una empresa anota sus ganancias (y pérdidas) mensuales en una lista que sigue una progresión aritmética estricta. El mes 1 tuvieron $\$2.500.000$, el mes 2 bajaron a $\$1.800.000$ y el mes 3 a $\$1.100.000$. ¿Cuál es el valor matemático de la diferencia común '$d$' que modela esta situación? (v{i})", "choices": ["A) $-700.000$", "B) $700.000$", "C) $-1.400.000$", "D) $-1.100.000$"], "correct_answer": "A) $-700.000$", "solution_steps": "Término 2 menos Término 1: $1.800.000 - 2.500.000 = -700.000$.", "paes_style": True})

# 2. RECONOCIMIENTO
sid2 = "MAT.NUM.PROG_ARITMETICA.RECONOCIMIENTO"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Auditar una lista de números para determinar rápidamente si califica o no como progresión aritmética.",
    "introduccion": "No todo lo que brilla es oro, y no toda secuencia que suma es aritmética. A veces un solo número fuera de lugar rompe toda la regla. Es hora de poner a prueba las secuencias.",
    "resumen": "Para reconocer una Progresión Aritmética (P.A.), es obligatorio comprobar que la diferencia 'd' sea idéntica a lo largo de TODOS los pares consecutivos entregados en el problema.",
    "explicacion": "Una trampa clásica en las pruebas es darte una secuencia que parece aritmética en sus primeros términos, pero falla al final.\n\nSecuencia sospechosa: $3, 7, 11, 16$\n1. $7 - 3 = 4$\n2. $11 - 7 = 4$\n3. $16 - 11 = 5$ $\\rightarrow$ **¡Fallo!** Aunque empezó como P.A, no lo es. La regla se rompió.\n\nOtro caso de confusión son las sucesiones alternadas ($1, -1, 1, -1$). Al restar: $(-1) - 1 = -2$. Luego: $1 - (-1) = 2$. Como $-2$ es distinto de $2$, tampoco es una progresión aritmética.",
    "procedimiento": ["Paso 1: Calcula la diferencia entre el 2do y 1er término.", "Paso 2: Calcula la diferencia entre el 3er y 2do término.", "Paso 3: Continúa hasta agotar los números visibles.", "Paso 4: Si absolutamente todas las restas dan el mismo número, puedes declararla oficialmente como P.A."],
    "ejemplos": [
        {"titulo": "Desenmascarando al infiltrado", "enunciado": "¿Es $1/2, 1, 3/2, 2, 5/2$ una Progresión Aritmética?", "solucion_pasos": ["Pasamos a decimales para verlo fácil: 0.5, 1.0, 1.5, 2.0, 2.5.", "1.0 - 0.5 = 0.5", "1.5 - 1.0 = 0.5", "2.0 - 1.5 = 0.5", "2.5 - 2.0 = 0.5", "Sí lo es, la diferencia constante es 0.5 (o 1/2)."]}
    ],
    "errores_frecuentes": ["Comprobar solo los primeros dos números y asumir que la regla se mantiene para el resto.", "Confundir una sucesión geométrica (donde se multiplica, ej: 2, 4, 8) con una aritmética."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPA-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si en una prueba te entregan la lista de cinco números $a_1, a_2, a_3, a_4, a_5$ y te preguntan si forman una progresión aritmética, el método de validación estricto exige que: (v{i})", "choices": ["A) Existan cuatro restas consecutivas y que todas den el mismo resultado.", "B) Exista una sola resta entre $a_2$ y $a_1$ y que sea mayor a cero.", "C) La resta entre el último y el primer término dé un número par.", "D) Todos los números de la lista sean positivos."], "correct_answer": "A) Existan cuatro restas consecutivas y que todas den el mismo resultado.", "solution_steps": "Hay que probar cada par de vecinos. $a_2-a_1, a_3-a_2, a_4-a_3, a_5-a_4$. Todas deben ser iguales.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RECPA-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál de las siguientes sucesiones verbales NO describe una progresión aritmética?", "choices": ["A) Cada mes el capital se duplica respecto al mes anterior.", "B) Cada día ahorro 500 pesos más que el día anterior.", "C) La temperatura desciende exactamente 2 grados por cada hora que pasa.", "D) Un taxi cobra 300 pesos adicionales por cada cuadra recorrida."], "correct_answer": "A) Cada mes el capital se duplica respecto al mes anterior.", "solution_steps": "Duplicar implica multiplicar por 2. Eso es geométrico, no aritmético (sumar/restar).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPA-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La sucesión de fracciones $\\frac{1}{3}, \\frac{2}{3}, 1, \\frac{4}{3}, \\frac{5}{3}$ representa una Progresión Aritmética perfectamente válida?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Sabiendo que 1 es igual a 3/3, la serie es 1/3, 2/3, 3/3, 4/3, 5/3. Siempre se suma 1/3.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPA-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un software generador de contraseñas arroja las siguientes cuatro secuencias de números. ¿Cuál de ellas es la única que cumple matemáticamente con ser una Progresión Aritmética? (v{i})", "choices": ["A) $-10, -5, 0, 5, 10$", "B) $2, 4, 8, 16, 32$", "C) $100, 90, 81, 73, 66$", "D) $1, 0, 1, 0, 1$"], "correct_answer": "A) $-10, -5, 0, 5, 10$", "solution_steps": "A: Suma 5 constante. B: Multiplica por 2. C: Resta 10, luego 9, luego 8. D: Resta 1, suma 1 (alterna). La correcta es A.", "paes_style": True})

# 3. TERMINO_GENERAL
sid3 = "MAT.NUM.PROG_ARITMETICA.TERMINO_GENERAL"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Aplicar la fórmula universal del término general de una progresión aritmética para hallar cualquier valor lejano.",
    "introduccion": "Si tu sueldo sube 10.000 pesos cada mes, ¿cuánto ganarás en el mes 48? Contar con los dedos no sirve aquí. Es la hora de usar el cañón pesado: la fórmula de la Progresión Aritmética.",
    "resumen": "Cualquier término de una P.A. se puede calcular con la fórmula maestra: $a_n = a_1 + (n - 1) \\cdot d$. Solo necesitas el primer término ($a_1$), la posición que buscas ($n$) y la diferencia ($d$).",
    "explicacion": "Anatomía de la fórmula: **$a_n = a_1 + (n - 1) \\cdot d$**\n- **$a_n$**: Es el número que quieres descubrir (el 'futuro').\n- **$a_1$**: Es tu punto de partida. Desde dónde empiezas a contar.\n- **$d$**: Es el tamaño de cada paso que das.\n- **$(n - 1)$**: Es la cantidad de pasos que debes dar. ¿Por qué menos uno? Porque ya estás parado en el primer término ($a_1$), así que para llegar a la posición 10, solo debes dar 9 pasos.\n\nEjemplo: Tienes la progresión $5, 8, 11...$ y te piden el término en la posición 20.\n- $a_1 = 5$\n- $d = 3$ (porque $8-5=3$)\n- $n = 20$\nFórmula: $a_{20} = 5 + (20 - 1) \\cdot 3 \\rightarrow 5 + (19) \\cdot 3 \\rightarrow 5 + 57 = 62$. ¡Directo al blanco!",
    "procedimiento": ["Paso 1: Extrae de la serie el valor de a1 (el primer número).", "Paso 2: Calcula la diferencia 'd' restando el segundo menos el primero.", "Paso 3: Identifica la posición 'n' que te pide el problema.", "Paso 4: Reemplaza estos tres datos en la fórmula $a_n = a_1 + (n-1)d$ y resuelve, recordando multiplicar antes de sumar."],
    "ejemplos": [
        {"titulo": "Retrocediendo en el tiempo", "enunciado": "Halla el término 15 de la P.A: 100, 95, 90...", "solucion_pasos": ["a1 = 100.", "d = 95 - 100 = -5.", "n = 15.", "Fórmula: a15 = 100 + (15 - 1) * (-5)", "a15 = 100 + (14) * (-5)", "a15 = 100 - 70 = 30."]}
    ],
    "errores_frecuentes": ["Olvidar restar 1 a la 'n' en el paréntesis. (Ej: multiplicar por 20 pasos en lugar de 19 para llegar a la posición 20).", "Sumar $a_1 + (n-1)$ antes de multiplicar por la diferencia 'd' (Error grave de Papomudas)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPA-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la fórmula del término general de una Progresión Aritmética ($a_n = a_1 + (n-1) \\cdot d$), ¿cuál es la razón lógica de usar la expresión '$(n-1)$' en lugar de simplemente multiplicar por '$n$'? (v{i})", "choices": ["A) Porque para llegar desde el primer término ($a_1$) hasta la posición '$n$', se deben dar '$n-1$' pasos o 'saltos' de tamaño '$d$'.", "B) Porque la fórmula se descubrió empíricamente y el '-1' ajusta un error matemático.", "C) Porque el primer término siempre vale 1 y hay que anularlo.", "D) Porque las posiciones en las sucesiones comienzan en cero, no en uno."], "correct_answer": "A) Porque para llegar desde el primer término ($a_1$) hasta la posición '$n$', se deben dar '$n-1$' pasos o 'saltos' de tamaño '$d$'.", "solution_steps": "Si quieres ir de la posición 1 a la 2, das 1 salto. De la 1 a la 3, das 2 saltos. Siempre das (n-1) saltos.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TGENPA-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al aplicar la fórmula $a_n = a_1 + (n-1)d$, la jerarquía de las operaciones (Papomudas) indica que lo último que debes resolver es:", "choices": ["A) La suma (o resta) final con el término $a_1$.", "B) El paréntesis $(n-1)$.", "C) La multiplicación por '$d$'.", "D) Encontrar el valor de '$d$'."], "correct_answer": "A) La suma (o resta) final con el término $a_1$.", "solution_steps": "Orden: Paréntesis (n-1), Multiplicación por d, y finalmente Sumar a1.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPA-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El término de posición $10$ de una progresión aritmética que empieza en $2$ ($a_1=2$) y va de $5$ en $5$ ($d=5$) es exactamente $52$?", "choices": [], "correct_answer": "Falso", "solution_steps": "a10 = 2 + (10-1)*5 = 2 + 9*5 = 2 + 45 = 47. Es falso (no 52, eso sería multiplicar por 10).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPA-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"La cuota mensual de mantenimiento de un edificio aumenta cada año según una progresión aritmética. En el año 1 la cuota es de $\$20.000$, en el año 2 es de $\$21.500$ y en el año 3 de $\$23.000$. Utilizando la fórmula correspondiente, ¿cuál será el valor de la cuota en el año 12? (v{i})", "choices": ["A) $\$36.500$", "B) $\$38.000$", "C) $\$35.000$", "D) $\$41.500$"], "correct_answer": "A) $\$36.500$", "solution_steps": "a1 = 20.000. d = 1.500. n = 12. Fórmula: a12 = 20000 + (12-1)*1500 = 20000 + 11*1500 = 20000 + 16500 = 36.500.", "paes_style": True})

# 4. CALCULO_PRIMER_TERMINO
sid4 = "MAT.NUM.PROG_ARITMETICA.CALCULO_PRIMER_TERMINO"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Despejar y calcular el primer término ($a_1$) de una P.A. conociendo un término cualquiera y la diferencia.",
    "introduccion": "A veces entras al cine cuando la película ya empezó. Te muestran el final de la progresión y te piden descubrir cómo empezó. Para esto debemos usar nuestra fórmula maestra, pero caminando hacia atrás.",
    "resumen": "Si conoces un término lejano ($a_n$), su posición ($n$) y la diferencia ($d$), puedes hallar el origen ($a_1$) despejando la fórmula principal: $a_1 = a_n - (n - 1) \\cdot d$.",
    "explicacion": "El término general funciona como una ecuación. Si tienes 3 de las 4 piezas del rompecabezas, puedes encontrar la faltante despejando la incógnita.\n\nFórmula original: $a_n = a_1 + (n-1)d$\nSi queremos encontrar $a_1$, simplemente pasamos todo el bloque de los pasos restando hacia el otro lado:\n**Fórmula despejada:** $a_1 = a_n - (n-1)d$\n\nTraducción lógica: 'Al término donde estoy ahora, le RESTO todos los pasos que di, y así regreso al inicio'.\n\nEjemplo: Sabemos que el término 8 vale 40 ($a_8=40$) y que la sucesión avanza de 4 en 4 ($d=4$). ¿Cuál era el primer número?\n- $a_1 = 40 - (8-1) \\cdot 4$\n- $a_1 = 40 - (7) \\cdot 4$\n- $a_1 = 40 - 28 = 12$. \n¡La película empezó en el 12!",
    "procedimiento": ["Paso 1: Identifica el valor del término conocido ($a_n$) y qué posición ocupa ($n$).", "Paso 2: Identifica la diferencia ($d$).", "Paso 3: Calcula cuántos pasos hay entre tu posición y el inicio (que es $n-1$).", "Paso 4: Multiplica esos pasos por la diferencia y réstaselo a tu término conocido."],
    "ejemplos": [
        {"titulo": "Buscando las raíces", "enunciado": "El décimo término de una P.A. es 5 y la diferencia es -2. ¿Cuánto vale el primer término?", "solucion_pasos": ["Datos: a10=5, n=10, d=-2.", "Fórmula: a1 = a10 - (10-1)*d", "a1 = 5 - (9) * (-2)", "a1 = 5 - (-18)", "a1 = 5 + 18 = 23."]}
    ],
    "errores_frecuentes": ["Equivocarse en la regla de los signos al restar un bloque que contiene una diferencia negativa, como en $40 - (7 \\cdot -4)$.", "Sustituir los datos de '$a_n$' y '$n$' al revés en la ecuación."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCINI-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si transformamos la fórmula $a_n = a_1 + (n-1)d$ con el objetivo de despejar el primer término ($a_1$), la expresión matemática correcta y equivalente es: (v{i})", "choices": [r"A) $a_1 = a_n - (n-1)d$", r"B) $a_1 = a_n + (n-1)d$", r"C) $a_1 = \frac{a_n}{(n-1)d}$", r"D) $a_1 = (a_n - 1)d$"], "correct_answer": r"A) $a_1 = a_n - (n-1)d$", "solution_steps": "El término $+(n-1)d$ pasa completo restando hacia el lado de $a_n$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CALCINI-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Desde el punto de vista lógico, si me encuentro en la posición $15$ y quiero regresar a la posición $1$ (el primer término), debo deshacer o retroceder exactamente:", "choices": ["A) $14$ pasos.", "B) $15$ pasos.", "C) $16$ pasos.", "D) $1$ paso."], "correct_answer": "A) $14$ pasos.", "solution_steps": "De la posición 1 a la 15 hay $15 - 1 = 14$ intervalos o pasos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCINI-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si el sexto término de una P.A. es $20$ y la diferencia es $2$, entonces el primer término necesariamente debe ser $10$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "a1 = 20 - (6-1)*2 = 20 - 5*2 = 20 - 10 = 10. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCINI-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un atleta corre diariamente aumentando su distancia en una cantidad fija (progresión aritmética). El día número $8$ de su entrenamiento logró correr exactamente $12$ km. Si se sabe que cada día aumentaba su distancia en $0.5$ km ($d=0.5$), ¿cuántos kilómetros corrió el primer día de su plan? (v{i})", "choices": ["A) $8.5$ km.", "B) $8.0$ km.", "C) $9.0$ km.", "D) $7.5$ km."], "correct_answer": "A) $8.5$ km.", "solution_steps": "a8 = 12, d = 0.5, n = 8. Despejamos: a1 = 12 - (8-1)*0.5 = 12 - 7*0.5 = 12 - 3.5 = 8.5 km.", "paes_style": True})

# 5. CALCULO_INDICE
sid5 = "MAT.NUM.PROG_ARITMETICA.CALCULO_INDICE"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Despejar y calcular la posición (n) que ocupa un número específico dentro de una progresión aritmética.",
    "introduccion": "¿A qué hora llegará el tren a la estación número 50? Ya sabemos calcular el número conociendo la posición, pero ¿y si te dan el número y te preguntan en qué asiento va sentado? Esto requiere encontrar la incógnita 'n'.",
    "resumen": "Para saber la posición de un término, despejamos '$n$' de la fórmula general: $n = \\frac{a_n - a_1}{d} + 1$. El resultado final siempre debe ser un número entero positivo.",
    "explicacion": "Supongamos que el primer término es 3 ($a_1=3$) y vas sumando 4 ($d=4$). De repente encuentras el número 43. ¿Qué posición ocupa en la lista?\n\nVolvemos a nuestra fiel ecuación $a_n = a_1 + (n-1)d$, pero ahora la incógnita es '$n$'.\n**Fórmula despejada para el índice:**\n$$n = \\frac{a_n - a_1}{d} + 1$$\n\nTraducción lógica: 'Resto mi destino menos el inicio para saber la distancia total. Divido por el tamaño del paso para saber cuántos pasos di. Y le sumo 1 porque ya estaba parado en el primer casillero'.\n\nResolviendo el ejemplo:\n- $n = \\frac{43 - 3}{4} + 1$\n- $n = \\frac{40}{4} + 1$\n- $n = 10 + 1 = 11$\nEl número 43 está en la 11va posición.",
    "procedimiento": ["Paso 1: Resta el término final menos el término inicial ($a_n - a_1$).", "Paso 2: Divide ese resultado por la diferencia constante 'd'.", "Paso 3: Súmale 1 al resultado de la división.", "Paso 4: Comprueba que tu respuesta sea un número natural (no puede existir la posición 3.5 o -2)."],
    "ejemplos": [
        {"titulo": "¿Qué número de cliente eres?", "enunciado": "La sucesión es 15, 20, 25... ¿En qué posición se encuentra el número 105?", "solucion_pasos": ["a1 = 15, d = 5. Destino an = 105.", "Distancia total: 105 - 15 = 90.", "Pasos dados: 90 / 5 = 18.", "Posición final: 18 + 1 = 19.", "El 105 está en la posición 19."]}
    ],
    "errores_frecuentes": ["Olvidar sumar el '+1' al final del despeje, entregando como respuesta solo el número de 'saltos'.", "Dividir por 'd' antes de haber hecho la resta $a_n - a_1$ (error de jerarquía de fracciones)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCIND-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si al despejar la posición '$n$' de un número dentro de una progresión aritmética el resultado final nos da $n = 5.3$, ¿cuál es la interpretación matemática correcta? (v{i})", "choices": ["A) Ese número no pertenece y jamás aparecerá en la sucesión, pues las posiciones deben ser enteros positivos.", "B) El número aparecerá entre la quinta y la sexta posición si dibujamos una gráfica.", "C) Hubo un error de cálculo porque 'n' siempre debe ser menor a 5.", "D) La sucesión es de tipo decimal."], "correct_answer": "A) Ese número no pertenece y jamás aparecerá en la sucesión, pues las posiciones deben ser enteros positivos.", "solution_steps": "No existe la posición 5.3 en una fila, igual que no existe la persona número 5.3 en una cola del banco. 'n' debe ser Natural.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CALCIND-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al utilizar la fórmula rápida $n = \\frac{a_n - a_1}{d} + 1$, el acto de sumar $1$ al final del cálculo representa lógicamente:", "choices": ["A) Contabilizar el primer término o punto de partida, que ocurre antes de dar el primer 'paso'.", "B) Un ajuste por el margen de error de la división.", "C) La diferencia constante de la progresión.", "D) El último término de la lista."], "correct_answer": "A) Contabilizar el primer término o punto de partida, que ocurre antes de dar el primer 'paso'.", "solution_steps": "La división $\\frac{a_n - a_1}{d}$ calcula los 'intervalos' o pasos. Hay que sumar 1 para convertir intervalos en cantidad de postes/términos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCIND-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El número $50$ ocupa la posición $n=10$ en la progresión aritmética que arranca en $5$ ($a_1=5$) y aumenta de $5$ en $5$ ($d=5$)?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$n = (50 - 5)/5 + 1 = 45/5 + 1 = 9 + 1 = 10$. Verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCIND-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una piscina pierde $20$ litros de agua cada día debido a una filtración (progresión aritmética). El día 1 la piscina tenía $1.000$ litros ($a_1 = 1000$). Si la diferencia de volumen diario es $d = -20$, ¿en qué día exacto el volumen de la piscina llegará por primera vez a los $400$ litros? (v{i})", "choices": ["A) Día $31$.", "B) Día $30$.", "C) Día $29$.", "D) Día $32$."], "correct_answer": "A) Día $31$.", "solution_steps": "$n = (400 - 1000)/(-20) + 1 = (-600)/(-20) + 1 = 30 + 1 = 31$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 3 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 3 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-3", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-3.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
