# scratch/build_alg_b0302_t7.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 30. MULTIPLES_VARIABLES
sid30 = "MAT.ALG.VALORIZACION.MULTIPLES_VARIABLES"
RECURSOS.append({
    "semantic_id": sid30, "objetivo": "Valorizar expresiones algebraicas que contienen más de una variable distinta.",
    "introduccion": "Muchas fórmulas en la vida real dependen de más de un factor. El área de un rectángulo depende de la base y de la altura. Al valorizar, simplemente tenemos que reemplazar cada letra por su número correspondiente, sin mezclarlas.",
    "resumen": "Al valorizar **Múltiples Variables**, se debe sustituir cada letra por su respectivo valor numérico de forma independiente. Si las variables están juntas (como en $xy$), significa que sus valores numéricos **se multiplican**.",
    "explicacion": "Consideremos la expresión $5xy + z$.\nSi nos dan los valores $x=2$, $y=3$, $z=4$:\n1. Reemplazamos la $x$ por (2).\n2. Reemplazamos la $y$ por (3).\n3. Reemplazamos la $z$ por (4).\nLa expresión queda: $5(2)(3) + (4)$.\n\nEl error fatal aquí es leer $xy$ como un número de dos cifras (ej. si $x=2$ e $y=3$, pensar que $xy$ es 23). ¡Falso! Es una multiplicación: $2 \\cdot 3 = 6$. Por eso el uso de paréntesis es obligatorio.",
    "procedimiento": ["Paso 1: Asigna a cada variable su valor numérico específico sin confundirlas.", "Paso 2: Sustituye las letras en la expresión por los números entre paréntesis.", "Paso 3: Si dos o más letras estaban pegadas (ej. abc), multiplica sus valores numéricos.", "Paso 4: Resuelve el resto de las operaciones respetando la jerarquía."],
    "ejemplos": [
        {"titulo": "Tres letras, un resultado", "enunciado": "Valoriza $a^2 + bc$, sabiendo que a=3, b=2, c=5.", "solucion_pasos": ["Reemplazamos: (3)^2 + (2)(5).", "Resolvemos la potencia: 9 + (2)(5).", "Resolvemos la multiplicación: 9 + 10.", "Sumamos: 19."]}
    ],
    "errores_frecuentes": ["Juntar los números en lugar de multiplicarlos (leer $ab$ como $23$ en lugar de $2 \\cdot 3$).", "Reemplazar el valor de una variable en el lugar de otra (confundir el valor de $x$ con el de $y$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MVAR-CONC-{i}", "semantic_id": sid30, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al valorizar un término algebraico que contiene variables yuxtapuestas como $xyz$, si $x=1, y=2, z=3$, ¿cuál es el error conceptual más grave al interpretar el resultado de la sustitución? (v{i})", "choices": ["A) Interpretar la yuxtaposición como la formación de un número posicional (ej. leerlo como $123$), en lugar de reconocer que las variables yuxtapuestas se multiplican ($1 \\cdot 2 \\cdot 3 = 6$).", "B) Interpretar que las variables deben sumarse ($1+2+3=6$).", "C) Interpretar que el resultado siempre será un número negativo.", "D) Creer que se debe multiplicar por $3$ debido a la cantidad de letras."], "correct_answer": "A) Interpretar la yuxtaposición como la formación de un número posicional (ej. leerlo como $123$), en lugar de reconocer que las variables yuxtapuestas se multiplican ($1 \\cdot 2 \\cdot 3 = 6$).", "solution_steps": "La yuxtaposición en álgebra (letras juntas) siempre implica multiplicación. Nunca es concatenación de dígitos.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MVAR-REC-1", "semantic_id": sid30, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Valora la expresión $2ab - c$ cuando $a = 4$, $b = 5$ y $c = 10$.", "choices": ["A) $30$", "B) $40$", "C) $70$", "D) $10$"], "correct_answer": "A) $30$", "solution_steps": "Reemplazamos: $2(4)(5) - 10$. Multiplicamos el primer término: $2 \\cdot 4 = 8$, luego $8 \\cdot 5 = 40$. Restamos $c$: $40 - 10 = 30$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MVAR-PROC-{i}", "semantic_id": sid30, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El valor numérico de $x^2 y$ es exactamente el mismo que el de $xy^2$ si se evalúan ambas para $x=2$ e $y=3$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Para $x=2, y=3$:\nEn $x^2 y$: el 2 está al cuadrado $\\rightarrow (2^2)(3) = 4 \\cdot 3 = 12$.\nEn $xy^2$: el 3 está al cuadrado $\\rightarrow (2)(3^2) = 2 \\cdot 9 = 18$.\nEl exponente solo afecta a la base inmediata que tiene debajo, no a toda la expresión.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MVAR-PAES-{i}", "semantic_id": sid30, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"La energía potencial elástica de un resorte se calcula con la fórmula $E = \\frac{1}{2} k x^2$, donde $k$ es la constante del resorte y $x$ es la deformación. Si para un experimento $k = 100$ y $x = 4$, ¿cuál es el valor de la energía $E$? (v{i})", "choices": ["A) $800$", "B) $160000$", "C) $400$", "D) $200$"], "correct_answer": "A) $800$", "solution_steps": "Sustituimos: $E = \\frac{1}{2}(100)(4)^2$. Por jerarquía, primero la potencia: $4^2 = 16$. Luego la multiplicación: $\\frac{1}{2} \\cdot 100 \\cdot 16 = 50 \\cdot 16 = 800$.", "paes_style": True})

# 31. MONOMIO_ENTEROS
sid31 = "MAT.ALG.VALORIZACION.MONOMIO_ENTEROS"
RECURSOS.append({
    "semantic_id": sid31, "objetivo": "Valorizar monomios simples con coeficientes y variables enteras.",
    "introduccion": "Un monomio es un bloque sólido de álgebra, sin sumas ni restas que lo dividan. Todo está conectado por la multiplicación. Es el ladrillo fundamental.",
    "resumen": "Para valorizar un **Monomio**, se sustituyen sus variables por los números dados y se realiza la **multiplicación continuada** entre el coeficiente (el número inicial) y los valores de las letras.",
    "explicacion": "Ejemplo de monomio: $7m^2n$.\nEste término es en realidad una multiplicación triple oculta: $7 \\cdot m^2 \\cdot n$.\nSi $m=2$ y $n=3$:\n1. Sustituimos: $7 \\cdot (2)^2 \\cdot (3)$.\n2. Papomudas nos obliga a resolver la potencia primero: $2^2 = 4$.\n3. La expresión queda como una cadena de multiplicaciones puras: $7 \\cdot 4 \\cdot 3$.\n4. Resolvemos de izquierda a derecha (o en el orden que prefieras, la multiplicación es conmutativa): $28 \\cdot 3 = 84$.",
    "procedimiento": ["Paso 1: Identifica el coeficiente (el número grande adelante) y anótalo.", "Paso 2: Sustituye las letras por sus valores numéricos entre paréntesis.", "Paso 3: Aplica los exponentes a los valores que los tengan.", "Paso 4: Multiplica todos los números resultantes para obtener el valor final del monomio."],
    "ejemplos": [
        {"titulo": "El bloque irrompible", "enunciado": "Valora -3xy^3 para x=4, y=2.", "solucion_pasos": ["Sustituyendo: -3 * (4) * (2)^3.", "Potencia primero: 2^3 = 8.", "Expresión: -3 * 4 * 8.", "Multiplicando: -12 * 8 = -96."]}
    ],
    "errores_frecuentes": ["Multiplicar primero y elevar a la potencia después. (Ej: $(2 \\cdot 3)^2$ en lugar de $2 \\cdot 3^2$).", "Ignorar el signo negativo del coeficiente inicial."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONO-CONC-{i}", "semantic_id": sid31, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al evaluar el monomio $5x^2y$, ¿qué operación aritmética debe resolverse primero estrictamente según la jerarquía de las operaciones (PAPOMUDAS)? (v{i})", "choices": ["A) La potencia de $x$ ($x^2$), antes de multiplicar por el $5$ o por $y$.", "B) La multiplicación de $5$ por $x$, y luego elevar ese resultado al cuadrado.", "C) La multiplicación de $x$ por $y$.", "D) Es indiferente, en la multiplicación el orden no altera el producto."], "correct_answer": "A) La potencia de $x$ ($x^2$), antes de multiplicar por el $5$ o por $y$.", "solution_steps": "Las potencias siempre tienen prioridad sobre las multiplicaciones. El cuadrado solo afecta a la $x$, no al 5 ni a la $y$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MONO-REC-1", "semantic_id": sid31, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Calcula el valor numérico de $4a^3b$ cuando $a=2$ y $b=5$.", "choices": ["A) $160$", "B) $40$", "C) $4000$", "D) $120$"], "correct_answer": "A) $160$", "solution_steps": "Sustituimos: $4(2)^3(5)$. Resolvemos potencia: $2^3 = 8$. Queda: $4 \\cdot 8 \\cdot 5 = 32 \\cdot 5 = 160$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONO-PROC-{i}", "semantic_id": sid31, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El valor del monomio $-2x^2$ evaluado en $x=3$ es $36$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Sustituyendo: $-2(3)^2$. Primero la potencia: $3^2 = 9$. Luego multiplicamos: $-2 \\cdot 9 = -18$. Quien obtuvo 36 (o -36) multiplicó primero (-6) y luego elevó al cuadrado, lo cual rompe la jerarquía.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONO-PAES-{i}", "semantic_id": sid31, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"La fórmula para el volumen de una pirámide de base cuadrada es $V = \\frac{1}{3} a^2 h$, donde $a$ es la arista de la base y $h$ la altura. Si un arquitecto diseña una pirámide con $a = 6$ m y $h = 10$ m, ¿cuál será su volumen en metros cúbicos? (v{i})", "choices": ["A) $120$", "B) $360$", "C) $400$", "D) $40$"], "correct_answer": "A) $120$", "solution_steps": "Sustituimos en el monomio: $V = \\frac{1}{3} (6)^2 (10)$. Potencia: $6^2 = 36$. Multiplicamos: $\\frac{1}{3} \\cdot 36 = 12$. Finalmente, $12 \\cdot 10 = 120$.", "paes_style": True})

# 32. POLINOMIO_ENTEROS
sid32 = "MAT.ALG.VALORIZACION.POLINOMIO_ENTEROS"
RECURSOS.append({
    "semantic_id": sid32, "objetivo": "Valorizar polinomios resolviendo múltiples términos separados por sumas y restas.",
    "introduccion": "Un polinomio es como un tren. Está compuesto por varios vagones (monomios) unidos por enganches de suma o resta. Para calcular el peso total del tren, primero calculamos el peso de cada vagón por separado y luego los sumamos todos.",
    "resumen": "Al valorizar un **Polinomio**, se debe evaluar cada término (monomio) de forma independiente respetando la jerarquía de operaciones, y **al final se realizan las sumas y restas** que conectan a los términos.",
    "explicacion": "Sea el polinomio: $2x^2 - 3x + 5$, para $x=4$.\nEvaluamos vagón por vagón:\n- Primer vagón ($2x^2$): $2(4)^2 = 2(16) = 32$.\n- Segundo vagón ($3x$): $3(4) = 12$.\n- Tercer vagón ($5$): Es una constante, se queda como 5.\n\nAhora reconstruimos el tren con sus signos originales:\n$32 - 12 + 5$\nOperamos de izquierda a derecha:\n$20 + 5 = 25$.\n¡Ese es el valor del polinomio!",
    "procedimiento": ["Paso 1: Sustituye la variable en cada término del polinomio.", "Paso 2: Resuelve las potencias y multiplicaciones dentro de cada término individual.", "Paso 3: Reescribe el polinomio completo solo con los resultados numéricos de cada término y sus signos originales.", "Paso 4: Realiza las sumas y restas finales de izquierda a derecha."],
    "ejemplos": [
        {"titulo": "El tren polinómico", "enunciado": "Valora 3a^2 - 2a + 1 para a=5.", "solucion_pasos": ["Sustitución: 3(5)^2 - 2(5) + 1.", "Primer término: 3(25) = 75.", "Segundo término: 2(5) = 10.", "Reescribiendo: 75 - 10 + 1.", "Resultado: 65 + 1 = 66."]}
    ],
    "errores_frecuentes": ["Mezclar términos antes de resolver sus multiplicaciones (ej. restar el 2 de '3a^2 - 2' antes de multiplicarlo por 'a').", "Equivocarse en la regla de los signos al sumar o restar los resultados finales."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLI-CONC-{i}", "semantic_id": sid32, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al evaluar el polinomio $3x^2 + 4x - 5$, ¿cuál es el procedimiento correcto respecto al orden de las sumas y restas centrales? (v{i})", "choices": ["A) Las sumas y restas deben realizarse estrictamente al final, después de haber calculado el valor individual (potencias y multiplicaciones) de cada término o 'vagón'.", "B) Se puede sumar el $3x^2$ con el $4x$ directamente sumando los coeficientes ($7x^3$) y luego sustituir.", "C) Se debe restar el $5$ al $4$ antes de multiplicarlo por $x$.", "D) Las operaciones deben hacerse de derecha a izquierda obligatoriamente."], "correct_answer": "A) Las sumas y restas deben realizarse estrictamente al final, después de haber calculado el valor individual (potencias y multiplicaciones) de cada término o 'vagón'.", "solution_steps": "Las sumas y restas (engranajes del polinomio) son la última operación de la jerarquía PAPOMUDAS.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"POLI-REC-1", "semantic_id": sid32, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Calcula el valor numérico del polinomio $2x^2 + 5x - 3$ para $x = 3$.", "choices": ["A) $30$", "B) $24$", "C) $36$", "D) $42$"], "correct_answer": "A) $30$", "solution_steps": "Término 1: $2(3)^2 = 2(9) = 18$. Término 2: $5(3) = 15$. Término 3: $-3$. Sumando: $18 + 15 - 3 = 33 - 3 = 30$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLI-PROC-{i}", "semantic_id": sid32, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si evaluamos el polinomio $x^3 - 2x^2 + x$ con el valor $x=1$, el resultado final es $0$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Sustituyendo: $1^3 - 2(1)^2 + 1$. Resolviendo: $1 - 2(1) + 1 = 1 - 2 + 1$. Efectuando: $-1 + 1 = 0$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLI-PAES-{i}", "semantic_id": sid32, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"La altura $h$ de un proyectil en función del tiempo $t$ está dada por el polinomio $h(t) = 50t - 5t^2$. Si se quiere conocer la altura exacta al los $4$ segundos de vuelo, ¿qué cálculo debe realizarse? (v{i})", "choices": ["A) $120$ metros.", "B) $200$ metros.", "C) $40$ metros.", "D) $80$ metros."], "correct_answer": "A) $120$ metros.", "solution_steps": "Evaluamos el polinomio en $t=4$: $50(4) - 5(4)^2$. Primer vagón: $200$. Segundo vagón: $5(16) = 80$. Diferencia: $200 - 80 = 120$.", "paes_style": True})

# 33. PARENTESIS_VALORES_NEGATIVOS
sid33 = "MAT.ALG.VALORIZACION.PARENTESIS_VALORES_NEGATIVOS"
RECURSOS.append({
    "semantic_id": sid33, "objetivo": "Manejar correctamente la sustitución de números negativos en una expresión algebraica mediante el uso riguroso de paréntesis.",
    "introduccion": "Si hay un 'asesino silencioso' en las pruebas de álgebra, es el número negativo. Si lo valorizas sin ponerle su 'chaleco antibalas' (el paréntesis), morirá a manos de las potencias o alterará los signos de toda la ecuación.",
    "resumen": "Al sustituir un **Valor Negativo**, es absolutamente obligatorio **encerrarlo entre paréntesis**. Esto garantiza que tanto las multiplicaciones como las potencias afecten también a su signo negativo.",
    "explicacion": "Veamos la tragedia de valorizar $x^2$ cuando $x = -3$.\n- Forma INCORRECTA (sin chaleco): $-3^2 = -9$. ¡Mortal! El cuadrado elevó solo al 3, dejando el menos intacto.\n- Forma CORRECTA (con chaleco): $(-3)^2 = (-3)(-3) = +9$. ¡Salvado! El cuadrado elevó también al signo menos, volviéndolo positivo.\n\nEl uso del paréntesis también salva vidas en restas. Valoremos $5 - x$ con $x = -2$.\n- Incorrecto: $5 - 2 = 3$. (Se perdió un signo).\n- Correcto: $5 - (-2) = 5 + 2 = 7$.",
    "procedimiento": ["Paso 1: Coloca la variable original entre paréntesis vacíos en la expresión.", "Paso 2: Introduce el número negativo junto con su signo dentro de ese paréntesis.", "Paso 3: Si hay una potencia exterior, recuerda la regla de los signos (base negativa a exponente par = positivo, a impar = negativo).", "Paso 4: Si hay un signo menos delante del paréntesis, haz chocar los signos (- por - da +)."],
    "ejemplos": [
        {"titulo": "Doble negatividad", "enunciado": "Valora la expresión -x^2 - x, cuando x = -4.", "solucion_pasos": ["Colocamos paréntesis vacíos: -( )^2 - ( ).", "Rellenamos con -4: -(-4)^2 - (-4).", "Resolvemos la potencia de adentro: (-4)^2 = +16.", "Reescribimos: -(16) - (-4).", "Chocamos signos: -16 + 4.", "Resultado final: -12."]}
    ],
    "errores_frecuentes": ["No usar paréntesis y que una potencia par no elimine el signo negativo (ej. decir que $x^2 = -16$ cuando $x=-4$).", "Olvidar chocar los signos cuando la variable tenía un signo negativo previo (ej. $2 - x$, con $x=-3$, escribir $2 - 3$ en lugar de $2 - (-3)$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNEG-CONC-{i}", "semantic_id": sid33, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Por qué es matemáticamente indispensable utilizar paréntesis al evaluar la expresión $x^2$ cuando la variable $x$ toma un valor negativo, por ejemplo, $x = -5$? (v{i})", "choices": ["A) Porque sin el paréntesis ($-5^2$), las reglas algebraicas asumen que el cuadrado afecta solo al número $5$, resultando en $-25$. Con el paréntesis ($(-5)^2$), el cuadrado afecta a todo el bloque, incluyendo el signo, resultando en $+25$.", "B) Porque los paréntesis sirven para recordar que el número es negativo, aunque el resultado matemático sería el mismo de todas formas.", "C) Porque los números negativos no pueden existir sin paréntesis en matemáticas.", "D) Porque el paréntesis indica que se debe multiplicar por dos."], "correct_answer": "A) Porque sin el paréntesis ($-5^2$), las reglas algebraicas asumen que el cuadrado afecta solo al número $5$, resultando en $-25$. Con el paréntesis ($(-5)^2$), el cuadrado afecta a todo el bloque, incluyendo el signo, resultando en $+25$.", "solution_steps": "El exponente opera inmediatamente sobre su base izquierda. En $-5^2$, la base es 5. En $(-5)^2$, la base es -5.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PNEG-REC-1", "semantic_id": sid33, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Evalúa correctamente la expresión $10 - x$ cuando $x = -7$.", "choices": ["A) $17$", "B) $3$", "C) $-17$", "D) $-3$"], "correct_answer": "A) $17$", "solution_steps": "El molde es $10 - ( )$. Metemos el valor: $10 - (-7)$. El choque de signos (menos por menos) da más: $10 + 7 = 17$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNEG-PROC-{i}", "semantic_id": sid33, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "alta", "competencia": "M1", "prompt": "¿El valor numérico de la expresión $-x^2$ evaluada en $x = -2$ resulta ser un número positivo ($+4$)?", "choices": [], "correct_answer": "Falso", "solution_steps": "Cuidado con la trampa doble. El molde es $-( )^2$. Rellenamos: $-(-2)^2$. Resolvemos la potencia: $(-2)^2 = +4$. El signo de afuera ataca: $-(+4) = -4$. El resultado final es negativo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNEG-PAES-{i}", "semantic_id": sid33, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Una función de transferencia en un circuito electrónico se define por $V = a^2 - ab$. Si el voltaje $a$ es de $-3$ voltios y la corriente $b$ es de $-2$ amperios, ¿cuál es el valor de $V$ procesado correctamente por el sistema? (v{i})", "choices": ["A) $3$", "B) $15$", "C) $-3$", "D) $9$"], "correct_answer": "A) $3$", "solution_steps": "Sustitución con chalecos: $V = (-3)^2 - (-3)(-2)$. Calculamos la potencia: $(-3)^2 = 9$. Calculamos el bloque derecho: $(-3)(-2) = +6$. Reconstruimos: $9 - (+6) = 9 - 6 = 3$.", "paes_style": True})

# 34. RACIONALES
sid34 = "MAT.ALG.VALORIZACION.RACIONALES"
RECURSOS.append({
    "semantic_id": sid34, "objetivo": "Valorizar expresiones fraccionarias sustituyendo el numerador y el denominador.",
    "introduccion": "Las fracciones en álgebra no son más que divisiones pospuestas. Valorizar una expresión racional es como calcular el peso de dos trenes distintos: uno arriba (numerador) y otro abajo (denominador), y luego ver si podemos simplificarlos.",
    "resumen": "Al valorizar **Expresiones Racionales** (fracciones), se debe tratar al **numerador y al denominador como polinomios independientes**. Se calcula el valor numérico de arriba, el valor de abajo, y finalmente se divide o simplifica la fracción resultante.",
    "explicacion": "Toma la expresión: $\\frac{2x + 4}{x - 1}$, para $x=3$.\nRegla del bloque: Jamás intentes cruzar operaciones entre el piso de arriba y el de abajo antes de que sean un solo número.\n- Arriba: $2(3) + 4 = 6 + 4 = 10$.\n- Abajo: $(3) - 1 = 2$.\n- Nueva fracción: $\\frac{10}{2}$.\n- División final: $5$.\n\n*Advertencia crítica:* Si al evaluar el denominador obtienes un $0$ (ej. en $\\frac{5}{x-2}$ con $x=2$, quedaría $\\frac{5}{0}$), la expresión es **indeterminada** o 'no existe' en los números reales. ¡El cero en el divisor es el apocalipsis matemático!",
    "procedimiento": ["Paso 1: Valoriza y calcula completamente el numerador como si fuera un ejercicio solitario.", "Paso 2: Valoriza y calcula el denominador de igual manera.", "Paso 3: Construye la fracción con ambos resultados finales (ej. 15 / 3).", "Paso 4: Divide si es un resultado entero, o simplifica la fracción si no lo es.", "Paso 5: Si el denominador dio cero, declara que la expresión está indeterminada."],
    "ejemplos": [
        {"titulo": "Pisos independientes", "enunciado": "Valora (x^2 - 1) / (x + 1) para x = 4.", "solucion_pasos": ["Numerador: (4)^2 - 1 = 16 - 1 = 15.", "Denominador: (4) + 1 = 5.", "Fracción final: 15 / 5.", "División: 3."]}
    ],
    "errores_frecuentes": ["Simplificar variables o números entre el numerador y denominador ANTES de terminar las sumas/restas (ej. 'cancelar' una $x$ de arriba con una $x$ de abajo si están sumando).", "No notar que un denominador igual a 0 invalida todo el problema."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RACI-CONC-{i}", "semantic_id": sid34, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al valorar una expresión algebraica racional (fraccionaria), ¿qué condición matemática sobre el resultado del denominador haría que el valor de la expresión se considere 'indeterminado' o 'inexistente'? (v{i})", "choices": ["A) Que el resultado final del denominador evaluado sea igual a $0$, ya que la división por cero no está definida en los números reales.", "B) Que el resultado del numerador sea igual a $0$.", "C) Que el denominador resulte en un número negativo.", "D) Que el denominador sea una fracción irreducible."], "correct_answer": "A) Que el resultado final del denominador evaluado sea igual a $0$, ya que la división por cero no está definida en los números reales.", "solution_steps": "El denominador representa 'entre cuántas partes se divide algo'. No se puede dividir entre cero partes.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RACI-REC-1", "semantic_id": sid34, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Calcula el valor numérico de la expresión $\\frac{3a - 1}{a + 2}$ evaluada en $a = 4$.", "choices": ["A) $\\frac{11}{6}$", "B) $\\frac{13}{6}$", "C) $\\frac{5}{6}$", "D) $2$"], "correct_answer": "A) $\\frac{11}{6}$", "solution_steps": "Numerador: $3(4) - 1 = 12 - 1 = 11$. Denominador: $4 + 2 = 6$. Fracción final: $\\frac{11}{6}$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RACI-PROC-{i}", "semantic_id": sid34, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si evaluamos la expresión $\\frac{x^2 - 9}{x - 3}$ usando el valor $x = 3$, el resultado algebraico válido de dicha valorización numérica es $0$?", "choices": [], "correct_answer": "Falso", "solution_steps": "El numerador da $3^2 - 9 = 0$. El denominador da $3 - 3 = 0$. La fracción queda $\\frac{0}{0}$, lo cual es una indeterminación absoluta. No da 0.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RACI-PAES-{i}", "semantic_id": sid34, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"La ley de gravitación indica que la fuerza es $F = \\frac{{G m_1 m_2}}{{r^2}}$. Si en un modelo simplificado asignamos $G=10$, las masas $m_1=5$ y $m_2=2$, y la distancia es $r=5$, ¿cuál es el valor de la fuerza $F$ en este escenario estático? (v{i})", "choices": ["A) $4$", "B) $20$", "C) $100$", "D) $10$"], "correct_answer": "A) $4$", "solution_steps": "Numerador: $10 \\cdot 5 \\cdot 2 = 100$. Denominador: $5^2 = 25$. Fracción: $\\frac{100}{25}$. Dividimos: $4$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 7 (B0302/Valorizacion)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 7...")
    append_jsonl("mat-alg-lenguaje-banco-gen-7", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-7.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
