# scratch/build_b0205_t15.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. MONTO_FINAL (Interés Simple)
sid1 = "MAT.NUM.INTERES_SIMPLE.MONTO_FINAL"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Diferenciar y calcular el monto final acumulado versus solo el interés ganado en un régimen simple.",
    "introduccion": "Si le prestas 100 lucas a un amigo y te devuelve solo las 10 lucas de interés, ¡perdiste 90 lucas! Al final del plazo, debe devolverte el Capital inicial MÁS los intereses. Eso es el Monto Final.",
    "resumen": "El Monto Final ($M$ o $C_f$) es la suma del Capital prestado ($C$) más los intereses generados ($I$). Fórmula directa: $M = C \\cdot (1 + i \\cdot t)$.",
    "explicacion": "A menudo los problemas preguntan por '¿cuánto retirará en total del banco?' o '¿cuál es la deuda total a pagar?'. No basta con calcular la ganancia ($I$). Debes calcular el **Monto Final ($M$)**.\n\nHay dos caminos:\n1. **Camino largo (en dos pasos):** Calculas el interés $I = C \\cdot i \\cdot t$ y luego se lo sumas al capital original: $M = C + I$.\n2. **Camino directo (Factorización):** Como $M = C + (C \\cdot i \\cdot t)$, si factorizamos $C$ nos queda:\n$$M = C \\cdot (1 + i \\cdot t)$$\nEste paréntesis $(1 + i \\cdot t)$ actúa como el gran factor multiplicador del interés simple total.",
    "procedimiento": ["Paso 1: Identifica si el problema pide 'cuánto ganó de interés' (solo I) o 'cuánto retiró en total' (M).", "Paso 2: Transforma la tasa $i$ a decimal.", "Paso 3: Si pide el total, usa la fórmula $M = C \\cdot (1 + i \\cdot t)$, asegurándote de que $i$ y $t$ estén en la misma unidad de tiempo."],
    "ejemplos": [
        {"titulo": "Retiro total del banco", "enunciado": "Guardas $20.000 al 3% anual simple durante 4 años. ¿Cuánto dinero retiras en total al final?", "solucion_pasos": ["C = 20.000, i = 0.03, t = 4.", "Monto = $20.000 \\cdot (1 + 0.03 \\cdot 4)$.", "Monto = $20.000 \\cdot (1 + 0.12) = 20.000 \\cdot 1.12$.", "Monto = $22.400$. Ese es el total a retirar."]}
    ],
    "errores_frecuentes": ["Responder solo con el valor del interés cuando la pregunta dice explícitamente 'monto final' o 'total a pagar'.", "Sumarle 1 a la tasa antes de multiplicar por el tiempo (hacer $C \\cdot (1+i) \\cdot t$ es un error algebraico grave)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOFINS-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué expresión algebraica representa correctamente el Monto Final (Capital más intereses) en un régimen de interés simple? (v{i})", "choices": ["A) $C \\cdot (1 + i \\cdot t)$", "B) $C \\cdot i \\cdot t$", "C) $C \\cdot (1 + i)^t$", "D) $C + i + t$"], "correct_answer": "A) $C \\cdot (1 + i \\cdot t)$", "solution_steps": "Es la factorización de $C + C \\cdot i \\cdot t$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MONTOFINS-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si un problema pregunta '¿A cuánto asciende la deuda total a pagar al final del plazo?', se debe calcular:", "choices": ["A) El Monto Final ($M$).", "B) El Interés ($I$).", "C) La Tasa ($i$).", "D) El Capital Inicial ($C$)."], "correct_answer": "A) El Monto Final ($M$).", "solution_steps": "La 'deuda total' incluye el capital prestado más el recargo por intereses.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOFINS-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El monto final de $\$1.000$ invertidos al $10\\%$ mensual simple por $3$ meses es $\$1.300$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$1000 \\cdot (1 + 0.10 \\cdot 3) = 1000 \\cdot 1.30 = 1300$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOFINS-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una persona solicita un crédito de consumo de $\$3.000.000$ bajo un régimen de interés simple con una tasa del $1.5\\%$ mensual. Si acuerda pagar el total de la deuda (capital e intereses) en una sola cuota al cabo de $24$ meses, ¿cuánto dinero deberá desembolsar en ese pago final? (v{i})", "choices": ["A) $\$4.080.000$", "B) $\$1.080.000$", "C) $\$3.045.000$", "D) $\$7.320.000$"], "correct_answer": "A) $\$4.080.000$", "solution_steps": "Monto = $C(1 + it) = 3.000.000(1 + 0.015 \\cdot 24) = 3.000.000(1 + 0.36) = 3.000.000 \\cdot 1.36 = 4.080.000$.", "paes_style": True})

# 2. CAPITAL_INICIAL (Interés Simple)
sid2 = "MAT.NUM.INTERES_SIMPLE.CAPITAL_INICIAL"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Despejar el capital inicial en la ecuación de interés simple.",
    "introduccion": "A veces sabes cuánto quieres retirar al final de un plazo y cuánto paga el banco, pero la gran pregunta es: ¿Cuánto dinero tengo que meter hoy para lograr esa meta? Para eso hay que despejar el Capital Inicial.",
    "resumen": "Si conoces el interés generado ($I$), $C = I / (i \\cdot t)$. Si conoces el monto final total ($M$), $C = M / (1 + i \\cdot t)$.",
    "explicacion": "Como $M = C \\cdot (1 + i \\cdot t)$ y $I = C \\cdot i \\cdot t$, podemos usar álgebra para encontrar el Capital Inicial ($C$) si nos dan los otros datos.\n\n**Caso 1: Te dan el dinero que ganaste (solo intereses $I$)**\nDespejando $C$ de la fórmula chica: \n$$C = \\frac{I}{i \\cdot t}$$\n\n**Caso 2: Te dan el dinero final total de la cuenta ($M$)**\nDespejando $C$ de la fórmula grande (el paréntesis pasa dividiendo):\n$$C = \\frac{M}{1 + i \\cdot t}$$\n*(Este caso es muy común en problemas de la PAES).* ",
    "procedimiento": ["Paso 1: Lee cuidadosamente si el dinero que te dan es el 'interés generado' o 'el total en la cuenta'.", "Paso 2: Convierte la tasa a decimal y asegúrate de que el tiempo esté en la misma unidad.", "Paso 3: Divide el dato por $(i \\cdot t)$ o por $(1 + i \\cdot t)$ según corresponda."],
    "ejemplos": [
        {"titulo": "Meta de ahorro", "enunciado": "Al cabo de 5 años, una inversión a interés simple del 4% anual se convirtió en un total de $3.600.000. ¿Cuánto se invirtió inicialmente?", "solucion_pasos": ["Es el total, usamos $C = M / (1 + i \\cdot t)$.", "$M = 3.600.000$, $i = 0.04$, $t = 5$.", "Denominador: $1 + (0.04 \\cdot 5) = 1 + 0.20 = 1.20$.", "$C = 3.600.000 / 1.20 = 3.000.000$. Se invirtieron 3 millones."]}
    ],
    "errores_frecuentes": ["Restar los intereses al Monto usando la tasa sobre el Monto Final (¡Los intereses siempre se calculan sobre el capital inicial desconocido, por eso hay que usar división!).", "Dividir el Monto $M$ solo por $(i \\cdot t)$, confundiendo las fórmulas."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CAPIN-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Para encontrar el Capital Inicial ($C$) conociendo el Monto Final total ($M$), la tasa ($i$) y el tiempo ($t$) en interés simple, se debe usar la expresión: (v{i})", "choices": ["A) $C = M / (1 + i \\cdot t)$", "B) $C = M - (i \\cdot t)$", "C) $C = M \\cdot (1 - i \\cdot t)$", "D) $C = M / (i \\cdot t)$"], "correct_answer": "A) $C = M / (1 + i \\cdot t)$", "solution_steps": "Despejando $C$ de la ecuación $M = C(1+it)$, el paréntesis pasa dividiendo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CAPIN-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si el problema dice: 'Una inversión generó $\$50.000$ de rentabilidad (intereses)...', la variable que conoces para despejar $C$ es:", "choices": ["A) El Interés ($I$).", "B) El Monto Final ($M$).", "C) La Tasa ($i$).", "D) El Tiempo ($t$)."], "correct_answer": "A) El Interés ($I$).", "solution_steps": "La 'rentabilidad' o ganancia pura corresponde a la variable $I$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CAPIN-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si un depósito generó $\$200$ de intereses puros en $1$ año a una tasa del $10\\%$ simple anual, el capital invertido fue de $\$2.000$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$C = I / (i \\cdot t) = 200 / (0.10 \\cdot 1) = 200 / 0.10 = 2000$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CAPIN-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Camila revisa su cartola del banco y ve que su fondo mutuo, tras $4$ años de inversión bajo un régimen de interés simple al $6\\%$ anual, ha alcanzado un saldo total acumulado de $\$6.200.000$. ¿Cuánto dinero depositó originalmente Camila al abrir la cuenta? (v{i})", "choices": ["A) $\$5.000.000$", "B) $\$4.712.000$", "C) $\$1.240.000$", "D) $\$6.052.000$"], "correct_answer": "A) $\$5.000.000$", "solution_steps": "$C = M / (1 + it) = 6.200.000 / (1 + 0.06 \\cdot 4) = 6.200.000 / (1 + 0.24) = 6.200.000 / 1.24 = 5.000.000$.", "paes_style": True})

# 3. TASA_INTERES (Interés Simple)
sid3 = "MAT.NUM.INTERES_SIMPLE.TASA_INTERES"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Despejar la tasa de interés aplicada en una operación de interés simple.",
    "introduccion": "Prestas 100 y te devuelven 150 después de 2 años. ¡Genial! Pero, ¿qué porcentaje de ganancia tuviste exactamente por año? Para comparar negocios, necesitas encontrar la Tasa de Interés.",
    "resumen": "Si conoces el Capital Inicial ($C$), el Interés generado ($I$) y el Tiempo ($t$), puedes despejar la tasa: $i = I / (C \\cdot t)$. El resultado será un decimal que multiplicas por 100 para pasarlo a porcentaje.",
    "explicacion": "Para descubrir qué tasa de interés se aplicó a un préstamo o inversión, usamos la fórmula básica $I = C \\cdot i \\cdot t$ y despejamos la $i$:\n\n$$i = \\frac{I}{C \\cdot t}$$\n\n- **Ojo con los datos:** Necesitas el 'Interés puro ($I$)'. Si el problema te da el Monto Final Total ($M$), primero debes calcular el interés restando: $I = M - C$.\n- **El resultado es decimal:** Al hacer la división, obtendrás un número como $0.05$. Para responder como porcentaje, debes multiplicar por 100 ($5\\%$).\n- **Unidad de tiempo:** La tasa obtenida tendrá la misma unidad que el tiempo $t$ que usaste en la fórmula. Si $t$ estaba en meses, la tasa será mensual.",
    "procedimiento": ["Paso 1: Asegúrate de tener el valor de la ganancia pura ($I$). Si tienes el Monto Final, resta el capital inicial ($I = M - C$).", "Paso 2: Divide $I$ por el producto de $(Capital \\cdot tiempo)$.", "Paso 3: Multiplica el decimal resultante por 100."],
    "ejemplos": [
        {"titulo": "Descubriendo la tasa del prestamista", "enunciado": "Te prestaron $50.000 y tras 3 meses tuviste que devolver $56.000 en total (capital + intereses). ¿Qué tasa de interés simple mensual te cobraron?", "solucion_pasos": ["Calculamos el interés puro: $56.000 - 50.000 = 6.000$.", "$i = I / (C \\cdot t) = 6000 / (50000 \\cdot 3)$.", "$i = 6000 / 150000 = 0.04$.", "En porcentaje: $0.04 \\cdot 100 = 4\\%$ mensual."]}
    ],
    "errores_frecuentes": ["Usar el Monto Final ($M$) en lugar del Interés ($I$) en el numerador.", "Olvidar multiplicar por 100 al final y decir que la tasa es del $0.05\\%$ (cuando en realidad era $5\\%$)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAS-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si despejas la tasa de interés ($i$) de la fórmula $I = C \\cdot i \\cdot t$, la expresión correcta es: (v{i})", "choices": ["A) $i = I / (C \\cdot t)$", "B) $i = (C \\cdot t) / I$", "C) $i = I - (C \\cdot t)$", "D) $i = I \\cdot C \\cdot t$"], "correct_answer": "A) $i = I / (C \\cdot t)$", "solution_steps": "C y t pasan dividiendo a la izquierda.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TASAS-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si el resultado de la fórmula $i = I / (C \\cdot t)$ da $0.12$, entonces la tasa en formato de porcentaje es:", "choices": ["A) $12\\%$", "B) $0.12\\%$", "C) $1.2\\%$", "D) $120\\%$"], "correct_answer": "A) $12\\%$", "solution_steps": "Se multiplica por 100.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAS-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si prestas $\$100$ y tras $2$ años te pagan $\$20$ de puros intereses, la tasa fue del $10\\%$ simple anual?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$i = 20 / (100 \\cdot 2) = 20 / 200 = 0.10$. En porcentaje es $10\\%$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAS-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una empresa emite bonos de deuda. Un inversionista compra un bono por $\$2.500.000$ (capital inicial). Al cabo de $5$ años, la empresa liquida el bono pagándole al inversionista un monto total final de $\$3.250.000$. ¿Cuál fue la tasa de interés simple anual que ofreció este bono? (v{i})", "choices": ["A) $6\\%$", "B) $26\\%$", "C) $30\\%$", "D) $0.06\\%$"], "correct_answer": "A) $6\\%$", "solution_steps": "Interés ganado ($I$) = $3.250.000 - 2.500.000 = 750.000$. Tasa $i = 750.000 / (2.500.000 \\cdot 5) = 750.000 / 12.500.000 = 0.06$. En porcentaje = $6\\%$.", "paes_style": True})

# 4. TIEMPO_INVERSION (Interés Simple)
sid4 = "MAT.NUM.INTERES_SIMPLE.TIEMPO_INVERSION"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Determinar el tiempo necesario para alcanzar un monto deseado en interés simple.",
    "introduccion": "¿Cuánto tendré que esperar para que mis ahorros se dupliquen? El tiempo es oro, literalmente. Aprende a calcular cuántos meses o años debe madurar una inversión.",
    "resumen": "Para hallar el tiempo $t$, se despeja la fórmula básica: $t = I / (C \\cdot i)$. Si la tasa es anual, el tiempo obtenido estará en años. Si la tasa es mensual, el tiempo estará en meses.",
    "explicacion": "Despejamos el tiempo ($t$) de la fórmula de interés simple $I = C \\cdot i \\cdot t$:\n\n$$t = \\frac{I}{C \\cdot i}$$\n\n- Igual que antes, si te dan el Monto Final, primero debes restar el capital para hallar $I$.\n- El tiempo que te dé como resultado **'hereda' el apellido de la tasa**. Si usaste una tasa del $4\\%$ *trimestral*, el número final que obtengas será una cantidad de *trimestres*. \n- Si el resultado da con decimales (ej. $2.5$ años), significa que son $2$ años y medio (es decir, $2$ años y $6$ meses).",
    "procedimiento": ["Paso 1: Calcula el interés generado ($I = Monto - Capital$).", "Paso 2: Transforma la tasa a decimal.", "Paso 3: Divide el interés por $(Capital \\cdot tasa)$.", "Paso 4: Interpreta el resultado numérico en la unidad de tiempo correspondiente a la tasa."],
    "ejemplos": [
        {"titulo": "Duplicando el dinero", "enunciado": "Si invierto a una tasa del 5% simple anual, ¿cuántos años debo esperar para duplicar mi capital?", "solucion_pasos": ["Duplicar capital significa que el Monto $M = 2C$.", "Por ende, el interés ganado debe ser igual al capital: $I = C$.", "$t = I / (C \\cdot i) \\rightarrow t = C / (C \\cdot 0.05)$.", "Las C se cancelan: $t = 1 / 0.05 = 20$. Debes esperar 20 años."]}
    ],
    "errores_frecuentes": ["Olvidar revisar si la tasa era mensual o anual, respondiendo 'meses' cuando la matemática indicaba 'años'.", "Poner el Capital en el numerador de la división."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIEMPOS-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el cálculo de interés simple, si utilizas la fórmula $t = I / (C \\cdot i)$ introduciendo una tasa '$i$' de carácter trimestral, el resultado numérico para '$t$' estará expresado obligatoriamente en: (v{i})", "choices": ["A) Trimestres.", "B) Años.", "C) Meses.", "D) Semestres."], "correct_answer": "A) Trimestres.", "solution_steps": "El tiempo 't' asume la misma unidad que la periodicidad de la tasa.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TIEMPOS-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si el resultado del despeje del tiempo da $t = 3.5$ y la tasa era anual, significa que el tiempo fue:", "choices": ["A) $3$ años y $6$ meses.", "B) $3$ años y $5$ meses.", "C) $3$ meses y medio.", "D) $35$ años."], "correct_answer": "A) $3$ años y $6$ meses.", "solution_steps": "$0.5$ años es exactamente la mitad de un año, o sea 6 meses.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIEMPOS-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Para que un capital de $\$500$ genere $\$50$ de intereses al $10\\%$ anual, debe transcurrir $1$ año exacto?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$t = 50 / (500 \\cdot 0.10) = 50 / 50 = 1$ año.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIEMPOS-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Matías invierte un bono de $\$1.200.000$ en una entidad que ofrece un $4\\%$ de interés simple semestral. Él se ha propuesto no retirar el dinero hasta que la cuenta acumule un total final de $\$1.440.000$. ¿Cuántos semestres deberá mantener la inversión para lograr su meta? (v{i})", "choices": ["A) $5$ semestres.", "B) $6$ semestres.", "C) $10$ semestres.", "D) $2.5$ semestres."], "correct_answer": "A) $5$ semestres.", "solution_steps": "Interés deseado $I = 1.440.000 - 1.200.000 = 240.000$. $t = 240.000 / (1.200.000 \\cdot 0.04) = 240.000 / 48.000 = 5$. Como la tasa era semestral, son $5$ semestres.", "paes_style": True})

# 5. INTERES_COMPUESTO_CONCEPTO
sid5 = "MAT.NUM.INTERES_COMPUESTO.CONCEPTO"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Comprender el concepto de interés compuesto como un proceso exponencial donde los intereses generan nuevos intereses.",
    "introduccion": "Albert Einstein supuestamente dijo que el interés compuesto es la octava maravilla del mundo. 'Aquel que lo entiende, lo gana; aquel que no, lo paga'. Es el motor secreto de la riqueza (y de las deudas impagables).",
    "resumen": "En el interés compuesto, la base de cálculo cambia en cada período (se capitaliza). Los intereses ganados se suman al capital, y en el siguiente mes calcularás el porcentaje sobre este monto mayor. Es un crecimiento exponencial (curva).",
    "explicacion": "A diferencia del interés simple donde siempre calculas sobre el capital original, el **Interés Compuesto** funciona bajo la regla de la **Capitalización**.\n\n- **Periodo 1:** Inviertes $\$100$ al $10\\%$. Ganas $\$10$. Tienes $\$110$.\n- **Periodo 2:** Ahora el $10\\%$ se calcula sobre los $\$110$. Ganas $\$11$. Tienes $\$121$.\n- **Periodo 3:** El $10\\%$ se calcula sobre $\$121$. Ganas $\$12.1$. Tienes $\$133.1$.\n\nComo ves, la cantidad de interés generada es cada vez mayor. Esto crea un efecto 'bola de nieve'. En el corto plazo la diferencia con el simple es pequeña, pero a largo plazo (20-30 años, como en los fondos de jubilación o créditos hipotecarios), la curva del interés compuesto despega exponencialmente hacia el cielo.",
    "procedimiento": ["Paso 1: Entiende que el Capital va cambiando y creciendo periodo a periodo.", "Paso 2: Reconoce la palabra clave 'Capitalizable' (significa que el interés se suma al pozo para el próximo cálculo).", "Paso 3: Visualiza un gráfico de curva exponencial ascendente."],
    "ejemplos": [
        {"titulo": "Bola de nieve financiera", "enunciado": "Si tienes una deuda de tarjeta de crédito y no pagas nada, ¿por qué la deuda crece tan rápido?", "solucion_pasos": ["El banco cobra intereses sobre la deuda inicial.", "Al mes siguiente, te cobran intereses sobre la deuda inicial MÁS los intereses impagos del mes pasado.", "Es la magia negra del interés compuesto trabajando en tu contra."]}
    ],
    "errores_frecuentes": ["Creer que si la tasa es 10% anual capitalizable, en 2 años ganarás el 20% (falso, ganarás 21% debido al interés sobre el interés del primer año).", "Usar la fórmula lineal del interés simple cuando el problema indica 'capitalización'."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTCOMP-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué frase define mejor el funcionamiento fundamental del Interés Compuesto? (v{i})", "choices": ["A) Es un modelo donde los intereses generados se suman al capital, produciendo nuevos intereses en los períodos siguientes.", "B) Es un modelo lineal donde el monto de interés pagado es constante todos los meses.", "C) Es un recargo que solo aplican las tarjetas de crédito.", "D) Es un modelo donde la tasa de interés disminuye a medida que pasa el tiempo."], "correct_answer": "A) Es un modelo donde los intereses generados se suman al capital, produciendo nuevos intereses en los períodos siguientes.", "solution_steps": "Esta es la definición de capitalización y crecimiento exponencial.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTCOMP-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En una gráfica de dinero acumulado versus tiempo, el modelo de interés compuesto a largo plazo se dibuja como:", "choices": ["A) Una curva exponencial ascendente.", "B) Una línea recta horizontal.", "C) Una línea recta en diagonal constante.", "D) Una parábola que baja y luego sube."], "correct_answer": "A) Una curva exponencial ascendente.", "solution_steps": "El efecto 'bola de nieve' hace que crezca cada vez más rápido curvándose hacia arriba.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTCOMP-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si inviertes $\$1.000$ al $10\\%$ de interés compuesto anual, en el segundo año ganarás más de $\$100$ de puro interés?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El primer año ganas $\$100$ (Capital sube a $\$1100$). El segundo año ganas el $10\\%$ de $\$1100$, que son $\$110$. Ganas más.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTCOMP-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Sofía evalúa dos opciones para invertir $\$1.000.000$ a un plazo de $3$ años. La Opción X ofrece un $5\\%$ de interés simple anual. La Opción Y ofrece un $5\\%$ de interés compuesto anualmente. Sin necesidad de calcular el monto exacto final, ¿qué se puede afirmar con certeza matemática sobre estas opciones? (v{i})", "choices": ["A) La Opción Y entregará un monto final mayor que la Opción X.", "B) Ambas opciones entregarán exactamente el mismo dinero al final.", "C) La Opción X entregará un monto final mayor porque es más segura.", "D) En el primer año, la Opción Y ganará más intereses que la Opción X."], "correct_answer": "A) La Opción Y entregará un monto final mayor que la Opción X.", "solution_steps": "A igual tasa y plazo (mayor a 1 periodo), el interés compuesto siempre vence al simple por la reinversión de intereses. (En el año 1, rinden exactamente lo mismo).", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 15...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 15...")
    append_jsonl("mat-num-razones-banco-gen-15", EJERCICIOS)
    print("Creado mat-num-razones-banco-gen-15.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
