# scratch/build_alg_b0303_t1.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. DEFINICION_TERMINOS_SEMEJANTES
sid1 = "MAT.ALG.SIMILARIDAD.DEFINICION_TERMINOS_SEMEJANTES"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Comprender la definición conceptual de términos semejantes en álgebra.",
    "introduccion": "En la vida diaria, podemos sumar 3 manzanas con 2 manzanas para obtener 5 manzanas. Pero no podemos sumar 3 manzanas con 2 peras y decir que tenemos '5 manzanaperas'. En álgebra, la regla es exactamente la misma.",
    "resumen": "Los **Términos Semejantes** son aquellos monomios que poseen exactamente el mismo **factor literal** (las mismas letras) afectado por los mismos **exponentes**, sin importar el coeficiente numérico que los acompañe.",
    "explicacion": "Dos términos son 'familia' (semejantes) única y exclusivamente si sus letras y los pequeños números sobre ellas (exponentes) son idénticos.\n- $3a$ y $5a$ son semejantes (ambos son de la familia 'a').\n- $-2x^2y$ y $7x^2y$ son semejantes (ambos de la familia 'x al cuadrado, y').\n\nEl coeficiente (el número grande adelante, como el $3$, $5$, $-2$ o $7$) nos dice **cuántos** elementos de esa familia tenemos. No define si son familia o no.",
    "procedimiento": ["Paso 1: Ignora temporalmente el coeficiente numérico y su signo.", "Paso 2: Observa la parte literal (las letras).", "Paso 3: Verifica que las letras sean exactamente las mismas en ambos términos.", "Paso 4: Verifica que cada letra tenga exactamente el mismo exponente en ambos términos. Si ambas condiciones se cumplen, son semejantes."],
    "ejemplos": [
        {"titulo": "Manzanas con manzanas", "enunciado": "¿Son semejantes 4m y -9m?", "solucion_pasos": ["Ignoramos los coeficientes 4 y -9.", "Observamos la parte literal del primero: m.", "Observamos la parte literal del segundo: m.", "Tienen la misma letra con el mismo exponente (1). Sí son semejantes."]}
    ],
    "errores_frecuentes": ["Creer que términos con el mismo coeficiente pero distintas letras son semejantes (ej. pensar que $3x$ y $3y$ son semejantes).", "Considerar que un número sin letras (constante) es semejante a un término con letras."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-DEF-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes afirmaciones define correctamente el concepto de 'términos semejantes' en álgebra? (v{i})", "choices": ["A) Son aquellos que tienen la misma parte literal con sus respectivos exponentes idénticos, independientemente de sus coeficientes numéricos.", "B) Son aquellos que tienen el mismo coeficiente numérico, aunque sus letras sean diferentes.", "C) Son aquellos que tienen las mismas letras, aunque sus exponentes varíen.", "D) Son aquellos que tienen el mismo signo y el mismo coeficiente."], "correct_answer": "A) Son aquellos que tienen la misma parte literal con sus respectivos exponentes idénticos, independientemente de sus coeficientes numéricos.", "solution_steps": "La semejanza algebraica depende única y exclusivamente del factor literal (letras y exponentes). Los coeficientes solo indican cantidad.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIM-DEF-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de los siguientes términos es semejante a $15x^2y^3$.", "choices": ["A) $-4x^2y^3$", "B) $15x^3y^2$", "C) $15xy$", "D) $-4x^3y^2$"], "correct_answer": "A) $-4x^2y^3$", "solution_steps": "Buscamos la familia $x^2y^3$. El coeficiente no importa. La alternativa A tiene la misma familia.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-DEF-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Es cierto que el término $12a$ y el término $12b$ son semejantes porque ambos tienen el número $12$?", "choices": [], "correct_answer": "Falso", "solution_steps": "El coeficiente (12) no define la semejanza. Las letras ($a$ y $b$) son distintas, por lo que pertenecen a 'familias' diferentes. No son semejantes.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-DEF-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un programa de software clasifica variables de memoria asignándoles etiquetas. Si asigna la etiqueta 'tipo A' al bloque $3x^4$ y busca agruparlo con otro bloque del mismo tipo para optimización, ¿cuál de los siguientes bloques debería seleccionar? (v{i})", "choices": ["A) $\\frac{1}{2}x^4$", "B) $3x^3$", "C) $4x^3$", "D) $3x$"], "correct_answer": "A) $\\frac{1}{2}x^4$", "solution_steps": "La etiqueta se define por el factor literal $x^4$. El bloque $\\frac{1}{2}x^4$ comparte esa estructura, siendo el único término semejante.", "paes_style": True})

# 2. IGUALDAD_FACTOR_LITERAL
sid2 = "MAT.ALG.SIMILARIDAD.IGUALDAD_FACTOR_LITERAL"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Reconocer la igualdad del factor literal como condición necesaria para la semejanza.",
    "introduccion": "La matemática es un idioma preciso. Una 'x' no es lo mismo que una 'y', así como un auto no es lo mismo que un barco. Si intentas mezclarlos operativamente, crearás caos.",
    "resumen": "La primera regla de la semejanza es la **Igualdad del Factor Literal**. Para que dos términos puedan sumarse o restarse, deben contener exactamente el mismo conjunto de variables (letras).",
    "explicacion": "Comparemos $8m$ y $5n$.\n- El primer término pertenece al grupo de las 'm'.\n- El segundo término pertenece al grupo de las 'n'.\nComo no comparten la misma letra, no son semejantes. No se pueden reducir. La expresión $8m + 5n$ queda exactamente así, no se puede simplificar a $13mn$ (ese es un error garrafal).",
    "procedimiento": ["Paso 1: Extrae visualmente todas las letras del primer término.", "Paso 2: Extrae todas las letras del segundo término.", "Paso 3: Compara. Si falta alguna letra en un lado, o sobra alguna, los términos NO son semejantes."],
    "ejemplos": [
        {"titulo": "Letras incompatibles", "enunciado": "¿Son semejantes 7pq y 7pr?", "solucion_pasos": ["Factor literal 1: pq.", "Factor literal 2: pr.", "Aunque la 'p' coincide, la 'q' no es lo mismo que la 'r'.", "Conclusión: No son semejantes."]}
    ],
    "errores_frecuentes": ["Creer que si comparten algunas letras (ej. $abc$ y $ab$) ya son semejantes. Tienen que ser exactamente todas las letras iguales.", "Asumir que un término con una letra extra se puede sumar ignorando la letra sobrante."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-LIT-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si tienes los términos $5abc$ y $-2ab$, ¿por qué no se consideran términos semejantes a pesar de compartir las letras $a$ y $b$? (v{i})", "choices": ["A) Porque para ser semejantes, el conjunto de letras debe ser exactamente idéntico; al segundo término le falta la variable $c$.", "B) Porque tienen signos opuestos ($+$ y $-$).", "C) Porque los coeficientes numéricos son diferentes ($5$ y $-2$).", "D) Porque tres letras nunca pueden ser semejantes a dos letras."], "correct_answer": "A) Porque para ser semejantes, el conjunto de letras debe ser exactamente idéntico; al segundo término le falta la variable $c$.", "solution_steps": "El factor literal debe ser un clon exacto. Si falta o sobra una variable, la semejanza se rompe.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIM-LIT-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Indica cuál de los siguientes términos NO es semejante a $8xy$.", "choices": ["A) $8xyz$", "B) $3xy$", "C) $-xy$", "D) $\\frac{1}{4}xy$"], "correct_answer": "A) $8xyz$", "solution_steps": "La familia es $xy$. La opción A incorpora la letra $z$, alterando el factor literal, por lo que deja de ser semejante.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-LIT-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La suma de $4x + 3y$ puede reducirse a $7xy$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Al no ser semejantes (las letras son distintas), no se pueden sumar sus coeficientes. Juntarlos como $7xy$ implica una multiplicación inventada.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-LIT-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una bodega de materiales, el inventario se registra algebraicamente. Tienes $10a$ cajas de clavos y te llega un cargamento de $5b$ cajas de tornillos. Si el jefe te pide el total agrupado, ¿cómo se expresa correctamente la cantidad total de cajas en inventario? (v{i})", "choices": ["A) $10a + 5b$", "B) $15ab$", "C) $50ab$", "D) $15(a+b)$"], "correct_answer": "A) $10a + 5b$", "solution_steps": "Clavos ($a$) y tornillos ($b$) no son la misma cosa. No son semejantes. Se deja indicada la suma: $10a + 5b$.", "paes_style": True})

# 3. IGUALDAD_EXPONENTES
sid3 = "MAT.ALG.SIMILARIDAD.IGUALDAD_EXPONENTES"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Distinguir términos algebraicos en función del grado (exponentes) de sus variables.",
    "introduccion": "Tener la misma letra no es suficiente. Un cuadrado no es lo mismo que una línea, aunque ambos estén hechos de tinta. $x$ representa una longitud, mientras que $x^2$ representa un área. ¡No puedes sumar metros con metros cuadrados!",
    "resumen": "Para que exista semejanza, es obligatoria la **Igualdad de Exponentes**. Cada letra en el primer término debe tener exactamente el mismo exponente sobre ella que la misma letra en el segundo término.",
    "explicacion": "Analicemos $5x^2$ y $5x^3$.\nAmbos tienen el coeficiente 5. Ambos tienen la letra 'x'.\nPero el primero está al cuadrado (exponente 2) y el segundo al cubo (exponente 3).\nComo los exponentes son distintos, **NO son semejantes**.\n\nEs el error más común en álgebra sumar $x^2 + x^3$ y decir que es $x^5$ o $2x^5$. Esto es falso. Son especies distintas. La expresión $x^2 + x^3$ no se puede reducir mediante sumas.",
    "procedimiento": ["Paso 1: Verifica que las letras sean iguales.", "Paso 2: Compara el exponente de la primera letra en ambos términos. Si difieren, descarta la semejanza.", "Paso 3: Repite el proceso para cada una de las letras presentes."],
    "ejemplos": [
        {"titulo": "Metros contra áreas", "enunciado": "¿Son semejantes 2a y 3a^2?", "solucion_pasos": ["La letra en ambos es 'a'.", "En 2a, la 'a' tiene exponente imaginario 1.", "En 3a^2, la 'a' tiene exponente 2.", "Como 1 no es igual a 2, no son semejantes."]}
    ],
    "errores_frecuentes": ["Sumar coeficientes ignorando que los exponentes son distintos (ej. $3x^2 + 4x = 7x^3$).", "Creer que si la suma de los exponentes totales (el grado del término) es igual, son semejantes (ej. pensar que $x^2y$ es semejante a $xy^2$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-EXP-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Por qué los términos $4x^2y$ y $4xy^2$ NO son semejantes, a pesar de tener el mismo coeficiente, las mismas letras y la misma suma total de exponentes (grado 3)? (v{i})", "choices": ["A) Porque el exponente está distribuido de manera diferente: en el primero, la $x$ está al cuadrado y la $y$ a la uno; en el segundo, es al revés.", "B) Porque la $y$ siempre debe ir antes que la $x$.", "C) Porque un término no puede tener exponente 1 imaginario.", "D) Porque los coeficientes deberían ser distintos para compensar los exponentes."], "correct_answer": "A) Porque el exponente está distribuido de manera diferente: en el primero, la $x$ está al cuadrado y la $y$ a la uno; en el segundo, es al revés.", "solution_steps": "La igualdad de exponentes es letra por letra. $x^2$ no es lo mismo que $x^1$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIM-EXP-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona el término que es semejante a $-9a^3b^2$.", "choices": ["A) $5a^3b^2$", "B) $-9a^2b^3$", "C) $5a^3b$", "D) $-9ab$"], "correct_answer": "A) $5a^3b^2$", "solution_steps": "El factor literal objetivo es $a^3b^2$. La única opción que mantiene intactas las letras y sus respectivos exponentes es la A.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-EXP-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $x^2 + x^2$ se reduce algebraicamente a $x^4$?", "choices": [], "correct_answer": "Falso", "solution_steps": "$x^2$ y $x^2$ son semejantes. Se suman sus coeficientes ($1+1=2$) manteniendo el factor literal intacto. El resultado es $2x^2$, no $x^4$. Sumar exponentes es un error de multiplicación, no de suma.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-EXP-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un arquitecto modela el costo de unos terrenos usando la expresión $C = 5x^2 + 10x$, donde $x^2$ representa el área y $x$ el perímetro frontal. Un pasante intenta simplificar la fórmula sumando los términos, obteniendo $C = 15x^3$. ¿Qué error fundamental cometió el pasante? (v{i})", "choices": ["A) Sumó los coeficientes de términos que no son semejantes (distinto exponente) e inventó un nuevo exponente.", "B) Multiplicó los términos en lugar de sumarlos.", "C) Olvidó sumar los coeficientes, el resultado debía ser $50x^3$.", "D) El cálculo del pasante es matemáticamente correcto."], "correct_answer": "A) Sumó los coeficientes de términos que no son semejantes (distinto exponente) e inventó un nuevo exponente.", "solution_steps": "$x^2$ (área) y $x$ (longitud) no son semejantes. Es como sumar metros cuadrados con metros lineales. La expresión $5x^2 + 10x$ es irreducible.", "paes_style": True})

# 4. ORDEN_LITERAL_DISTINTO
sid4 = "MAT.ALG.SIMILARIDAD.ORDEN_LITERAL_DISTINTO"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Comprender que el orden de los factores literales no altera la semejanza de los términos algebraicos.",
    "introduccion": "¿Es $3 \\times 4$ lo mismo que $4 \\times 3$? Sí, ambos dan 12. En álgebra pasa igual: las letras que se multiplican pueden cambiar de lugar sin alterar el resultado.",
    "resumen": "El **Orden Literal Distinto** es una trampa visual. Como las letras de un término se están multiplicando, la propiedad conmutativa aplica. Por lo tanto, $xy$ es **exactamente lo mismo** que $yx$.",
    "explicacion": "Mira estos dos términos: $5ab^2$ y $-2b^2a$.\nA primera vista, parecen diferentes. Pero analicemos:\n- ¿Tienen las mismas letras? Sí, ambos tienen 'a' y 'b'.\n- ¿Tienen los mismos exponentes letra por letra? La 'a' está elevada a 1 en ambos. La 'b' está elevada a 2 en ambos.\nConclusión: ¡Son totalmente semejantes!\n\nPara evitar confusiones, la convención matemática recomienda **ordenar las letras alfabéticamente**. Así, $-2b^2a$ se reescribe como $-2ab^2$, y la semejanza se hace evidente de inmediato.",
    "procedimiento": ["Paso 1: Si ves letras desordenadas, toma tu lápiz y reescribe cada término ordenando sus letras alfabéticamente.", "Paso 2: Asegúrate de que cada letra conserve su exponente original al moverla.", "Paso 3: Ahora compara los factores literales ya ordenados. Si coinciden, son semejantes."],
    "ejemplos": [
        {"titulo": "El disfraz del desorden", "enunciado": "¿Son semejantes 4xzy y 9yxz?", "solucion_pasos": ["Ordenamos el primero alfabéticamente: 4xyz.", "Ordenamos el segundo alfabéticamente: 9xyz.", "Comparamos: xyz es idéntico a xyz.", "Sí, son semejantes."]}
    ],
    "errores_frecuentes": ["Descartar la semejanza simplemente porque visualmente las letras no están en el mismo orden.", "Al ordenar, pasar el exponente de una letra a otra (ej. cambiar $a^2b$ a $ab^2$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-ORD-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿En qué propiedad matemática se basa el hecho de que el término $x^2y$ sea semejante al término $yx^2$? (v{i})", "choices": ["A) En la propiedad conmutativa de la multiplicación, que establece que el orden de los factores no altera el producto.", "B) En la propiedad distributiva de la multiplicación sobre la suma.", "C) En la regla de los signos.", "D) En la propiedad asociativa de la adición."], "correct_answer": "A) En la propiedad conmutativa de la multiplicación, que establece que el orden de los factores no altera el producto.", "solution_steps": "Las variables $x^2$ e $y$ se están multiplicando entre sí. Por la propiedad conmutativa, $x^2 \\cdot y = y \\cdot x^2$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIM-ORD-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Identifica cuál de las siguientes opciones contiene un par de términos que SÍ son semejantes.", "choices": ["A) $7m^2np^3$  y  $-2p^3nm^2$", "B) $3ab^2$  y  $3a^2b$", "C) $5xyz$  y  $5xy$", "D) $-4x$  y  $4x^2$"], "correct_answer": "A) $7m^2np^3$  y  $-2p^3nm^2$", "solution_steps": "Reordenemos la opción A alfabéticamente: $-2p^3nm^2 \\rightarrow -2m^2np^3$. Ahora es evidente que comparte el factor literal $m^2np^3$ con el primer término.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-ORD-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si sumamos $3ab$ y $2ba$, el resultado es $5ab$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Como $ba$ es lo mismo que $ab$, estamos sumando $3ab + 2ab$. Al ser semejantes, sumamos coeficientes: $3+2=5$, manteniendo el factor literal. Da $5ab$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-ORD-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"La energía de dos sistemas físicos se describe por las ecuaciones $E_1 = 4m^2v$ y $E_2 = -3vm^2$. Si se requiere calcular la energía neta ($E_1 + E_2$), ¿cuál es la expresión reducida correcta? (v{i})", "choices": ["A) $m^2v$", "B) $7m^2v$", "C) $m^4v^2$", "D) Las expresiones no se pueden sumar."], "correct_answer": "A) $m^2v$", "solution_steps": "$vm^2$ se reescribe como $m^2v$. Tenemos $4m^2v - 3m^2v$. Como son semejantes, restamos coeficientes: $4 - 3 = 1$. Queda $1m^2v$, que se escribe $m^2v$.", "paes_style": True})

# 5. TERMINOS_NO_SEMEJANTES
sid5 = "MAT.ALG.SIMILARIDAD.TERMINOS_NO_SEMEJANTES"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Identificar términos que no cumplen los criterios de semejanza y dejarlos expresados como suma o resta irreducible.",
    "introduccion": "En álgebra, hay un instinto compulsivo de querer juntar todo en una sola 'bola'. Pero a veces, la respuesta correcta es dejar las cosas exactamente como están.",
    "resumen": "Cuando los **Términos No son Semejantes** (difieren en letras o exponentes), es algebraicamente imposible agruparlos mediante sumas o restas. La expresión se considera **irreducible** en ese aspecto.",
    "explicacion": "Si te piden sumar $2x$ y $3y$, la respuesta final y definitiva es $2x + 3y$.\nSi te piden sumar $x^2$ y $x$, la respuesta final es $x^2 + x$.\nNo hay ninguna regla mágica que los funda en algo como $5xy$ o $2x^3$. Forzar una reducción donde no hay semejanza es destruir las reglas matemáticas fundamentales. La frontera queda trazada: lo que no es igual, no se mezcla en la suma.",
    "procedimiento": ["Paso 1: Aplica el test de semejanza (mismas letras, mismos exponentes).", "Paso 2: Si el test falla, los términos no son semejantes.", "Paso 3: Para sumar o restar, simplemente escribe un término al lado del otro conectado por su signo.", "Paso 4: Declara que la expresión está en su forma más simple (irreducible)."],
    "ejemplos": [
        {"titulo": "Forzando la mezcla", "enunciado": "Reduce si es posible: 8a^3 - 5a^2.", "solucion_pasos": ["Analizamos: tienen la letra 'a', pero uno es al cubo y otro al cuadrado.", "Veredicto: No son semejantes.", "Conclusión: La expresión no se puede reducir. Queda 8a^3 - 5a^2."]}
    ],
    "errores_frecuentes": ["Juntar las letras de términos que se suman (ej. $2a + 3b = 5ab$). ¡Eso sería si estuvieran multiplicando!", "Sumar los exponentes al sumar bases iguales (ej. $x^2 + x^3 = x^5$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-NO-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el procedimiento correcto cuando se solicita sumar o restar algebraicamente dos términos que resultan NO ser semejantes? (v{i})", "choices": ["A) Dejar la operación expresada como un polinomio sin agrupar sus coeficientes, ya que es irreducible mediante sumas y restas.", "B) Sumar los coeficientes y escribir todas las letras involucradas juntas.", "C) Multiplicar los coeficientes y sumar los exponentes.", "D) Sumar los exponentes y eliminar los coeficientes."], "correct_answer": "A) Dejar la operación expresada como un polinomio sin agrupar sus coeficientes, ya que es irreducible mediante sumas y restas.", "solution_steps": "Si no son semejantes, no pueden fusionarse en la adición/sustracción. Se dejan conectados por el signo de la operación (+ o -).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIM-NO-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Si se te pide reducir la expresión $5x^2y + 5xy^2$, ¿cuál es el resultado correcto?", "choices": ["A) $5x^2y + 5xy^2$ (no se puede reducir)", "B) $10x^3y^3$", "C) $10x^2y^2$", "D) $25x^3y^3$"], "correct_answer": "A) $5x^2y + 5xy^2$ (no se puede reducir)", "solution_steps": "El primer término tiene $x^2$ y el segundo tiene $x$. Al diferir los exponentes, no son semejantes. La expresión queda idéntica.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-NO-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La reducción final de la suma entre $7a$ y $2b$ es igual a $9ab$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Las variables son diferentes ($a$ y $b$), por lo que no son semejantes. La suma queda indicada como $7a + 2b$. Poner $9ab$ es un error de quien confunde la suma con la multiplicación.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIM-NO-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un sastre confecciona trajes usando metros de tela de algodón ($x$) y tela sintética ($y$). Para un lote usa $100x$ metros, y para un segundo lote requiere $50y$ metros. Si desea expresar el total de tela utilizada, ¿qué expresión debe entregarle al contador? (v{i})", "choices": ["A) $100x + 50y$", "B) $150xy$", "C) $150(x+y)$", "D) $5000xy$"], "correct_answer": "A) $100x + 50y$", "solution_steps": "El algodón ($x$) y lo sintético ($y$) son unidades distintas (no semejantes). El total simplemente se expresa sumándolos: $100x + 50y$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 1 (B0303/Similaridad)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 1...")
    append_jsonl("mat-alg-operaciones-banco-gen-1", EJERCICIOS)
    print("Creado mat-alg-operaciones-banco-gen-1.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
