# scratch/build_b0205_t13.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. TIPOS_DEUDA
sid1 = "MAT.NUM.FINANZAS_PERSONALES.TIPOS_DEUDA"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Clasificar los tipos de deuda personal y sus implicancias financieras.",
    "introduccion": "No toda la deuda es mala. Endeudarse para comprar una casa o estudiar puede ser una inversión en tu futuro. Pero endeudarse para ir de vacaciones o comprar comida es una trampa mortal.",
    "resumen": "Tipos de deuda comunes: Crédito Hipotecario (para bienes raíces, largo plazo), Crédito de Consumo (libre disposición, mediano plazo), Crédito Automotriz, CAE (estudiantil) y Tarjetas de Crédito (cupo rotativo, altas tasas).",
    "explicacion": "Una deuda es un compromiso de devolver dinero prestado más un interés. No todas tienen el mismo riesgo:\n\n- **Hipotecario:** Sirve para comprar propiedades. Suele tener las tasas de interés más bajas porque la propiedad es la garantía.\n- **Automotriz:** Para comprar vehículos. El vehículo queda en 'prenda' (no puedes venderlo hasta pagar la deuda).\n- **Consumo / Personal:** El banco te presta dinero en efectivo para lo que quieras. Tiene tasas más altas porque no hay garantías físicas fuertes.\n- **Estudiantil (CAE, Fondo Solidario):** Para financiar educación superior. Suelen tener tasas bajas y condiciones de pago asociadas a los ingresos futuros.\n- **Tarjetas de Crédito / Líneas de Crédito:** Es dinero plástico o disponible al instante. Si no pagas el total facturado a fin de mes, cobran los intereses más altos del mercado (interés rotativo).",
    "procedimiento": ["Paso 1: Analiza el propósito del dinero prestado.", "Paso 2: Evalúa qué tipo de garantía exige el banco (la casa, el auto, o solo tu firma).", "Paso 3: A menor garantía, mayor suele ser la tasa de interés que te cobran."],
    "ejemplos": [
        {"titulo": "Comprando un departamento", "enunciado": "Si quieres adquirir un departamento a 20 años plazo, ¿qué tipo de crédito debes solicitar?", "solucion_pasos": ["Es un bien raíz.", "Es a largo plazo.", "Por lo tanto, la opción correcta es un Crédito Hipotecario."]}
    ],
    "errores_frecuentes": ["Usar la Tarjeta de Crédito en muchas cuotas para pagar compras grandes y permanentes (sus intereses arruinan el presupuesto).", "Pedir un Crédito de Consumo para comprar una casa (los plazos son muy cortos y la cuota sería impagable)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEUDA-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué tipo de instrumento financiero está diseñado específicamente para la compra a largo plazo de bienes raíces, dejando el inmueble como garantía? (v{i})", "choices": ["A) Crédito Hipotecario.", "B) Crédito de Consumo.", "C) Tarjeta de Crédito.", "D) Línea de Crédito."], "correct_answer": "A) Crédito Hipotecario.", "solution_steps": "Hipotecario viene de hipoteca (garantía sobre inmuebles).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEUDA-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Generalmente, ¿qué instrumento de deuda suele tener la tasa de interés más alta y peligrosa si no se paga el monto total facturado a fin de mes?", "choices": ["A) Tarjeta de Crédito.", "B) Crédito Hipotecario.", "C) Crédito con Aval del Estado (CAE).", "D) Préstamo Estudiantil."], "correct_answer": "A) Tarjeta de Crédito.", "solution_steps": "El crédito rotativo de las tarjetas tiene altísimas tasas por su disponibilidad inmediata y bajo respaldo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEUDA-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Un crédito automotriz deja tu cuenta bancaria bloqueada como garantía de pago?", "choices": [], "correct_answer": "Falso", "solution_steps": "La garantía en un crédito automotriz es el vehículo (queda en prenda), no tu cuenta bancaria.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEUDA-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Pedro quiere hacer un viaje soñado a Europa que cuesta $\$3.000.000$. Él no tiene ahorros. Si va al banco a pedir ese dinero en efectivo para pagarlo en $36$ meses, ¿qué tipo de crédito le otorgará el banco? (v{i})", "choices": ["A) Crédito de Consumo.", "B) Crédito Hipotecario.", "C) Crédito Automotriz.", "D) Crédito Estudiantil."], "correct_answer": "A) Crédito de Consumo.", "solution_steps": "Un viaje es un bien inmaterial de libre disposición, por ende se financia con un crédito de consumo.", "paes_style": True})

# 2. PRESUPUESTO_PERSONAL
sid2 = "MAT.NUM.FINANZAS_PERSONALES.PRESUPUESTO_PERSONAL"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Comprender la estructura y finalidad de un presupuesto personal mensual.",
    "introduccion": "Si no le dices a tu dinero a dónde ir, terminarás preguntándote a dónde se fue. El presupuesto no es para restringirte, es un plan para que el dinero alcance para tus metas.",
    "resumen": "Un presupuesto es una herramienta que detalla Ingresos (dinero entrante), Gastos (dinero saliente) y Ahorro esperado. La regla de oro es que Gastos + Ahorro no deben superar los Ingresos.",
    "explicacion": "Un **Presupuesto Personal** es un documento (o tabla Excel) donde planificas el mes.\nSe construye sumando todos tus **Ingresos Totales** y restando todos tus **Gastos (Fijos y Variables)**.\n\nEstructura ideal (Regla 50/30/20):\n- **50% Necesidades Básicas:** Arriendo, comida, transporte, servicios.\n- **30% Gastos Personales / Deseos:** Salidas, ropa, entretenimiento.\n- **20% Ahorro / Pago de deudas:** Dinero que se guarda para el futuro o emergencias.\n\nEl peor error es 'ahorrar lo que sobra a fin de mes' (porque nunca sobra). El ahorro debe presupuestarse como si fuera un gasto fijo al principio del mes ('Págate a ti mismo primero').",
    "procedimiento": ["Paso 1: Suma tus ingresos fijos del mes.", "Paso 2: Define tu meta de ahorro y sepárala de inmediato.", "Paso 3: Lista tus gastos fijos obligatorios.", "Paso 4: Asigna el resto del dinero a tus gastos variables hasta que la cuenta llegue a cero ($Ingresos - Ahorro - Gastos = 0$)."],
    "ejemplos": [
        {"titulo": "Aplicando la regla 50/30/20", "enunciado": "Si ganas $600.000 al mes, ¿cuánto deberías destinar al ahorro idealmente usando la regla 50/30/20?", "solucion_pasos": ["El 20% debe ir a Ahorro.", "20% de 600.000 es $600.000 \\cdot 0.20 = 120.000$.", "Deberías ahorrar $120.000 mensuales."]}
    ],
    "errores_frecuentes": ["No incluir los gastos 'hormiga' (café, golosinas, Uber) en el presupuesto, los cuales terminan desequilibrándolo a fin de mes.", "Poner el ahorro al final de la lista de prioridades."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PRESUP-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el objetivo principal de elaborar un presupuesto personal mensual? (v{i})", "choices": ["A) Planificar y controlar en qué se gastarán los ingresos antes de que ocurran.", "B) Calcular cuánto impuesto debe pagar la persona al Estado.", "C) Pedir dinero prestado al banco.", "D) Gastar la menor cantidad de dinero posible en comida."], "correct_answer": "A) Planificar y controlar en qué se gastarán los ingresos antes de que ocurran.", "solution_steps": "El presupuesto es una herramienta de planificación anticipada.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PRESUP-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Según la regla financiera 50/30/20, ¿qué porcentaje de los ingresos debería destinarse idealmente al ahorro y pago de deudas?", "choices": ["A) $20\\%$", "B) $30\\%$", "C) $50\\%$", "D) $10\\%$"], "correct_answer": "A) $20\\%$", "solution_steps": "50 Necesidades / 30 Deseos / 20 Ahorro.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PRESUP-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El ahorro en un presupuesto estructurado debe calcularse con el dinero que sobra a fin de mes, una vez pagados todos los gastos variables?", "choices": [], "correct_answer": "Falso", "solution_steps": "Falso. El ahorro debe ser el primer 'gasto' que se separa al recibir el sueldo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PRESUP-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un estudiante universitario tiene una mesada de $\$150.000$. Él destina el $60\\%$ a pasajes y comida (necesidades), y decide que quiere ahorrar mensualmente el $15\\%$ de su mesada para comprar una consola. ¿Cuánto dinero le quedará libre para sus gastos variables de entretenimiento durante el mes? (v{i})", "choices": ["A) $\$37.500$", "B) $\$22.500$", "C) $\$90.000$", "D) $\$60.000$"], "correct_answer": "A) $\$37.500$", "solution_steps": "Total comprometido: $60\\% + 15\\% = 75\\%$. Le queda un $25\\%$ para entretenimiento. El $25\\%$ de $150.000$ es $150.000 / 4 = 37.500$.", "paes_style": True})

# 3. BALANCE_FLUJO
sid3 = "MAT.NUM.FINANZAS_PERSONALES.BALANCE_FLUJO"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Calcular el balance mensual restando los gastos totales a los ingresos totales.",
    "introduccion": "Llegó fin de mes. Sumamos todo lo que entró y restamos todo lo que salió. Si el número es verde, hiciste las cosas bien. Si el número es rojo, estás cavando un hoyo financiero.",
    "resumen": "Balance Financiero = Ingresos Totales - Gastos Totales. Un balance positivo indica superávit (capacidad de ahorro). Un balance negativo indica déficit (endeudamiento).",
    "explicacion": "El **Balance o Flujo de Caja Mensual** es la operación matemática que evalúa el resultado de tu mes.\n\nFórmula:\n$$\\text{Balance} = \\sum \\text{Ingresos} - \\sum \\text{Gastos}$$\n\n- **Superávit (Balance $> 0$):** Te sobró dinero. Tus ingresos fueron mayores que tus gastos. Este dinero debe ir a ahorro o inversión.\n- **Equilibrio (Balance $= 0$):** Gastaste exactamente todo lo que ganaste (vivir al día).\n- **Déficit (Balance $< 0$):** Gastaste más de lo que ganaste. Esto significa matemáticamente que usaste crédito (tarjeta, préstamo) o ahorros pasados para cubrir el mes. Estás aumentando tus deudas.",
    "procedimiento": ["Paso 1: Suma todos tus ingresos del periodo.", "Paso 2: Suma todos tus gastos (fijos, variables, cuotas de créditos).", "Paso 3: Resta $Ingresos - Gastos$ para obtener el Balance final."],
    "ejemplos": [
        {"titulo": "Cálculo de flujo", "enunciado": "Ingreso: $500.000. Gastos Fijos: $300.000. Gastos Variables: $250.000. ¿Cuál es el balance?", "solucion_pasos": ["Total Gastos = $300.000 + 250.000 = 550.000$.", "Balance = $500.000 - 550.000 = -50.000$.", "Hay un déficit de $50.000. Esa persona se endeudó ese mes."]}
    ],
    "errores_frecuentes": ["Olvidar sumar los 'pagos con tarjeta de crédito' como un gasto en el mes que se pagan.", "Creer que pedir un préstamo suma como 'Ingreso' (el préstamo te da efectivo hoy, pero aumenta tus gastos futuros, no es un ingreso real tuyo)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"BALANCE-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si en un mes particular el balance financiero de una familia resulta negativo (déficit), esto implica necesariamente que: (v{i})", "choices": ["A) Gastaron más dinero del que ingresó, incurriendo en deuda o gastando ahorros.", "B) Sus ingresos fijos fueron menores a sus ingresos variables.", "C) Pagaron todos sus créditos anticipadamente.", "D) Lograron ahorrar dinero para el futuro."], "correct_answer": "A) Gastaron más dinero del que ingresó, incurriendo en deuda o gastando ahorros.", "solution_steps": "Déficit significa que los egresos superaron a los ingresos.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"BALANCE-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál es la fórmula básica para calcular el balance financiero de un período?", "choices": ["A) Total de Ingresos menos Total de Gastos.", "B) Total de Gastos menos Total de Ahorros.", "C) Ingresos Fijos menos Ingresos Variables.", "D) Total de Deudas dividido por Ingresos."], "correct_answer": "A) Total de Ingresos menos Total de Gastos.", "solution_steps": "Ingresos - Gastos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"BALANCE-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si tus ingresos son de $\$800.000$ y tus gastos totales son de $\$750.000$, tienes un déficit financiero?", "choices": [], "correct_answer": "Falso", "solution_steps": "Tus ingresos son mayores que tus gastos ($800.000 - 750.000 = +50.000$). Tienes un superávit, no un déficit.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"BALANCE-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Carlos registra los siguientes movimientos en marzo: Sueldo base $\$600.000$, bono por metas $\$150.000$, pago de arriendo y cuentas $\$400.000$, cuota crédito automotriz $\$180.000$, supermercado $\$120.000$ y salidas $\$80.000$. ¿Cuál es su balance financiero a fin de mes? (v{i})", "choices": ["A) Déficit de $\$30.000$", "B) Superávit de $\$30.000$", "C) Déficit de $\$80.000$", "D) Equilibrio ($\$0$)"], "correct_answer": "A) Déficit de $\$30.000$", "solution_steps": "Ingresos = $600.000 + 150.000 = 750.000$. Gastos = $400.000 + 180.000 + 120.000 + 80.000 = 780.000$. Balance = $750.000 - 780.000 = -30.000$.", "paes_style": True})

# 4. IPC_DEFINICION
sid4 = "MAT.NUM.FINANZAS_PERSONALES.IPC_DEFINICION"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Comprender qué es el IPC (Índice de Precios al Consumidor) y cómo afecta el poder adquisitivo.",
    "introduccion": "Hace 10 años, con $10.000 llenabas el carro del supermercado. Hoy, con suerte compras un par de cosas. El dinero pierde valor invisiblemente. El culpable (o el termómetro de esto) es la inflación, medida a través del IPC.",
    "resumen": "El IPC mide la variación de los precios de una 'canasta básica' de bienes y servicios a lo largo del tiempo. Un IPC positivo indica inflación (las cosas están más caras, tu dinero vale menos).",
    "explicacion": "El **Índice de Precios al Consumidor (IPC)** es el indicador oficial que mide la **inflación**.\n- El Instituto Nacional de Estadísticas (INE) arma una 'Canasta Básica' representativa de lo que consume una familia chilena promedio (pan, transporte, vivienda, salud, educación).\n- Cada mes miden si esa misma canasta cuesta más o menos que el mes anterior.\n- **IPC Positivo (+0.4%):** Hubo inflación. El costo de vida subió.\n- **Poder Adquisitivo:** Si hay inflación, pero tu sueldo no sube, tu 'poder adquisitivo' (lo que puedes comprar con tu sueldo) disminuye.\n\nPor eso, la UF (Unidad de Fomento) se reajusta diariamente según la variación mensual del IPC. Los créditos, arriendos y planes de salud suelen estar en UF para proteger a los vendedores de la inflación.",
    "procedimiento": ["Paso 1: Identifica si el IPC del período fue positivo (inflación) o negativo (deflación).", "Paso 2: Si el IPC es positivo, los precios subieron.", "Paso 3: Si tu sueldo se mantuvo igual, tu capacidad de compra (poder adquisitivo) bajó en esa misma proporción."],
    "ejemplos": [
        {"titulo": "Aumento de precios y sueldo congelado", "enunciado": "Si el IPC del año fue de un 5% y tu sueldo no subió nada en todo el año, ¿eres más rico o más pobre?", "solucion_pasos": ["Los productos son un 5% más caros.", "Tu sueldo es el mismo en billetes, pero ahora compra menos cosas.", "Por lo tanto, eres un 5% más 'pobre' en poder adquisitivo."]}
    ],
    "errores_frecuentes": ["Creer que si la inflación baja, los precios bajan (Falso. Si la inflación baja de 8% a 4%, los precios SIGUEN SUBIENDO, pero más lento. Para que los precios bajen debe haber IPC negativo o Deflación).", "Pensar que el IPC mide solo el precio del pan y la bencina (Mide una canasta de cientos de productos)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IPC-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué fenómeno económico describe un aumento sostenido y generalizado de los precios, medido mensualmente por el IPC? (v{i})", "choices": ["A) Inflación.", "B) Deflación.", "C) Superávit.", "D) Devaluación."], "correct_answer": "A) Inflación.", "solution_steps": "La inflación es el alza generalizada de precios reflejada en el IPC.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"IPC-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en un año el IPC acumulado fue del $6\\%$, ¿qué efecto directo tiene esto sobre un trabajador cuyo sueldo en pesos no tuvo reajuste alguno durante ese año?", "choices": ["A) Su poder adquisitivo disminuyó.", "B) Su poder adquisitivo aumentó.", "C) Su poder adquisitivo se mantuvo igual.", "D) Pagará menos impuestos."], "correct_answer": "A) Su poder adquisitivo disminuyó.", "solution_steps": "Como las cosas son 6% más caras, con su mismo sueldo puede comprar menos cosas.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IPC-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La Unidad de Fomento (UF) en Chile es una unidad de medida que ajusta su valor en pesos diariamente de acuerdo a la variación del IPC del mes anterior?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Exactamente. La UF está indexada a la inflación para mantener su valor adquisitivo constante.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IPC-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una familia gasta mensualmente $\$400.000$ en bienes básicos. Si el Banco Central anuncia que la inflación proyectada (IPC) para el próximo año será de un $5\\%$, ¿cuánto dinero necesitará esa familia mensualmente el próximo año para comprar exactamente la misma cantidad de bienes? (v{i})", "choices": ["A) $\$420.000$", "B) $\$380.000$", "C) $\$400.000$", "D) $\$405.000$"], "correct_answer": "A) $\$420.000$", "solution_steps": "Debe aplicarse un aumento porcentual del $5\\%$ sobre los $\$400.000$. Factor = $1.05$. $400.000 \\cdot 1.05 = 420.000$.", "paes_style": True})

# 5. RENTABILIDAD
sid5 = "MAT.NUM.FINANZAS_PERSONALES.RENTABILIDAD"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Comprender el concepto de rentabilidad al invertir o guardar dinero.",
    "introduccion": "¿Dejar la plata bajo el colchón o meterla al banco? Si la dejas en el colchón, la inflación se la comerá. Si la inviertes, esperas que te pague un premio por usarla. Ese premio es la rentabilidad.",
    "resumen": "La rentabilidad es el beneficio económico que obtienes por invertir un capital. Se expresa como un porcentaje: $((Ganancia) / Capital Inicial) \\cdot 100$.",
    "explicacion": "La **Rentabilidad** es la variación porcentual positiva de una inversión.\n\nFórmula:\n$$\\text{Rentabilidad } \\% = \\left( \\frac{\\text{Ganancia Obtenida}}{\\text{Capital Inicial Invertido}} \\right) \\cdot 100$$\n\n- **Inversión de bajo riesgo:** Como un Depósito a Plazo. Te pagan poco (ej. $5\\%$ anual), pero tu dinero está 100% seguro.\n- **Inversión de alto riesgo:** Como comprar acciones o criptomonedas. Puedes ganar mucho (ej. $30\\%$ anual), pero también puedes perder tu capital inicial (rentabilidad negativa).\n\n**Regla de oro financiera:** A mayor rentabilidad esperada, mayor es el riesgo de perder tu dinero. No existen inversiones de alta rentabilidad y riesgo cero (quien prometa eso, probablemente ofrezca una estafa piramidal).",
    "procedimiento": ["Paso 1: Identifica tu Inversión Inicial (cuánto dinero pusiste).", "Paso 2: Calcula la ganancia neta (Valor Final - Inversión Inicial).", "Paso 3: Divide la ganancia por la inversión inicial y multiplica por 100 para obtener el porcentaje de rentabilidad."],
    "ejemplos": [
        {"titulo": "Rentabilidad de un negocio", "enunciado": "Invertiste $100.000 en comprar fundas de celulares. Las vendiste todas y recibiste $150.000. ¿Cuál fue tu rentabilidad?", "solucion_pasos": ["Inversión Inicial = $100.000.", "Ganancia = $150.000 - 100.000 = 50.000$.", "Rentabilidad = $(50.000 / 100.000) \\cdot 100 = 0.5 \\cdot 100 = 50\\%$.", "Obtuviste un 50% de rentabilidad."]}
    ],
    "errores_frecuentes": ["Dividir el Valor Final completo (y no solo la ganancia) sobre la Inversión, lo que daría rentabilidades infladas superiores al 100% en el ejemplo anterior.", "Ignorar el efecto de la inflación (si el banco te da 5% de rentabilidad pero la inflación es 6%, tu rentabilidad 'real' es negativa)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RENTAB-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el mundo de las inversiones financieras, ¿cuál es la relación general entre el nivel de riesgo y la rentabilidad esperada? (v{i})", "choices": ["A) A mayor riesgo, mayor es la rentabilidad esperada que se exige.", "B) A mayor riesgo, menor es la rentabilidad esperada.", "C) El riesgo no tiene relación con la rentabilidad en un mercado formal.", "D) Las inversiones sin riesgo ofrecen la mayor rentabilidad posible."], "correct_answer": "A) A mayor riesgo, mayor es la rentabilidad esperada que se exige.", "solution_steps": "Los inversionistas solo asumen alto riesgo si el premio (rentabilidad) es suficientemente atractivo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RENTAB-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "La fórmula para calcular la rentabilidad porcentual de una inversión es:", "choices": ["A) (Ganancia Neta / Capital Inicial) multiplicado por 100.", "B) (Capital Final / Capital Inicial) multiplicado por 100.", "C) Ganancia Neta menos Capital Inicial.", "D) (Capital Inicial / Ganancia Neta) multiplicado por 100."], "correct_answer": "A) (Ganancia Neta / Capital Inicial) multiplicado por 100.", "solution_steps": "Mide qué porcentaje del capital inicial se convirtió en utilidades nuevas.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RENTAB-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si inviertes $\$20.000$ y al mes siguiente retiras $\$22.000$, tu rentabilidad fue del $10\\%$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Ganancia: $2.000$. Rentabilidad: $(2.000 / 20.000) \\cdot 100 = 0.1 \\cdot 100 = 10\\%$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RENTAB-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un inversionista compró acciones por un total de $\$1.500.000$. Al cabo de un año, el valor de sus acciones subió a $\$1.800.000$ y decidió venderlas. Pagó $\$30.000$ en comisiones al corredor de bolsa por la venta. ¿Cuál fue su rentabilidad porcentual real neta? (v{i})", "choices": ["A) $18\\%$", "B) $20\\%$", "C) $120\\%$", "D) $22\\%$"], "correct_answer": "A) $18\\%$", "solution_steps": "Valor de venta: $1.800.000$. Descuenta comisión: $1.800.000 - 30.000 = 1.770.000$. Ganancia neta: $1.770.000 - 1.500.000 = 270.000$. Rentabilidad: $(270.000 / 1.500.000) \\cdot 100 = 0.18 \\cdot 100 = 18\\%$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 13...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 13...")
    append_jsonl("mat-num-razones-banco-gen-13", EJERCICIOS)
    print("Creado mat-num-razones-banco-gen-13.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
