# scratch/build_alg_b0302_t6.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 25. COMO_MAXIMO
sid25 = "MAT.ALG.LENGUAJE_RELACIONES.COMO_MAXIMO"
RECURSOS.append({
    "semantic_id": sid25, "objetivo": "Traducir el concepto de límite superior incluyente usando el símbolo menor o igual que.",
    "introduccion": "Si tu madre te dice: 'Puedes gastar como máximo 20 dólares', ¿puedes gastar exactamente 20? Sí. ¿Puedes gastar 19? Sí. ¿Puedes gastar 21? No. Este es un límite cerrado superior.",
    "resumen": "La frase **'Como máximo'** se traduce utilizando el símbolo de desigualdad **menor o igual que ($\\le$)**. Indica que la variable puede tomar cualquier valor por debajo del límite, o tocar el límite exactamente, pero nunca superarlo.",
    "explicacion": "Palabras clave que se traducen como $\\le$:\n- Como máximo\n- A lo más\n- No más de\n- Hasta\n- Tiene un tope de\n\nEjemplos:\n- 'El peso soportado ($P$) es como máximo 500 kg': $P \\le 500$\n- 'Gastaré a lo más el doble de mi sueldo ($S$)': $Gastos \\le 2S$\n\nLa diferencia crucial con el 'menor que' estricto ($<$) es la pequeña línea horizontal debajo del símbolo, que significa 'o igual'.",
    "procedimiento": ["Paso 1: Identifica la variable que está siendo limitada (el sujeto de la oración).", "Paso 2: Al leer 'como máximo' o 'a lo más', escribe el símbolo <= (menor o igual).", "Paso 3: Escribe el valor del límite máximo a la derecha del símbolo."],
    "ejemplos": [
        {"titulo": "El tope de gastos", "enunciado": "Traduce algebraicamente: 'El costo total de la obra no será de más de un millón'.", "solucion_pasos": ["Costo total de la obra: C.", "La frase 'no será de más de' significa que puede ser menos o exactamente igual: <=", "El límite es un millón: 1000000.", "Traducción: C <= 1000000."]}
    ],
    "errores_frecuentes": ["Traducir 'como máximo' usando el símbolo de mayor ($>$ o $\\ge$) confundidos por la palabra 'máximo'. (Si el tope es el máximo, la variable tiene que ser *menor* que el tope).", "Usar el símbolo estricto de menor ($<$) perdiendo la posibilidad de igualdad."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CMAX-CONC-{i}", "semantic_id": sid25, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Por qué es un error lógico traducir la restricción 'como máximo' utilizando el símbolo de 'mayor o igual que' ($\\ge$)? (v{i})", "choices": ["A) Porque 'como máximo' establece un techo o límite superior, por lo que los valores permitidos para la variable deben estar obligatoriamente por debajo o ser iguales a dicho límite ($\\le$).", "B) Porque el símbolo $\\ge$ solo se usa para ecuaciones de segundo grado.", "C) Porque 'como máximo' solo permite valores estrictamente menores ($<$), sin incluir el límite.", "D) Porque 'como máximo' significa que la variable debe multiplicarse por el valor máximo posible."], "correct_answer": "A) Porque 'como máximo' establece un techo o límite superior, por lo que los valores permitidos para la variable deben estar obligatoriamente por debajo o ser iguales a dicho límite ($\\le$).", "solution_steps": "Si te digo 'como máximo 10', puedes tener 9, 8... es decir, cantidades *menores* o iguales a 10. Por eso se usa $\\le$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CMAX-REC-1", "semantic_id": sid25, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica la traducción algebraica de la instrucción: 'La temperatura ($T$) del horno puede alcanzar, a lo más, los $250$ grados'.", "choices": ["A) $T \\le 250$", "B) $T \\ge 250$", "C) $T < 250$", "D) $T = 250$"], "correct_answer": "A) $T \\le 250$", "solution_steps": "La frase 'a lo más' es equivalente a 'como máximo'. El horno puede estar a 250 (igual) o menos. Símbolo: $\\le$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CMAX-PROC-{i}", "semantic_id": sid25, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La frase 'el equipo no puede tener más de $11$ jugadores en cancha ($J$)' se traduce correctamente como la inecuación $J \\le 11$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "No tener 'más de 11' significa que tener 12 es ilegal, pero tener exactamente 11 (o menos) sí es legal. Esto es la definición del límite incluyente $\\le$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CMAX-PAES-{i}", "semantic_id": sid25, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Para un bono de productividad, el contrato exige que 'el número de productos defectuosos ($D$) sea como máximo la cuarta parte de los productos perfectos ($P$)'. Un sindicato reclama que el bono debería darse con la condición $D < \\frac{{P}}{{4}}$. ¿En qué perjudica matemáticamente la versión del sindicato al trabajador respecto al contrato original? (v{i})", "choices": ["A) Le quita el bono en el caso frontera donde los defectuosos sean exactamente iguales a la cuarta parte de los perfectos, situación que el contrato original sí premiaba al incluir el 'o igual' ($\\le$).", "B) Ningún perjuicio, ambas inecuaciones son idénticas en números enteros.", "C) La versión del sindicato le exige al trabajador tener menos perfectos que defectuosos.", "D) La versión del sindicato obliga a que los productos defectuosos sean negativos."], "correct_answer": "A) Le quita el bono en el caso frontera donde los defectuosos sean exactamente iguales a la cuarta parte de los perfectos, situación que el contrato original sí premiaba al incluir el 'o igual' ($\\le$).", "solution_steps": "El contrato original era $D \\le P/4$. El sindicato propuso $D < P/4$. Al quitar la posibilidad de igualdad, se vuelve más estricto, perjudicando a los trabajadores que alcanzan justo el borde de la meta.", "paes_style": True})

# 26. POR_LO_MENOS
sid26 = "MAT.ALG.LENGUAJE_RELACIONES.POR_LO_MENOS"
RECURSOS.append({
    "semantic_id": sid26, "objetivo": "Traducir el concepto de límite inferior incluyente usando el símbolo mayor o igual que.",
    "introduccion": "Para subir a la montaña rusa debes medir 'por lo menos' 1.50 metros. Si mides exacto 1.50m, pasas. Si mides 1.60m, también. Este es el piso mínimo indispensable.",
    "resumen": "La frase **'Por lo menos'** se traduce utilizando el símbolo de desigualdad **mayor o igual que ($\\ge$)**. Indica que la variable tiene un valor de piso y puede tomar ese valor exacto o cualquiera superior a él.",
    "explicacion": "Palabras clave que se traducen como $\\ge$:\n- Por lo menos\n- Al menos\n- Como mínimo\n- No menos de\n- Desde\n\nEjemplos:\n- 'La edad ($E$) requerida es de por lo menos 18 años': $E \\ge 18$\n- 'Como mínimo debes sacar la mitad del puntaje ($P$)': $Nota \\ge \\frac{P}{2}$\n\nNuevamente, el instinto engaña. Uno lee 'por lo MENOS' y el cerebro quiere dibujar un signo 'menor'. ¡Error! Si te exigen 'por lo menos' algo, te están exigiendo que seas de ese tamaño *hacia arriba* (mayor o igual).",
    "procedimiento": ["Paso 1: Identifica la variable sujeta a la condición (el sujeto).", "Paso 2: Al leer 'por lo menos' o 'como mínimo', escribe el símbolo >= (mayor o igual).", "Paso 3: Escribe el valor del umbral mínimo a la derecha del símbolo."],
    "ejemplos": [
        {"titulo": "El piso de aprobación", "enunciado": "Traduce algebraicamente: 'Para aprobar, el estudiante necesita sacar no menos de 60 puntos'.", "solucion_pasos": ["Sujeto: El puntaje del estudiante (P).", "La frase 'no menos de' permite sacar 60 exactos, o 70, o 100. Es un piso mínimo: >=", "El umbral es 60.", "Traducción: P >= 60."]}
    ],
    "errores_frecuentes": ["Traducir 'por lo menos' con el símbolo $\\le$ o $<$ (caer en la trampa lingüística de la palabra 'menos').", "Traducirlo con el símbolo estricto $>$ (perdiendo el derecho a igualar el piso)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PMEN-CONC-{i}", "semantic_id": sid26, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al traducir al lenguaje algebraico, ¿por qué la expresión 'por lo menos' se representa con el símbolo de 'mayor o igual que' ($\\ge$) y no con uno de menor? (v{i})", "choices": ["A) Porque 'por lo menos' establece un piso (un requisito mínimo), permitiendo que la variable tome ese valor base o cualquier cantidad que lo supere.", "B) Porque en álgebra las palabras siempre significan lo contrario que en el lenguaje natural.", "C) Porque es imposible tener variables menores en una inecuación.", "D) Porque 'por lo menos' siempre se refiere a números negativos."], "correct_answer": "A) Porque 'por lo menos' establece un piso (un requisito mínimo), permitiendo que la variable tome ese valor base o cualquier cantidad que lo supere.", "solution_steps": "Si necesitas 'por lo menos 5 dólares' para un sándwich, te sirven 5, 10 o 100 dólares (cantidades mayores o iguales a 5).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PMEN-REC-1", "semantic_id": sid26, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona la traducción algebraica adecuada para el texto: 'El candidato debe tener, como mínimo, el doble de los votos de su rival ($R$)'. (Votos del candidato = $C$).", "choices": ["A) $C \\ge 2R$", "B) $C \\le 2R$", "C) $C > 2R$", "D) $C = 2R$"], "correct_answer": "A) $C \\ge 2R$", "solution_steps": "Como mínimo es un piso incluyente ($\\ge$). El piso es el doble de R ($2R$). Entonces $C \\ge 2R$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PMEN-PROC-{i}", "semantic_id": sid26, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La condición 'la velocidad en la autopista no debe ser menor de $80$ km/h' se traduce algebraicamente como $V < 80$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Si 'no debe ser menor', entonces puede ser igual a 80 o mayor a 80. La traducción de 'no menor de' es 'mayor o igual' ($V \\ge 80$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PMEN-PAES-{i}", "semantic_id": sid26, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Una ley municipal de recolección de agua lluvias exige que 'el volumen del estanque de reserva ($V$) sea al menos igual al producto del área del techo ($A$) por la precipitación histórica ($P$)'. ¿Cuál inecuación verifica que una casa cumple legalmente con la norma? (v{i})", "choices": ["A) $V \\ge A \\cdot P$", "B) $V \\le A \\cdot P$", "C) $V = A + P$", "D) $V > A + P$"], "correct_answer": "A) $V \\ge A \\cdot P$", "solution_steps": "La frase 'al menos' establece la frontera mínima ($\\ge$). El límite es el 'producto' de A y P ($A \\cdot P$). El tanque V debe ser mayor o igual a ese producto.", "paes_style": True})

# 27. SEMIDIFERENCIA_NUMEROS
sid27 = "MAT.ALG.LENGUAJE_RELACIONES.SEMIDIFERENCIA_NUMEROS"
RECURSOS.append({
    "semantic_id": sid27, "objetivo": "Traducir la división de una resta entre dos.",
    "introduccion": "El prefijo 'semi' en matemáticas y en español significa 'la mitad de'. Si entiendes lo que es una diferencia (resta), entonces la semidiferencia es simplemente cortarla por la mitad.",
    "resumen": "La **Semidiferencia** entre dos cantidades es la **mitad de su resta**. Se traduce algebraicamente estructurando la resta en el numerador y dividiendo todo entre dos: **$\\frac{a - b}{2}$**.",
    "explicacion": "Anatomía de la expresión:\n- Diferencia: $x - y$\n- Semi (mitad): Dividido por 2.\n- Semidiferencia: $\\frac{x - y}{2}$\n\nAl igual que en toda resta, el orden es ley. 'La semidiferencia entre $m$ y $n$' obliga a que $m$ sea el minuendo (positivo) y $n$ el sustraendo (negativo): $\\frac{m - n}{2}$.",
    "procedimiento": ["Paso 1: Identifica las dos entidades que se están comparando.", "Paso 2: Escribe la primera entidad menos la segunda (A - B).", "Paso 3: Envuelve toda esa resta en el numerador de una fracción, y coloca un 2 como denominador."],
    "ejemplos": [
        {"titulo": "Cortando la distancia", "enunciado": "Traduce algebraicamente: 'La semidiferencia entre el cuadrado de a y el cubo de b'.", "solucion_pasos": ["Entidad 1: cuadrado de a (a^2).", "Entidad 2: cubo de b (b^3).", "Diferencia: a^2 - b^3.", "Semi: Todo lo anterior dividido en 2. Traducción: (a^2 - b^3) / 2."]}
    ],
    "errores_frecuentes": ["Dividir solo el primer número por dos. Escribir $\\frac{x}{2} - y$ en lugar de $\\frac{x - y}{2}$.", "Confundirla con la semisuma."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SDIF-CONC-{i}", "semantic_id": sid27, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"A nivel estructural, ¿qué operaciones y en qué orden lógico combina el concepto de 'semidiferencia' de dos variables algebraicas? (v{i})", "choices": ["A) Primero se efectúa una resta entre las dos variables, y luego el resultado completo de esa resta se divide por dos.", "B) Primero se dividen ambas variables por dos, y luego se multiplican los resultados.", "C) Primero se suman las variables, y luego se restan por dos.", "D) Se resta el doble de la primera variable menos la segunda."], "correct_answer": "A) Primero se efectúa una resta entre las dos variables, y luego el resultado completo de esa resta se divide por dos.", "solution_steps": "El prefijo semi- afecta a la totalidad de la palabra que acompaña. Semidiferencia = (diferencia) / 2.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SDIF-REC-1", "semantic_id": sid27, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Selecciona la expresión que representa 'la semidiferencia entre el triple de $x$ y el doble de $y$'.", "choices": ["A) $\\frac{3x - 2y}{2}$", "B) $3x - \\frac{2y}{2}$", "C) $\\frac{3x}{2} - 2y$", "D) $\\frac{2y - 3x}{2}$"], "correct_answer": "A) $\\frac{3x - 2y}{2}$", "solution_steps": "La resta es entre $3x$ y $2y$. Toda la resta va sobre 2: $\\frac{3x - 2y}{2}$. Las opciones B y C dividen solo una parte.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SDIF-PROC-{i}", "semantic_id": sid27, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La semidiferencia entre $A$ y $B$ ($\\frac{A-B}{2}$) arroja siempre el mismo resultado algebraico que la semidiferencia entre $B$ y $A$ ($\\frac{B-A}{2}$)?", "choices": [], "correct_answer": "Falso", "solution_steps": "La resta no es conmutativa. Si intercambias minuendo y sustraendo, el resultado cambia de signo (ej. 5 y -5).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SDIF-PAES-{i}", "semantic_id": sid27, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un sistema de navegación calcula el 'margen de corrección' como la semidiferencia entre la coordenada objetivo ($O$) y la coordenada actual ($A$). ¿Qué expresión debe programarse en la computadora de a bordo? (v{i})", "choices": ["A) $Margen = \\frac{O - A}{2}$", "B) $Margen = \\frac{A - O}{2}$", "C) $Margen = O - \\frac{A}{2}$", "D) $Margen = \\frac{O + A}{2}$"], "correct_answer": "A) $Margen = \\frac{O - A}{2}$", "solution_steps": "El orden de mención fue Objetivo primero y Actual después. Por tanto, es (O - A). La palabra 'semi' obliga a dividir toda la resta por 2.", "paes_style": True})

# 28. SEMISUMA_NUMEROS
sid28 = "MAT.ALG.LENGUAJE_RELACIONES.SEMISUMA_NUMEROS"
RECURSOS.append({
    "semantic_id": sid28, "objetivo": "Traducir la división de una adición entre dos, conocida comúnmente como promedio o media aritmética de dos números.",
    "introduccion": "Si tú tienes 10 dulces y yo 4, y queremos ser justos, juntamos todos en una bolsa (14) y los dividimos a la mitad. Cada uno se lleva 7. Acabamos de hacer una semisuma.",
    "resumen": "La **Semisuma** entre dos cantidades es la **mitad de su suma**. Se traduce algebraicamente estructurando la adición en el numerador y dividiendo todo entre dos: **$\\frac{a + b}{2}$**.",
    "explicacion": "Anatomía de la expresión:\n- Suma: $x + y$\n- Semi (mitad): Dividido por 2.\n- Semisuma: $\\frac{x + y}{2}$\n\n*Conexión de Oro:* La semisuma de dos variables es exactamente el mismo concepto que el **promedio** (o media aritmética) de dos datos. Si un problema dice 'el promedio de dos números', escribe de inmediato su semisuma.",
    "procedimiento": ["Paso 1: Identifica las dos entidades que se están sumando.", "Paso 2: Escribe la primera entidad más la segunda (A + B).", "Paso 3: Envuelve toda esa suma en el numerador de una fracción, y coloca un 2 como denominador."],
    "ejemplos": [
        {"titulo": "El punto medio", "enunciado": "Traduce algebraicamente: 'El promedio entre la nota de control y la nota final'.", "solucion_pasos": ["Nota de control: C.", "Nota final: F.", "El promedio de dos valores es su semisuma.", "Traducción: (C + F) / 2."]}
    ],
    "errores_frecuentes": ["Dividir solo el último número por dos. Escribir $x + \\frac{y}{2}$ en lugar de $\\frac{x + y}{2}$.", "Dividir por otra constante que no sea 2 (el prefijo semi es estricto y significa dos)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SSUM-CONC-{i}", "semantic_id": sid28, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿A qué concepto estadístico fundamental equivale algebraicamente la operación de 'semisuma' aplicada sobre dos cantidades numéricas distintas? (v{i})", "choices": ["A) Al promedio o media aritmética simple de dichas dos cantidades.", "B) A la mediana estadística.", "C) A la desviación estándar.", "D) A la moda."], "correct_answer": "A) Al promedio o media aritmética simple de dichas dos cantidades.", "solution_steps": "Sumar dos números y dividir el resultado entre dos (semisuma) es la fórmula exacta para obtener su promedio.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SSUM-REC-1", "semantic_id": sid28, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Indica la expresión correcta para: 'La semisuma del triple de $a$ y el séxtuple de $b$'.", "choices": ["A) $\\frac{3a + 6b}{2}$", "B) $3a + \\frac{6b}{2}$", "C) $\\frac{3a}{2} + 6b$", "D) $\\frac{3a + 6b}{3}$"], "correct_answer": "A) $\\frac{3a + 6b}{2}$", "solution_steps": "Los términos sumados son $3a$ y $6b$. El prefijo 'semi' exige dividir todo el bloque aditivo entre 2.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SSUM-PROC-{i}", "semantic_id": sid28, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿A diferencia de la semidiferencia, la semisuma de $x$ e $y$ ($\\frac{x+y}{2}$) siempre es igual a la semisuma de $y$ y $x$ ($\\frac{y+x}{2}$) gracias a la propiedad conmutativa?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "La suma sí es conmutativa ($x+y = y+x$), por lo que el orden en el numerador de una semisuma no altera en lo absoluto el resultado matemático.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SSUM-PAES-{i}", "semantic_id": sid28, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"La normativa de evaluación de un instituto dice: 'La nota de presentación ($P$) de un alumno se calcula como la semisuma entre su nota teórica ($T$) y su nota práctica ($R$)'. Si un estudiante despeja su nota teórica en la ecuación, ¿qué expresión obtiene? (v{i})", "choices": ["A) $T = 2P - R$", "B) $T = P - 2R$", "C) $T = \\frac{P}{2} - R$", "D) $T = 2(P - R)$"], "correct_answer": "A) $T = 2P - R$", "solution_steps": "Ecuación original: $P = \\frac{T + R}{2}$. Al despejar T, el 2 pasa multiplicando: $2P = T + R$. Luego la R pasa restando: $2P - R = T$.", "paes_style": True})

# MAT.ALG.VALORIZACION

# 29. CONCEPTO_SUSTITUCION
sid29 = "MAT.ALG.VALORIZACION.CONCEPTO_SUSTITUCION"
RECURSOS.append({
    "semantic_id": sid29, "objetivo": "Entender la valorización como el proceso de sustitución de variables simbólicas por valores numéricos específicos.",
    "introduccion": "Hasta ahora, las letras eran fantasmas. Sabíamos que escondían un número, pero no cuál. Ha llegado el momento de arrancarles la máscara. En la valorización, por fin sabremos el valor real de la expresión.",
    "resumen": "La **Valorización o Sustitución** es el proceso de **reemplazar cada variable (letra) de una expresión algebraica por un número específico dado**, y luego resolver las operaciones aritméticas resultantes respetando la jerarquía.",
    "explicacion": "Imagina que tienes la expresión $3x + 5$. Esto es un 'molde' algebraico.\nSi te dicen 'Valora la expresión para $x = 2$', tu trabajo es quirúrgico:\n1. Borras la $x$.\n2. Pones un $(2)$ en su lugar.\n3. Calculas: $3(2) + 5 = 6 + 5 = 11$.\n\nEl valor numérico de esa expresión, cuando la variable vale 2, es 11. \nRegla de oro de la sustitución: **Cada vez que reemplaces una letra por un número, pon ese número entre paréntesis**. Esto te salvará la vida cuando haya signos negativos o exponentes.",
    "procedimiento": ["Paso 1: Copia la expresión algebraica original.", "Paso 2: Borra mentalmente la letra que vas a sustituir y deja un paréntesis vacío en su lugar (ej. si es 5x, deja 5( )).", "Paso 3: Introduce el valor numérico proporcionado dentro de ese paréntesis.", "Paso 4: Resuelve las operaciones aritméticas usando PAPOMUDAS (Paréntesis, Potencias, Multiplicación/División, Suma/Resta)."],
    "ejemplos": [
        {"titulo": "El molde en acción", "enunciado": "Valoriza la expresión 4y - 7, si sabemos que y = 5.", "solucion_pasos": ["Expresión: 4y - 7.", "Reemplazamos 'y' por '(5)': 4(5) - 7.", "Multiplicamos 4 por 5: 20 - 7.", "Restamos: 13. El valor numérico es 13."]}
    ],
    "errores_frecuentes": ["Olvidar que $4x$ es una multiplicación. Al reemplazar $x=5$, los estudiantes a veces escriben el número $45$ en lugar de multiplicar $4 \\cdot 5$.", "No respetar la jerarquía de operaciones después de sustituir (ej. sumar antes de multiplicar)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSUS-CONC-{i}", "semantic_id": sid29, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué transformación estructural ocurre en una expresión algebraica una vez que se realiza con éxito el proceso de 'valorización' para todas sus variables? (v{i})", "choices": ["A) La expresión algebraica deja de contener letras (incógnitas) y se transforma en una expresión puramente aritmética cuyo resultado final es un número real.", "B) La expresión se convierte en una ecuación con infinitas soluciones.", "C) Las variables cambian de minúsculas a mayúsculas.", "D) El grado del polinomio aumenta en una unidad."], "correct_answer": "A) La expresión algebraica deja de contener letras (incógnitas) y se transforma en una expresión puramente aritmética cuyo resultado final es un número real.", "solution_steps": "Al sustituir todas las variables por sus valores concretos, eliminamos el componente simbólico y pasamos a aritmética pura.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CSUS-REC-1", "semantic_id": sid29, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al valorizar la expresión $7x$ usando el valor $x = 3$, ¿cuál es el paso de sustitución correcto antes de calcular el resultado final?", "choices": ["A) $7(3)$ o $7 \\cdot 3$", "B) $73$", "C) $7 + 3$", "D) $7^3$"], "correct_answer": "A) $7(3)$ o $7 \\cdot 3$", "solution_steps": "La yuxtaposición $7x$ implica multiplicación. Al sustituir, se debe hacer explícita esa multiplicación usando paréntesis o el punto de multiplicar. Escribir 73 es un error grave de lectura.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSUS-PROC-{i}", "semantic_id": sid29, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El valor numérico de la expresión $10 - 2m$ evaluada para $m = 4$ es igual a $32$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Sustituimos $m$ por $4$: $10 - 2(4)$. Por jerarquía (PAPOMUDAS), primero se multiplica: $10 - 8$. Luego se resta: $2$. El valor real es $2$. Quien obtuvo $32$ restó primero ($10-2=8$) y multiplicó por $4$, rompiendo la jerarquía.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSUS-PAES-{i}", "semantic_id": sid29, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un sistema médico calcula la dosis de medicamento con el polinomio $D(p) = 5p + 10$, donde $p$ es el peso en kilos. Si ingresa un niño de $20$ kilos, ¿cuál es la dosis exacta que la máquina administrará tras valorizar la expresión? (v{i})", "choices": ["A) $110$", "B) $35$", "C) $100$", "D) $520$"], "correct_answer": "A) $110$", "solution_steps": "Se sustituye $p=20$ en la fórmula: $5(20) + 10$. Multiplicamos primero: $100 + 10$. Sumamos: $110$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 6 (B0302/Valorizacion)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 6...")
    append_jsonl("mat-alg-lenguaje-banco-gen-6", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-6.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
