# scratch/build_alg_b0302_t4.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 16. NUMERO_PAR
sid16 = "MAT.ALG.LENGUAJE_RELACIONES.NUMERO_PAR"
RECURSOS.append({
    "semantic_id": sid16, "objetivo": "Garantizar algebraicamente que una expresión siempre resulte en un número par.",
    "introduccion": "Si tú escoges el número 3, y te pido que lo vuelvas par sin sumar ni restar nada, ¿qué harías? Lo multiplicarías por 2. Esa es la esencia de la paridad en álgebra.",
    "resumen": "Un **Número Par** se traduce algebraicamente como **$2n$** (o $2x$, $2k$, etc.), donde $n$ pertenece a los números enteros.",
    "explicacion": "Cualquier número entero (ya sea par o impar), al ser multiplicado por 2, se convierte automáticamente en un número par. \n- Si $n=5$ (impar), $2n = 10$ (par).\n- Si $n=8$ (par), $2n = 16$ (par).\nPor esto, $2n$ es el 'candado' perfecto para forzar la paridad en cualquier demostración o problema.",
    "procedimiento": ["Paso 1: Asigna una variable cualquiera para representar un número entero (ej. n).", "Paso 2: Multiplica esa variable por 2.", "Paso 3: Usa la expresión 2n cada vez que el problema se refiera a 'un número par cualquiera'."],
    "ejemplos": [
        {"titulo": "Forzando la paridad", "enunciado": "Traduce algebraicamente: 'El cuádruple de un número par cualquiera'.", "solucion_pasos": ["Un número par cualquiera se escribe como 2n.", "El cuádruple significa multiplicar por 4.", "Traducción final: 4(2n), que puede reducirse a 8n."]}
    ],
    "errores_frecuentes": ["Traducir 'un número par' usando la letra $p$ a secas. La $p$ podría tomar el valor 3. Solo $2p$ garantiza que sea par.", "Creer que $x/2$ genera un número par. (La división por dos genera mitades, no fuerza paridad)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NPAR-CONC-{i}", "semantic_id": sid16, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Por qué la expresión algebraica $2x$, donde $x$ es un entero, es el estándar universal para representar 'un número par'? (v{i})", "choices": ["A) Porque por definición aritmética, cualquier número entero multiplicado por $2$ resulta obligatoriamente en un múltiplo de $2$, es decir, un número par.", "B) Porque el número $2$ es el único número par que existe.", "C) Porque la letra $x$ siempre asume el valor de $2$ en las ecuaciones lineales.", "D) Porque sumar $2$ a cualquier número lo vuelve par."], "correct_answer": "A) Porque por definición aritmética, cualquier número entero multiplicado por $2$ resulta obligatoriamente en un múltiplo de $2$, es decir, un número par.", "solution_steps": "El factor 2 actúa como un filtro que fuerza a que el resultado siempre sea divisible por 2 (definición de número par).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"NPAR-REC-1", "semantic_id": sid16, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Identifica la traducción correcta para el enunciado: 'La suma de un número par y el número 5'.", "choices": ["A) $2n + 5$", "B) $n + 5$", "C) $2 + n + 5$", "D) $5n + 2$"], "correct_answer": "A) $2n + 5$", "solution_steps": "El 'número par' se modela como $2n$. A eso se le suma 5. Resultado: $2n + 5$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NPAR-PROC-{i}", "semantic_id": sid16, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si un problema te pide modelar 'el producto de dos números pares distintos', la traducción correcta y rigurosa sería $(2x)(2x)$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Al ser distintos, debes usar variables bases diferentes. La traducción correcta es $(2x)(2y)$ o $(2n)(2m)$. Escribir $(2x)(2x)$ modelaría 'un número par multiplicado por sí mismo' (el cuadrado de un número par).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NPAR-PAES-{i}", "semantic_id": sid16, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"En un algoritmo de encriptación, se necesita que el código final ($C$) sea obligatoriamente par, independientemente del número entero ($N$) que ingrese el usuario. Un programador propone tres opciones: $C_1 = N + 2$, $C_2 = N^2$, y $C_3 = 2N$. ¿Cuál de ellas garantiza siempre el cumplimiento de la condición? (v{i})", "choices": ["A) Solo $C_3 = 2N$", "B) Solo $C_1 = N + 2$", "C) Solo $C_2 = N^2$", "D) Todas garantizan la condición."], "correct_answer": "A) Solo $C_3 = 2N$", "solution_steps": "Si $N=3$, $C_1 = 5$ (impar), $C_2 = 9$ (impar). Solo $C_3 = 2(3) = 6$ garantiza la paridad mediante el factor multiplicativo 2.", "paes_style": True})

# 17. NUMERO_IMPAR
sid17 = "MAT.ALG.LENGUAJE_RELACIONES.NUMERO_IMPAR"
RECURSOS.append({
    "semantic_id": sid17, "objetivo": "Garantizar algebraicamente que una expresión siempre resulte en un número impar.",
    "introduccion": "Ya sabemos cómo hacer que cualquier número sea par (multiplicando por 2). ¿Y cómo lo hacemos impar? Fácil: rompiendo la paridad empujándolo un paso hacia adelante o hacia atrás.",
    "resumen": "Un **Número Impar** se traduce algebraicamente como **$2n + 1$** (o $2n - 1$), donde $n$ pertenece a los enteros.",
    "explicacion": "Dado que $2n$ asegura un número par, sumar 1 ($2n + 1$) o restar 1 ($2n - 1$) nos mueve exactamente al número consecutivo en la recta numérica. Y como sabemos, al lado de cualquier número par siempre habita un impar.\n- Si $n=4$, $2(4) + 1 = 9$ (impar).\n- Si $n=5$, $2(5) + 1 = 11$ (impar).\n\nEn matemáticas formales, $2n+1$ es el estándar predilecto, aunque $2n-1$ es matemáticamente igual de válido.",
    "procedimiento": ["Paso 1: Construye el 'escudo par' multiplicando una variable por 2 (2n).", "Paso 2: Suma o resta 1 al bloque anterior.", "Paso 3: Protege la expresión (2n+1) entre paréntesis si la vas a multiplicar o elevar a potencias."],
    "ejemplos": [
        {"titulo": "El impar al cuadrado", "enunciado": "Traduce algebraicamente: 'El cuadrado de un número impar'.", "solucion_pasos": ["Construimos el número impar: (2n + 1).", "Elevamos todo el bloque al cuadrado.", "Traducción final: (2n + 1)^2."]}
    ],
    "errores_frecuentes": ["Usar simplemente $x$ o $y$ para denotar un impar. (La variable libre puede tomar cualquier valor).", "Usar $x+1$ para forzar un impar. (Si $x$ era 3, $x+1$ es 4, que es par. $x+1$ solo da el sucesor, no la imparidad absoluta)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NIMP-CONC-{i}", "semantic_id": sid17, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el mecanismo lógico-matemático detrás de la expresión $2x + 1$ para forzar la imparidad de un número? (v{i})", "choices": ["A) El término $2x$ asegura generar un número par y, dado que en la recta entera los números pares e impares se alternan, sumarle $1$ garantiza caer siempre en el número impar sucesor.", "B) El número $1$ es impar, y al sumarlo a cualquier otro número lo vuelve impar por contigüidad.", "C) El factor $2$ multiplica a la variable, y luego la suma de $1$ cancela el efecto del $2$.", "D) Es una simple convención sin sustento aritmético real."], "correct_answer": "A) El término $2x$ asegura generar un número par y, dado que en la recta entera los números pares e impares se alternan, sumarle $1$ garantiza caer siempre en el número impar sucesor.", "solution_steps": "Al anclar primero en un número seguro par ($2x$), avanzar un paso (+1) te arroja infaliblemente a un terreno impar.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"NIMP-REC-1", "semantic_id": sid17, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de estas expresiones también es una representación matemática infalible para 'un número impar cualquiera'.", "choices": ["A) $2k - 1$", "B) $k - 1$", "C) $3k + 1$", "D) $x + 2$"], "correct_answer": "A) $2k - 1$", "solution_steps": "Al igual que sumar 1 ($2k+1$) te lleva al sucesor impar, restar 1 ($2k-1$) te lleva al antecesor impar. Ambas son válidas.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NIMP-PROC-{i}", "semantic_id": sid17, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $x + 3$ es correcta para garantizar 'un número impar', argumentando que el número $3$ es impar?", "choices": [], "correct_answer": "Falso", "solution_steps": "Si $x$ es 1 (impar), $1+3=4$ (par). La paridad depende de la base completa. Solo $2n+1$ o $2n-1$ garantizan la imparidad absoluta independientemente del valor de la variable.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NIMP-PAES-{i}", "semantic_id": sid17, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un arquitecto quiere diseñar un estadio donde el número de asientos en cada fila sea siempre impar para garantizar un pasillo central simétrico. Si la fórmula depende de un parámetro de crecimiento $k$, ¿cuál de las siguientes fórmulas para el número de asientos por fila le servirá? (v{i})", "choices": ["A) Asientos $= 2k + 1$", "B) Asientos $= 3k$", "C) Asientos $= k^2 + 1$", "D) Asientos $= k / 2 + 1$"], "correct_answer": "A) Asientos $= 2k + 1$", "solution_steps": "La única estructura polinómica que garantiza generar valores impares para cualquier entero k es $2k+1$. Por ejemplo, en B ($3k$), si k=2, los asientos serían 6 (par).", "paes_style": True})

# 18. PARES_CONSECUTIVOS
sid18 = "MAT.ALG.LENGUAJE_RELACIONES.PARES_CONSECUTIVOS"
RECURSOS.append({
    "semantic_id": sid18, "objetivo": "Modelar una serie de números pares que se suceden entre sí.",
    "introduccion": "Si estamos contando de dos en dos (2, 4, 6, 8...), ya no nos sirve sumar de a 1. El salto entre números de la misma familia de paridad es mayor.",
    "resumen": "Los **Números Pares Consecutivos** se distancian siempre en **2 unidades**. Para modelarlos, anclamos el primer número como par ($2n$) y le sumamos $2, 4, 6...$ obteniendo: **$2n$, $2n+2$, $2n+4$**.",
    "explicacion": "Construcción lógica:\n1. El primer número debe ser garantizado par: $2n$.\n2. ¿Cuál es el siguiente número par? Si le sumo 1 ($2n+1$) caigo en un impar. Debo sumarle 2.\n3. El segundo par consecutivo es: $2n+2$.\n4. El tercer par consecutivo es: $2n+4$.\n\nSi el problema es más permisivo y no exige que las letras representen 'cualquier entero', a veces verás que usan $x, x+2, x+4$ asumiendo tácitamente que 'x' ya es par de antemano.",
    "procedimiento": ["Paso 1: Establece el primer número como 2n (el primer par).", "Paso 2: Suma 2 para hallar el segundo (2n + 2).", "Paso 3: Suma 4 para hallar el tercero (2n + 4), y así sucesivamente.", "Paso 4: Relaciona estos bloques según lo pida el enunciado (suma, resta, producto)."],
    "ejemplos": [
        {"titulo": "Sumando saltos pares", "enunciado": "Traduce algebraicamente: 'La suma de tres pares consecutivos'.", "solucion_pasos": ["Primer par: 2n.", "Segundo par: 2n + 2.", "Tercer par: 2n + 4.", "Suma total: 2n + (2n + 2) + (2n + 4).", "Reducido: 6n + 6."]}
    ],
    "errores_frecuentes": ["Traducirlos como $2n, 2n+1, 2n+2$. (Aquí estás alternando par-impar-par).", "Confundirlos con enteros consecutivos ($x, x+1, x+2$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCON-CONC-{i}", "semantic_id": sid18, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el intervalo matemático o 'salto' necesario para avanzar desde un número par cualquiera hacia su par consecutivo inmediato en la recta numérica? (v{i})", "choices": ["A) Un salto de $2$ unidades.", "B) Un salto de $1$ unidad.", "C) Un salto de $4$ unidades.", "D) Multiplicar el número por $2$."], "correct_answer": "A) Un salto de $2$ unidades.", "solution_steps": "Entre un par y el siguiente (ej. entre 6 y 8) hay una distancia exacta de 2 unidades, por eso se modela como $2n$, luego $2n+2$, etc.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PCON-REC-1", "semantic_id": sid18, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Indica cuál de las siguientes series representa algebraicamente a cuatro números pares consecutivos.", "choices": ["A) $2x, 2x+2, 2x+4, 2x+6$", "B) $2x, 2x+1, 2x+2, 2x+3$", "C) $x, 2x, 4x, 8x$", "D) $2x, 4x, 6x, 8x$"], "correct_answer": "A) $2x, 2x+2, 2x+4, 2x+6$", "solution_steps": "Partiendo de la base par segura ($2x$), se suma progresivamente de a dos unidades: $+2, +4, +6$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCON-PROC-{i}", "semantic_id": sid18, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si un estudiante decide modelar tres pares consecutivos usando la forma centrada $(2k - 2), 2k, (2k + 2)$, está cometiendo un error matemático?", "choices": [], "correct_answer": "Falso", "solution_steps": "No hay error. De hecho, es una técnica avanzada y muy útil. Todas las distancias entre ellos son de 2 unidades, garantizando que sean pares consecutivos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCON-PAES-{i}", "semantic_id": sid18, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un problema geométrico indica: 'Las longitudes de los tres lados de un triángulo son números pares consecutivos. Si su perímetro es $60$ cm, halla la ecuación correspondiente'. Si el lado más pequeño es $2x$, ¿cuál es la ecuación para resolver el perímetro? (v{i})", "choices": ["A) $2x + (2x + 2) + (2x + 4) = 60$", "B) $2x + 2(x + 1) + 2(x + 2) = 60$", "C) $2x + (2x + 1) + (2x + 2) = 60$", "D) $x + (x + 2) + (x + 4) = 60$"], "correct_answer": "A) $2x + (2x + 2) + (2x + 4) = 60$", "solution_steps": "Los tres pares consecutivos, partiendo del menor $2x$, son $2x, 2x+2, 2x+4$. Al sumarlos para igualarlos al perímetro 60, obtenemos la opción A. (La opción B matemáticamente equivale a la A, pero está factorizada innecesariamente; la A es la traducción directa más pulcra).", "paes_style": True})

# 19. IMPARES_CONSECUTIVOS
sid19 = "MAT.ALG.LENGUAJE_RELACIONES.IMPARES_CONSECUTIVOS"
RECURSOS.append({
    "semantic_id": sid19, "objetivo": "Modelar una serie de números impares que se suceden entre sí.",
    "introduccion": "¿A qué distancia está el 5 del 7? A dos unidades. Curiosamente, la distancia entre impares es exactamente la misma que la distancia entre pares.",
    "resumen": "Los **Números Impares Consecutivos** también se distancian en **2 unidades**. Se modelan anclando el primer número como impar ($2n+1$) y sumando $2, 4, 6...$ obteniendo: **$2n+1$, $2n+3$, $2n+5$**.",
    "explicacion": "Análisis del salto:\n1. Base impar garantizada: $2n+1$.\n2. Si a un impar le sumo 1, me vuelvo par. ¡Prohibido!\n3. Si le sumo 2, vuelvo a caer en la casilla impar: $(2n+1) + 2 = 2n+3$.\n4. El siguiente será $(2n+3) + 2 = 2n+5$.\n\n¡Cuidado con la trampa psicológica! Muchos estudiantes creen que como son 'impares', deben sumar números impares ($+1, +3, +5$). Eso es un error letal. Para mantener la imparidad, debes dar saltos pares ($+2, +4$). Impar + Par = Impar.",
    "procedimiento": ["Paso 1: Establece el primer número usando la estructura impar (2n + 1 o 2n - 1).", "Paso 2: Suma 2 para hallar el segundo (2n + 3).", "Paso 3: Suma 2 de nuevo para hallar el tercero (2n + 5)."],
    "ejemplos": [
        {"titulo": "El salto impar", "enunciado": "Traduce algebraicamente: 'El producto de dos impares consecutivos'.", "solucion_pasos": ["Primer impar: (2n + 1).", "Segundo impar (saltando 2 unidades): (2n + 3).", "Producto: (2n + 1) * (2n + 3)."]}
    ],
    "errores_frecuentes": ["Traducirlos como $2n+1, 2n+2, 2n+3$. (El $2n+2$ es par, se rompió la racha).", "Sumar impares a la base ($+1, +3, +5$) pensando erróneamente que eso mantiene la serie impar."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ICON-CONC-{i}", "semantic_id": sid19, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Por qué para construir una secuencia algebraica de números impares consecutivos ($2x+1, 2x+3...$) se debe sumar $2$ en cada paso, a pesar de estar tratando con números 'impares'? (v{i})", "choices": ["A) Porque la distancia (o diferencia) real en la recta numérica entre cualquier número impar y el siguiente (ej. de $7$ a $9$) es siempre de $2$ unidades (un número par). Sumar una cantidad impar cambiaría la paridad.", "B) Porque la regla establece que los números pares se suman con pares y los impares con impares.", "C) Porque sumar $2$ siempre genera números pares, cancelando el $1$ original.", "D) Es solo una coincidencia algebraica sin explicación en la recta numérica."], "correct_answer": "A) Porque la distancia (o diferencia) real en la recta numérica entre cualquier número impar y el siguiente (ej. de $7$ a $9$) es siempre de $2$ unidades (un número par). Sumar una cantidad impar cambiaría la paridad.", "solution_steps": "La paridad se conserva sumando números pares. Impar + Par = Impar. Si sumas un impar, te cambias de bando (Impar + Impar = Par).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ICON-REC-1", "semantic_id": sid19, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Si el número menor de una serie de tres impares consecutivos es $2k - 1$, ¿cómo se representan los dos siguientes?", "choices": ["A) $2k + 1$ y $2k + 3$", "B) $2k$ y $2k + 1$", "C) $2k - 2$ y $2k - 3$", "D) $2k - 1$ y $2k + 2$"], "correct_answer": "A) $2k + 1$ y $2k + 3$", "solution_steps": "Primer impar: $2k - 1$. Le sumamos 2 al primero: $(2k-1)+2 = 2k+1$. Le sumamos 2 al segundo: $(2k+1)+2 = 2k+3$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ICON-PROC-{i}", "semantic_id": sid19, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La secuencia $2x+1, 2x+2, 2x+3$ es el modelo correcto para representar algebraicamente a tres números impares consecutivos?", "choices": [], "correct_answer": "Falso", "solution_steps": "El término central $2x+2$ es un número par (factorizable por 2). La secuencia intercala impar, par, impar. La correcta debe saltar de a dos: $2x+1, 2x+3, 2x+5$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ICON-PAES-{i}", "semantic_id": sid19, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"En un edificio, se sabe que los números de tres departamentos contiguos en el mismo pasillo son números impares consecutivos y su suma es $105$. Si representamos el número del departamento del medio como $x$ (sabiendo que es impar), ¿cuál es la ecuación más eficiente para resolver este problema? (v{i})", "choices": ["A) $(x - 2) + x + (x + 2) = 105$", "B) $(x - 1) + x + (x + 1) = 105$", "C) $2x+1 + 2x+3 + 2x+5 = 105$", "D) $x + (x+2) + (x+4) = 105$"], "correct_answer": "A) $(x - 2) + x + (x + 2) = 105$", "solution_steps": "Si $x$ es el impar del medio, el impar anterior está 2 unidades atrás ($x-2$) y el siguiente 2 unidades adelante ($x+2$). La opción C asume que la variable a despejar es el parámetro generador (n), no el número de departamento. La opción A usa el modelo centrado directo en la incógnita.", "paes_style": True})

# 20. CUADRADO_NUMERO
sid20 = "MAT.ALG.LENGUAJE_RELACIONES.CUADRADO_NUMERO"
RECURSOS.append({
    "semantic_id": sid20, "objetivo": "Traducir correctamente la operación de elevar al cuadrado en contraposición a multiplicar por dos.",
    "introduccion": "En el álgebra, crecer multiplicando no es lo mismo que crecer exponencialmente. La diferencia entre el doble y el cuadrado es la diferencia entre un edificio y una bomba atómica.",
    "resumen": "El **Cuadrado de un Número** se traduce elevando la variable a la potencia de dos ($x^2$). Representa el área de un cuadrado de lado $x$, o el producto del número por sí mismo ($x \\cdot x$).",
    "explicacion": "Palabras clave:\n- El cuadrado de\n- Elevado a dos\n- Multiplicado por sí mismo\n\nComparación crítica:\n- 'El doble de un número' $\\rightarrow$ $2x$ (crecimiento lineal).\n- 'El cuadrado de un número' $\\rightarrow$ $x^2$ (crecimiento cuadrático).\n\nEl uso del paréntesis es dictatorial cuando hay más términos. \n- 'El cuadrado de la suma de dos números' $\\rightarrow$ Primero sumo, luego elevo: $(x + y)^2$.\n- 'La suma de los cuadrados de dos números' $\\rightarrow$ Primero elevo, luego sumo: $x^2 + y^2$.",
    "procedimiento": ["Paso 1: Identifica a qué entidad le aplicarás el cuadrado (a una letra sola, o a un grupo de operaciones).", "Paso 2: Si es a una letra sola, colócale el exponente 2 arriba a la derecha (x^2).", "Paso 3: Si es a un grupo u operación (una suma, un producto), envuelve el grupo en paréntesis y coloca el exponente 2 fuera de ellos."],
    "ejemplos": [
        {"titulo": "El orden del cuadrado", "enunciado": "Traduce algebraicamente: 'El cuadrado de la diferencia entre a y b'.", "solucion_pasos": ["Primero analizamos qué es lo que se va a elevar: 'la diferencia entre a y b'.", "Escribimos esa diferencia: a - b.", "Ahora aplicamos el cuadrado A TODO ESO, usando paréntesis: (a - b)^2."]}
    ],
    "errores_frecuentes": ["Confundir el cuadrado ($x^2$) con el doble ($2x$).", "Omitir los paréntesis, traduciendo 'el cuadrado de la suma' como $x + y^2$ (donde solo la y quedó elevada al cuadrado)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CUAD-CONC-{i}", "semantic_id": sid20, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el contexto de modelamiento matemático, ¿cuál es la diferencia operatoria entre 'el doble de una variable' y 'el cuadrado de una variable'? (v{i})", "choices": ["A) El 'doble' implica multiplicar la variable por $2$ ($2x$), mientras que el 'cuadrado' implica multiplicar la variable por sí misma ($x^2$).", "B) Ambas operaciones son equivalentes algebraicamente.", "C) El cuadrado implica sumar la variable $4$ veces ($x+x+x+x$).", "D) El 'doble' implica usar exponentes y el 'cuadrado' usar coeficientes."], "correct_answer": "A) El 'doble' implica multiplicar la variable por $2$ ($2x$), mientras que el 'cuadrado' implica multiplicar la variable por sí misma ($x^2$).", "solution_steps": "Doble = factor lineal (coeficiente 2). Cuadrado = factor exponencial (exponente 2).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CUAD-REC-1", "semantic_id": sid20, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Selecciona la traducción algebraica precisa para la oración: 'La suma de los cuadrados de dos números distintos'.", "choices": ["A) $x^2 + y^2$", "B) $(x + y)^2$", "C) $x + y^2$", "D) $2x + 2y$"], "correct_answer": "A) $x^2 + y^2$", "solution_steps": "El texto dice 'la suma de (varias cosas)'. ¿Qué cosas? 'los cuadrados' de dos números. Por ende, elevas x al cuadrado, elevas y al cuadrado, y luego los sumas: $x^2 + y^2$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CUAD-PROC-{i}", "semantic_id": sid20, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "alta", "competencia": "M1", "prompt": "¿La expresión matemática $(m - n)^2$ es la traducción correcta para el enunciado 'la diferencia de los cuadrados de $m$ y $n$'?", "choices": [], "correct_answer": "Falso", "solution_steps": "La expresión $(m-n)^2$ traduce 'el cuadrado de la diferencia'. La 'diferencia de los cuadrados' es $m^2 - n^2$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CUAD-PAES-{i}", "semantic_id": sid20, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un teorema en física afirma que 'la energía cinética de una partícula es proporcional a la mitad del producto entre su masa ($m$) y el cuadrado de su velocidad ($v$)'. ¿Cómo se traduce fielmente esta afirmación al lenguaje algebraico para estructurar la ecuación de energía ($E$)? (v{i})", "choices": ["A) $E = \\frac{1}{2} m v^2$", "B) $E = \\frac{1}{2} (mv)^2$", "C) $E = m \\cdot \\left(\\frac{v}{2}\\right)^2$", "D) $E = \\frac{1}{2} m \\cdot 2v$"], "correct_answer": "A) $E = \\frac{1}{2} m v^2$", "solution_steps": "Analizamos: 'la mitad' (fracción 1/2) del 'producto entre' (multiplicación de) su masa (m) y el 'cuadrado de la velocidad' ($v^2$). El cuadrado solo afecta a la velocidad. Resultado: $E = \\frac{1}{2} m v^2$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 4 (MAT.ALG.B0302)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 4 (MAT.ALG.B0302)...")
    append_jsonl("mat-alg-lenguaje-banco-gen-4", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-4.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
