# scratch/build_alg_b0301_t5.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 6. GRADO_ABSOLUTO_POLINOMIO
sid16 = "MAT.ALG.POLINOMIOS.GRADO_ABSOLUTO_POLINOMIO"
RECURSOS.append({
    "semantic_id": sid16, "objetivo": "Calcular el grado absoluto de un polinomio comparando los grados de sus términos.",
    "introduccion": "Si el grado absoluto de un término es su peso individual, el Grado Absoluto de un Polinomio no es la suma de todos los pesos, sino el peso del vagón más pesado de todo el tren.",
    "resumen": "El **Grado Absoluto de un Polinomio** es el **grado absoluto del término de mayor grado** que contiene dicho polinomio.",
    "explicacion": "No se suman los grados de todos los términos juntos. Se evalúa cada término por separado, como en un concurso, y el que tenga el mayor grado absoluto le hereda su grado a todo el polinomio.\n\nEjemplo: $x^4 - 5x^3y^2 + 8x^2$\n1. Evaluamos el primer vagón ($x^4$): Su grado absoluto es $4$.\n2. Evaluamos el segundo vagón ($-5x^3y^2$): Su grado absoluto es $3+2 = 5$.\n3. Evaluamos el tercer vagón ($8x^2$): Su grado absoluto es $2$.\n\nEl vagón ganador es el segundo (grado 5). Por lo tanto, decimos que todo el polinomio es de quinto grado absoluto.",
    "procedimiento": ["Paso 1: Calcula mentalmente el grado absoluto de cada término por separado (sumando los exponentes de sus letras).", "Paso 2: Compara los resultados obtenidos.", "Paso 3: El número mayor encontrado es el grado absoluto de todo el polinomio."],
    "ejemplos": [
        {"titulo": "Buscando al campeón", "enunciado": "Halla el grado absoluto del polinomio a^4b - a^3b^3 + ab^5.", "solucion_pasos": ["Término 1: a^4b. Grado = 4 + 1 = 5.", "Término 2: -a^3b^3. Grado = 3 + 3 = 6.", "Término 3: ab^5. Grado = 1 + 5 = 6.", "El mayor grado encontrado es 6. El polinomio es de sexto grado."]}
    ],
    "errores_frecuentes": ["Sumar los grados de todos los términos juntos (en el ejemplo anterior, decir que el grado es $5+6+6=17$).", "Mirar solamente el exponente más alto escrito, sin sumar las letras dentro de cada término compuesto."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPABS-CONC-{i}", "semantic_id": sid16, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Para determinar el 'Grado Absoluto' de un polinomio compuesto por múltiples términos, ¿cuál es el procedimiento matemático correcto? (v{i})", "choices": ["A) Se calcula el grado absoluto de cada término individualmente y se selecciona el mayor de todos como el grado del polinomio.", "B) Se calcula el grado absoluto de cada término y luego se suman todos esos resultados parciales.", "C) Se toma exclusivamente el grado del primer término que aparece escrito.", "D) Se restan los grados del término mayor y el término menor."], "correct_answer": "A) Se calcula el grado absoluto de cada término individualmente y se selecciona el mayor de todos como el grado del polinomio.", "solution_steps": "El grado del polinomio es heredado por su término de mayor grado absoluto, como un representante.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"GPABS-REC-1", "semantic_id": sid16, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Calcula de forma exacta el grado absoluto del siguiente polinomio: $4x^5 - x^3y^4 + 9xy^5$.", "choices": ["A) $7$", "B) $5$", "C) $6$", "D) $18$"], "correct_answer": "A) $7$", "solution_steps": "Calculamos por término: T1(5), T2(3+4=7), T3(1+5=6). El mayor es 7.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPABS-PROC-{i}", "semantic_id": sid16, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El polinomio $x^4 + y^4 + z^4$ posee un grado absoluto de $12$, producto de la suma de todos los exponentes de la expresión?", "choices": [], "correct_answer": "Falso", "solution_steps": "No se suman los exponentes de términos diferentes. Los términos individuales tienen grado 4. Por lo tanto, el grado del polinomio es 4.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPABS-PAES-{i}", "semantic_id": sid16, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un modelo de costos de manufactura obedece a la función $C(x,y) = x^3 + 5x^2y^2 - y^3$. Un ingeniero novato clasifica el modelo como 'de tercer grado' porque ve que el exponente máximo escrito sobre una letra es un $3$. ¿Cuál es el error en su clasificación? (v{i})", "choices": ["A) No sumó los exponentes de las variables mixtas dentro de los términos compuestos; el término central tiene grado cuatro ($2+2$), por lo que el polinomio es de cuarto grado.", "B) Olvidó sumar todos los exponentes de la expresión para obtener el grado total, que sería ocho.", "C) Se equivocó al tomar los negativos; el grado real es dos.", "D) El modelo no es clasificable porque tiene dos letras distintas."], "correct_answer": "A) No sumó los exponentes de las variables mixtas dentro de los términos compuestos; el término central tiene grado cuatro ($2+2$), por lo que el polinomio es de cuarto grado.", "solution_steps": "En $5x^2y^2$, el grado del término es $2+2=4$. Como 4 es mayor que 3 (grado de los otros términos), el polinomio es de 4to grado absoluto.", "paes_style": True})


# 7. GRADO_RELATIVO_POLINOMIO
sid17 = "MAT.ALG.POLINOMIOS.GRADO_RELATIVO_POLINOMIO"
RECURSOS.append({
    "semantic_id": sid17, "objetivo": "Calcular el grado relativo de un polinomio respecto a una variable particular.",
    "introduccion": "Así como podíamos buscar a la letra ganadora dentro de un solo término, podemos buscar a la letra con mayor exponente a lo largo de toda una expresión completa.",
    "resumen": "El **Grado Relativo de un Polinomio respecto a una letra** es el **mayor exponente con el que aparece dicha letra** en todo el polinomio.",
    "explicacion": "Es un concurso por especialidad. \nDado el polinomio: $x^6 - x^4y^2 + x^2y^5$\n\n- Grado relativo respecto a la $x$: Buscamos a todas las $x$ del tren. Encontramos $x^6$, $x^4$ y $x^2$. La ganadora es la del 6. El grado relativo a $x$ es 6.\n- Grado relativo respecto a la $y$: Buscamos a las $y$. Encontramos $y^2$ y $y^5$. La ganadora es la del 5. El grado relativo a $y$ es 5.\n\nEs útil para escribir polinomios de forma ordenada (ej: ordenando descendentemente respecto a la letra x).",
    "procedimiento": ["Paso 1: Identifica respecto a qué letra te están preguntando.", "Paso 2: Recorre todo el polinomio buscando esa letra en cada término.", "Paso 3: Compara sus exponentes.", "Paso 4: El exponente más alto que encuentres es el grado relativo de esa letra."],
    "ejemplos": [
        {"titulo": "Campeonato de exponentes", "enunciado": "Determina el grado relativo de 'a' y de 'b' en el polinomio a^3 + a^2b^4 - ab^5.", "solucion_pasos": ["Para 'a': Los exponentes son 3, 2 y 1. El mayor es 3. Grado relativo a 'a' = 3.", "Para 'b': Los exponentes son 4 y 5 (en el primer término la 'b' no está, es 0). El mayor es 5. Grado relativo a 'b' = 5."]}
    ],
    "errores_frecuentes": ["Sumar todos los exponentes que tiene esa letra en el polinomio, en lugar de elegir el mayor.", "Elegir la letra del término que tiene el mayor grado absoluto global, incluso si esa letra específica no tiene su exponente máximo allí."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPREL-CONC-{i}", "semantic_id": sid17, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al analizar el 'Grado Relativo' de un polinomio con respecto a la variable '$z$', ¿qué valor específico se debe entregar como respuesta matemática? (v{i})", "choices": ["A) El exponente más grande que posea la variable '$z$' en cualquiera de los términos de la expresión.", "B) La suma total de todos los exponentes que posea la variable '$z$' a lo largo del polinomio.", "C) El número total de veces que la variable '$z$' aparece repetida en la expresión.", "D) El grado absoluto del término que contenga a la variable '$z$'."], "correct_answer": "A) El exponente más grande que posea la variable '$z$' en cualquiera de los términos de la expresión.", "solution_steps": "Se hace una búsqueda de la variable z y se selecciona su exponente máximo encontrado en el polinomio.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"GPREL-REC-1", "semantic_id": sid17, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Dado el polinomio multicomponente $4x^3y^2 - 7x^2y^6 + 9x^5y$, ¿cuál es su grado relativo con respecto a la variable '$y$'?", "choices": ["A) $6$", "B) $2$", "C) $9$", "D) $5$"], "correct_answer": "A) $6$", "solution_steps": "Analizamos los exponentes de y en la expresión: 2, 6, 1. El mayor es 6.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPREL-PROC-{i}", "semantic_id": sid17, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El grado relativo respecto a '$x$' en el polinomio $x + x^2 + x^3$ es igual a $6$ por la suma de sus potencias?", "choices": [], "correct_answer": "Falso", "solution_steps": "No se suman. Se selecciona el exponente máximo, que en este caso es 3. El grado relativo a x es 3.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GPREL-PAES-{i}", "semantic_id": sid17, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un algoritmo de ordenamiento polinomial requiere que el usuario ingrese el grado relativo dominante de la variable base. Para el polinomio $-3a^5b^2 + 8a^2b^8 - a^7b$, si el algoritmo solicita el grado relativo respecto a '$a$', el usuario debe ingresar: (v{i})", "choices": ["A) $7$, ya que es el mayor exponente que acompaña exclusivamente a la variable '$a$'.", "B) $14$, sumando todos los exponentes de '$a$'.", "C) $8$, porque es el mayor exponente presente en toda la expresión, aunque pertenezca a '$b$'.", "D) $5$, por ser el exponente de '$a$' en el primer término."], "correct_answer": "A) $7$, ya que es el mayor exponente que acompaña exclusivamente a la variable '$a$'.", "solution_steps": "Buscamos 'a'. Sus exponentes son 5, 2 y 7. El mayor es 7.", "paes_style": True})

# 8. TERMINO_INDEPENDIENTE
sid18 = "MAT.ALG.POLINOMIOS.TERMINO_INDEPENDIENTE"
RECURSOS.append({
    "semantic_id": sid18, "objetivo": "Identificar el término independiente en un polinomio y comprender su naturaleza.",
    "introduccion": "En una fiesta llena de letras mutantes, siempre hay un invitado que se niega a usar disfraz: el número puro. Ese es el término independiente.",
    "resumen": "El **Término Independiente** de un polinomio es aquel término que **no tiene ninguna variable (letra)** visible. Es decir, consta únicamente de un número (constante).",
    "explicacion": "Su nombre se debe a que su valor *no depende* de las letras.\nEn $P(x) = 2x^2 + 5x - 7$:\n- $2x^2$ y $5x$ cambiarán de valor dependiendo del número que metamos en $x$.\n- El $-7$ siempre valdrá $-7$. Es independiente del valor de $x$.\n\nMatemáticamente, el término independiente tiene a la variable elevada a la potencia cero ($x^0 = 1$). Por eso decimos que es el término de 'grado cero'.\n\nSi un polinomio no tiene ningún número suelto (ej. $x^3 + 5x$), su término independiente es igual a $0$.",
    "procedimiento": ["Paso 1: Recorre el polinomio buscando un término que no esté acompañado de ninguna letra.", "Paso 2: Si lo encuentras, recuerda incluir el signo que lo antecede. Ese es el término independiente.", "Paso 3: Si todos los términos tienen letras, el término independiente es cero."],
    "ejemplos": [
        {"titulo": "El lobo solitario", "enunciado": "Encuentra el término independiente en el polinomio 4x^3 - 9x^2 + x + 15.", "solucion_pasos": ["Buscamos el término sin letras.", "Es el 15.", "Como tiene un más adelante, el término independiente es +15."]}
    ],
    "errores_frecuentes": ["Olvidar el signo del término independiente (ej. en $x^2 - 4$, decir que el independiente es 4 en lugar de -4).", "Creer que el coeficiente del término de mayor grado es el término independiente."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIND-CONC-{i}", "semantic_id": sid18, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué propiedad fundamental le otorga el nombre de 'Término Independiente' a una constante dentro de un polinomio? (v{i})", "choices": ["A) Que su valor final no depende del valor que asuman las variables (letras) del polinomio, ya que carece de parte literal.", "B) Que se encuentra al inicio del polinomio, independientemente de su orden.", "C) Que siempre es un número positivo.", "D) Que su grado absoluto es infinito."], "correct_answer": "A) Que su valor final no depende del valor que asuman las variables (letras) del polinomio, ya que carece de parte literal.", "solution_steps": "Al no estar multiplicado por variables, su valor es inmutable y no 'depende' de los valores de x, y, etc.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TIND-REC-1", "semantic_id": sid18, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica de manera precisa el término independiente del polinomio $P(x) = -5x^4 + 3x^2 - x - 8$.", "choices": ["A) $-8$", "B) $8$", "C) $-5$", "D) No tiene término independiente."], "correct_answer": "A) $-8$", "solution_steps": "El término sin letras es el 8. Nos llevamos su signo a la izquierda: -8.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIND-PROC-{i}", "semantic_id": sid18, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El polinomio $Q(x) = x^3 + 2x^2 + 5x$ carece por completo de término independiente, por lo que este no existe matemáticamente?", "choices": [], "correct_answer": "Falso", "solution_steps": "Cuando no se escribe un término numérico suelto, matemáticamente existe y su valor es $0$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TIND-PAES-{i}", "semantic_id": sid18, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una empresa modela sus ingresos usando $I(x) = 1500x - 2x^2 + 5000$, donde $x$ es la cantidad de clientes. Un economista explica que, incluso si no entra ningún cliente ($x = 0$), la empresa asegura un monto base garantizado. ¿A qué componente del polinomio corresponde este monto base? (v{i})", "choices": ["A) Al término independiente ($+5000$).", "B) Al coeficiente del término principal ($-2$).", "C) Al grado absoluto del polinomio ($2$).", "D) A la variable $x$ evaluada en cero."], "correct_answer": "A) Al término independiente ($+5000$).", "solution_steps": "Si x=0, todos los términos con x se anulan ($1500(0) - 2(0)^2 = 0$). Solo sobrevive el término independiente (5000), representando el valor inicial.", "paes_style": True})

# 9. ORDENAMIENTO
sid19 = "MAT.ALG.POLINOMIOS.ORDENAMIENTO"
RECURSOS.append({
    "semantic_id": sid19, "objetivo": "Ordenar un polinomio de forma ascendente o descendente con respecto a los exponentes de una variable u 'ordenatriz'.",
    "introduccion": "Tener los términos desordenados es como tener un diccionario sin orden alfabético. Para poder trabajar limpiamente con polinomios, la regla de etiqueta es ordenarlos.",
    "resumen": "Se dice que un polinomio está **Ordenado con respecto a una letra** (llamada *letra ordenatriz*) cuando los exponentes de esa letra van aumentando o disminuyendo de manera progresiva y sin retrocesos.",
    "explicacion": "Existen dos formas de ordenar un polinomio respecto a una variable:\n- **Orden Descendente (El más usado):** Del exponente más grande al más pequeño. \n  Ej: $x^4 + x^3 - 2x^2 + 5x - 7$. (Los exponentes bajan: 4, 3, 2, 1, y el término independiente que es 0).\n- **Orden Ascendente:** Del exponente más pequeño al más grande. \n  Ej: $-7 + 5x - 2x^2 + x^3 + x^4$. (Los exponentes suben: 0, 1, 2, 3, 4).\n\nPara ordenar, se mueven los términos completos con todo y su signo. El término $-2x^2$ siempre será negativo, sin importar dónde lo coloques.",
    "procedimiento": ["Paso 1: Elige o identifica la letra ordenatriz.", "Paso 2: Fíjate en los exponentes de esa letra en cada término.", "Paso 3: Decide si vas a ordenar de mayor a menor (descendente) o de menor a mayor (ascendente).", "Paso 4: Reescribe el polinomio moviendo los términos completos (con sus coeficientes y signos) siguiendo el orden de los exponentes elegidos."],
    "ejemplos": [
        {"titulo": "Alineando la fila", "enunciado": "Ordena el polinomio 5x^2 - x^4 + 3 - 2x de forma descendente.", "solucion_pasos": ["Buscamos el exponente mayor de x: es 4. El primer término es -x^4.", "El que le sigue hacia abajo es 2. El segundo término es +5x^2.", "Le sigue el exponente 1. El tercer término es -2x.", "Por último, el término independiente (exponente 0). Es +3.", "Resultado: -x^4 + 5x^2 - 2x + 3."]}
    ],
    "errores_frecuentes": ["Olvidar llevarse el signo del término al moverlo (ej. dejar el signo negativo de $-x^4$ tirado en el medio).", "Confundirse con polinomios de múltiples variables y mezclar los exponentes de una letra con los de otra."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDP-CONC-{i}", "semantic_id": sid19, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué criterio matemático se utiliza para establecer que un polinomio está 'ordenado en forma descendente' respecto a una letra ordenatriz? (v{i})", "choices": ["A) Que los exponentes numéricos de esa letra específica vayan disminuyendo progresivamente término a término.", "B) Que los coeficientes de los términos vayan de un número mayor a un número menor.", "C) Que el grado absoluto de los términos vaya disminuyendo en todos los casos.", "D) Que se escriban primero las letras del final del alfabeto (Z, Y, X...)."], "correct_answer": "A) Que los exponentes numéricos de esa letra específica vayan disminuyendo progresivamente término a término.", "solution_steps": "El orden polinomial se basa puramente en la secuencia de los exponentes de la variable elegida como referencia.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ORDP-REC-1", "semantic_id": sid19, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Ordena el polinomio $4x - 8 + 3x^3 - x^2$ en estricto orden descendente respecto a la variable '$x$'.", "choices": ["A) $3x^3 - x^2 + 4x - 8$", "B) $-8 + 4x - x^2 + 3x^3$", "C) $4x - x^2 + 3x^3 - 8$", "D) $3x^3 + x^2 - 4x + 8$"], "correct_answer": "A) $3x^3 - x^2 + 4x - 8$", "solution_steps": "Buscamos de mayor a menor exponente: x^3, luego x^2, luego x^1, por último término independiente (x^0). Llevando signos: $3x^3 - x^2 + 4x - 8$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDP-PROC-{i}", "semantic_id": sid19, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El polinomio $x^4 + x^2 + x^3 + 1$ está correctamente ordenado de forma descendente?", "choices": [], "correct_answer": "Falso", "solution_steps": "Los exponentes son 4, 2, 3, 0. Hay un retroceso (sube del 2 al 3 en el medio). No está ordenado. Debería ser $x^4 + x^3 + x^2 + 1$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDP-PAES-{i}", "semantic_id": sid19, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Para aplicar un teorema de división algebraica, la regla exige que el polinomio divisor esté ordenado en forma descendente respecto a '$a$'. El estudiante tiene la expresión $5a^2b^3 - 4a^3b^2 + 10ab^4$. ¿Cómo debe escribirlo para cumplir la regla y poder ejecutar el teorema? (v{i})", "choices": ["A) $-4a^3b^2 + 5a^2b^3 + 10ab^4$", "B) $10ab^4 + 5a^2b^3 - 4a^3b^2$", "C) $5a^2b^3 - 4a^3b^2 + 10ab^4$ (ya está ordenado)", "D) $-4a^3b^2 + 10ab^4 + 5a^2b^3$"], "correct_answer": "A) $-4a^3b^2 + 5a^2b^3 + 10ab^4$", "solution_steps": "Revisamos solo los exponentes de 'a': son 2, 3, 1. Para ordenar descendente: exponente 3 primero, luego 2, luego 1. Movilizando con signos: $-4a^3b^2 + 5a^2b^3 + 10ab^4$.", "paes_style": True})


# 10. POLINOMIO_COMPLETO
sid20 = "MAT.ALG.POLINOMIOS.POLINOMIO_COMPLETO"
RECURSOS.append({
    "semantic_id": sid20, "objetivo": "Reconocer si un polinomio está completo o incompleto con respecto a los exponentes de una variable.",
    "introduccion": "Imagina una escalera. Para que esté completa, no le puede faltar ningún peldaño. En los polinomios pasa lo mismo con los exponentes: si falta un peldaño numérico, el polinomio está incompleto.",
    "resumen": "Un **Polinomio Completo** con respecto a una letra es aquel que contiene **absolutamente todos los exponentes sucesivos** de dicha letra, desde el grado más alto (grado relativo) hasta el término independiente (exponente cero), sin saltarse ninguno.",
    "explicacion": "Vamos a revisar peldaños.\n- Polinomio: $x^3 + 2x^2 - 4x + 5$.\nRevisamos la 'x'. Exponente más alto es 3. ¿Tiene exponente 2? Sí. ¿Tiene exponente 1? Sí ($-4x$). ¿Tiene término independiente (exponente 0)? Sí ($+5$). ¡Es un **polinomio completo**!\n\n- Polinomio: $x^4 - 2x^2 + 1$.\nRevisamos la 'x'. Exponente más alto es 4. ¿Tiene exponente 3? ¡No está! Se saltó el peldaño. ¿Tiene el 2? Sí. ¿Tiene el 1? No. ¿Tiene el 0? Sí. Es un **polinomio incompleto**.\n\nAl realizar operaciones avanzadas como la división larga, los huecos de los polinomios incompletos suelen rellenarse con coeficientes de cero (ej. $x^4 + 0x^3 - 2x^2 + 0x + 1$) para no perder la alineación estructural.",
    "procedimiento": ["Paso 1: Identifica la letra ordenatriz y encuentra su exponente mayor.", "Paso 2: Haz una cuenta regresiva mental desde ese exponente mayor hasta cero.", "Paso 3: Verifica si cada número de tu cuenta regresiva está presente como exponente en la expresión.", "Paso 4: Si todos están, es completo. Si falta aunque sea uno, es incompleto."],
    "ejemplos": [
        {"titulo": "Contando peldaños", "enunciado": "Verifica si el polinomio 5x^4 - 3x^3 + x es completo o incompleto.", "solucion_pasos": ["Mayor exponente es 4. Faltarían el 3, el 2, el 1 y el 0.", "Está el 3. No está el 2 (no hay término con x^2).", "Al faltar el exponente 2 (y el 0), concluimos inmediatamente que es Incompleto."]}
    ],
    "errores_frecuentes": ["Creer que si el polinomio está desordenado es incompleto. El orden no importa, si los términos están escondidos por ahí, sigue estando completo.", "Ignorar la necesidad del término independiente ($x^0$). Un polinomio completo usualmente debe terminar en un número suelto."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCOM-CONC-{i}", "semantic_id": sid20, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué condición estricta define a un 'Polinomio Completo' respecto a una letra determinada? (v{i})", "choices": ["A) Que contenga todos los exponentes sucesivos de esa letra, desde su grado máximo hasta el grado cero, sin omitir ninguno.", "B) Que todos sus coeficientes numéricos sean distintos de cero.", "C) Que sus términos estén perfectamente ordenados de forma descendente.", "D) Que tenga el mismo número de letras que de números en su estructura."], "correct_answer": "A) Que contenga todos los exponentes sucesivos de esa letra, desde su grado máximo hasta el grado cero, sin omitir ninguno.", "solution_steps": "La 'completitud' se refiere a la secuencia continua de las potencias de la variable.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PCOM-REC-1", "semantic_id": sid20, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "¿Cuál de los siguientes polinomios clasifica como 'Completo' respecto a la variable '$x$'?", "choices": ["A) $2x^3 - x^2 + 5x - 8$", "B) $x^4 + x^2 + 1$", "C) $x^3 + 3x^2 + 4$", "D) $5x^2 - 8x$"], "correct_answer": "A) $2x^3 - x^2 + 5x - 8$", "solution_steps": "A tiene exponentes 3, 2, 1, 0 (Completo). B salta el 3 y el 1. C salta el 1. D salta el 0 (independiente).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCOM-PROC-{i}", "semantic_id": sid20, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El polinomio $x^2 + 5x^3 - 2 + x$ es un polinomio incompleto porque está desordenado?", "choices": [], "correct_answer": "Falso", "solution_steps": "El orden visual no afecta la completitud. Contiene los exponentes 3, 2, 1 y 0, por lo que posee todos los elementos y es Completo. El desorden es irrelevante.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PCOM-PAES-{i}", "semantic_id": sid20, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un sistema de división polinomial exige que el polinomio dividendo esté 'completo'. El usuario ingresa la expresión $P(x) = 4x^3 - 2x + 7$. El sistema rechaza la operación, indicando un hueco en los grados. ¿Cómo debe reescribir el usuario la expresión para que el sistema la acepte como completa sin alterar su valor? (v{i})", "choices": ["A) $4x^3 + 0x^2 - 2x + 7$", "B) $4x^3 + x^2 - 2x + 7$", "C) $4x^3 - 2x^2 + 7x + 0$", "D) No es posible completarlo sin alterar el valor matemático."], "correct_answer": "A) $4x^3 + 0x^2 - 2x + 7$", "solution_steps": "Falta el término de grado 2. Para rellenar el hueco sin cambiar el valor total, se usa un coeficiente cero: $+0x^2$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 5 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 5 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-5", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-5.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
