# scratch/build_alg_b0301_t2.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 6. DEFINICION_TERMINO
sid6 = "MAT.ALG.TERMINO.DEFINICION_TERMINO"
RECURSOS.append({
    "semantic_id": sid6, "objetivo": "Comprender la definición de término algebraico como la unidad mínima indivisible mediante sumas o restas.",
    "introduccion": "¿Cómo se construyen las oraciones matemáticas? Así como una oración está formada por palabras separadas por espacios, el álgebra está formada por 'términos' separados por signos de suma o resta.",
    "resumen": "Un **Término Algebraico** es una expresión matemática que consta de un solo símbolo o de varios símbolos no separados entre sí por los signos $+$ (más) o $-$ (menos). Es la pieza fundamental (el ladrillo) con la que se construyen las expresiones.",
    "explicacion": "Visualiza el término como un vagón de tren cerrado. Todo lo que hay adentro (números, letras, potencias, divisiones) está pegado con multiplicaciones y divisiones. \n- $3a$ es un solo término (el 3 y la $a$ están pegados por multiplicación).\n- $\\frac{4xy}{z}$ es un solo término (están pegados por división).\n- $3a + b$ NO es un término, son DOS términos. El signo $+$ actúa como un enganche que separa los vagones.\n\nTodo término tiene 4 partes anatómicas fundamentales que estudiaremos: el signo, el coeficiente, la parte literal y el grado.",
    "procedimiento": ["Paso 1: Lee la expresión de izquierda a derecha.", "Paso 2: Busca signos + o - que no estén encerrados en paréntesis ni denominadores.", "Paso 3: Cada segmento entre esos signos libres es un término independiente."],
    "ejemplos": [
        {"titulo": "Contando vagones", "enunciado": "En la expresión '5x - 8y^2 + z/4', identifica cuáles son los términos individuales.", "solucion_pasos": ["Observamos los separadores: hay un signo menos (-) y un signo más (+).", "Esto divide la expresión en tres partes.", "Los tres términos son: '5x', '-8y^2' y 'z/4'."]}
    ],
    "errores_frecuentes": ["Creer que una división separa términos (ej. ver $\\frac{x+y}{2}$ y pensar que son dos términos; en realidad el denominador largo consolida todo en un solo término fraccionario gigantesco).", "Asumir que un número suelto (como un 5) no es un término porque no tiene letra. Los números sueltos son términos independientes."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFT-CONC-{i}", "semantic_id": sid6, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Según la definición estructural del álgebra, ¿qué operaciones matemáticas fungen como los 'separadores' universales que delimitan dónde termina un término y dónde comienza el siguiente? (v{i})", "choices": ["A) La adición (+) y la sustracción (-) no encerradas en paréntesis.", "B) La multiplicación y la división.", "C) Las potencias y las raíces.", "D) Los signos de igualdad y desigualdad."], "correct_answer": "A) La adición (+) y la sustracción (-) no encerradas en paréntesis.", "solution_steps": "Los signos más y menos actúan como las fronteras que dividen a las expresiones en términos separados.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEFT-REC-1", "semantic_id": sid6, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál de las siguientes expresiones matemáticas representa un ÚNICO término algebraico?", "choices": [r"A) $\frac{5xy^2}{4z}$", r"B) $5xy^2 - 4z$", r"C) $5x + y^2 + 4z$", r"D) $5x - y^2 - 4z$"], "correct_answer": r"A) $\frac{5xy^2}{4z}$", "solution_steps": "La opción A solo contiene multiplicaciones y divisiones internamente, por lo que constituye un solo bloque indivisible (un término).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFT-PROC-{i}", "semantic_id": sid6, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La expresión puramente numérica $150$ se considera un término algebraico válido a pesar de no poseer letras visibles?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Un número suelto es un término (conocido como término independiente) donde la parte literal se asume elevada a cero ($x^0 = 1$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFT-PAES-{i}", "semantic_id": sid6, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un software de matemáticas requiere que el usuario ingrese una fórmula dividiendo conceptualmente sus términos. El estudiante ingresa la expresión completa $\\frac{{a+b+c}}{{2}}$. El software le informa que ha ingresado un solo término. El estudiante reclama diciendo que hay signos más. ¿Quién tiene la razón matemática? (v{i})", "choices": ["A) El software tiene la razón, ya que la gran barra de división agrupa todo el numerador como un bloque unitario, formando un único término fraccionario.", "B) El estudiante tiene la razón, hay tres letras distintas separadas por sumas, son tres términos obligatoriamente.", "C) Ambos se equivocan, en realidad hay dos términos, la suma y la división.", "D) El software falló porque las letras no pueden dividirse por números enteros."], "correct_answer": "A) El software tiene la razón, ya que la gran barra de división agrupa todo el numerador como un bloque unitario, formando un único término fraccionario.", "solution_steps": "Una barra de fracción que abarca toda la suma actúa como un paréntesis agrupador gigante. Es un solo término fraccionario. Si la barra solo dividiera a la 'c', serían tres términos.", "paes_style": True})

# 7. SIGNO_TERMINO
sid7 = "MAT.ALG.TERMINO.SIGNO_TERMINO"
RECURSOS.append({
    "semantic_id": sid7, "objetivo": "Identificar y clasificar el signo de un término algebraico (positivo o negativo).",
    "introduccion": "En el álgebra, ningún vagón de tren viaja sin placa patente. Esa placa puede ser positiva (+) o negativa (-), e indica la naturaleza y dirección de esa cantidad matemática.",
    "resumen": "El **Signo** es la primera parte de un término. \n- Son **términos positivos** los que van precedidos del signo $+$.\n- Son **términos negativos** los que van precedidos del signo $-$.\n- **Regla de oro:** Cuando un término no va precedido de ningún signo, se asume que es positivo.",
    "explicacion": "El signo es el ADN de la suma y resta. \nSi tienes la expresión: $4a - 5b + c$\n1. El término $4a$ no tiene signo escrito adelante. Automáticamente, es un $+4a$.\n2. El término $-5b$ tiene un signo negativo. Pertenece al equipo negativo.\n3. El término $+c$ tiene un signo positivo. \n\nNunca asumas que el signo '-' es 'una resta que le pertenece al espacio'. El signo le pertenece exclusivamente al término que está INMEDIATAMENTE a su derecha. En $-5b$, el menos es parte inseparable del $5b$.",
    "procedimiento": ["Paso 1: Mira el extremo izquierdo del término que estás analizando.", "Paso 2: Si hay un signo '-' escrito explícitamente, el término es negativo.", "Paso 3: Si hay un signo '+' o si no hay absolutamente NADA escrito, el término es positivo."],
    "ejemplos": [
        {"titulo": "El dueño del signo", "enunciado": "Determina los signos de los términos de la expresión: x - 3y + 2z - 8", "solucion_pasos": ["Término 'x': No tiene signo visible al principio. Es positivo (+).", "Término '3y': Tiene un '-' a la izquierda. Es negativo (-).", "Término '2z': Tiene un '+' a la izquierda. Es positivo (+).", "Término '8': Tiene un '-' a la izquierda. Es negativo (-)."]}
    ],
    "errores_frecuentes": ["Creer que si la letra es negativa, el término completo cambia de naturaleza (El signo del término lo dicta el '+' o '-' exterior, independiente del valor oculto que pueda tener la variable).", "Asignarle el signo al término que está a la izquierda del signo, en lugar de al que está a la derecha."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIGT-CONC-{i}", "semantic_id": sid7, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"De acuerdo a la regla convencional de signos en álgebra, ¿qué indica la ausencia total de un símbolo '+' o '-' al inicio (extremo izquierdo) de un término algebraico aislado? (v{i})", "choices": ["A) Indica que se asume implícitamente que el término es de naturaleza positiva.", "B) Indica que el término es equivalente a cero.", "C) Indica que falta información y la ecuación es irresoluble.", "D) Indica que el término es estrictamente negativo."], "correct_answer": "A) Indica que se asume implícitamente que el término es de naturaleza positiva.", "solution_steps": "Al igual que con los números ordinarios, la falta de signo asume el signo positivo (+).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SIGT-REC-1", "semantic_id": sid7, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la expresión polinómica $7x^2 - 4xy + 9y - z$, ¿cuáles son los dos únicos términos que poseen signo negativo?", "choices": ["A) $-4xy$ y $-z$", "B) $7x^2$ y $-z$", "C) $-4xy$ y $9y$", "D) $-z$ y $9y$"], "correct_answer": "A) $-4xy$ y $-z$", "solution_steps": "El signo pertenece al término que se encuentra inmediatamente a su derecha. -4xy y -z tienen el signo menos delante.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIGT-PROC-{i}", "semantic_id": sid7, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿En la expresión $A - B$, el signo menos le pertenece algebraicamente al término $A$ porque está a su lado?", "choices": [], "correct_answer": "Falso", "solution_steps": "El signo afecta y le pertenece al término que se ubica inmediatamente a su DERECHA. Le pertenece a B, no a A. A es positivo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SIGT-PAES-{i}", "semantic_id": sid7, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un profesor presenta el modelo de utilidades $U = I - G$, donde $I$ son los ingresos y $G$ son los gastos fijos. Un estudiante decide reorganizar la fórmula colocando los gastos primero para enfatizarlos, escribiendo $U = G - I$. ¿Es correcta esta modificación a nivel algebraico de los signos? (v{i})", "choices": ["A) Es incorrecta, debió escribir $U = -G + I$ para respetar el signo original que le pertenecía a cada término.", "B) Es correcta, porque el orden de los factores no altera el resultado.", "C) Es correcta, porque en álgebra las letras siempre deben ser positivas sin importar su lugar.", "D) Es incorrecta, porque jamás se puede iniciar una fórmula con una letra de gasto."], "correct_answer": "A) Es incorrecta, debió escribir $U = -G + I$ para respetar el signo original que le pertenecía a cada término.", "solution_steps": "En I - G, la G es negativa y la I es positiva. Al mover los vagones, deben llevarse su placa patente consigo: -G + I.", "paes_style": True})

# 8. COEFICIENTE_NUMERICO
sid8 = "MAT.ALG.TERMINO.COEFICIENTE_NUMERICO"
RECURSOS.append({
    "semantic_id": sid8, "objetivo": "Identificar el coeficiente numérico de un término algebraico y comprender su función multiplicadora.",
    "introduccion": "Si tienes una caja llena de gatos, la variable es 'gato'. Pero, ¿cuántos gatos tienes? El número grande que va al frente de la palabra es el que te da la cantidad. Ese número es el coeficiente.",
    "resumen": "El **Coeficiente Numérico** es el factor (el número conocido) que antecede a las letras en un término algebraico. Indica cuántas veces se debe sumar la parte literal a sí misma. \n- **Regla del uno invisible:** Si un término no tiene coeficiente numérico visible (ej. $x$), se asume obligatoriamente que su coeficiente es el número $1$.",
    "explicacion": "El coeficiente es el capitán del barco. \n- En el término $5a$, el coeficiente es $5$. Significa que tenemos $a + a + a + a + a$. Es el multiplicador.\n- En el término $-3x^2$, el coeficiente es $-3$.\n- En el término $ab$, no ves ningún número. ¿Significa que hay cero $ab$? ¡Claro que no! Si hubiese cero, no verías las letras (porque $0 \\cdot ab = 0$). El coeficiente es $1$. (Un $ab$).\n- En el término $-x$, el coeficiente es $-1$.\n\n*Ojo con las fracciones:* En un término como $\\frac{x}{4}$, el coeficiente numérico no es un '4 abajo', es la fracción completa $\\frac{1}{4}$.",
    "procedimiento": ["Paso 1: Localiza el número grande que multiplica las letras.", "Paso 2: Incluye el signo que lo acompaña (+ o -) como parte de su identidad.", "Paso 3: Si no hay número, escribe '1'. Si está en forma de división por 'k', el coeficiente es la fracción '1/k'."],
    "ejemplos": [
        {"titulo": "Cacería de coeficientes", "enunciado": "Extrae el coeficiente numérico de a) -8y, b) abc, c) -z, d) 3x/5", "solucion_pasos": ["a) -8. (Se lleva su signo negativo).", "b) 1. (El uno invisible).", "c) -1. (El negativo y el uno invisible).", "d) 3/5. (Es una fracción multiplicando a x)."]}
    ],
    "errores_frecuentes": ["Confundir el coeficiente con el exponente (Ej: en $x^5$ decir que el coeficiente es 5, cuando el coeficiente es 1 y el exponente es 5).", "Decir que el coeficiente de una variable solitaria es cero, lo que eliminaría todo el término matemáticamente."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COEF-CONC-{i}", "semantic_id": sid8, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué significado aritmético tiene el coeficiente numérico '$4$' en el término algebraico $4xy$? (v{i})", "choices": ["A) Significa que el bloque '$xy$' está siendo sumado repetidamente a sí mismo cuatro veces.", "B) Significa que la letra $x$ y la letra $y$ deben elevarse ambas a la cuarta potencia.", "C) Significa que se le debe sumar cuatro al valor final de '$xy$'.", "D) Significa que el número cuatro se divide entre las letras."], "correct_answer": "A) Significa que el bloque '$xy$' está siendo sumado repetidamente a sí mismo cuatro veces.", "solution_steps": "El coeficiente es un multiplicador (factor). $4xy = xy + xy + xy + xy$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"COEF-REC-1", "semantic_id": sid8, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica de forma exacta cuál es el coeficiente numérico del término algebraico $-\\frac{m^2}{7}$.", "choices": ["A) $-\\frac{1}{7}$", "B) $-7$", "C) $-1$", "D) $7$"], "correct_answer": "A) $-\\frac{1}{7}$", "solution_steps": "El número oculto arriba de la m es 1. El denominador es 7. El signo es negativo. La fracción constante que multiplica a la letra es -1/7.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COEF-PROC-{i}", "semantic_id": sid8, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El coeficiente numérico de la expresión $-x^3$ es $3$, ya que es el único número visible en el término?", "choices": [], "correct_answer": "Falso", "solution_steps": "El número 3 es el exponente. El coeficiente numérico es el factor de multiplicación exterior, que al no estar visible y tener un menos, es obligatoriamente $-1$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COEF-PAES-{i}", "semantic_id": sid8, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un test automatizado evalúa las características de la expresión $-y$. Un estudiante marca que 'su coeficiente numérico es cero porque no hay números y su signo es negativo'. La retroalimentación automática rechaza la respuesta porque: (v{i})", "choices": ["A) Si el coeficiente fuera verdaderamente cero, la expresión completa se anularía matemáticamente; el coeficiente real es $-1$.", "B) El coeficiente sí es cero, pero el estudiante falló en el signo.", "C) Las variables individuales no poseen coeficiente numérico por definición.", "D) El coeficiente debe ser obligatoriamente una letra."], "correct_answer": "A) Si el coeficiente fuera verdaderamente cero, la expresión completa se anularía matemáticamente; el coeficiente real es $-1$.", "solution_steps": "Cero multiplicado por cualquier cosa da cero ($0 \\cdot y = 0$). Como la y sobrevive en la expresión $-y$, su coeficiente es el neutro multiplicativo con signo cambiado ($-1$).", "paes_style": True})

# 9. PARTE_LITERAL
sid9 = "MAT.ALG.TERMINO.PARTE_LITERAL"
RECURSOS.append({
    "semantic_id": sid9, "objetivo": "Identificar la parte literal de un término algebraico y reconocer su función fundamental como el 'apellido' o especie de la cantidad.",
    "introduccion": "Si el coeficiente te dice 'cuántos' tienes, la parte literal te dice 'qué' tienes. ¿Tienes 5 gatos o tienes 5 manzanas? En el álgebra, el apellido de tu número es la parte literal.",
    "resumen": "La **Parte Literal** está constituida por las letras que haya en el término y sus correspondientes exponentes. Es el bloque alfabético que sigue al coeficiente numérico.",
    "explicacion": "Anatomía de la parte literal:\n- En el término $8xyz$, la parte literal completa es $xyz$.\n- En el término $-2a^2b^3$, la parte literal no son solo las letras sueltas, ¡son las letras con sus exponentes pegados! La parte literal es $a^2b^3$.\n\nLa parte literal es sagrada porque funciona como un clasificador de especies. Así como en la vida real no puedes sumar 3 perros con 4 gatos para obtener 7 'perro-gatos', en el álgebra no puedes sumar la parte literal $x$ con la parte literal $x^2$. Son de especies distintas. Analizar bien la parte literal es el paso cero antes de intentar sumar o restar.",
    "procedimiento": ["Paso 1: Identifica y aísla el coeficiente numérico (el número grande y su signo).", "Paso 2: Todo lo que sobra a la derecha del coeficiente (letras y sus pequeños exponentes) es el bloque que compone la parte literal."],
    "ejemplos": [
        {"titulo": "Separando aguas", "enunciado": "Extrae la parte literal del término fraccionario 3m^4/5", "solucion_pasos": ["Separamos el coeficiente: La fracción numérica es 3/5.", "Todo lo que resta es la letra y su exponente.", "La parte literal es m^4."]}
    ],
    "errores_frecuentes": ["Olvidar incluir los exponentes en la parte literal, mencionando solo las letras base.", "Pensar que un término puramente numérico (ej. $15$) tiene una parte literal invisible igual a $x$. (Su parte literal es $x^0 = 1$, que no altera el número, por ende 'carece' funcionalmente de parte literal visible)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PLIT-CONC-{i}", "semantic_id": sid9, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde una perspectiva estructural, ¿cuál es la función principal que cumple la 'parte literal' dentro de un término algebraico? (v{i})", "choices": ["A) Define la 'especie' o el tipo de la cantidad, determinando con qué otros términos es compatible para sumar o restar.", "B) Define cuántas veces se debe multiplicar el término por sí mismo.", "C) Indica si el resultado del cálculo será obligatoriamente positivo o negativo.", "D) Determina el valor absoluto máximo que puede alcanzar el término."], "correct_answer": "A) Define la 'especie' o el tipo de la cantidad, determinando con qué otros términos es compatible para sumar o restar.", "solution_steps": "La parte literal es como la 'unidad de medida'. Solo términos con exactamente la misma parte literal (misma especie) pueden reducirse mediante adición.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PLIT-REC-1", "semantic_id": sid9, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Extrae de forma precisa la parte literal completa del término algebraico $-14p^3q^2r$.", "choices": ["A) $p^3q^2r$", "B) $pqr$", "C) $3, 2, 1$", "D) $-14$"], "correct_answer": "A) $p^3q^2r$", "solution_steps": "La parte literal incluye todas las bases y sus respectivos exponentes. No incluye al coeficiente (-14).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PLIT-PROC-{i}", "semantic_id": sid9, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Es matemáticamente correcto afirmar que los términos $5x^2$ y $9x^3$ comparten idéntica parte literal porque ambos están formados por la misma letra base '$x$'?", "choices": [], "correct_answer": "Falso", "solution_steps": "La parte literal incluye obligatoriamente los exponentes. Al ser $x^2$ y $x^3$ exponentes diferentes, son partes literales de distinta especie matemática.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PLIT-PAES-{i}", "semantic_id": sid9, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un programador requiere que su base de datos solo sume cajas del mismo volumen. Modela las dimensiones de las cajas grandes como $x^3$ y las rectangulares como $x^2y$. Un empleado suma el inventario y reporta '$10x^5y$'. El programador detecta de inmediato que el cálculo es absurdo algebraicamente porque: (v{i})", "choices": ["A) Sumó coeficientes de cajas con partes literales de distinta naturaleza matemática ($x^3$ y $x^2y$), fusionando los exponentes como si hubiera multiplicado.", "B) Debió reportar el resultado en litros en lugar de letras.", "C) Restó las partes literales en vez de sumar sus volúmenes.", "D) El exponente máximo permitido por las leyes algebraicas es tres."], "correct_answer": "A) Sumó coeficientes de cajas con partes literales de distinta naturaleza matemática ($x^3$ y $x^2y$), fusionando los exponentes como si hubiera multiplicado.", "solution_steps": "No se pueden sumar peras con manzanas. $x^3$ y $x^2y$ tienen partes literales diferentes, su suma queda indicada, jamás se fusionan los exponentes.", "paes_style": True})

# 10. EXPONENTE_LITERAL
sid10 = "MAT.ALG.TERMINO.EXPONENTE_LITERAL"
RECURSOS.append({
    "semantic_id": sid10, "objetivo": "Reconocer y operar con los exponentes dentro de la parte literal, especialmente el exponente 'uno' implícito.",
    "introduccion": "Hemos dicho que las letras representan números. Pero a veces, una sola letra está multiplicándose por sí misma muchas veces. El pequeño número que flota arriba de la letra es un ahorrador de espacio profesional: el exponente.",
    "resumen": "El **Exponente** es el número pequeño en la esquina superior derecha de una letra que indica cuántas veces esa letra se multiplica por sí misma. \n- **La regla del exponente invisible:** Cuando una letra no tiene un exponente explícitamente escrito, se asume matemáticamente que **su exponente es $1$**.",
    "explicacion": "Análisis microscópico de una letra:\n- $x^3$ significa $x \\cdot x \\cdot x$.\n- $a^4$ significa $a \\cdot a \\cdot a \\cdot a$.\n- Si ves la expresión $5y$, la letra $y$ se ve solita. ¿Significa que su exponente es 0? ¡NO! Porque todo número elevado a 0 se vuelve 1. Si fuera $y^0$, sería $5 \\cdot 1 = 5$, ¡la letra desaparecería! \n- La letra sobrevive porque su exponente real es 1. $y$ es en realidad $y^1$. \n\nEntender el uno invisible es crucial para multiplicar letras más adelante. Si multiplicas $x \\cdot x^2$, en realidad estás multiplicando $x^1 \\cdot x^2$, lo que te da $x^3$. Si olvidas el uno, el cálculo fallará.",
    "procedimiento": ["Paso 1: Mira la esquina superior derecha de cada letra en el término.", "Paso 2: Si hay un número, ese es su exponente.", "Paso 3: Si la esquina está vacía, dibuja mentalmente un '1'. Jamás asumas que es un cero."],
    "ejemplos": [
        {"titulo": "Desenmascarando los unos", "enunciado": "Extrae los exponentes individuales de las letras en el término -7ab^2c.", "solucion_pasos": ["La 'a' no tiene exponente visible. Por tanto, es a^1. Exponente: 1.", "La 'b' tiene un 2. Exponente: 2.", "La 'c' no tiene exponente visible. Es c^1. Exponente: 1."]}
    ],
    "errores_frecuentes": ["Creer que una letra sin exponente tiene exponente 0.", "Confundir el coeficiente (el multiplicador que va adelante) con el exponente (el potenciador que va arriba). El 3 en $3x$ hace algo totalmente distinto al 3 en $x^3$."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EXPL-CONC-{i}", "semantic_id": sid10, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Por qué es un error matemático fatal asumir que una variable 'solitaria' (como $x$ en la expresión $2x$) posee un exponente de valor cero? (v{i})", "choices": ["A) Porque cualquier base elevada a cero resulta en $1$ (por propiedades de potencias), lo que haría desaparecer la variable y convertiría la expresión en un simple número ($2 \\cdot 1 = 2$).", "B) Porque los exponentes cero están prohibidos en álgebra moderna.", "C) Porque si tuviera exponente cero el resultado completo de la expresión sería automáticamente negativo.", "D) Porque una variable solitaria en realidad tiene un exponente infinito."], "correct_answer": "A) Porque cualquier base elevada a cero resulta en $1$ (por propiedades de potencias), lo que haría desaparecer la variable y convertiría la expresión en un simple número ($2 \\cdot 1 = 2$).", "solution_steps": "Como $x^0 = 1$, asumir exponente cero destruye la variable. Para que la $x$ siga valiendo $x$, su exponente debe ser el elemento neutro $1$ ($x^1 = x$).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"EXPL-REC-1", "semantic_id": sid10, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la parte literal del término $12m^4n$, la suma aritmética de los exponentes de TODAS sus variables involucradas da como resultado total:", "choices": ["A) $5$", "B) $4$", "C) $0$", "D) $16$"], "correct_answer": "A) $5$", "solution_steps": "El exponente de m es 4. El exponente invisible de n es 1. La suma es 4 + 1 = 5.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EXPL-PROC-{i}", "semantic_id": sid10, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La expresión $x \\cdot x^3$ da como resultado correcto $x^3$, ya que el término de la izquierda al no tener exponente aporta cero al cálculo de la multiplicación de potencias?", "choices": [], "correct_answer": "Falso", "solution_steps": "La x de la izquierda tiene exponente 1. Por propiedades de las potencias de igual base se suman: 1 + 3 = 4. El resultado correcto es $x^4$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EXPL-PAES-{i}", "semantic_id": sid10, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Para calcular el volumen de una caja se usa la fórmula $V = Largo \\cdot Ancho \\cdot Alto$. Un estudiante anota en su bitácora que una caja cúbica donde todos sus lados miden '$a$' tendría un volumen de '$3a$'. Su profesor de geometría le marca el ejercicio como incorrecto. ¿Qué confusión conceptual experimentó el estudiante? (v{i})", "choices": ["A) Confundió la regla de la multiplicación de potencias con exponente 1 ($a \\cdot a \\cdot a = a^3$) con la suma aritmética de coeficientes ($a + a + a = 3a$).", "B) Olvidó sumar los exponentes y debió responder $a^0$.", "C) Aplicó mal el signo negativo a la fórmula del volumen.", "D) El volumen correcto de esa caja es $a^4$."], "correct_answer": "A) Confundió la regla de la multiplicación de potencias con exponente 1 ($a \\cdot a \\cdot a = a^3$) con la suma aritmética de coeficientes ($a + a + a = 3a$).", "solution_steps": "Volumen = $a \\cdot a \\cdot a$. Usando el 'uno invisible' es $a^1 \\cdot a^1 \\cdot a^1 = a^3$. El estudiante sumó las letras en lugar de multiplicarlas.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 2 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 2 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-2", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-2.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
