# scratch/build_alg_b0301_t4.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. CONCEPTO_CONSTANTE
sid16 = "MAT.ALG.FUNDAMENTOS.CONCEPTO_CONSTANTE"
RECURSOS.append({
    "semantic_id": sid16, "objetivo": "Comprender la diferencia entre una variable y una constante en una expresión algebraica.",
    "introduccion": "En el teatro de las matemáticas, algunos actores cambian de disfraz en cada obra (las variables), pero otros siempre interpretan el mismo papel, pase lo que pase.",
    "resumen": "Una **Constante** es un valor fijo que no cambia bajo ninguna circunstancia dentro de un problema. Se representa habitualmente mediante números explícitos (ej. $5$, $-3$, $\\pi$) o mediante las primeras letras del alfabeto ($a$, $b$, $c$) cuando generalizamos una fórmula.",
    "explicacion": "A diferencia de las variables (usualmente $x$, $y$, $z$) que están esperando que les asignes un valor, las constantes nacen con su valor definido.\nEn la fórmula del perímetro de una circunferencia $P = 2 \\cdot \\pi \\cdot r$:\n- El $2$ es una constante numérica. Jamás dejará de ser dos.\n- $\\pi$ es una constante (aprox. 3.14159...).\n- La $r$ (radio) es la variable, porque puedes tener círculos grandes o pequeños.\n\nEn la expresión genérica $ax^2 + bx + c$, por convención matemática, asumimos que $a, b, c$ son constantes (números fijos que rellenaremos luego) y la $x$ es la única variable que mutará.",
    "procedimiento": ["Paso 1: Identifica los números explícitos o constantes universales (como pi o e).", "Paso 2: Según el contexto del problema, identifica letras de inicio del abecedario (a, b, k) que funcionen como parámetros fijos.", "Paso 3: Distínguelas de las letras finales (x, y, z) o variables que cambian su valor dinámicamente."],
    "ejemplos": [
        {"titulo": "El elenco de la fórmula", "enunciado": "En la fórmula física de la velocidad en caída libre v = g*t (donde g es la gravedad de la Tierra y t el tiempo), identifica la constante y la variable.", "solucion_pasos": ["La gravedad de la Tierra 'g' no cambia, es un valor fijo (9.8 m/s^2). Es la constante.", "El tiempo 't' fluye y cambia constantemente. Es la variable.", "La velocidad 'v' cambia dependiendo de 't', por lo que también es variable."]}
    ],
    "errores_frecuentes": ["Creer que todas las letras son variables por el simple hecho de ser letras. A veces usamos letras para guardar números constantes.", "Confundir constante con coeficiente. El coeficiente es un tipo específico de constante que multiplica a una variable."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCON-CONC-{i}", "semantic_id": sid16, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la principal característica que distingue a una 'constante' de una 'variable' en el contexto de una fórmula algebraica? (v{i})", "choices": ["A) La constante mantiene un único valor fijo y predeterminado a lo largo de todo el análisis del problema, mientras la variable puede adoptar múltiples valores.", "B) La constante siempre se representa con un número y jamás puede ser representada con una letra.", "C) La constante debe ser obligatoriamente un número positivo, mientras la variable puede ser negativa.", "D) La constante es el resultado final de la ecuación."], "correct_answer": "A) La constante mantiene un único valor fijo y predeterminado a lo largo de todo el análisis del problema, mientras la variable puede adoptar múltiples valores.", "solution_steps": "Una constante no muta. Es la roca fija alrededor de la cual el resto de las variables (los ríos) fluyen y cambian.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CCON-REC-1", "semantic_id": sid16, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la fórmula general para una línea recta, dada por la expresión $y = mx + n$, donde $x$ e $y$ son las coordenadas cambiantes de los puntos en el plano. ¿Qué rol asumen las letras '$m$' y '$n$' por convención matemática?", "choices": ["A) Representan constantes (o parámetros fijos) para una recta específica.", "B) Representan variables independientes secundarias.", "C) Representan incógnitas que no tienen solución.", "D) Representan operaciones de multiplicación implícita."], "correct_answer": "A) Representan constantes (o parámetros fijos) para una recta específica.", "solution_steps": "En el modelo $y=mx+n$, para una recta en particular, m y n quedan fijos (como m=2, n=-1), mientras x e y varían formando la gráfica.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCON-PROC-{i}", "semantic_id": sid16, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El número $\\pi$ (pi) es considerado una variable en las fórmulas geométricas ya que se representa mediante un símbolo del alfabeto griego en lugar de un número arábigo?", "choices": [], "correct_answer": "Falso", "solution_steps": "El uso de una letra (griega o latina) no la hace variable. Pi representa un valor numérico universal e inmutable (aprox 3.1415), por lo tanto, es una constante universal.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCON-PAES-{i}", "semantic_id": sid16, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un programador diseña un algoritmo para calcular el costo de un viaje en taxi. Escribe el modelo: $Costo = BajadaDeBandera + (PrecioPorKm \\cdot KmRecorridos)$. Para una ciudad particular donde las tarifas están reguladas por ley y no cambian, ¿qué elementos del modelo deben ser declarados como 'constantes' en el código? (v{i})", "choices": ["A) La Bajada de Bandera y el Precio por Km.", "B) Únicamente los Kilómetros Recorridos.", "C) El Costo Total y los Kilómetros Recorridos.", "D) Todas las letras son variables por definición en un programa."], "correct_answer": "A) La Bajada de Bandera y el Precio por Km.", "solution_steps": "La tarifa de inicio y el costo por kilómetro son fijos para la ciudad (son las reglas del juego). Lo único que varía entre un pasajero y otro son los kilómetros recorridos (variable independiente) y el costo final (variable dependiente).", "paes_style": True})

# 2. MULTIPLICACION_IMPLICITA
sid17 = "MAT.ALG.FUNDAMENTOS.MULTIPLICACION_IMPLICITA"
RECURSOS.append({
    "semantic_id": sid17, "objetivo": "Reconocer la multiplicación implícita por ausencia de signos entre números, letras y paréntesis.",
    "introduccion": "En matemáticas, a veces el mayor mensaje es el que no está escrito. Cuando las letras y los números se abrazan sin separadores en medio, hay una operación invisible ocurriendo.",
    "resumen": "La **Multiplicación Implícita** es la convención algebraica donde **la ausencia de un signo de operación entre números, letras o paréntesis indica obligatoriamente una multiplicación**.",
    "explicacion": "El signo 'por' ($\\cdot$ o $\\times$) a menudo se omite por estética y velocidad.\n- Entre un número y una letra: $5x$ significa $5 \\cdot x$.\n- Entre dos letras: $ab$ significa $a \\cdot b$.\n- Antes de un paréntesis: $3(x + 2)$ significa $3 \\cdot (x + 2)$.\n- Entre dos paréntesis: $(a)(b)$ significa $(a) \\cdot (b)$.\n\nATENCIÓN: Esto NO aplica entre dos números explícitos. $52$ es cincuenta y dos, NO es $5 \\cdot 2$. Para multiplicar números explicitamente debes usar el punto ($5 \\cdot 2$) o paréntesis $5(2)$.",
    "procedimiento": ["Paso 1: Observa si dos elementos están adyacentes sin un signo '+' ni '-' entre ellos.", "Paso 2: Si al menos uno de ellos es una letra o un paréntesis, asume que están multiplicándose.", "Paso 3: Si ambos son números arábigos sueltos (ej. 4 y 7 formados como 47), no hay multiplicación, es la conformación posicional del número."],
    "ejemplos": [
        {"titulo": "Traductor explícito", "enunciado": "Reescribe la expresión 4xyz(a+b) mostrando todas sus multiplicaciones ocultas.", "solucion_pasos": ["Entre el 4 y la x hay multiplicación: 4 * x", "Entre x, y, z hay multiplicación: x * y * z", "Entre la z y el paréntesis hay multiplicación: z * (a+b)", "Resultado: 4 * x * y * z * (a+b)"]}
    ],
    "errores_frecuentes": ["Confundir la multiplicación implícita con adición. (Ej: pensar que $xy$ significa $x + y$).", "Aplicar la regla a números fijos (ej: al reemplazar $x=2$ en $3x$, escribir 32 en lugar de $3 \\cdot 2 = 6$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MIMP-CONC-{i}", "semantic_id": sid17, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el lenguaje algebraico formal, ¿qué operación matemática se asume implícitamente cuando dos variables se escriben adyacentes una de la otra sin ningún signo intermedio (por ejemplo, $pq$)? (v{i})", "choices": ["A) Multiplicación.", "B) Suma.", "C) División.", "D) Elevación a potencia."], "correct_answer": "A) Multiplicación.", "solution_steps": "La yuxtaposición (colocar cosas juntas) de letras o de un número con una letra denota siempre producto o multiplicación.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MIMP-REC-1", "semantic_id": sid17, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Expande la expresión $7a(b+c)$ escribiendo explícitamente todos los signos de operación ocultos.", "choices": ["A) $7 \\cdot a \\cdot (b + c)$", "B) $7 + a \\cdot (b + c)$", "C) $7 \\cdot a + (b + c)$", "D) $7^a \\cdot (b+c)$"], "correct_answer": "A) $7 \\cdot a \\cdot (b + c)$", "solution_steps": "Existe multiplicación entre el coeficiente 7 y la variable 'a', y también entre la variable 'a' y el bloque en paréntesis (b+c).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MIMP-PROC-{i}", "semantic_id": sid17, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si $x = 3$ e $y = 5$, entonces la evaluación de la expresión algebraica $xy$ da como resultado numérico $35$?", "choices": [], "correct_answer": "Falso", "solution_steps": "No se forma el número 35. Las letras adjuntas indican multiplicación. El resultado es $3 \\cdot 5 = 15$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MIMP-PAES-{i}", "semantic_id": sid17, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una estudiante modela el área de un terreno rectangular en su cuaderno. Al costado del terreno anota la letra $A$, y en el borde inferior anota la letra $B$. Luego escribe dentro del rectángulo la expresión $AB$. Su compañero le dice que está mal, porque el área se calcula multiplicando y ella no puso el signo 'por'. ¿Quién tiene la razón matemática? (v{i})", "choices": ["A) La estudiante tiene la razón, ya que la convención algebraica establece que dos letras adyacentes sin signo se están multiplicando entre sí.", "B) El compañero tiene la razón, sin el signo '$\\times$' o '$\\cdot$', la expresión $AB$ significa la suma de los lados.", "C) El compañero tiene la razón, porque $AB$ representa un número de dos dígitos donde A son las decenas y B las unidades.", "D) Ambos se equivocan, debió escribir $A^B$."], "correct_answer": "A) La estudiante tiene la razón, ya que la convención algebraica establece que dos letras adyacentes sin signo se están multiplicando entre sí.", "solution_steps": "El lenguaje algebraico no requiere símbolos explícitos de multiplicación para el producto de variables. AB es el área correcta.", "paes_style": True})

# 3. IDENTIFICACION_BINOMIO
sid18 = "MAT.ALG.EXPRESIONES.IDENTIFICACION_BINOMIO"
RECURSOS.append({
    "semantic_id": sid18, "objetivo": "Reconocer y clasificar polinomios de exactamente dos términos (Binomios).",
    "introduccion": "Si 'mono' es uno, 'bi' es dos. Bicicleta, binocular, bilingüe... y en álgebra, Binomio. Es el tren más corto posible que no viaja solo.",
    "resumen": "Un **Binomio** es un polinomio formado por la suma o diferencia de **exactamente dos términos** algebraicos que no son semejantes entre sí.",
    "explicacion": "Todo binomio tiene un único 'puente' o separador principal (un signo $+$ o un signo $-$) libre en la mitad de la expresión, separando dos grandes bloques.\n- $a + b$ es un binomio.\n- $5x^3 - 8y^2$ es un binomio (el menos es el puente).\n- $\\frac{x}{2} + 4$ es un binomio.\n\n*La trampa mortal:* ¿Es $3x + 5x$ un binomio? Visualmente tiene dos términos y un puente en medio. ¡Pero CUIDADO! Los términos son semejantes. Antes de clasificar, hay que sumar: $3x + 5x = 8x$. En realidad es un **monomio** disfrazado. Para que sea un binomio real, los dos términos deben ser de especies diferentes.",
    "procedimiento": ["Paso 1: Simplifica la expresión sumando todos los términos semejantes si los hay.", "Paso 2: Cuenta cuántos términos distintos te quedan en la versión final irreductible.", "Paso 3: Si te quedan exactamente dos, y están unidos por un +, o por un -, es un binomio."],
    "ejemplos": [
        {"titulo": "El puente", "enunciado": "Clasifica la expresión 4a^2b + 5ab^2", "solucion_pasos": ["Verificamos si son semejantes. El primero es especie a^2b, el segundo es ab^2. No se pueden sumar.", "Contamos los términos separados por el '+'. Hay 1 y 2.", "La clasificación es Binomio."]}
    ],
    "errores_frecuentes": ["Llamar binomio a expresiones reducibles como $x + x$.", "Creer que una división separa términos y decir que $\\frac{a}{b}$ es un binomio (es un monomio)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDBIN-CONC-{i}", "semantic_id": sid18, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué exigencia fundamental, más allá del conteo visual, debe cumplir una expresión de dos componentes separados por una adición para ser clasificada definitivamente como un Binomio algebraico? (v{i})", "choices": ["A) Los dos componentes deben ser términos NO semejantes, garantizando que la expresión no pueda reducirse a un solo término (Monomio).", "B) Ambos componentes deben ser positivos.", "C) Ambos componentes deben tener distintas letras, no importa el exponente.", "D) El primer término debe tener un grado mayor que el segundo."], "correct_answer": "A) Los dos componentes deben ser términos NO semejantes, garantizando que la expresión no pueda reducirse a un solo término (Monomio).", "solution_steps": "Si fueran semejantes (ej: $2x + 3x$), se fusionarían en $5x$, siendo un monomio y perdiendo la categoría bi.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"IDBIN-REC-1", "semantic_id": sid18, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de las siguientes expresiones matemáticas es un Binomio puro e irreductible.", "choices": ["A) $x^2 - y^2$", "B) $x^2 - x^2$", "C) $4x^2 + 2x^2$", "D) $\\frac{x^2 - y^2}{x+y}$ (con la barra principal uniendo todo)"], "correct_answer": "A) $x^2 - y^2$", "solution_steps": "A tiene 2 términos no semejantes. B se anula a cero. C se reduce a $6x^2$ (monomio). D es un monomio fraccionario complejo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDBIN-PROC-{i}", "semantic_id": sid18, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $7a^2b + 3ab^2$ NO es un binomio porque se puede sumar para formar $10a^3b^3$?", "choices": [], "correct_answer": "Falso", "solution_steps": "No se pueden sumar porque sus partes literales no son idénticas ($a^2b$ vs $ab^2$). Al no poder reducirse, se mantiene firme con dos términos. Es un Binomio legítimo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDBIN-PAES-{i}", "semantic_id": sid18, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una evaluación, se pide dar un ejemplo de binomio de grado cinco. Un estudiante escribe $3x^5y^5 + 2x^5y^5$. El profesor tacha la respuesta e indica puntaje cero. ¿Por qué la respuesta es conceptualmente errónea para la pregunta? (v{i})", "choices": ["A) Porque la expresión del estudiante es reducible a $5x^5y^5$, lo cual es un monomio, no un binomio.", "B) Porque el grado absoluto es diez ($5+5$), no cinco.", "C) Ambas razones A y B contribuyen a que el ejemplo sea incorrecto.", "D) El profesor se equivocó, el estudiante escribió un binomio válido."], "correct_answer": "C) Ambas razones A y B contribuyen a que el ejemplo sea incorrecto.", "solution_steps": "A: Es un monomio disfrazado ($5x^5y^5$). B: El grado de ese monomio es 10, no 5. Doble error.", "paes_style": True})

# 4. IDENTIFICACION_TRINOMIO
sid19 = "MAT.ALG.EXPRESIONES.IDENTIFICACION_TRINOMIO"
RECURSOS.append({
    "semantic_id": sid19, "objetivo": "Reconocer y clasificar polinomios de exactamente tres términos (Trinomios).",
    "introduccion": "El 'tri' lo vemos en triángulos, triciclos, trípodes. Cuando el tren algebraico suma un vagón más y llega a tres piezas fundamentales, lo bautizamos como Trinomio.",
    "resumen": "Un **Trinomio** es un polinomio compuesto por la suma o diferencia de **exactamente tres términos** que no son semejantes entre sí.",
    "explicacion": "Visualmente, un trinomio puro tiene dos 'puentes' (+ o -) libres en su estructura, separando el conjunto en tres bloques.\n- Expresión base: $x^2 + 5x + 6$. (Un bloque cuadrático, un bloque lineal, y un bloque numérico independiente). Es el clásico trinomio de la forma general.\n- Expresión: $a + b - c$. Tres variables distintas. Es un trinomio.\n- Expresión engañosa: $x^2 + 2x - 2x$. ¿Es un trinomio? ¡No! El $+2x$ y el $-2x$ son semejantes y se anulan mutuamente (da $0x$). La expresión real es simplemente $x^2$. Era un **monomio** disfrazado de trinomio.",
    "procedimiento": ["Paso 1: Detecta y reduce todos los términos semejantes que existan (suma peras con peras).", "Paso 2: Cuenta los bloques que sobrevivieron a la reducción, separados por los signos de adición/sustracción.", "Paso 3: Si el conteo final de bloques irreductibles es tres, es un trinomio."],
    "ejemplos": [
        {"titulo": "Contando bloques irreductibles", "enunciado": "Verifica si 5x^3 - x^2 - x^2 es un trinomio.", "solucion_pasos": ["Visualmente tiene tres pedazos.", "Pero -x^2 y -x^2 son semejantes. Se reducen a -2x^2.", "La expresión final es 5x^3 - 2x^2.", "Solo quedaron dos términos. Es un Binomio, no un trinomio."]}
    ],
    "errores_frecuentes": ["No reducir términos semejantes y clasificar una expresión larga como trinomio solo contando los espacios.", "Ignorar el término numérico independiente (ej. en $x^2+x+1$, creer que no es trinomio porque el 1 no tiene letras. Los tres bloques cuentan)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDTRI-CONC-{i}", "semantic_id": sid19, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuántos términos independientes no reducibles entre sí requiere poseer un polinomio para ser clasificado y nombrado formalmente como un 'Trinomio'? (v{i})", "choices": ["A) Exactamente tres.", "B) Exactamente dos.", "C) Tres o más.", "D) Exactamente cuatro."], "correct_answer": "A) Exactamente tres.", "solution_steps": "El prefijo Tri determina un número exacto de componentes (3).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"IDTRI-REC-1", "semantic_id": sid19, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Luego de reducir términos semejantes, ¿cuál de las siguientes opciones representa verdaderamente a un Trinomio?", "choices": ["A) $2x^2 + 5x - 7$", "B) $x^2 + 3x + 2x + 1$", "C) $x^3 + x^3 + x^3$", "D) $a+b$"], "correct_answer": "A) $2x^2 + 5x - 7$", "solution_steps": "A ya está reducido y tiene 3 términos. B se reduce a $x^2+5x+1$ (3 términos, pero la opción A es directa). C se reduce a $3x^3$ (Monomio). D es Binomio.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDTRI-PROC-{i}", "semantic_id": sid19, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $100 + x + y$ es un trinomio válido aunque su primer término carezca de parte literal?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El término independiente (100) cuenta como un término perfectamente válido dentro del polinomio. Las tres partes (100, x, y) no se pueden sumar entre sí. Es un trinomio.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IDTRI-PAES-{i}", "semantic_id": sid19, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un sistema geométrico genera polinomios basados en los lados de un terreno. Una lectura arroja la expresión de perímetro: $L + L + 2L$. El sistema intenta enviarlo al módulo de 'Resolución de Trinomios' porque cuenta tres separaciones, pero la red colapsa. ¿Por qué fue un error de sistema? (v{i})", "choices": ["A) Porque todos los términos son semejantes y se reducen a un Monomio ($4L$); intentar aplicar métodos de Trinomio a algo que no lo es provoca el fallo.", "B) Porque el número 2 en el último término lo convierte en Binomio.", "C) Porque los trinomios requieren al menos dos letras diferentes en su estructura.", "D) Porque los trinomios no se pueden usar en perímetros."], "correct_answer": "A) Porque todos los términos son semejantes y se reducen a un Monomio ($4L$); intentar aplicar métodos de Trinomio a algo que no lo es provoca el fallo.", "solution_steps": "Jamás se clasifica una expresión sin antes reducir términos. $L+L+2L = 4L$. Es un simple monomio lineal.", "paes_style": True})

# 5. NUMERO_TERMINOS
sid20 = "MAT.ALG.EXPRESIONES.NUMERO_TERMINOS"
RECURSOS.append({
    "semantic_id": sid20, "objetivo": "Determinar con exactitud la cantidad de términos que conforman un polinomio mediante la identificación de los signos separadores operativos.",
    "introduccion": "Para no perder vagones en el viaje, debemos saber contarlos correctamente. Esto requiere entrenar al ojo para ver los signos de sumar y restar como muros que dividen habitaciones.",
    "resumen": "El **Número de Términos** de un polinomio indica cuántos bloques irreductibles conforman la expresión. Se cuentan observando los separadores de suma ($+$) y resta ($-$) que se encuentran **fuera de cualquier paréntesis, corchete, raíz o denominador**.",
    "explicacion": "Una técnica infalible para contar términos es jugar a 'separar las aguas':\n- Si ves: $3x^2 - 4x + 7$.\n1. Empieza en la izquierda.\n2. Al primer '-' haz un corte vertical. Ahí acaba el primer término ($3x^2$).\n3. Avanza. Al encontrar el '+' haz otro corte. Termina el segundo ($-4x$).\n4. Avanza hasta el final. Termina el tercero ($+7$).\nTotal: 3 términos.\n\n*La regla del escudo protector:* Si un signo + o - está atrapado dentro de un paréntesis (ej. $5(a+b)$) o dentro de un denominador largo (ej. $\\frac{x+y+z}{2}$), ese signo está 'protegido'. No sirve como separador principal. Esos bloques gigantescos cuentan como un solo término inmenso.",
    "procedimiento": ["Paso 1: Simplifica o reduce el polinomio si tiene partes semejantes.", "Paso 2: Subraya cada pedazo de la expresión, cortando el subrayado justo ANTES de cada signo + o - que esté 'libre' al aire (no encerrado en escudos).", "Paso 3: Cuenta cuántas líneas de subrayado hiciste."],
    "ejemplos": [
        {"titulo": "Esquivando trampas", "enunciado": "Determina el número de términos de la expresión: a - (b+c) + d/4", "solucion_pasos": ["Término 1: 'a'. Luego viene un menos libre. Corte.", "Término 2: '-(b+c)'. El signo más interior no cuenta porque está protegido. Luego viene un más libre. Corte.", "Término 3: '+ d/4'.", "Total: 3 términos."]}
    ],
    "errores_frecuentes": ["Contar como términos a los elementos que están sumándose *dentro* de un numerador común (ej. ver $\\frac{x+y}{2}$ y pensar que son dos términos porque hay un '$+$' arriba).", "Contar las multiplicaciones. Separar $5x$ en dos términos (5 y x)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NTCON-CONC-{i}", "semantic_id": sid20, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué papel juegan los signos de agrupación (como paréntesis o grandes líneas fraccionarias) al momento de contabilizar el número de términos de una expresión algebraica general? (v{i})", "choices": ["A) Actúan como 'escudos' que empaquetan todo su contenido en un único bloque o término indivisible, inutilizando los signos $+$ o $-$ internos como separadores principales.", "B) Multiplican la cantidad de términos que hay adentro por la cantidad que hay afuera.", "C) Obligan a sumar todos los coeficientes numéricos.", "D) Descomponen la expresión en el doble de sus términos originales."], "correct_answer": "A) Actúan como 'escudos' que empaquetan todo su contenido en un único bloque o término indivisible, inutilizando los signos $+$ o $-$ internos como separadores principales.", "solution_steps": "Un paréntesis agrupa cosas. Todo lo que esté dentro funciona como una unidad integral (un solo vagón sellado) frente al resto de la expresión.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"NTCON-REC-1", "semantic_id": sid20, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Aplica las reglas de contabilización de términos e indica el número exacto de términos libres que posee la siguiente expresión macro: $4x^2 - 5(x+y+z) + \\frac{a+b}{3} + 8$.", "choices": ["A) 4 términos.", "B) 8 términos.", "C) 3 términos.", "D) 6 términos."], "correct_answer": "A) 4 términos.", "solution_steps": "T1: $4x^2$. T2: $-5(x+y+z)$ [es un solo bloque]. T3: $\\frac{a+b}{3}$ [un bloque fraccionario]. T4: $8$. Total: 4.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NTCON-PROC-{i}", "semantic_id": sid20, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $x \\cdot y \\cdot z \\cdot w$ posee cuatro términos porque presenta cuatro variables claramente identificables?", "choices": [], "correct_answer": "Falso", "solution_steps": "La multiplicación no separa términos. Al estar todos fusionados por multiplicaciones, conforman 1 único término (monomio multivariable).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NTCON-PAES-{i}", "semantic_id": sid20, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Una fórmula de corrección de vuelo está dada por $E = 1000 - \\frac{{v+w}}{{t}} + 4(a-b)$. El computador de vuelo reserva en memoria un 'registro' de cálculo para cada término matemático individual e independiente que conforma la fórmula. ¿Cuántos registros de memoria utilizará la computadora para evaluar el lado derecho de la ecuación? (v{i})", "choices": ["A) 3 registros de memoria.", "B) 7 registros de memoria.", "C) 5 registros de memoria.", "D) 1 registro de memoria."], "correct_answer": "A) 3 registros de memoria.", "solution_steps": "Analizamos $1000 - \\frac{{v+w}}{{t}} + 4(a-b)$. El primer corte es tras el 1000 (T1). El segundo corte es tras la fracción compleja que agrupa $v+w$ sobre $t$ (T2). El tercer bloque es la multiplicación del 4 por el paréntesis protegido (T3). Son 3 términos gruesos.", "paes_style": True})


def generate_all():
    print("Escribiendo YAMLs Tanda 4 corregida (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 4 corregida (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-4", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-4.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
