# scratch/build_alg_b0302_t3.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 11. RAZON_COMPARACION
sid11 = "MAT.ALG.LENGUAJE_OPERACIONES.RAZON_COMPARACION"
RECURSOS.append({
    "semantic_id": sid11, "objetivo": "Traducir una razón como una comparación por cociente entre dos cantidades.",
    "introduccion": "Si en un salón hay 2 niños por cada 3 niñas, no sabemos cuántos alumnos hay en total. Solo sabemos la proporción o el 'ritmo' de la mezcla. Esa es la magia de la razón.",
    "resumen": "Una **Razón** es una comparación entre dos cantidades mediante una división. Se traduce algebraicamente de la misma forma que un cociente ($\\frac{a}{b}$) o usando el símbolo de proporción ($a:b$).",
    "explicacion": "Palabras clave:\n- La razón entre\n- La relación entre\n- Está en proporción de\n- Es a (ej: 'x es a y')\n\nEjemplos:\n- 'La razón entre hombres y mujeres es de 2 a 3': Se traduce como $\\frac{H}{M} = \\frac{2}{3}$\n- 'El peso de A y el peso de B están en razón de 5 a 1': $\\frac{A}{B} = \\frac{5}{1}$\n\nEl orden de aparición en el enunciado dicta estrictamente el orden en la fracción. El primero nombrado va al numerador (arriba), y el segundo al denominador (abajo).",
    "procedimiento": ["Paso 1: Identifica las dos variables que se están comparando.", "Paso 2: Construye la fracción con la primera variable arriba y la segunda abajo.", "Paso 3: Si el problema te da los números de la proporción (ej. 'es de 3 a 4'), iguala la fracción de las variables a la fracción numérica (3/4)."],
    "ejemplos": [
        {"titulo": "Comparando pesos", "enunciado": "Traduce algebraicamente: 'La razón entre la masa de Júpiter y la masa de la Tierra es de 318 a 1'.", "solucion_pasos": ["Las variables son masa de Júpiter (J) y masa de la Tierra (T).", "El texto dice 'La razón entre Júpiter y la Tierra'. Formamos la fracción J/T.", "La proporción numérica es '318 a 1', formando la fracción 318/1.", "Igualamos: J/T = 318/1."]}
    ],
    "errores_frecuentes": ["Invertir el orden de las variables al construir la fracción. (Ej: 'La razón entre oro y plata es 1 a 2', traducido erróneamente como $\\frac{P}{O} = \\frac{1}{2}$).", "Confundir la 'razón geométrica' (división) con la 'razón aritmética' (resta). En álgebra básica, 'razón' a secas siempre implica división."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZC-CONC-{i}", "semantic_id": sid11, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Cuando se pide traducir la 'razón entre la variable $A$ y la variable $B$', ¿qué estructura operativa subyace obligatoriamente a esta comparación en el contexto del álgebra elemental? (v{i})", "choices": ["A) Un cociente o división, ordenando estrictamente la primera variable mencionada como numerador y la segunda como denominador ($\\frac{A}{B}$).", "B) Una suma entre las dos variables ($A + B$).", "C) Una resta, donde a la mayor se le quita la menor.", "D) Una multiplicación directa ($A \\cdot B$)."], "correct_answer": "A) Un cociente o división, ordenando estrictamente la primera variable mencionada como numerador y la segunda como denominador ($\\frac{A}{B}$).", "solution_steps": "La palabra 'razón' en este contexto significa proporción geométrica, es decir, un cociente que compara dos tamaños.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RAZC-REC-1", "semantic_id": sid11, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Selecciona la ecuación algebraica que traduce perfectamente el enunciado: 'La relación entre la edad del padre ($P$) y la edad del hijo ($H$) es de cinco a dos'.", "choices": ["A) $\\frac{P}{H} = \\frac{5}{2}$", "B) $\\frac{H}{P} = \\frac{5}{2}$", "C) $P + H = 5 + 2$", "D) $5P = 2H$"], "correct_answer": "A) $\\frac{P}{H} = \\frac{5}{2}$", "solution_steps": "Padre se nombra primero (va al numerador). Hijo segundo (va al denominador). Cinco va arriba y dos abajo. Queda P/H = 5/2.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZC-PROC-{i}", "semantic_id": sid11, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $x:y = 3:4$ es algebraicamente equivalente a la ecuación $\\frac{x}{y} = \\frac{3}{4}$ para representar una razón?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El símbolo de dos puntos ($:$) es la notación clásica de proporción y representa exactamente un cociente o fracción. Ambas ecuaciones son idénticas en su significado.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZC-PAES-{i}", "semantic_id": sid11, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un nutricionista indica que 'en esta dieta, la razón entre gramos de proteínas ($P$) y gramos de carbohidratos ($C$) debe ser de uno a tres'. Si el paciente arma su plan alimenticio usando la ecuación $P = 3C$, ¿está cumpliendo la instrucción del nutricionista? (v{i})", "choices": ["A) No, la ecuación del paciente indica que las proteínas son el triple de los carbohidratos, mientras que la razón original $\\frac{P}{C} = \\frac{1}{3}$ exige que los carbohidratos sean el triple ($C = 3P$).", "B) Sí, porque en una razón el orden de los números no importa, $1$ a $3$ es lo mismo que $3$ a $1$.", "C) Sí, porque al multiplicar cruzado $\\frac{P}{C} = \\frac{1}{3}$ resulta en $P = 3C$.", "D) No, porque no debió usar ecuaciones lineales sino logaritmos para las dietas."], "correct_answer": "A) No, la ecuación del paciente indica que las proteínas son el triple de los carbohidratos, mientras que la razón original $\\frac{P}{C} = \\frac{1}{3}$ exige que los carbohidratos sean el triple ($C = 3P$).", "solution_steps": "Traducción original: P/C = 1/3. Al multiplicar cruzado (propiedad de las proporciones): $3P = 1C \\rightarrow C = 3P$. El paciente se equivocó e invirtió la proporción, comiendo un exceso peligroso de proteínas.", "paes_style": True})

# 12. RAZON_FRENTE_FRACCION
sid12 = "MAT.ALG.LENGUAJE_OPERACIONES.RAZON_FRENTE_FRACCION"
RECURSOS.append({
    "semantic_id": sid12, "objetivo": "Diferenciar la traducción de una razón (comparación) de la traducción de una fracción de un total.",
    "introduccion": "Imagina una pizza. Si te digo 'comí 3 porciones de 8', estoy usando una fracción. Si te digo 'comí 3 porciones por cada 5 que tú comiste', estoy usando una razón. Ambas usan números fraccionarios, pero cuentan historias totalmente distintas.",
    "resumen": "Una **Fracción** compara una parte contra el **total** (ej. $3/8$ del total). Una **Razón** compara una parte contra **otra parte** (ej. la razón $3:5$).",
    "explicacion": "Análisis del error clásico:\nSituación: En un curso la razón entre hombres (H) y mujeres (M) es de 2 a 3.\n- Traducción de razón: $\\frac{H}{M} = \\frac{2}{3}$.\n- Conclusión falsa común: 'Los hombres son 2/3 del total del curso'. ¡FALSO!\n- Conclusión verdadera: Si por cada 2 hombres hay 3 mujeres, el 'grupo mínimo' es de 5 personas. Por lo tanto, los hombres son los $2/5$ del total, y las mujeres los $3/5$ del total.\n\nRegla de traducción:\n- Si el texto dice 'la razón entre A y B es $a:b$', usa proporciones ($\\frac{A}{B} = \\frac{a}{b}$).\n- Si el texto dice 'A es los $a/b$ del total', se traduce como $A = \\frac{a}{b} \\cdot Total$.",
    "procedimiento": ["Paso 1: Lee el enunciado. ¿Se están comparando dos partes distintas (ej. autos rojos vs autos azules)? Es una razón.", "Paso 2: ¿Se está comparando una parte contra todo el conjunto (ej. autos rojos vs el total del estacionamiento)? Es una fracción de un total.", "Paso 3: Si es una razón (a:b), para saber qué fracción del total representa 'a', debes sumar a+b y colocarlo como denominador: a/(a+b)."],
    "ejemplos": [
        {"titulo": "De razón a fracción total", "enunciado": "Si la razón entre agua y jarabe es de 4 a 1, ¿qué fracción de la mezcla total es agua?", "solucion_pasos": ["Partes de agua: 4.", "Partes de jarabe: 1.", "Total de partes en la mezcla: 4 + 1 = 5.", "Fracción de agua respecto al total: 4/5 de la mezcla."]}
    ],
    "errores_frecuentes": ["Pensar que si la razón A:B es 1:4, entonces A es 1/4 del total. (Realidad: A es 1/5 del total, porque hay 1+4=5 partes)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RZFR-CONC-{i}", "semantic_id": sid12, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Si en una asamblea la razón entre los votos a favor y los votos en contra fue de $3$ a $2$, ¿por qué es matemáticamente incorrecto afirmar que los votos a favor representaron los $\\frac{3}{2}$ del total de la asamblea? (v{i})", "choices": ["A) Porque la razón $3:2$ compara las dos partes entre sí (a favor vs contra); para compararla con el total hay que sumar las partes ($3+2=5$), concluyendo que los votos a favor fueron $\\frac{3}{5}$ del total.", "B) Porque las fracciones nunca pueden tener un numerador mayor que el denominador.", "C) Porque los votos en contra debieron sumarse al numerador y no al denominador.", "D) Porque una razón de $3$ a $2$ significa que en total solo votaron $5$ personas, ni una más ni una menos."], "correct_answer": "A) Porque la razón $3:2$ compara las dos partes entre sí (a favor vs contra); para compararla con el total hay que sumar las partes ($3+2=5$), concluyendo que los votos a favor fueron $\\frac{3}{5}$ del total.", "solution_steps": "La trampa de la razón es que los números ($3$ y $2$) no incluyen al total. El total oculto es la suma de las partes proporcionales ($5$). Por eso la fracción real respecto al universo es $3/5$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RZFR-REC-1", "semantic_id": sid12, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Si en un jarro la razón entre jugo de limón y agua es de $1:4$, ¿cuál expresión indica correctamente la cantidad de jugo de limón ($L$) en función de la capacidad total del jarro ($T$)?", "choices": ["A) $L = \\frac{1}{5}T$", "B) $L = \\frac{1}{4}T$", "C) $L = 4T$", "D) $L = T - 4$"], "correct_answer": "A) $L = \\frac{1}{5}T$", "solution_steps": "Partes de limón = 1. Partes de agua = 4. Partes totales = 1+4 = 5. El limón es una parte de las 5 del total, por ende $L = \\frac{1}{5}T$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RZFR-PROC-{i}", "semantic_id": sid12, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si un enunciado afirma que 'las mujeres representan los tres cuartos ($3/4$) de los asistentes al evento', se puede deducir algebraicamente que la razón entre mujeres y hombres es de $3$ a $1$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Si las mujeres son 3 partes de un total de 4, queda 1 sola parte para los hombres ($4 - 3 = 1$). Por lo tanto, la razón mujeres:hombres es $3:1$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RZFR-PAES-{i}", "semantic_id": sid12, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un inversionista inyecta capital en una empresa bajo la condición de que 'la razón entre mi inversión y la del fundador sea de $2$ a $3$'. Al momento de repartir los dividendos totales ($D$), el inversionista exige los $\\frac{2}{3} D$. El abogado del fundador le dice que su exigencia es matemáticamente incorrecta. ¿Qué fracción del total de dividendos le corresponde realmente al inversionista según su contrato? (v{i})", "choices": ["A) Le corresponden los $\\frac{2}{5} D$.", "B) Le corresponde exactamente $\\frac{1}{2} D$.", "C) Le corresponden los $\\frac{3}{2} D$.", "D) Le corresponden los $\\frac{3}{5} D$."], "correct_answer": "A) Le corresponden los $\\frac{2}{5} D$.", "solution_steps": "La inversión tiene la forma 2k (inversionista) y 3k (fundador). El capital total es 5k. Por lo tanto, al inversionista le corresponden 2 partes de las 5 totales, es decir, 2/5 del dividendo. Exigir los 2/3 es confundir la razón con la fracción del total.", "paes_style": True})

# 13. ANTECESOR_NUMERO
sid13 = "MAT.ALG.LENGUAJE_RELACIONES.ANTECESOR_NUMERO"
RECURSOS.append({
    "semantic_id": sid13, "objetivo": "Traducir el concepto de antecesor de un número entero.",
    "introduccion": "En la fila del supermercado, la persona que está justo delante de ti es tu antecesor. En la recta numérica de los números enteros, ocurre exactamente lo mismo.",
    "resumen": "El **Antecesor** de un número entero se traduce algebraicamente restando una unidad a dicho número. Si el número es $x$, su antecesor es **$x - 1$**.",
    "explicacion": "Esta regla aplica para cualquier número entero, independientemente de si es positivo, negativo o cero.\n- El antecesor de $5$ es $5 - 1 = 4$.\n- El antecesor de $0$ es $0 - 1 = -1$.\n- El antecesor de $x$ es $x - 1$.\n- El antecesor del doble de un número ($2x$) es $2x - 1$.\n\nEs fundamental usar paréntesis cuando el antecesor se va a multiplicar. Por ejemplo, 'el triple del antecesor de x' se escribe $3(x - 1)$. Si no pones paréntesis y escribes $3x - 1$, la matemática entenderá 'el antecesor del triple de x'.",
    "procedimiento": ["Paso 1: Identifica a quién se le está calculando el antecesor.", "Paso 2: Escribe esa variable (o expresión).", "Paso 3: Réstale 1.", "Paso 4: Si toda esta nueva expresión (x-1) va a sufrir alguna otra operación (multiplicarse o dividirse), enciérrala entre paréntesis."],
    "ejemplos": [
        {"titulo": "Protegiendo al antecesor", "enunciado": "Traduce: 'La mitad del antecesor de un número'.", "solucion_pasos": ["El antecesor del número es (x - 1).", "Se pide la mitad de esa cantidad completa.", "Traducción: (x - 1) / 2."]}
    ],
    "errores_frecuentes": ["Olvidar los paréntesis. Traducir 'el doble del antecesor' como $2x - 1$ en lugar de $2(x - 1)$.", "Confundir antecesor con número negativo (ej. pensar que el antecesor de $x$ es $-x$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ANTE-CONC-{i}", "semantic_id": sid13, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde una perspectiva posicional en la recta de los números enteros, ¿qué operación matemática básica garantiza siempre hallar el antecesor de cualquier número $x$? (v{i})", "choices": ["A) La sustracción de la unidad ($x - 1$).", "B) La división por dos ($x/2$).", "C) La multiplicación por menos uno ($-x$).", "D) La adición de la unidad ($x + 1$)."], "correct_answer": "A) La sustracción de la unidad ($x - 1$).", "solution_steps": "El antecesor es el número que está inmediatamente a la izquierda en la recta entera, lo cual siempre se calcula restando 1.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ANTE-REC-1", "semantic_id": sid13, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona la expresión que traduce: 'El antecesor del producto entre $m$ y $n$'.", "choices": ["A) $mn - 1$", "B) $m(n-1)$", "C) $(m-1)(n-1)$", "D) $m - 1 - n$"], "correct_answer": "A) $mn - 1$", "solution_steps": "Primero construimos el producto: $mn$. Luego le sacamos el antecesor a ese bloque completo: $mn - 1$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ANTE-PROC-{i}", "semantic_id": sid13, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Las expresiones algebraicas $5x - 1$ y $5(x - 1)$ son traducciones equivalentes para el enunciado 'el antecesor del quíntuple de un número'?", "choices": [], "correct_answer": "Falso", "solution_steps": "No son equivalentes ni significan lo mismo. 'El antecesor del quíntuple' es $5x - 1$. La expresión $5(x - 1)$ significa 'el quíntuple del antecesor'.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ANTE-PAES-{i}", "semantic_id": sid13, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un juego de acertijos computacionales pide al usuario: 'Ingresa un número entero $N$. La máquina calculará el cuadrado del antecesor de tu número'. ¿Qué expresión algebraica evalúa internamente la máquina? (v{i})", "choices": ["A) $(N - 1)^2$", "B) $N^2 - 1$", "C) $N - 1^2$", "D) $2(N - 1)$"], "correct_answer": "A) $(N - 1)^2$", "solution_steps": "Primero hallamos el antecesor, que es $(N-1)$. Luego, le aplicamos el cuadrado a toda esa entidad, requiriendo paréntesis: $(N - 1)^2$. La opción B sería 'el antecesor del cuadrado'.", "paes_style": True})

# 14. SUCESOR_NUMERO
sid14 = "MAT.ALG.LENGUAJE_RELACIONES.SUCESOR_NUMERO"
RECURSOS.append({
    "semantic_id": sid14, "objetivo": "Traducir el concepto de sucesor de un número entero.",
    "introduccion": "Si el antecesor mira hacia el pasado, el sucesor mira hacia el futuro. Es el siguiente número en la fila.",
    "resumen": "El **Sucesor** (o consecutivo) de un número entero se traduce algebraicamente sumando una unidad a dicho número. Si el número es $x$, su sucesor es **$x + 1$**.",
    "explicacion": "Al igual que con el antecesor, funciona en toda la recta entera.\n- El sucesor de $14$ es $14 + 1 = 15$.\n- El sucesor de $-5$ es $-5 + 1 = -4$. (Ojo aquí: el sucesor es 'más grande', por lo que avanza hacia el cero en los negativos).\n- El sucesor de $y$ es $y + 1$.\n\nNuevamente, el uso de paréntesis dictamina el orden de las operaciones. \n'El cuadrado del sucesor' es $(x+1)^2$.\n'El sucesor del cuadrado' es $x^2 + 1$.",
    "procedimiento": ["Paso 1: Identifica la base a la cual le calcularás el sucesor.", "Paso 2: Súmale 1 (+1).", "Paso 3: Si se le aplicará una operación externa a este sucesor, usa paréntesis para agrupar (x+1)."],
    "ejemplos": [
        {"titulo": "El consecutivo", "enunciado": "Traduce: 'La suma de un número con su propio sucesor'.", "solucion_pasos": ["El número es x.", "Su sucesor es (x + 1).", "Sumamos ambas partes: x + (x + 1)."]}
    ],
    "errores_frecuentes": ["Pensar que el sucesor de un número negativo como $-3$ es $-4$. (El sucesor se halla sumando 1, así que $-3 + 1 = -2$).", "Omitir los paréntesis al multiplicar o elevar potencias."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCE-CONC-{i}", "semantic_id": sid14, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el ámbito de los números enteros, ¿qué sinónimo verbal se utiliza frecuentemente en los problemas algebraicos para referirse al 'sucesor' de la variable $x$? (v{i})", "choices": ["A) El consecutivo de $x$.", "B) El recíproco de $x$.", "C) El opuesto de $x$.", "D) El múltiplo de $x$."], "correct_answer": "A) El consecutivo de $x$.", "solution_steps": "Sucesor y consecutivo son términos intercambiables que denotan avanzar una unidad ($x+1$) en la serie de números enteros.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SUCE-REC-1", "semantic_id": sid14, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Indica cuál de las expresiones corresponde fielmente a la frase: 'El triple del sucesor de $z$'.", "choices": ["A) $3(z + 1)$", "B) $3z + 1$", "C) $(3z) + 1$", "D) $z + 3$"], "correct_answer": "A) $3(z + 1)$", "solution_steps": "El sucesor es $(z+1)$. Se pide el triple de ese bloque, por tanto el 3 multiplica al paréntesis entero: $3(z+1)$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCE-PROC-{i}", "semantic_id": sid14, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $x + (x + 1)$ puede simplificarse a $2x + 1$, indicando que la suma de cualquier número con su sucesor siempre resulta en una estructura algebraica de un número impar?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "La reducción de términos semejantes de $x + x + 1$ nos da $2x + 1$. Esta es la definición universal de número impar. Sumar dos consecutivos siempre da impar.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCE-PAES-{i}", "semantic_id": sid14, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Durante una excavación arqueológica, se determina que un objeto A data del año $x$ (con $x$ siendo un año negativo antes de Cristo). Un objeto B se fabricó exactamente un año después. ¿Cuál expresión indica el año de fabricación del objeto B y qué significa en la recta cronológica? (v{i})", "choices": ["A) El año es $x + 1$, y el número será más cercano al cero (año 0) que el objeto A.", "B) El año es $x - 1$, y el número será más negativo (más alejado del año 0).", "C) El año es $1 - x$, porque los años negativos se restan al revés.", "D) El año es $|x| + 1$ para forzar que sea positivo."], "correct_answer": "A) El año es $x + 1$, y el número será más cercano al cero (año 0) que el objeto A.", "solution_steps": "'Un año después' es el sucesor. Se suma 1. Al ser $x$ un número negativo (ej. -500), sumarle 1 da -499, que es matemáticamente un valor mayor y cronológicamente más cercano al cero.", "paes_style": True})

# 15. ENTEROS_CONSECUTIVOS
sid15 = "MAT.ALG.LENGUAJE_RELACIONES.ENTEROS_CONSECUTIVOS"
RECURSOS.append({
    "semantic_id": sid15, "objetivo": "Modelar series de varios números enteros que se suceden uno tras otro.",
    "introduccion": "Ya sabemos encontrar al que sigue en la fila, pero ¿qué pasa si necesitamos a los tres siguientes, o a una familia entera de consecutivos? Necesitamos encadenar la lógica del sucesor.",
    "resumen": "Una **Serie de Enteros Consecutivos** se traduce tomando una variable inicial ($x$) y sumándole progresivamente $1, 2, 3...$ para representar los siguientes elementos: **$x, (x+1), (x+2), (x+3)$...**",
    "explicacion": "Al modelar problemas verbales con tres o más números consecutivos, tienes libertad para elegir el punto de partida, pero la progresión debe mantenerse intacta.\n- Modelo clásico: El menor es $x$. Los tres consecutivos son $x$, $x+1$, $x+2$.\n- Modelo centrado (muy útil para simplificar ecuaciones): El del medio es $x$. Los tres consecutivos son $x-1$, $x$, $x+1$.\n\nAmbos modelos son correctos, pero si el problema te pide 'el número menor' y usaste el modelo centrado, ¡recuerda que el menor era $x-1$, no $x$!",
    "procedimiento": ["Paso 1: Identifica cuántos números consecutivos pide el problema (tres, cuatro, cinco...).", "Paso 2: Decide si partirás desde el menor (x) o desde un punto central.", "Paso 3: Construye la lista sumando 1 sucesivamente: x, x+1, x+2...", "Paso 4: Si el problema pide la suma de todos, escribe la suma total de la lista y reduce términos semejantes."],
    "ejemplos": [
        {"titulo": "Tres hermanos seguidos", "enunciado": "Traduce algebraicamente: 'La suma de las edades de tres hermanos que nacieron en años consecutivos'.", "solucion_pasos": ["Hermano menor: x.", "Hermano del medio: x + 1.", "Hermano mayor: x + 2.", "Suma total: x + (x + 1) + (x + 2).", "Si reducimos, obtenemos: 3x + 3."]}
    ],
    "errores_frecuentes": ["Traducir 'tres números consecutivos' usando tres letras distintas como $x, y, z$. (Error fatal: se pierde la relación matemática entre ellos, que es distar en una unidad).", "Olvidar a la $x$ solita y empezar a contar desde $x+1$. (Ej. escribir $x+1, x+2, x+3$ como tres consecutivos, lo cual es válido, pero hace que la variable $x$ no sea ninguno de los números del conjunto)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ECON-CONC-{i}", "semantic_id": sid15, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al enfrentar un problema que involucra 'tres números enteros consecutivos', ¿por qué es perjudicial modelar la situación asignando tres variables distintas, como $a, b, c$? (v{i})", "choices": ["A) Porque usar múltiples variables no refleja la restricción matemática que los conecta (cada uno es el anterior más uno), creando una ecuación con demasiadas incógnitas irresolubles.", "B) Porque el alfabeto no tiene suficientes letras para tantos problemas.", "C) Porque usar $a, b, c$ obligatoriamente significa que son números pares.", "D) Porque los números consecutivos deben ser obligatoriamente representados por la letra $x$."], "correct_answer": "A) Porque usar múltiples variables no refleja la restricción matemática que los conecta (cada uno es el anterior más uno), creando una ecuación con demasiadas incógnitas irresolubles.", "solution_steps": "La clave de la palabra 'consecutivos' es que reduce todas las incógnitas a una sola variable base, aprovechando el espaciado conocido (+1).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ECON-REC-1", "semantic_id": sid15, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Un estudiante decide que la letra $m$ representará al número *mayor* de un trío de enteros consecutivos. ¿Cómo debe escribir los otros dos números restantes?", "choices": ["A) $m - 1$ y $m - 2$", "B) $m + 1$ y $m + 2$", "C) $m$ y $m - 1$", "D) $\\frac{m}{2}$ y $\\frac{m}{3}$"], "correct_answer": "A) $m - 1$ y $m - 2$", "solution_steps": "Si $m$ es el mayor de los tres, entonces los que le preceden en la serie hacia atrás son el antecesor ($m-1$) y el antecesor del antecesor ($m-2$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ECON-PROC-{i}", "semantic_id": sid15, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La suma de tres enteros consecutivos $x + (x+1) + (x+2)$ puede reducirse algebraicamente a la expresión $3x + 3$, de lo cual se concluye que dicha suma siempre será un múltiplo de $3$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Al reducir queda $3x + 3$. Al factorizar, obtenemos $3(x + 1)$. Como todo el bloque está multiplicado por 3, la suma de tres consecutivos siempre es divisible por 3.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ECON-PAES-{i}", "semantic_id": sid15, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un problema PAES pide encontrar cuatro números enteros consecutivos tales que su suma equivalga a 130. Un estudiante usa el modelo centrado para ganar simetría y nombra al segundo número de la serie como $x$. ¿Cuál es la ecuación correcta que debe plantear el estudiante para que los cuatro números mantengan la consecutividad? (v{i})", "choices": ["A) $(x - 1) + x + (x + 1) + (x + 2) = 130$", "B) $x + (x + 1) + (x + 2) + (x + 3) = 130$", "C) $(x - 2) + (x - 1) + x + (x + 1) = 130$", "D) $4x + 1 = 130$"], "correct_answer": "A) $(x - 1) + x + (x + 1) + (x + 2) = 130$", "solution_steps": "Si el segundo número es x, el primero (que está antes) es x-1. El tercero es x+1, y el cuarto x+2. La opción B asume que x es el primero. La C asume que x es el tercero.", "paes_style": True})


def generate_all():
    print("Escribiendo YAMLs Tanda 3 (MAT.ALG.B0302)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 3 (MAT.ALG.B0302)...")
    append_jsonl("mat-alg-lenguaje-banco-gen-3", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-3.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
