# scratch/build_b0205_t16.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. CALCULO_MONTO (Interés Compuesto)
sid1 = "MAT.NUM.INTERES_COMPUESTO.CALCULO_MONTO"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Calcular el monto final acumulado en una operación de interés compuesto.",
    "introduccion": "Si inviertes dinero en la bolsa a largo plazo, no calculas tu ganancia sumando el mismo billete año tras año. Para ver el futuro, usas la fórmula mágica del crecimiento exponencial.",
    "resumen": "La fórmula del Monto Final ($M$ o $C_f$) en interés compuesto es: $M = C \\cdot (1 + i)^t$. Donde el paréntesis $(1+i)$ se eleva a la cantidad de períodos $t$.",
    "explicacion": "En el interés compuesto, la fórmula principal nos da directamente el **Monto Final Total** (Capital + Intereses sumados):\n\n$$M = C \\cdot (1 + i)^t$$\n\n- **$C$:** Capital Inicial.\n- **$i$:** Tasa de interés (en decimal, ej: $0.05$).\n- **$t$:** Cantidad de períodos de capitalización.\n\nNotar que el factor de aumento $(1 + i)$ no se multiplica por $t$ (como en el simple), sino que se **eleva** a $t$. Multiplicar un número por sí mismo repetidas veces es lo que genera la curva exponencial que hace crecer el dinero agresivamente en el tiempo.",
    "procedimiento": ["Paso 1: Convierte la tasa de interés a decimal ($i$).", "Paso 2: Suma 1 a la tasa para obtener el factor de crecimiento ($1 + i$).", "Paso 3: Eleva ese factor a la potencia $t$ (el número de periodos).", "Paso 4: Multiplica el resultado por el Capital Inicial."],
    "ejemplos": [
        {"titulo": "Depósito a plazo compuesto", "enunciado": "Se invierten $100.000 al 5% de interés compuesto anual durante 3 años. ¿Cuánto dinero hay al final?", "solucion_pasos": ["C = 100.000, i = 0.05, t = 3.", "Factor = $(1 + 0.05) = 1.05$.", "Elevamos a t: $(1.05)^3 = 1.05 \\cdot 1.05 \\cdot 1.05 = 1.157625$.", "Multiplicamos por C: $100.000 \\cdot 1.157625 = 115.762,5$.", "El monto final es aproximadamente $115.763."]}
    ],
    "errores_frecuentes": ["Multiplicar $(1 + i)$ por $t$ en lugar de usar potencias (confundir la fórmula con interés simple).", "Olvidar sumar el 1 antes de elevar a la potencia (calcular $0.05^3$ destruirá el capital en lugar de hacerlo crecer)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOC-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la fórmula del Monto Final de Interés Compuesto $M = C \\cdot (1 + i)^t$, ¿qué rol cumple el exponente '$t$' matemáticamente? (v{i})", "choices": ["A) Representa la cantidad de veces que el capital acumulado se multiplica por el factor de crecimiento.", "B) Representa una multiplicación simple de la tasa por el tiempo.", "C) Es una constante que siempre vale 12.", "D) Indica el monto fijo de dinero que se suma cada mes."], "correct_answer": "A) Representa la cantidad de veces que el capital acumulado se multiplica por el factor de crecimiento.", "solution_steps": "La exponenciación representa multiplicaciones sucesivas (capitalización).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MONTOC-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si inviertes a una tasa del $8\\%$ compuesto, la base de la potencia que utilizarás en la fórmula es:", "choices": ["A) $1.08$", "B) $0.08$", "C) $1.8$", "D) $8.0$"], "correct_answer": "A) $1.08$", "solution_steps": "$1 + 0.08 = 1.08$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOC-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El monto final de $\$500$ al $10\\%$ compuesto por $2$ años se calcula resolviendo $500 \\cdot (1.10)^2$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "C=500, factor=1.10, t=2. Correcto.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONTOC-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una corporación emite bonos y capta $\$50.000.000$ a una tasa de interés compuesto del $4\\%$ anual. ¿Qué expresión algebraica le permitirá al área contable determinar la deuda total (capital más intereses) que deberá pagar la corporación al cabo de $10$ años? (v{i})", "choices": ["A) $50.000.000 \\cdot (1.04)^{10}$", "B) $50.000.000 \\cdot (1 + 0.04 \\cdot 10)$", "C) $50.000.000 \\cdot (0.04)^{10}$", "D) $50.000.000 \\cdot (1.4)^{10}$"], "correct_answer": "A) $50.000.000 \\cdot (1.04)^{10}$", "solution_steps": "C = 50.000.000, tasa i = 0.04. Factor = 1.04. Tiempo = 10. Fórmula: $50.000.000 \\cdot (1.04)^{10}$.", "paes_style": True})

# 2. CALCULO_INTERES (Interés Compuesto)
sid2 = "MAT.NUM.INTERES_COMPUESTO.CALCULO_INTERES"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Calcular únicamente el monto de los intereses ganados en una operación de interés compuesto.",
    "introduccion": "Si la fórmula del interés compuesto te da siempre el total (con tu capital incluido), ¿cómo haces para saber exactamente cuánta 'ganancia pura' obtuviste? Simple lógica: al total, réstale lo que tú pusiste.",
    "resumen": "A diferencia del interés simple, no hay una fórmula corta directa para el interés puro ($I$) en compuesto. Se calcula hallando primero el Monto Final ($M$) y restando el Capital Inicial ($C$): $I = M - C$.",
    "explicacion": "En interés compuesto, la fórmula principal es $M = C(1+i)^t$.\nSi un problema te pregunta **exclusivamente por la ganancia** (los intereses), debes proceder en dos pasos ineludibles:\n\n1. Usa la fórmula principal para encontrar el dinero total que hay en la cuenta al final ($M$).\n2. Al resultado anterior ($M$), réstale tu capital inicial ($C$).\n\nFórmula derivada: \n$$I = C(1+i)^t - C$$\nFactorizando C, también se puede escribir como:\n$$I = C \\cdot [ (1+i)^t - 1 ]$$",
    "procedimiento": ["Paso 1: Calcula el Monto Final $M = C \\cdot (1+i)^t$.", "Paso 2: Al resultado $M$, réstale el capital inicial $C$.", "Paso 3: El número resultante es el interés puro ganado."],
    "ejemplos": [
        {"titulo": "Obteniendo la ganancia pura", "enunciado": "Se invierten $10.000 al 10% de interés compuesto anual por 2 años. ¿Cuánto dinero se ganó solo por concepto de intereses?", "solucion_pasos": ["Calculamos el Monto Final: $M = 10.000 \\cdot (1.10)^2$.", "Resolvemos la potencia: $(1.10)^2 = 1.21$.", "M = $10.000 \\cdot 1.21 = 12.100$. (Ese es el total en la cuenta).", "Restamos el capital: Interés = $12.100 - 10.000 = 2.100$. Se ganaron $2.100 puros."]}
    ],
    "errores_frecuentes": ["Responder con el Monto Final cuando se pregunta por 'los intereses'.", "Tratar de usar la fórmula $I = C \\cdot i \\cdot t$ (que es solo para interés simple)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGAN-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Para calcular matemáticamente la 'ganancia pura' (Interés) en un régimen de interés compuesto, el procedimiento lógico es: (v{i})", "choices": ["A) Calcular el Monto Final usando la potencia y luego restarle el Capital Inicial.", "B) Multiplicar el Capital Inicial por la Tasa y por el Tiempo.", "C) Dividir el Monto Final por el Capital Inicial.", "D) Restar la Tasa de interés al Monto Final."], "correct_answer": "A) Calcular el Monto Final usando la potencia y luego restarle el Capital Inicial.", "solution_steps": "No hay fórmula directa corta para el interés compuesto, se saca por diferencia $M - C$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTGAN-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Qué expresión factorizada representa la cantidad de intereses ganados ($I$) en un sistema de interés compuesto?", "choices": ["A) $C \\cdot [ (1+i)^t - 1 ]$", "B) $C \\cdot i \\cdot t$", "C) $C \\cdot (1+i)^t$", "D) $(C+i)^t - 1$"], "correct_answer": "A) $C \\cdot [ (1+i)^t - 1 ]$", "solution_steps": "Proviene de $C(1+i)^t - C$. Al factorizar la C, queda $[(1+i)^t - 1]$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGAN-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si inviertes $\$20.000$ en un banco y tras unos años retiras un cheque total por $\$25.500$, el interés compuesto que ganaste fue de $\$5.500$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$I = M - C = 25.500 - 20.000 = 5.500$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGAN-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un fondo de inversión capta $\$2.000.000$ de un cliente bajo un interés compuesto anual del $5\\%$. Al final del tercer año, el cliente decide cerrar la cuenta y solicita que le transfieran únicamente las ganancias obtenidas, dejando el capital inicial intacto. ¿Qué expresión determina el monto exacto de la transferencia que recibirá el cliente? (v{i})", "choices": ["A) $2.000.000 \\cdot (1.05)^3 - 2.000.000$", "B) $2.000.000 \\cdot (1.05)^3$", "C) $2.000.000 \\cdot 0.05 \\cdot 3$", "D) $2.000.000 \\cdot (0.05)^3$"], "correct_answer": "A) $2.000.000 \\cdot (1.05)^3 - 2.000.000$", "solution_steps": "Las 'ganancias obtenidas' son el interés puro. Es decir, $M - C$. La expresión correcta es $C(1+i)^t - C$.", "paes_style": True})

# 3. MODELO_EXPONENCIAL (Interés Compuesto)
sid3 = "MAT.NUM.INTERES_COMPUESTO.MODELO_EXPONENCIAL"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Reconocer y modelar situaciones financieras mediante funciones exponenciales.",
    "introduccion": "Las matemáticas tienen patrones. Cuando sumas lo mismo cada vez, haces una escalera recta (lineal). Cuando multiplicas por lo mismo cada vez, construyes un cohete hacia el cielo (exponencial). Así crece el interés compuesto.",
    "resumen": "La fórmula del interés compuesto $M(t) = C \\cdot (1+i)^t$ es una función exponencial $f(x) = a \\cdot b^x$. El capital inicial '$C$' es el valor inicial ($a$), y el factor $(1+i)$ es la base de crecimiento ($b$).",
    "explicacion": "En la PAES a menudo no te piden calcular dinero, sino **identificar el tipo de modelo matemático**.\n\n- Interés Simple $\\rightarrow$ Suma constante $\\rightarrow$ **Modelo Lineal** (Línea recta).\n- Interés Compuesto $\\rightarrow$ Multiplicación constante por $(1+i)$ $\\rightarrow$ **Modelo Exponencial** (Curva).\n\nSi analizamos la fórmula $M(t) = C \\cdot (1+i)^t$ como una función:\n- La variable independiente (la $x$) es el tiempo $t$, y está ubicada en el **exponente**.\n- Por lo tanto, el dinero crece de forma exponencial. \n- Como la base $(1+i)$ siempre es mayor que $1$ (porque la tasa es positiva), es una función exponencial de **crecimiento** (la curva va hacia arriba).",
    "procedimiento": ["Paso 1: Identifica si el problema describe un crecimiento donde los intereses se capitalizan.", "Paso 2: Si hay capitalización, asocia inmediatamente la situación a un modelo exponencial.", "Paso 3: Construye la función: $f(x) = Capital \\cdot (Factor)^x$."],
    "ejemplos": [
        {"titulo": "Deuda de tarjeta", "enunciado": "Una persona debe $100.000 en su tarjeta, la cual cobra 3% de interés compuesto mensual. Modela su deuda total en función de los meses 'x'.", "solucion_pasos": ["Capital = 100.000. Tasa = 0.03. Factor = 1.03.", "La variable tiempo es 'x'.", "La función exponencial es $f(x) = 100.000 \\cdot (1.03)^x$."]}
    ],
    "errores_frecuentes": ["Creer que la función es cuadrática porque tiene un exponente (las cuadráticas tienen el 2 fijo como exponente, las exponenciales tienen la variable 'x' en el exponente).", "Asignar un modelo lineal al interés compuesto."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODEXP-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde el punto de vista del modelamiento matemático, una cuenta de ahorros que opera con interés compuesto y no recibe nuevos depósitos describe un crecimiento del tipo: (v{i})", "choices": ["A) Exponencial.", "B) Lineal.", "C) Cuadrático.", "D) Logarítmico."], "correct_answer": "A) Exponencial.", "solution_steps": "El interés compuesto se basa en potencias donde la variable es el tiempo, lo que define una función exponencial.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MODEXP-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la función exponencial de interés compuesto $M(t) = C \\cdot (1+i)^t$, la variable independiente '$t$' se encuentra ubicada en:", "choices": ["A) El exponente.", "B) La base.", "C) El coeficiente.", "D) El denominador."], "correct_answer": "A) El exponente.", "solution_steps": "Por eso se llama exponencial, la variable de tiempo es el exponente.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODEXP-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La deuda de un crédito con interés compuesto mensual del $2\\%$ inicial de $\$50.000$ se modela con la función $f(x) = 50.000 \\cdot (1.02)^x$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Sí, C=50.000, factor=1.02, exponente variable x.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODEXP-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"El valor de un terreno de alta plusvalía aumenta su valor comercial a una tasa compuesta del $12\\%$ anual. Si hoy el terreno está avaluado en $\$80.000.000$, ¿qué función $V(t)$ permite proyectar el valor del terreno en un tiempo de '$t$' años? (v{i})", "choices": ["A) $V(t) = 80.000.000 \\cdot (1.12)^t$", "B) $V(t) = 80.000.000 \\cdot (0.12)^t$", "C) $V(t) = 80.000.000 + (1.12)^t$", "D) $V(t) = 80.000.000 \\cdot (1 + 0.12t)$"], "correct_answer": "A) $V(t) = 80.000.000 \\cdot (1.12)^t$", "solution_steps": "Factor = $1 + 0.12 = 1.12$. Función Exponencial: $C \\cdot (\text{factor})^t$. Opción D es modelo lineal (simple).", "paes_style": True})

# 4. TASA_PERIODICA (Interés Compuesto)
sid4 = "MAT.NUM.INTERES_COMPUESTO.TASA_PERIODICA"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Calcular la tasa periódica cuando la tasa nominal y el período de capitalización no coinciden.",
    "introduccion": "Los bancos son astutos. Te dicen 'Tasa de 12% anual', pero luego en letra chica agregan 'capitalizable mensualmente'. ¿Significa que te cobran 12% cada mes? No. Significa que fraccionan ese 12% en pequeñas cuotas mensuales.",
    "resumen": "Si la tasa es 'Anual capitalizable Mensualmente', debes dividir la tasa anual en 12 (meses) para obtener la tasa real de cada período ($i_p$). Si es bimestral, divides en 6. Si es semestral, divides en 2.",
    "explicacion": "En interés compuesto puro, la tasa debe coincidir con los períodos de tiempo en la fórmula. Pero los bancos suelen publicitar una **Tasa Anual Nominal (TAN)** acompañada de un período de capitalización distinto (ej. mensual).\n\nPara aplicar la fórmula $M = C(1+i)^t$, la tasa $i$ debe ser la **Tasa Periódica**.\n\n**¿Cómo se calcula?**\nDivide la Tasa Nominal por la cantidad de períodos que hay en un año:\n- Si dice 'Capitalizable mensualmente': $i_p = \\text{Tasa Anual} / 12$.\n- Si dice 'Capitalizable semestralmente': $i_p = \\text{Tasa Anual} / 2$.\n- Si dice 'Capitalizable trimestralmente': $i_p = \\text{Tasa Anual} / 4$.\n\nEjemplo: Un $24\\%$ anual capitalizable mensualmente, significa que cada mes te aplicarán un $24\\% / 12 = 2\\%$ mensual. Usarás $i = 0.02$ en la fórmula.",
    "procedimiento": ["Paso 1: Lee la 'letra chica' para ver la frecuencia de capitalización.", "Paso 2: Divide la tasa anual dada por el número de esos períodos que caben en un año.", "Paso 3: Esa tasa fraccionada es la que debes transformar a decimal para usar en $(1+i)$."],
    "ejemplos": [
        {"titulo": "Capitalización Trimestral", "enunciado": "Un banco ofrece un 16% de interés anual capitalizable trimestralmente. ¿Cuál es la tasa periódica que se usa en la fórmula?", "solucion_pasos": ["Un año tiene 4 trimestres (3 meses x 4 = 12).", "Tasa periódica = $16\\% / 4 = 4\\%$ trimestral.", "En la fórmula usarás $i = 0.04$."]}
    ],
    "errores_frecuentes": ["Dividir por 3 cuando dice trimestral (Trimestre son 3 meses, pero hay 4 trimestres en el año, se divide por 4).", "Usar el 16% directamente en la fórmula como si fuera anual, ignorando la capitalización."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAPER-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si un crédito tiene una tasa de interés del $X\\%$ anual con 'capitalización bimestral', ¿entre qué número se debe dividir la tasa $X$ para obtener la tasa periódica de cada ciclo? (v{i})", "choices": ["A) Entre 6.", "B) Entre 2.", "C) Entre 12.", "D) Entre 4."], "correct_answer": "A) Entre 6.", "solution_steps": "Un bimestre dura 2 meses. En un año de 12 meses, caben 6 bimestres.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TASAPER-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Una tasa del $12\\%$ anual capitalizable mensualmente equivale a una tasa efectiva en cada período del:", "choices": ["A) $1\\%$ mensual.", "B) $12\\%$ mensual.", "C) $0.1\\%$ mensual.", "D) $2\\%$ mensual."], "correct_answer": "A) $1\\%$ mensual.", "solution_steps": "$12\\% / 12$ meses = $1\\%$ cada mes.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAPER-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si la tasa es $10\\%$ anual capitalizable semestralmente, el factor de crecimiento a usar en la fórmula es $1.05$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$10\\% / 2$ semestres = $5\\%$ semestral. Factor $1 + 0.05 = 1.05$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TASAPER-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un ahorrante deposita $\$2.500.000$ en un banco que le ofrece una tasa de interés del $12\\%$ anual capitalizable trimestralmente. Si mantiene su dinero allí por un total de $3$ años, ¿qué expresión matemática permite calcular el dinero exacto que retirará? (v{i})", "choices": ["A) $2.500.000 \\cdot (1.03)^{12}$", "B) $2.500.000 \\cdot (1.12)^3$", "C) $2.500.000 \\cdot (1.03)^3$", "D) $2.500.000 \\cdot (1.04)^{12}$"], "correct_answer": "A) $2.500.000 \\cdot (1.03)^{12}$", "solution_steps": "La tasa periódica es $12\\% / 4 = 3\\% = 0.03$. El factor es $1.03$. El tiempo total son $3$ años $\\times 4 = 12$ trimestres. Por ende es a la potencia 12.", "paes_style": True})

# 5. NUMERO_PERIODOS (Interés Compuesto)
sid5 = "MAT.NUM.INTERES_COMPUESTO.NUMERO_PERIODOS"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Determinar el número total de períodos (exponente $t$) en operaciones con diferentes frecuencias de capitalización.",
    "introduccion": "¿Qué pasa si guardas plata por 5 años, pero el banco te paga los intereses cada mes? No puedes poner un '5' en la fórmula. Tienes que pensar cuántas veces pasará el camión de los intereses en total.",
    "resumen": "El exponente $t$ representa el 'número total de veces que se capitaliza' (las veces que la bola de nieve da la vuelta). Se calcula multiplicando los años de la inversión por la cantidad de períodos en un año.",
    "explicacion": "Al igual que tuvimos que ajustar la tasa, **debemos ajustar el tiempo** en la fórmula $M = C(1+i)^t$.\n\n- La letra $t$ NO significa necesariamente 'años'. Significa **Cantidad Total de Períodos**.\n- Si la inversión dura **3 años**, pero la cuenta es capitalizable **mensualmente**, significa que el interés se suma 12 veces por año.\n- ¿Cuántas veces se sumará el interés en total durante los 3 años?\n$$t = 3 \\text{ años} \\cdot 12 \\text{ meses/año} = 36 \\text{ períodos mensules}.$$\n\nEn la PAES, la clave está en que la tasa periódica ($i_p$) y el exponente total de tiempo ($t$) DEBEN estar en la misma frecuencia de tiempo.",
    "procedimiento": ["Paso 1: Identifica la duración total de la inversión en años.", "Paso 2: Lee la frecuencia de capitalización (ej. Semestral).", "Paso 3: Multiplica los años por cuántos periodos hay en un año (ej. $x 2$ para semestres).", "Paso 4: El resultado será el número entero que pondrás como exponente."],
    "ejemplos": [
        {"titulo": "Contando los trimestres", "enunciado": "Una inversión a 5 años plazo se capitaliza trimestralmente. ¿Cuál será el exponente en la fórmula?", "solucion_pasos": ["Tiempo en años = 5.", "En un año hay 4 trimestres.", "Total de periodos (exponente t) = $5 \\cdot 4 = 20$.", "El exponente a usar es 20."]}
    ],
    "errores_frecuentes": ["Poner directamente los 'años' como exponente sin fijarse en la capitalización.", "Confundir trimestral (multiplicar por 4) con cuatrimestral (multiplicar por 3)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PERIODOS-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la fórmula del interés compuesto $M = C(1+i)^t$, si la tasa es capitalizable semestralmente y la inversión dura $A$ años, ¿qué valor debe tomar el exponente '$t$'? (v{i})", "choices": ["A) $2 \\cdot A$", "B) $A / 2$", "C) $A$", "D) $6 \\cdot A$"], "correct_answer": "A) $2 \\cdot A$", "solution_steps": "Hay 2 semestres en un año, así que en A años habrán $2 \\cdot A$ semestres totales.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PERIODOS-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si una operación financiera dura $4$ años completos y tiene una capitalización mensual, ¿cuántos ciclos de capitalización (exponente $t$) existirán en total?", "choices": ["A) $48$", "B) $4$", "C) $24$", "D) $12$"], "correct_answer": "A) $48$", "solution_steps": "$4$ años $\\times 12$ meses = $48$ ciclos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PERIODOS-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si inviertes dinero por $2$ años con capitalización bimestral, el exponente que debes usar en la fórmula es $12$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "En un año hay 6 bimestres. En 2 años, hay $2 \\cdot 6 = 12$ bimestres totales.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PERIODOS-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una Pyme pide un préstamo para expandir su negocio por $\$15.000.000$. El banco se lo otorga a una tasa de interés del $18\\%$ anual con capitalización cuatrimestral. El plazo del préstamo es de $4$ años. ¿Cuál es el exponente y la base de la potencia que modelará la deuda final de esta Pyme? (v{i})", "choices": ["A) Base $1.06$, exponente $12$.", "B) Base $1.18$, exponente $4$.", "C) Base $1.045$, exponente $16$.", "D) Base $1.06$, exponente $4$."], "correct_answer": "A) Base $1.06$, exponente $12$.", "solution_steps": "Cuatrimestral significa cada 4 meses (hay 3 al año). Tasa periódica: $18\\% / 3 = 6\\%$ (Base $1.06$). Exponente: $4$ años $\\times 3$ cuatrimestres/año = $12$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 16...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 16...")
    append_jsonl("mat-num-razones-banco-gen-16", EJERCICIOS)
    print("Creado mat-num-razones-banco-gen-16.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
