# scratch/build_alg_b0302_t1.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. CONCEPTO_TRADUCCION
sid1 = "MAT.ALG.LENGUAJE_OPERACIONES.CONCEPTO_TRADUCCION"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Comprender la función del lenguaje algebraico como traductor de lenguaje natural.",
    "introduccion": "Imagina viajar a un país donde nadie habla tu idioma. Necesitarías un traductor. El álgebra es exactamente eso: un traductor entre el mundo de las palabras cotidianas y el estricto mundo de las matemáticas.",
    "resumen": "El **Lenguaje Algebraico** es un sistema de símbolos y letras que permite traducir expresiones y problemas del **lenguaje común (natural)** a un formato matemático estructurado para poder operarlas lógicamente.",
    "explicacion": "¿Para qué sirve traducir?\nSi te digo: 'Un número cualquiera más su mitad equivale a veinte', intentar adivinar el número mentalmente puede ser difícil. Pero si lo traducimos al idioma de las matemáticas, obtenemos la ecuación: $x + \\frac{x}{2} = 20$.\n\nUna vez que el problema está en lenguaje algebraico, deja de ser una adivinanza y se convierte en un mecanismo. Las letras asumen el rol de 'variables' o 'incógnitas', y las palabras operativas (más, de, por, disminuido) se convierten en signos matemáticos ( $+$, $\\times$, $-$).",
    "procedimiento": ["Paso 1: Lee el enunciado completo en lenguaje natural para entender el contexto.", "Paso 2: Identifica las 'entidades desconocidas' y asígnales una letra (generalmente x, y, z).", "Paso 3: Identifica los verbos y palabras de acción ('aumenta', 'equivale a', 'el doble') y asócialos con sus operaciones matemáticas correspondientes."],
    "ejemplos": [
        {"titulo": "El primer paso de la traducción", "enunciado": "Traduce la frase 'Un número desconocido' y la frase 'El resultado es cinco'.", "solucion_pasos": ["'Un número desconocido' se traduce simplemente eligiendo una letra, por ejemplo: x.", "'El resultado es' se traduce como el signo de igualdad: =.", "'cinco' se traduce como el número: 5.", "Combinando (si la frase fuera 'un número es cinco'): x = 5."]}
    ],
    "errores_frecuentes": ["Traducir palabra por palabra en el mismo orden que el lenguaje natural, ignorando las reglas gramaticales matemáticas (ej. escribir $x 2$ en vez de $2x$).", "Creer que el lenguaje algebraico siempre obliga a resolver una ecuación; a veces, solo sirve para modelar la situación sin llegar a un resultado final."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CTRAD-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el objetivo primordial del lenguaje algebraico cuando se aplica en la resolución de problemas descritos en palabras? (v{i})", "choices": ["A) Traducir el problema desde el lenguaje natural (verbal) a una estructura matemática formal de símbolos y operaciones para facilitar su análisis y resolución.", "B) Ocultar el verdadero valor de los números detrás de letras para hacer el problema más difícil.", "C) Eliminar la necesidad de utilizar números en las matemáticas, reemplazándolos totalmente por letras del alfabeto.", "D) Demostrar teoremas geométricos sin usar dibujos."], "correct_answer": "A) Traducir el problema desde el lenguaje natural (verbal) a una estructura matemática formal de símbolos y operaciones para facilitar su análisis y resolución.", "solution_steps": "El lenguaje algebraico es fundamentalmente una herramienta de modelado y traducción. Permite estructurar la lógica verbal en leyes matemáticas.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CTRAD-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En el proceso de traducción algebraica, ¿qué función cumple la asignación de una letra, comúnmente la '$x$'?", "choices": ["A) Actúa como un marcador de posición (variable o incógnita) para representar una cantidad específica cuyo valor numérico aún es desconocido.", "B) Representa exclusivamente la operación de multiplicación.", "C) Representa siempre al número uno.", "D) Indica que el problema es irresoluble."], "correct_answer": "A) Actúa como un marcador de posición (variable o incógnita) para representar una cantidad específica cuyo valor numérico aún es desconocido.", "solution_steps": "La letra x toma el lugar del 'número desconocido' mencionado en la historia.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CTRAD-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La frase 'un número cualquiera' siempre debe traducirse obligatoriamente con la letra '$x$' bajo las reglas del lenguaje algebraico formal?", "choices": [], "correct_answer": "Falso", "solution_steps": "Aunque 'x' es la convención más común, puedes usar absolutamente cualquier letra ($a, y, z, m$) para representar un número cualquiera.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CTRAD-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un arquitecto describe la longitud de una viga diciendo: 'La medida total es igual a un largo desconocido más tres metros'. Su asistente, intentando modelar esto en el software de cálculo, teclea: $x + 3$. Sin embargo, el programa arroja un error de sintaxis al evaluar la expresión. ¿Qué elemento de la traducción gramatical omitió el asistente para que sea una ecuación completa? (v{i})", "choices": ["A) Omitió traducir la frase 'La medida total es igual a', es decir, debió asignar una segunda variable y el signo igual (por ejemplo, $L = x + 3$).", "B) Omitió ponerle paréntesis a la variable $x$.", "C) Se equivocó de letra; debió usar la letra V de viga.", "D) Tradujo mal la palabra 'más', debía usar el signo de multiplicación."], "correct_answer": "A) Omitió traducir la frase 'La medida total es igual a', es decir, debió asignar una segunda variable y el signo igual (por ejemplo, $L = x + 3$).", "solution_steps": "La traducción de 'es igual a' requiere el signo '$=$' y asignar lo que está a la izquierda (la medida total, $L$).", "paes_style": True})

# 2. SUMA_CANTIDADES
sid2 = "MAT.ALG.LENGUAJE_OPERACIONES.SUMA_CANTIDADES"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Traducir la suma de dos o más cantidades desconocidas desde el lenguaje natural.",
    "introduccion": "¿Cómo escribes matemáticamente que tienes manzanas y además naranjas, sin saber cuántas hay de cada una? Usas la suma algebraica.",
    "resumen": "La **Suma de Cantidades** en lenguaje algebraico se representa utilizando el signo de adición ($+$) entre variables distintas.",
    "explicacion": "Palabras clave que indican suma:\n- Más\n- Sumado con\n- Añadido a\n- Agregado a\n- El total de\n- Excedido en\n\nEjemplos de traducción:\n- 'La suma de dos números distintos': $x + y$\n- 'Un número sumado a otro número diferente': $a + b$\n- 'El total de la edad de Juan y la edad de María': $J + M$\n\n*Nota vital:* Si el enunciado dice 'la suma de dos números' (sin especificar si son iguales o distintos), por convención rigurosa asumimos que **son distintos** y usamos letras diferentes ($x+y$). Si fueran el mismo número, diría 'la suma de un número con sí mismo' ($x+x$).",
    "procedimiento": ["Paso 1: Identifica las cantidades desconocidas en la frase.", "Paso 2: Si el problema sugiere que las cantidades son (o pueden ser) diferentes, usa letras diferentes para cada una (x, y).", "Paso 3: Une las letras con un signo más (+)."],
    "ejemplos": [
        {"titulo": "Uniendo fuerzas", "enunciado": "Traduce algebraicamente: 'El peso de un auto más el peso de una camioneta'.", "solucion_pasos": ["Peso del auto es una cantidad desconocida: a.", "Peso de la camioneta es otra cantidad desconocida: c.", "La palabra 'más' indica suma.", "Traducción final: a + c."]}
    ],
    "errores_frecuentes": ["Traducir 'la suma de dos números' como $x+x$. (A menos que te digan que los números son idénticos, siempre asume que son diferentes: $x+y$).", "Confundir 'la suma de' con 'un número más un número fijo', usando una constante en vez de dos variables."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMA-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Cuando un problema verbal pide expresar algebraicamente 'la suma de dos números', y no ofrece información adicional sobre ellos, ¿qué convención de traducción se debe aplicar? (v{i})", "choices": ["A) Asumir que pueden ser números diferentes y representarlos con dos letras distintas, como $x + y$.", "B) Asumir que son el mismo número y representarlos como $x + x$.", "C) Reemplazarlos por números al azar como $2 + 3$.", "D) Escribir siempre $xy$, porque los números en álgebra no se suman."], "correct_answer": "A) Asumir que pueden ser números diferentes y representarlos con dos letras distintas, como $x + y$.", "solution_steps": "Al no especificar que los números son iguales, lo general (y por lo tanto lo matemáticamente riguroso) es tratarlos como variables independientes usando letras distintas.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SUMA-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Indica cuál es la traducción correcta al lenguaje algebraico de la frase: 'La suma de tres números distintos'.", "choices": ["A) $a + b + c$", "B) $3x$", "C) $x + x + x$", "D) $abc$"], "correct_answer": "A) $a + b + c$", "solution_steps": "Tres números distintos exigen el uso de tres variables diferentes sumándose. Por ende, $a+b+c$ es la respuesta correcta.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMA-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La frase verbal 'el total del dinero de Carlos y el dinero de Laura' se traduce algebraicamente como $C \\cdot L$, indicando que sus fondos operan en conjunto?", "choices": [], "correct_answer": "Falso", "solution_steps": "La palabra 'total de A y B' en el contexto de reunir cantidades implica una suma ($C + L$), no una multiplicación.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMA-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un contador modela las finanzas de una pequeña tienda. Las ventas del día de ayer fueron un monto desconocido, y las ventas de hoy son un monto distinto y también desconocido. El banco le pide registrar la 'venta acumulada de ambos días'. ¿Cuál es la expresión algebraica exacta que representa ese requerimiento bancario? (v{i})", "choices": ["A) $x + y$", "B) $2x$", "C) $xy$", "D) $x + 2$"], "correct_answer": "A) $x + y$", "solution_steps": "Ayer fue un monto ($x$). Hoy es un monto distinto ($y$). La venta acumulada (total) es la suma de ambos: $x + y$. No es $2x$ porque los montos no son necesariamente iguales.", "paes_style": True})

# 3. NUMERO_AUMENTADO
sid3 = "MAT.ALG.LENGUAJE_OPERACIONES.NUMERO_AUMENTADO"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Traducir el concepto de aumentar un número desconocido en una cantidad fija o variable.",
    "introduccion": "¿Qué pasa si ya tienes algo guardado en una caja, y le agregas exactamente 5 monedas más? Aumentaste tu cantidad. Esa es una de las traducciones más comunes en álgebra.",
    "resumen": "Un **Número Aumentado** es una expresión donde una variable (que representa el número original) se suma con otra cantidad, ya sea un valor fijo u otra variable.",
    "explicacion": "Palabras clave de aumento:\n- Aumentado en\n- Incrementado en\n- Más\n\nEjemplos clásicos:\n- 'Un número aumentado en ocho': $x + 8$\n- 'Cinco incrementado en un número': $5 + x$\n- 'La edad de Pedro aumentada en 10 años': $P + 10$\n\nEn la suma, el orden de los factores no altera el resultado (propiedad conmutativa), por lo que $x + 8$ es matemáticamente equivalente a $8 + x$.",
    "procedimiento": ["Paso 1: Identifica el 'sujeto' de la oración (el número inicial) y ponle una variable.", "Paso 2: Detecta la palabra clave 'aumentado', 'incrementado' o 'más'. Escribe el signo +.", "Paso 3: Identifica la cantidad de aumento y ponla a la derecha del signo más."],
    "ejemplos": [
        {"titulo": "Crecimiento de temperatura", "enunciado": "Traduce: 'La temperatura actual aumentada en quince grados'.", "solucion_pasos": ["Temperatura actual es la variable: T.", "Aumentada en: +.", "Quince grados es la constante: 15.", "Traducción: T + 15."]}
    ],
    "errores_frecuentes": ["Confundir 'aumentado en' con 'multiplicado por'. Traducir 'Un número aumentado en 5' como $5x$ en vez de $x + 5$.", "En problemas de edades, olvidar aumentar a todas las personas. (Ej: 'Dentro de 5 años', la edad de Juan será $J+5$ y la de Ana $A+5$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NAUM-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la traducción de enunciados algebraicos, ¿cuál es la diferencia fundamental entre la frase 'Un número aumentado en cinco' y la frase 'Un número cinco veces mayor'? (v{i})", "choices": ["A) 'Aumentado en cinco' implica la adición de una constante ($x + 5$), mientras que 'cinco veces mayor' implica la multiplicación de la variable por un coeficiente ($5x$).", "B) Ambas frases significan matemáticamente lo mismo ($x + 5$).", "C) Ambas frases significan matemáticamente lo mismo ($5x$).", "D) 'Aumentado en cinco' es una potencia ($x^5$) y 'cinco veces mayor' es una suma ($x+5$)."], "correct_answer": "A) 'Aumentado en cinco' implica la adición de una constante ($x + 5$), mientras que 'cinco veces mayor' implica la multiplicación de la variable por un coeficiente ($5x$).", "solution_steps": "La palabra 'aumentado en' requiere un incremento sumativo. 'Veces' requiere un factor multiplicativo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"NAUM-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona la expresión algebraica que traduce fielmente el texto: 'El salario actual de Martín incrementado en veinte mil pesos'. (Usa $S$ para el salario actual).", "choices": ["A) $S + 20000$", "B) $20000S$", "C) $S - 20000$", "D) $S + 20$"], "correct_answer": "A) $S + 20000$", "solution_steps": "Salario actual ($S$). Incrementado ($+$). Veinte mil ($20000$). Queda $S + 20000$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NAUM-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $12 + m$ traduce correctamente el enunciado 'doce incrementado por un número desconocido'?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "La base fija es doce ($12$). Se incrementa ($+$). El incremento es un número desconocido ($m$). Traduce perfectamente.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NAUM-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Para configurar la fórmula de un peaje dinámico, el ingeniero de sistemas recibe la instrucción: 'La tarifa base del automóvil debe ser aumentada en una tarifa variable según la cantidad de tráfico'. Si la tarifa base es $B$ y la tarifa por tráfico es $T$, ¿cómo debe programar el ingeniero la tarifa final ($F$) para no cobrar de más a los usuarios? (v{i})", "choices": ["A) $F = B + T$", "B) $F = B \\cdot T$", "C) $F = B + B^T$", "D) $F = B - T$"], "correct_answer": "A) $F = B + T$", "solution_steps": "La palabra 'aumentada en' exige una suma lineal directa entre la base y la variable. Si cobrara $B \\cdot T$, multiplicaría los montos causando tarifas exponenciales irreales.", "paes_style": True})

# 4. DIFERENCIA_CANTIDADES
sid4 = "MAT.ALG.LENGUAJE_OPERACIONES.DIFERENCIA_CANTIDADES"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Traducir la diferencia o resta entre dos cantidades algebraicas.",
    "introduccion": "Si tú mides 1.80m y tu amigo 1.70m, ¿cuál es la diferencia de altura? La respuesta la da la operación de resta. En álgebra, la diferencia compara la distancia entre dos variables.",
    "resumen": "La **Diferencia de Cantidades** se traduce utilizando el signo de sustracción ($-$). A diferencia de la suma, **el orden sí importa**, por lo que se debe respetar quién es el minuendo (el que va primero) y quién el sustraendo (el que resta).",
    "explicacion": "Palabras clave:\n- La diferencia entre\n- Menos\n- Restado a\n- Restado de\n\nEjemplos clásicos:\n- 'La diferencia entre dos números': $x - y$\n- 'El sueldo de Ana menos los gastos': $S - G$\n\n*La Trampa Mortal del Lenguaje:* Cuidado con el orden de la palabra 'restado de'.\n- 'Si a $x$ le restamos $5$' $\\rightarrow$ $x - 5$.\n- 'Si $5$ es restado DE un número $x$' $\\rightarrow$ el número inicial es $x$, por lo tanto la traducción es $x - 5$. ¡El que va después del 'DE' es el dueño de la cantidad principal!",
    "procedimiento": ["Paso 1: Identifica las variables involucradas.", "Paso 2: Lee atentamente para descubrir de quién es la cantidad inicial (quién va a sufrir la resta).", "Paso 3: Coloca esa cantidad inicial a la izquierda del signo menos (-), y la cantidad que se quita, a la derecha."],
    "ejemplos": [
        {"titulo": "El orden altera el producto", "enunciado": "Traduce algebraicamente: 'Seis restado de un número cualquiera'.", "solucion_pasos": ["La palabra 'de' nos dice que el 'número cualquiera' es nuestro punto de partida. Lo llamamos x.", "La cantidad 'seis' es lo que estamos quitando.", "Traducción correcta: x - 6. (Escribir 6 - x sería 'un número restado de seis')."]}
    ],
    "errores_frecuentes": ["Traducir en el mismo orden de lectura sin analizar. (Ej: 'Cinco restado de $x$' traducido equivocadamente como $5 - x$).", "Asumir que 'la diferencia' siempre será positiva; en álgebra abstracta $x - y$ puede dar resultados negativos."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFC-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En el lenguaje matemático, ¿por qué es crucial identificar correctamente la proposición 'restado de' frente a 'menos' al construir una expresión algebraica de diferencia? (v{i})", "choices": ["A) Porque la resta no posee la propiedad conmutativa; invertir el orden del minuendo y el sustraendo ($x-y$ vs $y-x$) altera completamente el valor de la expresión.", "B) Porque 'restado de' indica una división, mientras que 'menos' indica una resta convencional.", "C) Porque 'restado de' se usa exclusivamente para números enteros negativos.", "D) Porque 'restado de' indica que el resultado siempre será un número irracional."], "correct_answer": "A) Porque la resta no posee la propiedad conmutativa; invertir el orden del minuendo y el sustraendo ($x-y$ vs $y-x$) altera completamente el valor de la expresión.", "solution_steps": "Si traduces '3 restado de x' como 3 - x (está mal, es x - 3). Como la resta no es conmutativa, el error de traducción lleva a un error de cálculo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DIFC-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Identifica la traducción algebraica rigurosamente exacta para el siguiente enunciado: 'Un número $y$ restado de un número $x$'.", "choices": ["A) $x - y$", "B) $y - x$", "C) $x - x - y$", "D) $y - y - x$"], "correct_answer": "A) $x - y$", "solution_steps": "La palabra clave 'de' indica el punto de partida (minuendo). Partimos DE x, y le quitamos y. Resultado: $x - y$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFC-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La frase 'la diferencia entre dos números distintos' se traduce convencionalmente como $a - a$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Como son distintos, se deben usar letras diferentes, por ejemplo $a - b$. $a - a$ daría siempre cero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DIFC-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"En el examen de admisión, el problema plantea: 'Las ganancias líquidas de una empresa equivalen a sus costos fijos ($C$) restados de sus ingresos totales ($I$)'. Un estudiante apurado escribe la ecuación de ganancias como $G = C - I$ y entrega la prueba. ¿Qué consecuencia tendrá su error de traducción? (v{i})", "choices": ["A) Su modelo calculará pérdidas financieras constantes en lugar de ganancias, ya que invirtió el orden de la resta al no respetar la preposición 'de'.", "B) Ninguna, porque al igual que la suma, el orden de la resta no altera el resultado de las ganancias.", "C) Su modelo calculará una multiplicación entre costos e ingresos.", "D) El modelo fallará porque las variables C e I debieron sumarse para hallar ganancias líquidas."], "correct_answer": "A) Su modelo calculará pérdidas financieras constantes en lugar de ganancias, ya que invirtió el orden de la resta al no respetar la preposición 'de'.", "solution_steps": "El enunciado dice 'costos fijos (C) restados DE sus ingresos (I)'. Es decir, partimos de I, y quitamos C. La ecuación correcta era $G = I - C$. Al escribir $C - I$, calculó un número negativo (pérdida).", "paes_style": True})

# 5. NUMERO_DISMINUIDO
sid5 = "MAT.ALG.LENGUAJE_OPERACIONES.NUMERO_DISMINUIDO"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Traducir expresiones donde una cantidad se ve reducida en un valor específico.",
    "introduccion": "Si a un estanque de agua se le hace un agujero, la cantidad de agua disminuye. Al igual que el concepto de 'aumentado', el álgebra tiene una traducción directa para cuando perdemos cantidad.",
    "resumen": "Un **Número Disminuido** se traduce tomando la variable inicial y aplicándole una sustracción ($-$) con la cantidad que se pierde o disminuye.",
    "explicacion": "Palabras clave:\n- Disminuido en\n- Reducido en\n- Rebajado en\n\nEjemplos:\n- 'Un número disminuido en quince': $x - 15$\n- 'El precio de la camisa reducido en un descuento desconocido': $P - d$\n- 'Diez disminuido en un número': $10 - x$\n\nNuevamente, el orden es ley. Si la oración dice 'un número disminuido en siete', el número es el que sufre la pérdida, por lo tanto él va primero: $x - 7$.",
    "procedimiento": ["Paso 1: Identifica el objeto principal de la oración que va a sufrir la pérdida.", "Paso 2: Escribe la letra que lo representa.", "Paso 3: Escribe el signo de resta (-).", "Paso 4: Escribe la cantidad de reducción a la derecha del signo menos."],
    "ejemplos": [
        {"titulo": "Pérdida de peso", "enunciado": "Traduce algebraicamente: 'El peso de un paciente disminuido en 5 kilogramos'.", "solucion_pasos": ["El sujeto principal es el peso del paciente: P.", "Sufre una reducción: -.", "La reducción es de 5 kg: 5.", "Traducción completa: P - 5."]}
    ],
    "errores_frecuentes": ["Escribir la constante primero por inercia cuando se lee rápido. (Ej: 'un número disminuido en 8' traducido como $8 - x$).", "Confundir 'disminuido en' con 'disminuido a'. (Ej: 'El precio rebajado a la mitad' es una división $\\frac{x}{2}$, pero 'el precio rebajado en la mitad' es una resta $x - \\frac{x}{2}$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NDIS-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al traducir el enunciado verbal 'una variable disminuida en una constante', ¿qué estructura matemática lineal se debe construir? (v{i})", "choices": ["A) Un binomio de resta donde la variable es el minuendo (va a la izquierda) y la constante es el sustraendo (va a la derecha).", "B) Una división entre la constante y la variable.", "C) Un binomio de resta donde la constante va a la izquierda y la variable a la derecha.", "D) Una multiplicación con un signo negativo frente a la variable."], "correct_answer": "A) Un binomio de resta donde la variable es el minuendo (va a la izquierda) y la constante es el sustraendo (va a la derecha).", "solution_steps": "Como es la variable la que sufre la disminución, ella va primero ($x - k$).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"NDIS-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona la expresión que representa correctamente la frase: 'El número 100 disminuido en un valor desconocido $z$'.", "choices": ["A) $100 - z$", "B) $z - 100$", "C) $100z$", "D) $\\frac{100}{z}$"], "correct_answer": "A) $100 - z$", "solution_steps": "El punto de partida es el número fijo 100. Se le aplica la disminución de la variable z. Queda $100 - z$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NDIS-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si un enunciado dicta 'el precio de lista de un producto rebajado en $2000$ pesos', la traducción algebraica correcta asumiendo que el precio de lista es $P$, sería $2000 - P$?", "choices": [], "correct_answer": "Falso", "solution_steps": "El precio de lista (P) es la base que sufre la rebaja. La traducción correcta es $P - 2000$. Escribir $2000 - P$ significaría 'dos mil pesos rebajados por el precio del producto', lo cual carece de sentido comercial.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"NDIS-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un programador lee las reglas de negocio de una tienda: 'Si el cliente tiene código premium, el costo de despacho (representado por $D$) debe ser disminuido en su totalidad'. ¿Cuál es la representación matemática del nuevo costo de despacho para el cliente premium? (v{i})", "choices": ["A) $D - D = 0$", "B) $D - 1$", "C) $D / D = 1$", "D) $0 - D$"], "correct_answer": "A) $D - D = 0$", "solution_steps": "El valor inicial es D. Se le disminuye 'su totalidad', es decir, se le disminuye D. La expresión es $D - D$, lo cual resulta en un costo de despacho igual a 0.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 1 (MAT.ALG.B0302)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 1 (MAT.ALG.B0302)...")
    append_jsonl("mat-alg-lenguaje-banco-gen-1", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-1.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
