# scratch/build_alg_b0301_t6.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 11. POLINOMIO_HOMOGENEO
sid16 = "MAT.ALG.POLINOMIOS.POLINOMIO_HOMOGENEO"
RECURSOS.append({
    "semantic_id": sid16, "objetivo": "Identificar polinomios homogéneos donde todos los términos poseen idéntico grado absoluto.",
    "introduccion": "¿Alguna vez has visto un equipo de levantamiento de pesas donde todos levantan exactamente los mismos kilos? En álgebra, a ese equipo perfectamente equilibrado en peso se le llama Homogéneo.",
    "resumen": "Un **Polinomio Homogéneo** es aquel en el que **todos y cada uno de sus términos tienen exactamente el mismo grado absoluto**.",
    "explicacion": "Homo significa 'igual' o 'mismo'. Para saber si es homogéneo, debemos pesar (calcular el grado absoluto) de cada vagón por separado.\n- Polinomio: $x^3 + x^2y - xy^2 + y^3$\n  - Vagón 1 ($x^3$): Grado $3$.\n  - Vagón 2 ($x^2y$): Grado $2+1 = 3$.\n  - Vagón 3 ($-xy^2$): Grado $1+2 = 3$.\n  - Vagón 4 ($y^3$): Grado $3$.\nTodos los vagones pesan $3$. ¡Es un polinomio homogéneo de tercer grado!\n\nSi tan solo un término tuviera un grado distinto, la homogeneidad se rompe al instante.",
    "procedimiento": ["Paso 1: Calcula el grado absoluto (suma de exponentes de las letras) del primer término.", "Paso 2: Haz lo mismo con el segundo término.", "Paso 3: Continúa hasta el final.", "Paso 4: Si todos los resultados numéricos son idénticos, es Homogéneo."],
    "ejemplos": [
        {"titulo": "Prueba de equilibrio", "enunciado": "Determina si a^4 + a^2b^2 - b^4 es homogéneo.", "solucion_pasos": ["Término 1 (a^4): Grado 4.", "Término 2 (a^2b^2): Grado 2+2 = 4.", "Término 3 (-b^4): Grado 4.", "Todos tienen grado 4. Sí, es un polinomio homogéneo."]}
    ],
    "errores_frecuentes": ["Creer que 'homogéneo' significa que todos los términos deben tener la misma letra (eso sería tener una sola variable, no ser homogéneo).", "Olvidarse de sumar los exponentes ocultos ('1') y clasificar mal un término mixto, rompiendo falsamente la homogeneidad."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHOM-CONC-{i}", "semantic_id": sid16, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Según la clasificación estructural de los polinomios, ¿qué rasgo distintivo define a un polinomio como 'Homogéneo'? (v{i})", "choices": ["A) Que el grado absoluto (la suma de exponentes de las variables) es idéntico en todos y cada uno de sus términos.", "B) Que todos sus términos tienen coeficientes numéricos iguales.", "C) Que está formado exclusivamente por una sola variable.", "D) Que todos sus términos son positivos."], "correct_answer": "A) Que el grado absoluto (la suma de exponentes de las variables) es idéntico en todos y cada uno de sus términos.", "solution_steps": "La homogeneidad polinomial se refiere al equilibrio perfecto de grados absolutos a través de toda la expresión.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PHOM-REC-1", "semantic_id": sid16, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Identifica cuál de las siguientes expresiones algebraicas corresponde a un Polinomio Homogéneo.", "choices": ["A) $x^5 - 2x^3y^2 + 7xy^4 - y^5$", "B) $x^3 + y^2 + z$", "C) $a^2 + 2ab + b^3$", "D) $m^4 + m^3n + m^2n^3$"], "correct_answer": "A) $x^5 - 2x^3y^2 + 7xy^4 - y^5$", "solution_steps": "Evaluamos A: 5, 3+2=5, 1+4=5, 5. Todos pesan 5. B: 3,2,1. C: 2,2,3. D: 4,4,5.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHOM-PROC-{i}", "semantic_id": sid16, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿El binomio $x^2y - xy^2$ es homogéneo, ya que ambos términos poseen grado absoluto tres?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Término 1: x(2)+y(1)=3. Término 2: x(1)+y(2)=3. Tienen el mismo grado absoluto total. Es homogéneo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHOM-PAES-{i}", "semantic_id": sid16, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En el diseño de curvas aerodinámicas, las ecuaciones deben ser 'homogéneas de grado $4$' para no alterar la escala tridimensional. Un ingeniero propone la fórmula $F(x,y) = 3x^4 - 2x^2y^2 + 5y^4 - 10$. El sistema arroja un error de escala. ¿Por qué la fórmula no es homogénea? (v{i})", "choices": ["A) Porque contiene el término independiente $-10$, el cual tiene grado $0$, rompiendo la homogeneidad de grado $4$ del resto de los términos.", "B) Porque el término $2x^2y^2$ tiene grado $2$, no $4$.", "C) Porque los coeficientes numéricos $3, -2, 5, -10$ son diferentes entre sí.", "D) Porque una fórmula homogénea no puede tener signos negativos."], "correct_answer": "A) Porque contiene el término independiente $-10$, el cual tiene grado $0$, rompiendo la homogeneidad de grado $4$ del resto de los términos.", "solution_steps": "T1(4), T2(4), T3(4). Todo iba bien hasta el -10, que es T4(0). Un solo término con grado distinto destruye la homogeneidad.", "paes_style": True})

# 12. POLINOMIO_HETEROGENEO
sid17 = "MAT.ALG.POLINOMIOS.POLINOMIO_HETEROGENEO"
RECURSOS.append({
    "semantic_id": sid17, "objetivo": "Identificar polinomios heterogéneos donde existe disparidad en el grado absoluto de sus términos.",
    "introduccion": "En el mundo real, los equipos suelen estar formados por personas de diferentes pesos y estaturas. En el álgebra, la inmensa mayoría de los polinomios son así: diversos y desiguales.",
    "resumen": "Un **Polinomio Heterogéneo** es aquel en el que **sus términos NO tienen el mismo grado absoluto**. Basta con que un solo término tenga un grado distinto para que todo el polinomio sea heterogéneo.",
    "explicacion": "Hetero significa 'diferente' o 'desigual'. \n- Polinomio: $x^3 - 5x^2 + 6$\n  - Vagón 1 ($x^3$): Grado 3.\n  - Vagón 2 ($-5x^2$): Grado 2.\n  - Vagón 3 ($+6$): Grado 0.\nLos grados son 3, 2 y 0. Son diferentes. Por tanto, es un polinomio heterogéneo.\n\nCasi todos los polinomios de una sola variable que incluyen un término numérico suelto (independiente) son heterogéneos automáticamente, a menos que consten *solamente* del término independiente.",
    "procedimiento": ["Paso 1: Calcula el grado absoluto de cada término.", "Paso 2: Compara los resultados.", "Paso 3: En el momento en que encuentres al menos dos términos con grados diferentes, puedes detenerte y clasificarlo como Heterogéneo."],
    "ejemplos": [
        {"titulo": "Buscando la diferencia", "enunciado": "Clasifica el polinomio a^2b + ab^2 - a^3b^2.", "solucion_pasos": ["T1: a^2b (Grado 3).", "T2: ab^2 (Grado 3).", "T3: -a^3b^2 (Grado 5).", "T1 y T2 son iguales, pero T3 es diferente. Por ende, es Heterogéneo."]}
    ],
    "errores_frecuentes": ["Creer que heterogéneo significa que tiene letras distintas (variables diferentes). La heterogeneidad se mide en el grado total, no en la variedad de letras.", "Revisar solo los dos primeros términos, ver que coinciden, y asumir que es homogéneo sin revisar hasta el final."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHET-CONC-{i}", "semantic_id": sid17, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuándo se clasifica una expresión algebraica como un 'Polinomio Heterogéneo'? (v{i})", "choices": ["A) Cuando no todos sus términos poseen el mismo grado absoluto (basta una desigualdad para ser heterogéneo).", "B) Cuando está compuesto por dos o más variables (letras) diferentes en su estructura.", "C) Cuando sus coeficientes son números fraccionarios o irracionales.", "D) Cuando carece de un término independiente."], "correct_answer": "A) Cuando no todos sus términos poseen el mismo grado absoluto (basta una desigualdad para ser heterogéneo).", "solution_steps": "Heterogéneo indica variedad en el 'peso' de los términos. Si no son todos idénticos en grado, es heterogéneo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PHET-REC-1", "semantic_id": sid17, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Analiza los siguientes polinomios e identifica cuál es estrictamente Heterogéneo.", "choices": ["A) $4x^3 - 5x^2 + 8$", "B) $x^4 - y^4$", "C) $a^2b + ab^2$", "D) $5x^3y - 2xy^3$"], "correct_answer": "A) $4x^3 - 5x^2 + 8$", "solution_steps": "A tiene grados 3, 2 y 0 (Heterogéneo). B tiene grados 4 y 4 (Homogéneo). C tiene 3 y 3. D tiene 4 y 4.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHET-PROC-{i}", "semantic_id": sid17, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El polinomio $x^5 - y^5 + z^5$ es un polinomio heterogéneo debido a que está conformado por tres letras diferentes?", "choices": [], "correct_answer": "Falso", "solution_steps": "La heterogeneidad no depende de las letras. Los términos tienen grado 5, 5 y 5. Al tener grados idénticos, es Homogéneo, sin importar que usen letras diferentes.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PHET-PAES-{i}", "semantic_id": sid17, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un sistema de ecuaciones requiere una lista de 'Polinomios Heterogéneos' para entrenar una red neuronal en reconocimiento de asimetrías. Un programador carga el polinomio $8x^2y^2 - 4x^3y + 2xy^3$. La red lo expulsa del entrenamiento. ¿Por qué el polinomio fue rechazado? (v{i})", "choices": ["A) Porque todos sus términos suman exactamente grado $4$ ($2+2, 3+1, 1+3$), convirtiéndolo en un polinomio homogéneo.", "B) Porque tiene más de dos letras.", "C) Porque falta el término con grado cero.", "D) Porque los coeficientes son todos números pares."], "correct_answer": "A) Porque todos sus términos suman exactamente grado $4$ ($2+2, 3+1, 1+3$), convirtiéndolo en un polinomio homogéneo.", "solution_steps": "Al analizar los grados de los términos vemos que todos pesan 4. No hay asimetría de grados. Al ser homogéneo, incumple la regla del sistema.", "paes_style": True})

# 13. POLINOMIO_NULO
sid18 = "MAT.ALG.POLINOMIOS.POLINOMIO_NULO"
RECURSOS.append({
    "semantic_id": sid18, "objetivo": "Comprender el concepto de polinomio nulo y su condición de coeficientes iguales a cero.",
    "introduccion": "Imagina un tren fantasma: ves los vagones, pero adentro no hay nada ni nadie. En álgebra, existe un polinomio que aparentemente tiene estructura, pero no vale absolutamente nada.",
    "resumen": "Un **Polinomio Nulo** es aquel en el cual **todos y cada uno de sus coeficientes numéricos son iguales a cero**. Su valor numérico será siempre cero, sin importar qué valores tomen sus variables.",
    "explicacion": "Se denota convencionalmente como $P(x) \\equiv 0$.\nUna forma de escribirlo explícitamente sería:\n$P(x) = 0x^3 + 0x^2 + 0x + 0$\n\nAunque visualmente parezca de tercer grado, como todo está multiplicado por cero, el polinomio completo colapsa a la nada. \n\n*Nota teórica importante:* Como todos los términos desaparecen, el polinomio nulo carece de grado definido. No se dice que es de grado cero (porque eso sería un número como el $5$), directamente **no tiene grado**.",
    "procedimiento": ["Paso 1: Revisa el coeficiente (el número grande) que acompaña a cada término de la expresión.", "Paso 2: Revisa también el término independiente.", "Paso 3: Si absolutamente todos esos números son un gran '0', estás ante un polinomio nulo."],
    "ejemplos": [
        {"titulo": "El tren vacío", "enunciado": "Sabiendo que P(x) = (a-2)x^2 + (b-3)x es un polinomio nulo, halla a y b.", "solucion_pasos": ["Si es nulo, todos sus coeficientes deben valer cero.", "El primer coeficiente (a-2) debe ser 0. Por ende, a = 2.", "El segundo coeficiente (b-3) debe ser 0. Por ende, b = 3."]}
    ],
    "errores_frecuentes": ["Confundir 'Polinomio Nulo' con 'Polinomio de grado cero'. Un polinomio de grado cero es una constante ($P(x) = 5$). Un polinomio nulo es literalmente el vacío ($P(x) = 0$).", "Creer que si la 'x' vale cero, el polinomio se llama nulo. El polinomio es nulo solo si sus *coeficientes fijos* son cero de fábrica."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUL-CONC-{i}", "semantic_id": sid18, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Cuál es la condición algebraica necesaria e indispensable para que una expresión sea formalmente categorizada como un 'Polinomio Nulo' ($P(x) \\equiv 0$)? (v{i})", "choices": ["A) Que la totalidad de sus coeficientes numéricos, incluyendo el término independiente, sean estrictamente iguales a cero.", "B) Que la variable o incógnita del problema tome obligatoriamente el valor numérico cero.", "C) Que el polinomio carezca de término independiente.", "D) Que todos sus exponentes sean cero."], "correct_answer": "A) Que la totalidad de sus coeficientes numéricos, incluyendo el término independiente, sean estrictamente iguales a cero.", "solution_steps": "Si $C_i = 0$ para todo término, la expresión se anula permanentemente sin importar el valor de las variables.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PNUL-REC-1", "semantic_id": sid18, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Si se declara que el polinomio $Q(x) = (A-5)x^3 + (B+4)x$ es un polinomio idénticamente nulo, ¿qué se puede deducir directamente de dicha afirmación?", "choices": ["A) Que el valor de $A$ es $5$ y el valor de $B$ es $-4$.", "B) Que $A$ y $B$ deben valer cero.", "C) Que la variable $x$ vale cero.", "D) Que el polinomio no es resoluble."], "correct_answer": "A) Que el valor de $A$ es $5$ y el valor de $B$ es $-4$.", "solution_steps": "Para ser nulo, los coeficientes deben dar cero. $A-5 = 0 \\rightarrow A=5$. $B+4 = 0 \\rightarrow B=-4$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUL-PROC-{i}", "semantic_id": sid18, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "alta", "competencia": "M1", "prompt": "¿El grado absoluto de un polinomio nulo es siempre cero, dado que su valor final es cero?", "choices": [], "correct_answer": "Falso", "solution_steps": "A nivel del álgebra teórica superior, el polinomio nulo carece de grado definido (o se dice que su grado es $-\\infty$), para mantener la coherencia de las propiedades de multiplicación de grados. No es grado cero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUL-PAES-{i}", "semantic_id": sid18, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"En el desarrollo de un motor físico para videojuegos, se programa que cuando el 'Polinomio de Fuerza Neta' ($F(x)$) se convierte en un polinomio nulo, el objeto entra en reposo absoluto inalterable. El sistema lee $F(x) = (c-2)x^2 + (k)x$. Para que la nave espacial quede anclada en reposo, ¿qué valores deben inyectar los sensores a las constantes $c$ y $k$? (v{i})", "choices": ["A) $c = 2$ y $k = 0$.", "B) $c = 0$ y $k = 0$.", "C) $c = -2$ y $k = 0$.", "D) Cualquier valor de $c$ y $k$ si $x = 0$."], "correct_answer": "A) $c = 2$ y $k = 0$.", "solution_steps": "Si debe ser un polinomio nulo ($F(x) \\equiv 0$), sus coeficientes valen cero. $c-2 = 0 \\rightarrow c=2$. Y directamente $k=0$.", "paes_style": True})

# 14. POLINOMIOS_IDENTICOS
sid19 = "MAT.ALG.POLINOMIOS.POLINOMIOS_IDENTICOS"
RECURSOS.append({
    "semantic_id": sid19, "objetivo": "Comprender cuándo dos polinomios son idénticos y aplicar esta propiedad para hallar valores desconocidos.",
    "introduccion": "Existen gemelos idénticos que, aunque usen ropa diferente un día, debajo siguen siendo la misma persona. En álgebra, dos expresiones que parecen distintas pueden ser en realidad el mismo polinomio.",
    "resumen": "Dos **Polinomios son Idénticos** ($P(x) \\equiv Q(x)$) si tienen exactamente **los mismos coeficientes para sus términos semejantes**. Es decir, la cantidad de $x^3$ en uno es igual a la cantidad de $x^3$ en el otro, y así sucesivamente.",
    "explicacion": "Esta no es una ecuación que se resuelve buscando la 'x'. Es una declaración de igualdad estructural profunda.\nSi nos dicen que $ax^2 + bx + c \\equiv 5x^2 - 3x + 8$:\n- Emparejamos el vagón cuadrático con el cuadrático: $ax^2$ va con $5x^2$. Conclusión: $a = 5$.\n- Emparejamos el vagón lineal: $bx$ va con $-3x$. Conclusión: $b = -3$.\n- Emparejamos los independientes: $c$ va con $8$. Conclusión: $c = 8$.\n\nEsta herramienta es extremadamente poderosa en matemáticas avanzadas (como fracciones parciales) para 'descubrir' los valores de las constantes ocultas.",
    "procedimiento": ["Paso 1: Asegúrate de que ambos polinomios estén reducidos y ordenados de la misma manera (ej. descendente).", "Paso 2: Iguala el coeficiente del término de mayor grado del primero, con el del segundo.", "Paso 3: Continúa emparejando término a término (los x^2 con los x^2, las x con las x, etc).", "Paso 4: Resuelve las pequeñas ecuaciones que se formen de esos emparejamientos."],
    "ejemplos": [
        {"titulo": "El juego de los gemelos", "enunciado": "Si (m-1)x^2 + 4x es idéntico a 7x^2 + nx, descubre m y n.", "solucion_pasos": ["Emparejamos las x^2: m - 1 = 7. Despejando: m = 8.", "Emparejamos las x: 4 = n. Despejando: n = 4.", "Los valores son m=8, n=4."]}
    ],
    "errores_frecuentes": ["Intentar 'despejar la x' como si fuera una ecuación normal, pasando términos de un lado al otro para aislarla, arruinando el emparejamiento.", "Olvidar los signos al igualar los coeficientes."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PIDE-CONC-{i}", "semantic_id": sid19, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Si dos polinomios de la misma variable se declaran como 'Idénticos' ($P(x) \\equiv Q(x)$), ¿qué propiedad operativa se deriva de esta afirmación teórica? (v{i})", "choices": ["A) Que los coeficientes de los términos de igual grado en ambos polinomios son exactamente iguales entre sí.", "B) Que al sumar ambos polinomios el resultado es un polinomio nulo.", "C) Que las raíces (o soluciones) de ambos polinomios son cero.", "D) Que ambos polinomios son reducibles a un solo monomio."], "correct_answer": "A) Que los coeficientes de los términos de igual grado en ambos polinomios son exactamente iguales entre sí.", "solution_steps": "Polinomios idénticos son espejos. Lo que acompaña a x^2 en uno, debe acompañar a x^2 en el otro.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PIDE-REC-1", "semantic_id": sid19, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": "Si el polinomio $P(x) = (A)x^3 + 5x^2 - 1$ es idénticamente igual a $Q(x) = 2x^3 + (B)x^2 - 1$, entonces:", "choices": ["A) $A = 2$ y $B = 5$", "B) $A = 5$ y $B = 2$", "C) $A = 2x^3$ y $B = 5x^2$", "D) No se puede determinar sin conocer el valor de $x$."], "correct_answer": "A) $A = 2$ y $B = 5$", "solution_steps": "Igualamos término a término: el coeficiente de x^3 es A y 2 (A=2). El coeficiente de x^2 es 5 y B (B=5).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PIDE-PROC-{i}", "semantic_id": sid19, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "alta", "competencia": "M1", "prompt": "¿Si se declara que $3x^2 + Cx \\equiv 3x^2 - 4x$, es algebraicamente correcto intentar pasar las '$x$' de un lado al otro para despejarlas como en una ecuación ordinaria?", "choices": [], "correct_answer": "Falso", "solution_steps": "No es una ecuación condicional, es una identidad. No se busca el valor de x, se emparejan los coeficientes de x. $C = -4$. Intentar despejar x arruinaría el análisis.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PIDE-PAES-{i}", "semantic_id": sid19, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un software de criptografía requiere igualar un polinomio cifrado con la clave maestra para destrabar un archivo. El polinomio cifrado es $Kx^2 + (W-2)x + 5$ y la clave maestra es la estructura polinomial $-3x^2 + 8x + 5$. Si el software impone la condición de que ambos sean polinomios idénticos, ¿qué valores numéricos tomarán los parámetros $K$ y $W$ respectivamente en el núcleo del programa? (v{i})", "choices": ["A) $K = -3$ y $W = 10$.", "B) $K = -3$ y $W = 8$.", "C) $K = 3$ y $W = 6$.", "D) $K = 8$ y $W = -3$."], "correct_answer": "A) $K = -3$ y $W = 10$.", "solution_steps": "Emparejamos grado 2: $K = -3$. Emparejamos grado 1: $W-2 = 8 \\rightarrow W = 10$.", "paes_style": True})

# 15. IGUALDAD_COEFICIENTES
sid20 = "MAT.ALG.POLINOMIOS.IGUALDAD_COEFICIENTES"
RECURSOS.append({
    "semantic_id": sid20, "objetivo": "Aplicar el principio de igualdad de coeficientes para resolver problemas de identidades algebraicas.",
    "introduccion": "El principio que usamos para encontrar a los gemelos idénticos tiene un nombre formal y un campo de aplicación inmenso en las ciencias exactas. Se llama el Principio de Igualdad de Coeficientes.",
    "resumen": "El **Principio de Igualdad de Coeficientes** dicta que en una identidad polinomial (donde dos expresiones son siempre iguales sin importar el valor de las variables), **los coeficientes de los términos del mismo grado deben ser estrictamente iguales** entre ambos lados de la igualdad.",
    "explicacion": "Este principio te da una 'llave maestra' para romper problemas que parecen imposibles.\nImagina este problema de física, donde te dicen que una trayectoria $Ax^2 + Bx$ siempre equivale, a todo momento, a $4x^2 - 7x$.\nSin el principio, te quedarías atascado intentando darle valores a $x$.\nCon el principio, sabes de inmediato y por ley matemática que:\n$A = 4$\n$B = -7$\nHas descompuesto un problema enorme con infinitas $x$ posibles, en dos pequeñas certezas absolutas e independientes.",
    "procedimiento": ["Paso 1: Organiza el polinomio de la izquierda agrupando los términos según el grado de su variable.", "Paso 2: Organiza el de la derecha exactamente igual.", "Paso 3: Si en un lado falta un término (por ejemplo, no hay x), asume que su coeficiente es cero (+ 0x).", "Paso 4: Crea una lista de mini-ecuaciones igualando el coeficiente izquierdo con el derecho para cada grado.", "Paso 5: Resuelve el sistema."],
    "ejemplos": [
        {"titulo": "Rellenando los huecos", "enunciado": "Si mx^2 + n = 5x^2 - 4x + 8, halla m y n.", "solucion_pasos": ["Lado izquierdo falta la x. Lo reescribimos como: mx^2 + 0x + n", "Igualamos cuadráticos: m = 5", "Igualamos lineales: 0 = -4 (¡Cuidado! Esto genera una contradicción, significa que esos polinomios NO pueden ser idénticos jamás en la vida real).", "Nota teórica: un buen problema siempre tiene congruencia."]}
    ],
    "errores_frecuentes": ["Olvidar rellenar con coeficiente cero los términos faltantes antes de emparejar, lo que descalabra las ecuaciones.", "Igualar el coeficiente cuadrático de la izquierda con el término independiente de la derecha por no haber ordenado primero."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IGCO-CONC-{i}", "semantic_id": sid20, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Qué paso previo es metodológicamente fundamental antes de aplicar el 'Principio de Igualdad de Coeficientes' entre dos polinomios extensos? (v{i})", "choices": ["A) Ambos polinomios deben estar reducidos y ordenados bajo la misma variable ordenatriz, rellenando con ceros los grados faltantes si fuese necesario.", "B) Despejar la variable 'x' pasándola toda a un solo lado del signo de identidad.", "C) Dividir todo el polinomio por su término independiente.", "D) Eliminar todos los signos negativos."], "correct_answer": "A) Ambos polinomios deben estar reducidos y ordenados bajo la misma variable ordenatriz, rellenando con ceros los grados faltantes si fuese necesario.", "solution_steps": "Sin orden ni reducción, emparejarás peras con manzanas. El orden asegura que compares grado 2 con grado 2, grado 1 con grado 1, etc.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"IGCO-REC-1", "semantic_id": sid20, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": "Si se sabe por definición teórica que la expresión polinomial $Ax^3 + C$ es idéntica a $8x^3 - 5x + 9$, ¿qué valor debe tomar obligatoriamente la constante ausente que acompañaría a la variable '$x$' en el lado izquierdo?", "choices": ["A) $0$", "B) $-5$", "C) $8$", "D) $9$"], "correct_answer": "A) $0$", "solution_steps": "A la izquierda no hay término con 'x' visible, por lo que su coeficiente es 0. Igualarlo a -5x demuestra que es una identidad imposible, pero el valor del coeficiente oculto de x a la izquierda siempre es 0.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IGCO-PROC-{i}", "semantic_id": sid20, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "alta", "competencia": "M1", "prompt": "¿El Principio de Igualdad de Coeficientes permite concluir que en la identidad $5x^2 - x \\equiv 5x^2 + (k)x$, el valor exacto del parámetro $k$ es $-1$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El coeficiente de $x$ a la izquierda es $-1$ (por el menos invisible de $-x$). El coeficiente a la derecha es $k$. Por igualdad, $k = -1$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"IGCO-PAES-{i}", "semantic_id": sid20, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Una empresa descompone el modelo de pérdida de inventario en dos fracciones teóricas sumadas. Tras realizar el álgebra, la consultora concluye que la identidad global del sistema se rige por: $(P+Q)x + (P-Q) \\equiv 10x + 2$. Para descubrir los valores reales de pérdida ($P$) y merma ($Q$), aplican el principio de igualdad de coeficientes. ¿Qué sistema de ecuaciones lineales es el correcto a resolver? (v{i})", "choices": ["A) $P+Q = 10$ y $P-Q = 2$", "B) $P+Q = 2$ y $P-Q = 10$", "C) $(P+Q)x = 10$ y $P-Q = 2x$", "D) No se puede plantear un sistema sin conocer $x$."], "correct_answer": "A) $P+Q = 10$ y $P-Q = 2$", "solution_steps": "El coeficiente de x a la izquierda es $(P+Q)$, a la derecha es $10$. Se igualan. El término independiente es $(P-Q)$, a la derecha es $2$. Se igualan. Se forma un sistema clásico 2x2.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 6 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 6 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-6", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-6.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
