# scratch/build_alg_b0301_t1.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. DEFINICION_ALGEBRA
sid1 = "MAT.ALG.FUNDAMENTOS.DEFINICION_ALGEBRA"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Comprender la definición formal y el propósito del álgebra en las matemáticas.",
    "introduccion": "¿Por qué complicar los números con letras? El álgebra no nace para torturarnos, sino para darnos el poder de resolver no solo un problema, sino todos los problemas similares al mismo tiempo.",
    "resumen": "El **Álgebra** es la rama de las matemáticas que estudia las cantidades del modo más general posible. Mientras la aritmética trabaja con números específicos, el álgebra usa letras para representar números cualesquiera, permitiendo formular leyes y ecuaciones.",
    "explicacion": "Imagina que quieres calcular el área de un cuadrado. \nEn aritmética dirías: 'Si el lado mide 3, el área es 3 por 3, que es 9'.\nEn álgebra dices: 'Si el lado mide $L$, el área es $L^2$'. \nEsa pequeña fórmula $L^2$ sirve para infinitos cuadrados, sean grandes como una galaxia o pequeños como un átomo. \nEl álgebra es el lenguaje universal que nos permite encontrar patrones, descubrir valores ocultos y modelar la realidad entera.",
    "procedimiento": ["Paso 1: Reconocer que el álgebra es una generalización.", "Paso 2: Entender que las letras no son textos, sino 'cajas vacías' donde puede ir cualquier número.", "Paso 3: Usar estas herramientas para establecer fórmulas generales."],
    "ejemplos": [
        {"titulo": "El poder de generalizar", "enunciado": "Aritmética vs Álgebra: Suma de dos números iguales.", "solucion_pasos": ["Aritmética: 5 + 5 = 10.", "Álgebra: x + x = 2x.", "La regla algebraica sirve para el 5, para el 1000 y para cualquier número que exista."]}
    ],
    "errores_frecuentes": ["Pensar que las letras en álgebra tienen un valor alfabético (ej. que A vale 1, B vale 2).", "Creer que el álgebra inventa reglas nuevas; en realidad, aplica las mismas reglas aritméticas pero a cantidades desconocidas."],
    "fuente": "Álgebra de Baldor / Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFALG-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes afirmaciones describe de forma más precisa el propósito fundamental del Álgebra? (v{i})", "choices": ["A) Estudiar las cantidades del modo más general posible utilizando letras para representar números.", "B) Realizar cálculos precisos exclusivamente con números enteros y fracciones.", "C) Medir las figuras geométricas con instrumentos físicos.", "D) Estudiar la probabilidad de que ocurran eventos aleatorios."], "correct_answer": "A) Estudiar las cantidades del modo más general posible utilizando letras para representar números.", "solution_steps": "El álgebra generaliza la aritmética usando letras (variables).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEFALG-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Una de las grandes ventajas de expresar una ley en lenguaje algebraico (como $A = b \\cdot h$ para el área de un rectángulo) es que:", "choices": ["A) Sirve para calcular el área de cualquier rectángulo sin importar sus medidas específicas.", "B) Solo sirve para un rectángulo particular.", "C) Obliga a usar números irracionales.", "D) Hace que el cálculo sea siempre igual a cero."], "correct_answer": "A) Sirve para calcular el área de cualquier rectángulo sin importar sus medidas específicas.", "solution_steps": "El álgebra proporciona fórmulas universales para infinitos casos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFALG-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Es correcto afirmar que en álgebra las letras del abecedario se utilizan exclusivamente para propósitos decorativos o de nomenclatura de vértices, y nunca para representar cantidades numéricas?", "choices": [], "correct_answer": "Falso", "solution_steps": "En álgebra, las letras representan números y cantidades numéricas generalizadas o desconocidas.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFALG-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una profesora pide a sus alumnos que formulen una regla general que describa el doble de cualquier número sumado con tres. ¿Qué estudiante logra la verdadera abstracción algebraica? (v{i})", "choices": ["A) Estudiante X: '$2 \\cdot n + 3$, donde $n$ es cualquier número'.", "B) Estudiante Y: '$2 \\cdot 5 + 3 = 13$'.", "C) Estudiante Z: 'El doble de ocho es dieciséis, y más tres es diecinueve'.", "D) Estudiante W: '$n + n + n + n$ y luego tres'."], "correct_answer": "A) Estudiante X: '$2 \\cdot n + 3$, donde $n$ es cualquier número'.", "solution_steps": "El estudiante X generaliza usando una variable 'n' y las operaciones correspondientes, logrando el objetivo del álgebra.", "paes_style": True})

# 2. DISTINCION_ARITMETICA
sid2 = "MAT.ALG.FUNDAMENTOS.DISTINCION_ARITMETICA"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Identificar las diferencias clave entre el enfoque aritmético y el enfoque algebraico.",
    "introduccion": "Si la Aritmética es tomar una fotografía de un solo instante numérico, el Álgebra es grabar un video de todo lo que podría pasar. Ambas ramas operan parecido, pero sus alcances son muy diferentes.",
    "resumen": "La diferencia principal es que la **Aritmética** solo representa cantidades con **números exactos** (ej. $20$). El número $20$ siempre vale $20$. El **Álgebra**, en cambio, usa **letras** (ej. $x$) que pueden tomar cualquier valor (generalización) o representar un valor exacto pero que aún ignoramos (incógnita).",
    "explicacion": "Piensa en el precio de una entrada al cine.\n- **Aritmética:** 'Compré 3 entradas a 5.000 pesos cada una. Total = $3 \\cdot 5000 = 15000$ pesos'. Se aplica a este cine, hoy.\n- **Álgebra:** 'Compré 3 entradas a un precio $p$. Total = $3p$'. Esta expresión $3p$ sirve para cuando haya ofertas, cuando suba la inflación, o para un cine en otro país.\n\nEn la aritmética las cantidades tienen valores absolutos y determinados. En el álgebra, son valores relativos, variables o sujetos a descubrimiento.",
    "procedimiento": ["Paso 1: Observa la expresión matemática.", "Paso 2: Si solo ves números explícitos y operaciones directas (5 + 8 / 2), es Aritmética.", "Paso 3: Si ves letras representando partes de la operación (5x + 8 / y), es Álgebra."],
    "ejemplos": [
        {"titulo": "Comparación directa", "enunciado": "Clasifica como Aritmética o Álgebra: a) 4 + 7 = 11, b) a + b = c", "solucion_pasos": ["a) 4 + 7 = 11. Solo usa números conocidos absolutos. Es Aritmética.", "b) a + b = c. Usa letras para generalizar la suma. Es Álgebra."]}
    ],
    "errores_frecuentes": ["Creer que la Aritmética no usa reglas o fórmulas (sí las usa, pero para números conocidos).", "Asumir que un cálculo algebraico siempre da una letra como resultado (puede dar un número exacto si se conocen o se anulan las variables)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DISARI-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la diferencia fundamental en la forma de representar las cantidades entre la Aritmética y el Álgebra? (v{i})", "choices": ["A) La Aritmética usa números para valores determinados y el Álgebra usa letras para representar valores generales o incógnitas.", "B) El Álgebra solo usa sumas y la Aritmética solo usa multiplicaciones.", "C) La Aritmética permite fracciones pero el Álgebra solo admite números enteros.", "D) El Álgebra se resuelve sin operaciones aritméticas básicas."], "correct_answer": "A) La Aritmética usa números para valores determinados y el Álgebra usa letras para representar valores generales o incógnitas.", "solution_steps": "La generalización a través de literales es lo que separa estructuralmente al álgebra de la aritmética clásica.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DISARI-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al examinar la expresión $12 + 5 \\cdot 4 = 32$, podemos catalogarla primariamente como un desarrollo de tipo:", "choices": ["A) Aritmético.", "B) Algebraico.", "C) Geométrico.", "D) Exponencial."], "correct_answer": "A) Aritmético.", "solution_steps": "No hay generalizaciones literales ni incógnitas, es un cálculo con valores precisos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DISARI-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El enunciado 'El triple de un número cualquiera más cuatro es igual a diez' corresponde a un enfoque algebraico de pensamiento?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Alude a 'un número cualquiera' (una variable $x$), lo que exige abstracción algebraica ($3x + 4 = 10$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DISARI-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Dos analistas de datos discuten cómo programar el descuento de productos en una base de datos de supermercado. El analista A propone restar $\$500$ al precio de hoy del champú. El analista B propone establecer una celda que tome el precio '$P$' de cualquier producto y lo multiplique por $0.8$ para aplicar un $20\\%$ general. ¿Qué enfoques usaron respectivamente? (v{i})", "choices": ["A) El analista A usó un enfoque aritmético y el B un enfoque algebraico.", "B) Ambos usaron un enfoque aritmético.", "C) Ambos usaron un enfoque algebraico.", "D) El analista A usó un enfoque algebraico y el B un enfoque aritmético."], "correct_answer": "A) El analista A usó un enfoque aritmético y el B un enfoque algebraico.", "solution_steps": "El caso A es un cálculo numérico específico. El caso B generaliza sobre una variable $P$, lo cual es álgebra.", "paes_style": True})

# 3. REPRESENTACION_LETRAS
sid3 = "MAT.ALG.FUNDAMENTOS.REPRESENTACION_LETRAS"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Comprender que las letras en álgebra representan cantidades numéricas que operan bajo las mismas leyes que los números.",
    "introduccion": "Si ves una '$a$' en un libro de lenguaje, es la primera vocal. Si la ves en un libro de matemáticas, es un número disfrazado. Tienes que aprender a tratar a las letras con el mismo respeto (y las mismas reglas) que a los números de siempre.",
    "resumen": "En álgebra, las **letras representan números**. Por lo tanto, puedes sumar, restar, multiplicar o dividirlas siguiendo exactamente las **mismas propiedades aritméticas** que los números reales (conmutatividad, asociatividad, distributividad).",
    "explicacion": "Como la letra representa un número escondido, debes obedecer las reglas universales:\n1. Propiedad Conmutativa: Así como $2 + 5$ es igual a $5 + 2$, también ocurre que $x + y = y + x$.\n2. Propiedad Distributiva: Así como $3 \\cdot (4 + 2) = 3\\cdot 4 + 3\\cdot 2$, también ocurre que $a \\cdot (b + c) = ab + ac$.\n\nSi le asignas el valor numérico 10 a la letra $k$, entonces la expresión $k + 5$ automáticamente vale 15. Las letras son solo 'recipientes' maleables, y operan como si ya tuvieran el número adentro.",
    "procedimiento": ["Paso 1: Observa las letras de la expresión.", "Paso 2: Recuerda que son números reales, y aplícales las reglas de la aritmética que ya conoces.", "Paso 3: No intentes sumar letras diferentes (como a + b) en un solo término final a menos que sepas su valor, porque son recipientes distintos."],
    "ejemplos": [
        {"titulo": "Operando a ciegas", "enunciado": "Aplica la propiedad conmutativa a la multiplicación de 'p' y 'q'.", "solucion_pasos": ["En aritmética, 3 * 4 = 4 * 3.", "En álgebra, p * q = q * p.", "No importa qué números escondan p y q, el orden de los factores no altera el producto."]}
    ],
    "errores_frecuentes": ["Olvidar que las letras son números y tratar de operar fuera de las reglas aritméticas (ej. pensar que $a + a = a^2$ en lugar de $2a$, como si fueran manzanas en lugar de cantidades).", "Creer que letras distintas siempre deben tener valores distintos (a veces $x$ e $y$ podrían valer 5 ambas, a menos que el problema diga lo contrario)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REPL-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si en una ecuación algebraica aparece la expresión $m + n$, ¿cuál de las siguientes propiedades aritméticas de los números reales garantiza que el resultado es idéntico a $n + m$? (v{i})", "choices": ["A) La propiedad conmutativa de la adición.", "B) La propiedad distributiva.", "C) La propiedad del elemento neutro.", "D) La propiedad asociativa."], "correct_answer": "A) La propiedad conmutativa de la adición.", "solution_steps": "Como m y n son números, heredan la propiedad conmutativa de la suma: el orden de los sumandos no altera la suma.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"REPL-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Sabiendo que las letras en álgebra se rigen por las leyes de los números reales, ¿cuál de las siguientes igualdades es CORRECTA por la propiedad distributiva?", "choices": ["A) $x(y + z) = xy + xz$", "B) $x(y + z) = x + y + z$", "C) $x(y + z) = yz + x$", "D) $x(y + z) = xy + z$"], "correct_answer": "A) $x(y + z) = xy + xz$", "solution_steps": "El factor $x$ se distribuye multiplicando a cada término dentro del paréntesis.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REPL-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La expresión algebraica $a \\cdot b$ siempre debe dar un resultado distinto al de la expresión $b \\cdot a$, porque las letras están en distinto orden alfabético?", "choices": [], "correct_answer": "Falso", "solution_steps": "Por propiedad conmutativa de la multiplicación de números, $a \\cdot b = b \\cdot a$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REPL-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una fórmula de física indica que la energía es igual a $m \\cdot c \\cdot c$. Si un estudiante reescribe libremente la fórmula de su cuaderno como $c^2 \\cdot m$, ¿ha cometido un error matemático? (v{i})", "choices": ["A) No ha cometido error, aplicó la propiedad conmutativa y la definición de potencia para reescribir correctamente el equivalente algebraico.", "B) Sí, porque $m$ debe ir primero obligatoriamente.", "C) Sí, porque al multiplicar letras repetidas se suma, no se eleva a potencia.", "D) Sí, porque $c \\cdot c$ es $2c$."], "correct_answer": "A) No ha cometido error, aplicó la propiedad conmutativa y la definición de potencia para reescribir correctamente el equivalente algebraico.", "solution_steps": "Como las letras son números, $m \\cdot c \\cdot c = m \\cdot c^2$. Y por propiedad conmutativa $m \\cdot c^2 = c^2 \\cdot m$.", "paes_style": True})

# 4. CONVENCION_LETRAS
sid4 = "MAT.ALG.FUNDAMENTOS.CONVENCION_LETRAS"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Reconocer las convenciones clásicas de letras utilizadas para cantidades conocidas (parámetros) y desconocidas (incógnitas).",
    "introduccion": "En álgebra puedes usar cualquier letra, desde la A hasta la Z (incluso el alfabeto griego). ¡Y todas funcionan igual! Pero existe una 'etiqueta' no escrita, una convención histórica de matemáticos europeos de hace siglos, para no confundirnos entre lo que sabemos y lo que no sabemos.",
    "resumen": "Por convención (y gracias a René Descartes):\n- Las **primeras letras del alfabeto** ($a, b, c, d \\dots$) se usan para cantidades **conocidas** o parámetros fijos.\n- Las **últimas letras del alfabeto** ($x, y, z, u, v, w$) se usan para cantidades **desconocidas**, incógnitas o variables que cambian.",
    "explicacion": "Piensa en la clásica ecuación de la recta: $y = mx + b$.\n- Las últimas letras ($x, y$) son las variables que van cambiando a lo largo del gráfico (incógnitas que evalúas).\n- La letra ($b$) y la ($m$) están al principio/medio del abecedario, y actúan como números fijos o constantes para esa recta en particular (por ejemplo, pendiente 2, corte 3).\n\nOtro ejemplo: En la ecuación $ax + b = c$, asumimos instantáneamente que nuestro trabajo es despejar la $x$, porque es la última letra y por tanto la incógnita, mientras que $a, b, c$ representan números ordinarios que alguien olvidó poner.\n\n*Recuerda: Es solo una convención. No se rompe el universo si usas la $x$ como una constante, pero te ganarás la mirada de confusión de tu profesor.*",
    "procedimiento": ["Paso 1: Lee la fórmula algebraica.", "Paso 2: Asume que las letras del final (x, y, z) son las incógnitas que debes despejar o calcular.", "Paso 3: Asume que las primeras letras (a, b, c) son constantes o números dados."],
    "ejemplos": [
        {"titulo": "Despejando al culpable correcto", "enunciado": "En la fórmula general $ax^2 + bx + c = 0$, ¿qué letras representan números dados y cuál es la incógnita a buscar?", "solucion_pasos": ["a, b y c son las primeras letras: Representan constantes numéricas (ej. 3, -5, 1).", "x es una de las últimas letras: Representa la incógnita que la fórmula busca resolver."]}
    ],
    "errores_frecuentes": ["Intentar 'despejar la a' en lugar de la 'x' en un problema estándar, confundiendo la incógnita real con un parámetro.", "Creer que es una ley matemática inquebrantable, bloqueándose en física si les piden despejar la aceleración 'a' (que ahí sí es incógnita)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CONL-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Según la convención algebraica clásica, cuando se presenta la ecuación genérica $ax + b = 0$, ¿qué representan usualmente las letras $a$ y $b$? (v{i})", "choices": ["A) Cantidades conocidas, constantes o parámetros de la ecuación.", "B) Las principales incógnitas que deben ser despejadas obligatoriamente.", "C) Variables que pueden tomar infinitos valores a la vez.", "D) Números exclusivamente irracionales."], "correct_answer": "A) Cantidades conocidas, constantes o parámetros de la ecuación.", "solution_steps": "Por convención de Descartes, las primeras letras del alfabeto (a, b, c...) actúan como parámetros o constantes dadas.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CONL-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al observar la expresión $cx + dy = k$, ¿cuáles letras representan usualmente las incógnitas del sistema?", "choices": ["A) $x$ e $y$.", "B) $c$ y $d$.", "C) $x$ y $k$.", "D) Ninguna letra es incógnita."], "correct_answer": "A) $x$ e $y$.", "solution_steps": "Las últimas letras del alfabeto (x, y, z) se reservan convencionalmente para las incógnitas variables.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CONL-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Es matemáticamente imposible e incorrecto usar la letra '$a$' como una incógnita y despejarla en una ecuación si el profesor te lo pide?", "choices": [], "correct_answer": "Falso", "solution_steps": "La asignación de letras es solo una convención social, algebraicamente se puede despejar cualquier letra si así lo exige el contexto.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CONL-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un problema de modelamiento presenta la función de costos $C = p \\cdot x + k$, donde representa un proceso fabril real. ¿Cuál de las siguientes afirmaciones describe de mejor forma el rol convencional de las letras en este contexto matemático? (v{i})", "choices": ["A) '$p$' y '$k$' actúan como parámetros fijos del problema, mientras que '$x$' es la variable independiente (cantidad de producto).", "B) Todas las letras cambian de valor al mismo tiempo.", "C) '$x$' es un parámetro fijo y '$k$' es la incógnita principal.", "D) Es imposible saber cuál es cuál sin que nos den los números."], "correct_answer": "A) '$p$' y '$k$' actúan como parámetros fijos del problema, mientras que '$x$' es la variable independiente (cantidad de producto).", "solution_steps": "En el estándar matemático, p y k (o m, b, c) son parámetros fijos (precio, costo fijo), y la x es la variable del problema.", "paes_style": True})

# 5. CONCEPTO_VARIABLE
sid5 = "MAT.ALG.FUNDAMENTOS.CONCEPTO_VARIABLE"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Definir e interpretar el concepto de variable y su rol fundamental en las expresiones algebraicas.",
    "introduccion": "Imagina una caja de regalo mágica. Cuando la abres a las 8 am tiene un peluche, pero a las 9 am tiene un reloj. La caja es la misma, pero su contenido cambia. Eso es exactamente una variable en matemáticas.",
    "resumen": "Una **variable** es un símbolo constitutivo (usualmente una letra como $x, y, z, t$) que representa un valor que puede **cambiar, variar o ser reemplazado** por diferentes números dentro de un conjunto determinado de posibilidades.",
    "explicacion": "La variable es el motor de las funciones. \nEn la expresión que calcula el perímetro de un cuadrado $P = 4L$, la letra $L$ es la variable.\n- Si dibujas un cuadradito en tu cuaderno, $L$ puede valer 2 cm.\n- Si pintas un cuadrado en la calle, $L$ puede valer 5 metros.\n\nLa variable es lo que le da 'vida' a las fórmulas matemáticas. Permite que una misma fórmula de física calcule la caída de una pluma o la órbita de un planeta con solo reemplazar el valor de $t$ (tiempo) o $m$ (masa).\n\nEn una ecuación simple (ej. $x + 2 = 5$), la variable solo puede tomar un valor específico que la hace verdadera ($x=3$). Ahí la variable está 'atrapada' y se le llama incógnita. Pero en una función (ej. $y = x + 2$), la variable $x$ es libre de valer 1, 10 o 1000, y la $y$ cambiará en respuesta.",
    "procedimiento": ["Paso 1: Detecta el símbolo o letra en la ecuación/función.", "Paso 2: Pregúntate si ese valor representa algo fijo o si puede admitir múltiples reemplazos según el caso.", "Paso 3: Si admite múltiples reemplazos numéricos, estás frente a una variable."],
    "ejemplos": [
        {"titulo": "El taxi cobrador", "enunciado": "La tarifa es $1000 iniciales más $200 por kilómetro. La expresión es T = 1000 + 200k. Identifica la variable independiente.", "solucion_pasos": ["El 1000 y el 200 son constantes (números fijos del taxímetro).", "La letra 'k' (kilómetros) puede ser 1, 5, o 20 dependiendo del viaje.", "Por tanto, 'k' es la variable que tú puedes reemplazar libremente."]}
    ],
    "errores_frecuentes": ["Confundir una constante (como el número Pi $\\pi$ o el número de Euler $e$) con una variable solo por ser símbolos/letras. Pi jamás variará, siempre será 3.1415...", "Creer que una variable $x$ siempre significa 'un número desconocido que hay que despejar', olvidando que también puede ser 'cualquier número que yo decida ingresar'."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"VAR-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la característica definitoria de una 'variable' en una función algebraica como $f(x) = 2x + 1$? (v{i})", "choices": ["A) Es un símbolo (generalmente letra) que puede ser sustituido por diferentes valores numéricos dentro de un conjunto.", "B) Es un número desconocido que tiene un único valor correcto posible y constante.", "C) Es una letra que representa siempre al número 1 por defecto.", "D) Es un símbolo griego que tiene un valor universal como $3.1415$."], "correct_answer": "A) Es un símbolo (generalmente letra) que puede ser sustituido por diferentes valores numéricos dentro de un conjunto.", "solution_steps": "La naturaleza de la variable es 'variar', permitiendo ser reemplazada por múltiples valores en el dominio.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"VAR-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la fórmula del área del círculo $A = \\pi \\cdot r^2$, ¿cuál es el símbolo que actúa estrictamente como la variable independiente que puede modificarse?", "choices": ["A) La letra $r$ (radio).", "B) El símbolo $\\pi$.", "C) El exponente $2$.", "D) El signo de multiplicación."], "correct_answer": "A) La letra $r$ (radio).", "solution_steps": "El radio $r$ cambia según el círculo. Pi ($\\pi$) es una constante fija.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"VAR-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El número $\\pi$ (Pi), al estar representado por una letra/símbolo griego en vez de un número arábigo, se clasifica como una variable algebraica en la fórmula del perímetro de una circunferencia?", "choices": [], "correct_answer": "Falso", "solution_steps": "Pi siempre vale aproximadamente 3.14159, su valor jamás varía. Por tanto, es una constante, no una variable.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"VAR-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un ecólogo modela la población de un tipo de ave migratoria con la expresión $P = C \\cdot (1.05)^t$, donde '$C$' es el tamaño de la bandada al llegar en enero, y '$t$' representa los meses transcurridos. Si desea proyectar cómo evolucionará **esa bandada específica** a lo largo del año actual mes a mes, ¿qué rol cumplen los símbolos en este análisis? (v{i})", "choices": ["A) '$C$' actúa como una constante y '$t$' actúa como la variable que él debe ir cambiando.", "B) '$C$' y '$t$' son ambas variables libres.", "C) '$C$' es la variable y '$t$' es una constante fija del problema.", "D) Ambas letras actúan como constantes porque ya pasó enero."], "correct_answer": "A) '$C$' actúa como una constante y '$t$' actúa como la variable que él debe ir cambiando.", "solution_steps": "Para ESA bandada, el tamaño inicial 'C' está fijo (ej. 100 aves). El tiempo 't' es lo que irá cambiando (variando) de 1 a 12 meses.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 1 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 1 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-1", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-1.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
