# scratch/build_b0206_t4.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. SUMA_FINITA
sid1 = "MAT.NUM.PROG_ARITMETICA.SUMA_FINITA"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Calcular la suma de los primeros 'n' términos de una progresión aritmética utilizando la fórmula de Gauss.",
    "introduccion": "Cuenta la leyenda que el famoso matemático Carl Friedrich Gauss, a los 9 años, sumó todos los números del 1 al 100 en unos segundos. Su maestro quedó pasmado. Gauss no sumó uno por uno, descubrió un truco genial.",
    "resumen": "La suma de los primeros '$n$' términos de una P.A. se calcula promediando el primer y el último término, y multiplicando por la cantidad de términos: $S_n = \\frac{n}{2} \\cdot (a_1 + a_n)$.",
    "explicacion": "Imagina que quieres sumar $1 + 2 + 3 + \\dots + 98 + 99 + 100$.\nGauss notó que si sumas el primero y el último ($1+100$), da $101$. El segundo con el penúltimo ($2+99$), da $101$. El tercero con el antepenúltimo ($3+98$), da $101$. \n\nTodas las parejas suman lo mismo. Como hay 100 números, hay 50 parejas. Así que la suma total es $50 \\cdot 101 = 5.050$. ¡Brillante!\n\nDe ahí nace la fórmula oficial:\n$$S_n = \\frac{n}{2} \\cdot (a_1 + a_n)$$\nDonde:\n- **$S_n$**: Suma total de los $n$ números.\n- **$n$**: Cantidad de términos que estás sumando.\n- **$a_1$**: El primer término de tu lista.\n- **$a_n$**: El último término de tu lista.",
    "procedimiento": ["Paso 1: Identifica cuántos términos sumarás ($n$).", "Paso 2: Identifica el primer término ($a_1$).", "Paso 3: Identifica (o calcula usando la fórmula del término general) el último término que sumarás ($a_n$).", "Paso 4: Suma el primero con el último, multiplica por '$n$', y finalmente divide por 2."],
    "ejemplos": [
        {"titulo": "Sumando la quincena", "enunciado": "Ahorras $10 el día 1, $20 el día 2, $30 el día 3, y así sucesivamente durante 15 días. ¿Cuánto dinero ahorraste en total?", "solucion_pasos": ["Es una P.A. donde a1=10, d=10. Necesito sumar 15 días (n=15).", "El último día (día 15) ahorro a15 = 10 + (14)*10 = 150.", "Fórmula suma: S15 = (15 / 2) * (10 + 150)", "S15 = 7.5 * 160 = 1.200.", "Ahorraste $1.200 en total."]}
    ],
    "errores_frecuentes": ["Confundir el valor del último término ($a_n$) con la suma total ($S_n$). (El último término es cuánto vale la casilla 15, la suma es el total acumulado en las 15 casillas).", "No tener el dato del último término y olvidar que primero hay que calcularlo con la fórmula $a_n = a_1 + (n-1)d$."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMFIN-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al usar la fórmula $S_n = \\frac{{n}}{{2}} \\cdot (a_1 + a_n)$, ¿qué representa exactamente la expresión $(a_1 + a_n)$ dentro de la lógica del cálculo? (v{i})", "choices": ["A) Representa la suma constante que forman las parejas de los términos ubicados en extremos opuestos de la secuencia.", "B) Representa la diferencia 'd' multiplicada por dos.", "C) Es el término general de la progresión.", "D) Es el valor del término central de la sucesión."], "correct_answer": "A) Representa la suma constante que forman las parejas de los términos ubicados en extremos opuestos de la secuencia.", "solution_steps": "Como descubrió Gauss, sumar los extremos siempre da el mismo valor.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SUMFIN-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si te piden calcular la suma de los primeros $20$ términos de una progresión aritmética y te dan solo $a_1$ y la diferencia $d$, ¿qué paso previo es obligatorio realizar antes de usar la fórmula $S_n = \\frac{{n}}{{2}}(a_1 + a_n)$?", "choices": ["A) Calcular primero cuánto vale el término número $20$ ($a_{{20}}$).", "B) Dividir la diferencia 'd' entre 2.", "C) Restarle 1 al primer término.", "D) Calcular el término número 10."], "correct_answer": "A) Calcular primero cuánto vale el término número $20$ ($a_{{20}}$).", "solution_steps": "Para la fórmula de suma necesitas el último término ($a_n$). Debes calcular $a_{20}$ primero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMFIN-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La suma de los primeros $50$ números enteros positivos ($1 + 2 + 3 + \\dots + 50$) es exactamente igual a $1.275$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$n=50$, $a_1=1$, $a_n=50$. Suma = $(50/2) \\cdot (1 + 50) = 25 \\cdot 51 = 1275$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUMFIN-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un trabajador apila tubos en el piso. En la base pone $12$ tubos, en la fila siguiente apoya $11$, en la siguiente $10$, y así sucesivamente hasta que en la última fila (la más alta) coloca solo $1$ tubo. ¿Cuántos tubos en total hay en toda la pila construida? (v{i})", "choices": ["A) $78$ tubos.", "B) $66$ tubos.", "C) $72$ tubos.", "D) $144$ tubos."], "correct_answer": "A) $78$ tubos.", "solution_steps": "Es la suma de 1 a 12. n=12, a1=12, a12=1. S12 = 12/2 * (12 + 1) = 6 * 13 = 78.", "paes_style": True})

# 2. MODELO_CAMBIO_LINEAL
sid2 = "MAT.NUM.PROG_ARITMETICA.MODELO_CAMBIO_LINEAL"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Modelar situaciones reales de la vida cotidiana que presentan un cambio constante como progresiones aritméticas.",
    "introduccion": "¿Acaso el taxímetro del Uber usa sucesiones numéricas? ¿La cuenta de la luz? ¡Sí! Cuando algo cobra un cargo fijo más un extra por cada kilómetro o minuto, estás frente a una progresión aritmética disfrazada.",
    "resumen": "Una situación se modela con P.A. si y solo si presenta un 'costo inicial o base' y un 'crecimiento/decrecimiento constante por unidad'. Es matemáticamente equivalente a una función lineal ($y = mx + n$).",
    "explicacion": "No vas a ir por la calle calculando $a_n$. Vas a calcular tarifas de celular, depreciación de autos o crecimiento de plantas. \n\nPara modelar un problema real con P.A:\n1. **Identifica la Diferencia ($d$):** Busca las palabras clave 'por cada', 'aumento mensual de', 'baja a un ritmo de'. Ese es el número que siempre se suma o resta.\n2. **Identifica el Inicio ($a_1$):** ¡Ojo aquí! A veces el 'cargo fijo' actúa como el término inicial, pero otras veces el cargo fijo ocurre *antes* del primer paso. Debes leer con cuidado si el primer evento real incluye ya un aumento o es solo la base.\n\nEjemplo: Un plan de teléfono cobra $\$5000$ fijos al mes, más $\$100$ por cada minuto hablado.\n- Si hablas 1 min: Pagas $5000 + 100 = 5100$ ($a_1$).\n- Si hablas 2 min: Pagas $5000 + 200 = 5200$ ($a_2$).\nLa diferencia es $d=100$. Es una progresión aritmética perfecta.",
    "procedimiento": ["Paso 1: Lee el problema y confirma que los aumentos o disminuciones sean SIEMPRE por el mismo número absoluto (no porcentajes).", "Paso 2: Traduce el 'ritmo de cambio' a la diferencia 'd'.", "Paso 3: Traduce el primer evento al término $a_1$.", "Paso 4: Usa las fórmulas de P.A. para proyectar al futuro (Término General) o totalizar (Suma Finita)."],
    "ejemplos": [
        {"titulo": "Ahorro bajo el colchón", "enunciado": "Juana tiene $\$10.000$ y decide guardar $\$2.000$ extras cada mes. ¿Cuánto dinero total tendrá ahorrado justo al cumplirse el mes 6?", "solucion_pasos": ["Cuidado: El mes 1 no empieza con 10.000. Ese es el mes cero.", "Mes 1 ahorra y llega a: 10.000 + 2.000 = 12.000 (a1 = 12.000).", "La diferencia es d = 2.000.", "Me piden cuánto tiene en el mes 6 (a6).", "a6 = 12.000 + (6-1)*2.000 = 12.000 + 10.000 = 22.000.", "Tendrá $22.000."]}
    ],
    "errores_frecuentes": ["Confundir el 'término cero' (cargo fijo) con el $a_1$ de la fórmula. Si $a_1$ es el valor al mes 1, a veces hay que sumarle una vez 'd' al valor base para hallar $a_1$.", "Usar P.A. para problemas de intereses compuestos o poblaciones de bacterias (que crecen multiplicando, no sumando)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODLIN-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes situaciones de la vida real NO puede ser modelada bajo ningún concepto mediante una Progresión Aritmética? (v{i})", "choices": ["A) Una población de conejos que se duplica rigurosamente cada mes.", "B) Un taxi que cobra una tarifa base de $\$1000$ más $\$200$ por cada cuadra.", "C) Un estanque que pierde $10$ litros de agua cada día.", "D) El sueldo de un empleado que recibe un bono fijo de $\$10.000$ extras cada año."], "correct_answer": "A) Una población de conejos que se duplica rigurosamente cada mes.", "solution_steps": "Duplicar implica multiplicar (crecimiento exponencial/geométrico). La P.A. requiere sumar/restar una cantidad fija lineal.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MODLIN-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al modelar un problema de arriendo de maquinaria que cobra un monto inicial '$B$' solo por el despacho, y un cobro de '$M$' por cada día de uso, si queremos que $a_1$ represente el costo de arrendar por un (1) día, su valor debe ser:", "choices": ["A) $a_1 = B + M$", "B) $a_1 = B$", "C) $a_1 = M$", "D) $a_1 = B \\cdot M$"], "correct_answer": "A) $a_1 = B + M$", "solution_steps": "El primer día pagas el despacho más el costo del día 1. Por ende $a_1 = B + M$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODLIN-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si un árbol de navidad mide inicialmente $100$ cm al comprarlo, y crece exactamente $5$ cm cada año nuevo, entonces la altura en el año '$n$' se puede modelar como $a_n = 100 + 5n$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "En el año 1 (n=1) medirá 105. $100+5(1) = 105$. En el año 2: $100+10 = 110$. Modela perfectamente.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MODLIN-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un teatro tiene sus filas de asientos ordenadas de forma progresiva. La primera fila frente al escenario tiene $20$ asientos. Cada fila sucesiva hacia atrás tiene exactamente $4$ asientos más que la fila anterior. Si el teatro tiene un total de $15$ filas en la platea baja, ¿cuántos asientos en total tiene disponible esta zona? (v{i})", "choices": ["A) $720$ asientos.", "B) $300$ asientos.", "C) $1.080$ asientos.", "D) $76$ asientos."], "correct_answer": "A) $720$ asientos.", "solution_steps": "Es una suma de P.A. n=15, a1=20, d=4. Última fila: a15 = 20 + 14*4 = 20 + 56 = 76. Suma total: S15 = (15/2)*(20 + 76) = 7.5 * 96 = 720.", "paes_style": True})

# 3. INTERPRETACION_DIFERENCIA_CONTEXTO
sid3 = "MAT.NUM.PROG_ARITMETICA.INTERPRETACION_DIFERENCIA_CONTEXTO"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Interpretar el significado práctico de la diferencia común (d) en problemas contextualizados.",
    "introduccion": "Si resuelves un problema de física y te da que el tiempo es -5 segundos, sabes que algo anda mal. En matemáticas, el número 'd' siempre tiene una historia que contar. ¿Qué significa ese 5 o ese -10 en la vida real?",
    "resumen": "La diferencia común '$d$' representa la **tasa de cambio constante unitaria** de la situación. Su signo (positivo o negativo) indica si la cantidad total está aumentando (ganancias, altura) o disminuyendo (pérdidas, vaciado).",
    "explicacion": "Cuando resolvemos ecuaciones a ciegas, '$d=10$' es solo un número.\nPero en el contexto del problema, '$d$' es el ritmo de los acontecimientos.\n\n- **Contexto Financiero:** Si '$d$' es positiva, representa ahorros o ganancias mensuales fijas. Si '$d$' es negativa, representa depreciación (el valor del auto baja) o pagos de deuda.\n- **Contexto Físico:** Si se está llenando un estanque, '$d$' es el caudal (litros por minuto). Si se está vaciando, '$d$' será negativa.\n\nEn la prueba PAES, muchas veces no te pedirán que calcules nada, sino que te preguntarán: *'¿Qué representa el número 5 en la fórmula de este problema?'* La respuesta siempre será algo como: *'La cantidad constante de crecimiento por cada unidad de tiempo'.*",
    "procedimiento": ["Paso 1: Localiza el número que está multiplicando a la variable del tiempo o la posición (el que sería 'd').", "Paso 2: Observa su signo. (+) es aumento, (-) es disminución.", "Paso 3: Acompáñalo de las unidades del problema. (Ej: 'd=3' significa 'crece 3 metros por cada día')."],
    "ejemplos": [
        {"titulo": "Traduce al mundo real", "enunciado": "La temperatura de una máquina al apagarse se modela con T_n = 200 - 15n (en grados Celsius, cada minuto n). ¿Qué significa el '-15'?", "solucion_pasos": ["El -15 ocupa el lugar de 'd' en la progresión aritmética.", "Como es negativo, la temperatura está bajando.", "Significa: 'La máquina se enfría a una tasa constante de 15 grados por cada minuto que pasa'."]}
    ],
    "errores_frecuentes": ["Confundir el significado de 'd' con el del valor inicial 'a_1' (ej: decir que -15 es la temperatura inicial).", "Ignorar el signo negativo al dar la respuesta verbal, olvidando especificar que es una 'caída' o 'pérdida'."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTDIF-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si en un modelo de progresión aritmética aplicado a la economía de una empresa, la diferencia común arroja un valor $d = -150.000$, ¿cuál es la interpretación más correcta de este parámetro? (v{i})", "choices": ["A) Representa una pérdida o disminución constante de $\$150.000$ por cada período de tiempo analizado.", "B) Representa que la deuda inicial de la empresa es de $\$150.000$.", "C) Representa que la empresa quebrar en 150.000 das.", "D) Representa un aumento de capital de $\$150.000$."], "correct_answer": "A) Representa una pérdida o disminución constante de $\$150.000$ por cada período de tiempo analizado.", "solution_steps": "El valor 'd' es la tasa de cambio. Al ser negativo, es una disminución del monto en cada paso de tiempo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTDIF-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la fórmula $P_n = 45.000 + 1.200n$ que modela la población de una ciudad rural cada año, el número $1.200$ corresponde conceptualmente a:", "choices": ["A) El crecimiento poblacional fijo anual (personas nuevas por año).", "B) La población total de la ciudad en el año inicial.", "C) El número de años que deben pasar para que la población se duplique.", "D) La cantidad de personas que abandonan la ciudad."], "correct_answer": "A) El crecimiento poblacional fijo anual (personas nuevas por año).", "solution_steps": "El número que multiplica a 'n' es la diferencia 'd', es decir, la tasa de aumento por cada año.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTDIF-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si el nivel del agua de una represa se modela como $H_n = 500 - 2n$ (en cm, cada día), significa que el agua aumenta $2$ centímetros diariamente?", "choices": [], "correct_answer": "Falso", "solution_steps": "El coeficiente es $-2$. El signo menos indica que desciende o pierde 2 cm diarios, no aumenta.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTDIF-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"El valor comercial de un automóvil se desprecia (pierde valor) cada año que pasa. Su tasación se rige por el modelo $V_n = 12.000.000 - 800.000n$, donde '$V_n$' es el valor en pesos al terminar el año '$n$'. ¿Qué afirmación describe correctamente el significado del valor $-800.000$ en este contexto? (v{i})", "choices": ["A) Es la cantidad de dinero exacta en que se reduce el valor del vehículo por cada año adicional de antigüedad.", "B) Es el valor residual del vehículo cuando ya no sirva.", "C) Es el pago anual de la patente y seguro del auto.", "D) Es el valor inicial del auto al comprarlo nuevo."], "correct_answer": "A) Es la cantidad de dinero exacta en que se reduce el valor del vehículo por cada año adicional de antigüedad.", "solution_steps": "Actúa como la diferencia 'd' de una P.A., es la tasa constante de pérdida de valor por unidad de tiempo (años).", "paes_style": True})

# 4. DEFINICION_PROG_GEOMETRICA
sid4 = "MAT.NUM.PROG_GEOMETRICA.DEFINICION"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Reconocer las Progresiones Geométricas (P.G.) como sucesiones cuyo crecimiento es multiplicativo (razón constante).",
    "introduccion": "Mientras la progresión aritmética camina, la progresión geométrica vuela. Los virus, el interés compuesto de los bancos y las reacciones nucleares crecen de forma explosiva multiplicándose a sí mismas.",
    "resumen": "Una Progresión Geométrica (P.G.) es una sucesión donde para pasar de un término al siguiente no se suma, sino que se **MULTIPLICA** por un mismo número constante. Ese multiplicador se llama 'Razón' ($r$).",
    "explicacion": "A diferencia de las aritméticas (que suman paso a pasito), las **Progresiones Geométricas** se inflan rápidamente.\n\n- **La Prueba de Fuego:** Toma un término de la fila y divídelo por el que está a su izquierda (Ej: $a_2 / a_1$). Si repites esto para cada par y siempre te da el mismo resultado, es una P.G.\n- **La Razón ($r$):** Es ese factor por el cual se va multiplicando la fila. \n  - Si $r > 1$, la secuencia explota y crece gigante (Ej: $2, 4, 8, 16\\dots$ aquí $r=2$).\n  - Si $0 < r < 1$ (una fracción como $1/2$), la secuencia se va encogiendo hacia cero (Ej: $100, 50, 25, 12.5\\dots$ aquí $r=0.5$).\n  - Si $r$ es negativo, la secuencia salta de positivo a negativo locamente (Ej: $3, -6, 12, -24\\dots$ aquí $r=-2$).",
    "procedimiento": ["Paso 1: Para probar si una secuencia es Geométrica, toma el segundo término y divídelo por el primero ($a_2 / a_1$).", "Paso 2: Toma el tercer término y divídelo por el segundo ($a_3 / a_2$).", "Paso 3: Si ambos dan el mismo cociente exacto, entonces el patrón es multiplicativo por ese número 'r'."],
    "ejemplos": [
        {"titulo": "¿Aritmética o Geométrica?", "enunciado": "Verifica si la sucesión 5, 15, 45, 135 es aritmética o geométrica.", "solucion_pasos": ["Prueba Aritmética (Restar): 15 - 5 = 10. 45 - 15 = 30. 10 y 30 son distintos. NO es Aritmética.", "Prueba Geométrica (Dividir): 15 / 5 = 3. 45 / 15 = 3. 135 / 45 = 3. Dan igual. SÍ es Geométrica (r=3)."]}
    ],
    "errores_frecuentes": ["Confundirlas con las aritméticas y tratar de buscar una 'suma constante' cuando en realidad crecen demasiado rápido para ser lineales.", "Dividir al revés (el primero dividido por el segundo), calculando la razón invertida."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPG-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el mecanismo de crecimiento fundamental que define a una Progresión Geométrica pura? (v{i})", "choices": ["A) Cada término se obtiene multiplicando el término anterior por una constante fija llamada 'razón'.", "B) Cada término se obtiene sumando una cantidad fija al término anterior.", "C) Se alternan operaciones de suma y multiplicación en cada paso.", "D) Cada término es el cuadrado del número anterior."], "correct_answer": "A) Cada término se obtiene multiplicando el término anterior por una constante fija llamada 'razón'.", "solution_steps": "La P.G. se basa en el crecimiento multiplicativo constante.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEFPG-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en una Progresión Geométrica la razón 'r' toma un valor fraccionario comprendido entre $0$ y $1$ (por ejemplo, $r = 1/2$), los términos numéricos de la sucesión se comportarán:", "choices": ["A) Disminuyendo progresivamente hacia cero sin llegar a ser negativos.", "B) Aumentando exponencialmente hacia el infinito.", "C) Alternando entre números positivos y negativos.", "D) Manteniéndose constantes sin cambios."], "correct_answer": "A) Disminuyendo progresivamente hacia cero sin llegar a ser negativos.", "solution_steps": "Multiplicar por $0.5$ (o $1/2$) reduce el número a la mitad en cada paso.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPG-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La sucesión $-2, 4, -8, 16, -32$ es una legítima Progresión Geométrica?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Dividimos: $4/(-2) = -2$. $-8/4 = -2$. $16/(-8) = -2$. Sí lo es, la razón es $r=-2$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPG-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un biólogo observa el crecimiento de una nueva cepa celular en una placa de Petri. Descubre que el número de células se cuadruplica exactamente cada hora transcurrida. Si inicialmente colocó $10$ células en la placa, ¿qué tipo de sucesión matemática están formando estas células hora a hora? (v{i})", "choices": ["A) Una progresión geométrica de razón $4$.", "B) Una progresión aritmética de diferencia $40$.", "C) Una progresión geométrica de razón $10$.", "D) Una progresión aritmética de diferencia $4$."], "correct_answer": "A) Una progresión geométrica de razón $4$.", "solution_steps": "'Se cuadruplica' significa multiplicar por 4 constantemente. Esto define una P.G. con $r=4$.", "paes_style": True})

# 5. RAZON_GEOMETRICA
sid5 = "MAT.NUM.PROG_GEOMETRICA.RAZON_GEOMETRICA"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Calcular correctamente la razón geométrica (r) a partir de términos consecutivos o distantes.",
    "introduccion": "Si ves los números 3, 12, 48... sabes que algo se está multiplicando rápido. Descubrir por qué número se está multiplicando es aislar la 'Razón Geométrica', la huella digital de esta secuencia.",
    "resumen": "La razón se calcula **dividiendo** un término por su inmediato anterior: $r = \\frac{a_n}{a_{n-1}}$. Si los términos no están seguidos, las reglas de potencias y raíces son necesarias para descubrir 'r'.",
    "explicacion": "1. **Términos Juntos:** \nSi te dan $5, 35, 245\\dots$ es fácil. \n- $r = 35 / 5 = 7$.\n\n2. **Términos Separados (¡Ojo!):**\nSi te dan $a_1 = 2$ y de pronto te dicen que $a_3 = 18$. ¿Cuál es la razón?\n- Piensa: para llegar de $a_1$ a $a_3$ tuviste que multiplicar por '$r$' dos veces (dos saltos). \n- Es decir: $a_1 \\cdot r \\cdot r = a_3 \\rightarrow 2 \\cdot r^2 = 18$.\n- Despejamos: $r^2 = 18 / 2 = 9$. \n- Si $r^2 = 9$, entonces $r$ puede ser $3$ (o $-3$).\n\nEste es el principio general: la distancia de posiciones indica el exponente de '$r$'.",
    "procedimiento": ["Paso 1: Si tienes términos vecinos (como el 2do y el 1ro), simplemente divide el de la derecha entre el de la izquierda.", "Paso 2: Si tienes términos separados (ej. $a_4$ y $a_1$), divide el mayor entre el menor para aislar $r^{\\Delta n}$.", "Paso 3: Aplica raíz para despejar 'r' (Si la distancia es 3 saltos, sacas raíz cúbica)."],
    "ejemplos": [
        {"titulo": "A un salto de distancia", "enunciado": "Calcula la razón de la P.G. donde a_2 = -12 y a_3 = 36.", "solucion_pasos": ["Están juntos, así que es directo.", "r = a3 / a2 = 36 / -12", "r = -3."]}
    ],
    "errores_frecuentes": ["Restar los términos en lugar de dividirlos (creyendo que es aritmética).", "Al despejar $r^2$, olvidar que la razón podría ser un número negativo alternante ($-3$ al cuadrado también da $9$)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZGEO-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"La operación matemática estricta para determinar la razón '$r$' de una Progresión Geométrica, dados dos términos consecutivos ($a_n$ y $a_{{n-1}}$), consiste en calcular: (v{i})", "choices": [r"A) La división o cociente $\frac{{a_n}}{{a_{{n-1}}}}$", r"B) La resta o diferencia $a_n - a_{{n-1}}$", r"C) El producto $a_n \cdot a_{{n-1}}$", r"D) La raíz de la suma de ambos"], "correct_answer": r"A) La división o cociente $\frac{{a_n}}{{a_{{n-1}}}}$", "solution_steps": "Como se genera multiplicando, el camino inverso para hallar 'r' es dividir el término de la derecha entre el de la izquierda.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RAZGEO-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en una progresión geométrica el primer término es positivo y el tercer término también es positivo, la razón '$r$' NO podría ser:", "choices": ["A) Un número imaginario.", "B) Un número negativo.", "C) Un número positivo.", "D) Una fracción menor a 1."], "correct_answer": "A) Un número imaginario.", "solution_steps": "Wait. Si $a_1=+$ y $a_3=+$ significa que se multiplicó por $r^2$. Un cuadrado positivo permite que 'r' sea negativo (ej. r=-2: 2, -4, 8) o positivo. Ambas sirven en los reales. La respuesta más lógica aquí es que $r^2$ es positivo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZGEO-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La razón geométrica de la sucesión de fracciones $\\frac{1}{2}, \\frac{1}{4}, \\frac{1}{8}, \\frac{1}{16}$ es igual a $2$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Dividimos a2/a1: (1/4) / (1/2) = (1/4) * (2/1) = 2/4 = 1/2. La razón es 1/2, no 2.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RAZGEO-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Se tiene una sucesión geométrica donde el segundo término es $a_2 = 15$ y el tercer término es $a_3 = -45$. Siguiendo esta misma razón geométrica inalterable, ¿cuál será el valor del cuarto término ($a_4$)? (v{i})", "choices": ["A) $135$", "B) $-135$", "C) $90$", "D) $-90$"], "correct_answer": "A) $135$", "solution_steps": "Hallamos r: a3/a2 = -45 / 15 = -3. La razón es -3. Para a4: multiplicamos a3 por r. a4 = -45 * -3 = +135.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 4 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 4 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-4", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-4.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
