# scratch/build_b0206_t2.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. REGULARIDAD_NUMERICA
sid1 = "MAT.NUM.SUCESIONES_BASE.REGULARIDAD_NUMERICA"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Identificar el patrón o regularidad oculta en una secuencia numérica para predecir términos siguientes.",
    "introduccion": "Si ves los números 10, 20, 30... tu cerebro automáticamente grita '¡40!'. Acabas de encontrar una regularidad numérica. Descubrir el patrón es como ser un detective matemático.",
    "resumen": "Una regularidad numérica es la regla constante que relaciona un término de la sucesión con el siguiente. Puede ser sumar, restar, multiplicar, dividir, o incluso elevar al cuadrado.",
    "explicacion": "Para descubrir qué regla gobierna una sucesión, debes probar operaciones básicas entre números consecutivos:\n\n1. **¿Sumar o Restar?** Revisa si la diferencia entre números juntos es siempre la misma. Ej: $7, 10, 13, 16$ (el patrón es $+3$).\n2. **¿Multiplicar o Dividir?** Si los números crecen muy rápido, prueba dividir un término por el anterior. Ej: $3, 6, 12, 24$ (el patrón es $\\cdot 2$).\n3. **¿Cuadrados perfectos?** Si ves $1, 4, 9, 16, 25$, no están sumando ni multiplicando por lo mismo. Son los números $1^2, 2^2, 3^2, 4^2\\dots$\n\nUna vez que descubres el 'secreto' de la sucesión, puedes calcular el siguiente término fácilmente.",
    "procedimiento": ["Paso 1: Calcula la diferencia (resta) entre el segundo y el primer término, y luego entre el tercero y el segundo.", "Paso 2: Si la diferencia es constante, la regularidad es una suma/resta.", "Paso 3: Si no es constante, prueba dividiendo para ver si hay un factor multiplicativo.", "Paso 4: Aplica la regla encontrada al último término para hallar el siguiente."],
    "ejemplos": [
        {"titulo": "Buscando el eslabón perdido", "enunciado": "Encuentra la regularidad y el siguiente número en la sucesión: 80, 40, 20, 10...", "solucion_pasos": ["Resto: 40 - 80 = -40. Resto 20 - 40 = -20. No es una resta constante.", "Divido: 40 / 80 = 0.5 (o dividir por 2). Divido 20 / 40 = 0.5.", "El patrón constante es 'dividir por 2' (o multiplicar por 1/2).", "El siguiente es 10 / 2 = 5."]}
    ],
    "errores_frecuentes": ["Asumir una regla comprobando solo los dos primeros números, sin verificar que se cumpla en el tercer y cuarto número.", "Pensar que las reglas solo pueden ser sumas simples."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGNUM-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué paso fundamental de validación se debe realizar antes de asegurar que se ha encontrado la 'regularidad' de una secuencia numérica? (v{i})", "choices": ["A) Comprobar que la regla imaginada se cumple para todos los términos mostrados en la secuencia, no solo para los dos primeros.", "B) Verificar que el patrón siempre implique sumar un número entero.", "C) Asegurarse de que el último número sea par.", "D) Despejar la 'x' de la ecuación."], "correct_answer": "A) Comprobar que la regla imaginada se cumple para todos los términos mostrados en la secuencia, no solo para los dos primeros.", "solution_steps": "Una regla no es válida si falla en la mitad de la sucesión.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"REGNUM-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si observas la secuencia $1, 4, 9, 16, 25\\dots$, la regularidad subyacente corresponde a:", "choices": ["A) Los cuadrados perfectos de los números naturales.", "B) Sumar 3 a cada término anterior.", "C) Multiplicar por 4 el término anterior.", "D) Los números primos elevados a dos."], "correct_answer": "A) Los cuadrados perfectos de los números naturales.", "solution_steps": "Son $1^2, 2^2, 3^2, 4^2, 5^2$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGNUM-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El número que continúa la secuencia $2, -4, 8, -16\\dots$ es el número $32$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El patrón es multiplicar por $-2$. Entonces $-16 \\cdot (-2) = +32$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGNUM-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un investigador anota el crecimiento de una bacteria en un cultivo registrando la cantidad de células cada una hora. Sus registros son: $5, 15, 45, 135\\dots$ ¿Cuál será la cantidad de células registradas al cumplirse la quinta hora, si se mantiene la misma regularidad matemática? (v{i})", "choices": ["A) $405$", "B) $270$", "C) $315$", "D) $540$"], "correct_answer": "A) $405$", "solution_steps": "Regularidad: $15/5 = 3$; $45/15 = 3$. Se multiplica por 3. Siguiente: $135 \\cdot 3 = 405$.", "paes_style": True})

# 2. REGULARIDAD_GRAFICA
sid2 = "MAT.NUM.SUCESIONES_BASE.REGULARIDAD_GRAFICA"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Identificar patrones y regularidades en secuencias de figuras o arreglos geométricos.",
    "introduccion": "No todos los patrones son solo números en una pizarra. A veces, los patrones son visuales: pirámides de puntos, baldosas en el piso o fractales. Traducir dibujos a números es un superpoder geométrico.",
    "resumen": "Una sucesión gráfica o geométrica muestra figuras que crecen o cambian según una regla. El truco principal es **contar** los elementos de cada figura y transformar el problema visual en una secuencia de números.",
    "explicacion": "En las pruebas suelen presentarse dibujos de cuadrados apilados, puntos formando triángulos o palitos de fósforo armando figuras.\n\nPara resolverlos sin enredarte, sigue el 'método de traducción':\n1. Mira la **Figura 1**. Cuenta sus elementos (ej. tiene 3 palitos). Escribe un $3$.\n2. Mira la **Figura 2**. Cuenta sus elementos (ej. tiene 5 palitos). Escribe un $5$.\n3. Mira la **Figura 3**. Cuenta sus elementos (ej. tiene 7 palitos). Escribe un $7$.\n\nAcabas de transformar los dibujos en una sucesión numérica simple: $3, 5, 7\\dots$\nAhora aplicas lo que ya sabes: el patrón numérico es $+2$. La siguiente figura tendrá $9$ palitos.",
    "procedimiento": ["Paso 1: Asigna un número a cada etapa o 'Figura n'.", "Paso 2: Cuenta metódicamente los elementos (puntos, lados, áreas) de la Figura 1 y anótalo.", "Paso 3: Repite para las Figuras 2 y 3 para crear tu lista ordenada de números.", "Paso 4: Encuentra la regularidad matemática de esos números."],
    "ejemplos": [
        {"titulo": "Triángulos de fósforos", "enunciado": "La Figura 1 es un triángulo (3 fósforos). La Figura 2 son dos triángulos unidos por un lado (5 fósforos). La Figura 3 son tres triángulos unidos en fila (7 fósforos). ¿Cuántos fósforos tendrá la Figura 4?", "solucion_pasos": ["Traducimos a números: a1=3, a2=5, a3=7.", "La regularidad es +2 por cada nuevo triángulo adherido.", "La figura 4 tendrá 7 + 2 = 9 fósforos."]}
    ],
    "errores_frecuentes": ["Intentar dibujar la figura número 10 o 20 a mano en lugar de usar la lógica matemática de la secuencia.", "Contar mal los elementos que se 'comparten' entre figuras geométricas adyacentes."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGGRA-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la estrategia analítica más efectiva para predecir el comportamiento de una sucesión de figuras geométricas que crece etapa por etapa? (v{i})", "choices": ["A) Contar los elementos de las primeras figuras para traducir el problema visual a una sucesión numérica estándar.", "B) Dibujar pacientemente a mano todas las figuras hasta llegar a la que se pregunta.", "C) Medir con una regla el perímetro de cada dibujo impreso en el papel.", "D) Asumir que la cantidad de elementos siempre se duplica respecto a la figura anterior."], "correct_answer": "A) Contar los elementos de las primeras figuras para traducir el problema visual a una sucesión numérica estándar.", "solution_steps": "Convertir geometría a aritmética simplifica el hallazgo de la regla.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"REGGRA-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si los números de puntos que forman figuras piramidales en las tres primeras etapas son $1, 3, 6\\dots$, ¿cuántos puntos tendrá la cuarta pirámide sabiendo que la diferencia aumenta gradualmente $(+2, +3\\dots)$?", "choices": ["A) $10$", "B) $9$", "C) $12$", "D) $8$"], "correct_answer": "A) $10$", "solution_steps": "$1 (+2) \\rightarrow 3 (+3) \\rightarrow 6 (+4) \\rightarrow 10$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGGRA-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si la figura 1 tiene $4$ cuadrados, la figura 2 tiene $8$ cuadrados y la figura 3 tiene $12$ cuadrados, entonces la regularidad indica que se suman $4$ cuadrados por figura?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Secuencia: $4, 8, 12$. La diferencia es $8-4 = 4$ y $12-8 = 4$. Correcto.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"REGGRA-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una secuencia de arreglos florales cuadrados se arma de la siguiente manera: La Etapa 1 tiene $1$ flor central. La Etapa 2 la rodea formando un cuadrado de $4$ flores. La Etapa 3 la rodea formando un cuadrado de $9$ flores. Siguiendo este patrón visual de cuadrados compactos, ¿cuántas flores en total conformarán el arreglo de la Etapa 6? (v{i})", "choices": ["A) $36$ flores.", "B) $25$ flores.", "C) $24$ flores.", "D) $16$ flores."], "correct_answer": "A) $36$ flores.", "solution_steps": "La secuencia es: 1, 4, 9. Corresponde a $1^2, 2^2, 3^2$. Para la Etapa 6, el número es $6^2 = 36$.", "paes_style": True})

# 3. SUCESION_RECURSIVA
sid3 = "MAT.NUM.SUCESIONES_BASE.SUCESION_RECURSIVA"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Entender y utilizar el concepto de sucesión definida por recurrencia, donde cada término depende del anterior.",
    "introduccion": "Imagina una cadena de favores: solo puedes hacer un favor si alguien te hizo uno primero. En matemáticas, hay fórmulas que te obligan a conocer el número anterior para poder calcular el siguiente. Eso es la recurrencia.",
    "resumen": "Una sucesión recursiva se define dando el primer término (ej. $a_1 = 5$) y una regla que conecta el término actual ($a_n$) con el término inmediatamente anterior ($a_{n-1}$).",
    "explicacion": "Hasta ahora vimos el **Término General**, que funciona como un teletransportador (pones $n=100$ y viajas directo al valor cien). \n\nPero muchas sucesiones se definen de forma **Recursiva**. Esta notación funciona como subir escalones: no puedes saltar al escalón 100 sin pisar el 99 antes.\n\nUna definición recursiva SIEMPRE tiene dos partes:\n1. **Una semilla (condición inicial):** Te deben decir cómo empieza. Ej: $a_1 = 2$.\n2. **La regla de dependencia:** Una fórmula que usa **$a_{n-1}$**. (Recuerda: si '$a_n$' es el término de ahora, '$a_{n-1}$' significa 'el término anterior').\n\nEjemplo: $a_1 = 2$,  $a_n = a_{n-1} + 3$\nTraducción al español: 'Empieza en 2. Para calcular cualquier número, toma el resultado anterior y súmale 3'.\n- $a_2 = a_1 + 3 = 2 + 3 = 5$\n- $a_3 = a_2 + 3 = 5 + 3 = 8$",
    "procedimiento": ["Paso 1: Identifica el valor inicial o semilla ($a_1$).", "Paso 2: Lee la fórmula de recurrencia. Donde veas '$a_{n-1}$', reemplázalo por el valor del número que calculaste en el paso anterior.", "Paso 3: Repite el ciclo (iteración) hasta llegar a la posición deseada."],
    "ejemplos": [
        {"titulo": "El ciclo sin fin", "enunciado": "Si $a_1 = 10$ y la recurrencia es $a_n = a_{n-1} \\cdot 2$. Calcula el tercer término ($a_3$).", "solucion_pasos": ["Empezamos con a1 = 10.", "Calculamos a2 reemplazando el valor de a1: $a_2 = 10 \\cdot 2 = 20$.", "Calculamos a3 reemplazando el valor de a2: $a_3 = 20 \\cdot 2 = 40$.", "El tercer término es 40."]}
    ],
    "errores_frecuentes": ["Reemplazar la letra '$n$' por la posición directamente en el lugar de '$a_{n-1}$'. (Ej. pensar que $a_{n-1}$ vale 4 si estás en la posición 5). ¡$a_{n-1}$ representa el VALOR de la casilla anterior, no la posición!", "Olvidar la condición inicial y no saber de dónde arrancar."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECURS-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la definición de una sucesión recursiva o por recurrencia, la expresión algebraica '$a_{{n-1}}$' representa estrictamente: (v{i})", "choices": ["A) El valor numérico del término inmediatamente anterior en la sucesión.", "B) El número de la posición actual menos uno.", "C) El término general de cualquier sucesión.", "D) El primer término de la sucesión."], "correct_answer": "A) El valor numérico del término inmediatamente anterior en la sucesión.", "solution_steps": "El subíndice $n-1$ indica la posición anterior. Por ende, la expresión completa representa el valor alojado en esa posición anterior.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RECURS-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Para que una fórmula de recurrencia funcione y permita generar los números, ¿qué dato adicional es absolutamente obligatorio conocer?", "choices": ["A) Un valor inicial o semilla (por ejemplo, $a_1$).", "B) El término general explícito.", "C) El último término de la sucesión.", "D) El valor de la variable $x$."], "correct_answer": "A) Un valor inicial o semilla (por ejemplo, $a_1$).", "solution_steps": "Sin un punto de partida, la recurrencia no tiene qué número utilizar para iniciar la cadena.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECURS-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si una sucesión se define como $a_1 = 5$ y $a_n = a_{n-1} - 1$, entonces el tercer término $a_3$ será igual a $3$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$a_2 = 5 - 1 = 4$. $a_3 = 4 - 1 = 3$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECURS-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un algoritmo matemático produce números siguiendo la regla recursiva: $x_1 = 2$, y para el resto, $x_n = (x_{{n-1}})^2 + 1$. ¿Cuál es el valor exacto del tercer número que arrojará este algoritmo ($x_3$)? (v{i})", "choices": ["A) $26$", "B) $5$", "C) $10$", "D) $25$"], "correct_answer": "A) $26$", "solution_steps": "x1 = 2. Para n=2: $x_2 = (x_1)^2 + 1 = 2^2 + 1 = 5$. Para n=3: $x_3 = (x_2)^2 + 1 = 5^2 + 1 = 25 + 1 = 26$.", "paes_style": True})

# 4. COMPARACION_EXPLICITA_RECURSIVA
sid4 = "MAT.NUM.SUCESIONES_BASE.COMPARACION_EXPLICITA_RECURSIVA"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Diferenciar entre la fórmula del término general (explícita) y la de recurrencia, comprendiendo sus ventajas.",
    "introduccion": "Si quieres saber qué número está en la posición 1.000 de una fila, tienes dos opciones: o cuentas uno a uno desde el principio (recurrencia), o tomas un atajo matemático que te deja ahí instantáneamente (fórmula explícita).",
    "resumen": "La **Fórmula Explícita** ($a_n = 5n$) usa solo 'n' y te permite hallar cualquier posición directamente. La **Recurrencia** ($a_n = a_{n-1} + 5$) usa términos anteriores y te obliga a calcular todo paso a paso.",
    "explicacion": "Una misma sucesión, por ejemplo los múltiplos de cinco ($5, 10, 15, 20\\dots$), puede escribirse en 'dos idiomas':\n\n1. **Idioma Explícito (Término General):** $a_n = 5 \\cdot n$\n   - *Ventaja:* Es rápido. Si quieres el término 100, haces $5 \\cdot 100 = 500$. Listo.\n   \n2. **Idioma Recursivo:** $a_1 = 5$ y $a_n = a_{n-1} + 5$\n   - *Desventaja:* Es lento para el futuro. Si quieres el término 100, primero debes calcular los 99 anteriores.\n   - *Ventaja:* Es muy fácil de entender y de programar en un computador. La famosa sucesión de Fibonacci ($1, 1, 2, 3, 5, 8\\dots$) es muy fácil de escribir como recurrencia ($a_n = a_{n-1} + a_{n-2}$), pero su fórmula explícita es horriblemente compleja.",
    "procedimiento": ["Paso 1: Para identificar una fórmula EXPLÍCITA, busca que solo contenga la letra '$n$' operando con números.", "Paso 2: Para identificar una fórmula RECURSIVA, busca que contenga expresiones con subíndices de posiciones relativas, como '$a_{n-1}$' o '$a_{n-2}$'.", "Paso 3: Si te piden un término muy lejano, intenta siempre deducir la explícita."],
    "ejemplos": [
        {"titulo": "Reconociendo el idioma", "enunciado": "Analiza: Opción 1: $b_n = 2n + 1$. Opción 2: $b_n = b_{n-1} + 2$. ¿Cuál es cuál?", "solucion_pasos": ["Opción 1 solo usa 'n'. Es explícita (Término General).", "Opción 2 usa 'b_{n-1}'. Es recursiva."]}
    ],
    "errores_frecuentes": ["Confundir el concepto de recurrencia con el de término general en preguntas de verdadero/falso.", "Intentar calcular el término cien usando una recurrencia a mano, perdiendo valioso tiempo en una prueba."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COMPEXR-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"La principal ventaja matemática de definir una sucesión mediante una fórmula 'explícita' (término general) en lugar de una recursiva es: (v{i})", "choices": ["A) Permite calcular el valor de un término en una posición lejana sin necesidad de calcular todos los anteriores.", "B) Garantiza que todos los números de la sucesión sean positivos.", "C) Elimina la necesidad de conocer en qué posición estamos.", "D) Evita el uso de fracciones y decimales en el cálculo."], "correct_answer": "A) Permite calcular el valor de un término en una posición lejana sin necesidad de calcular todos los anteriores.", "solution_steps": "La fórmula explícita evalúa directamente en 'n', actuando como un atajo.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"COMPEXR-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de las siguientes expresiones algebraicas corresponde a la definición 'recursiva' de una sucesión:", "choices": ["A) $a_n = a_{n-1} + 4$", "B) $a_n = 4n + 1$", "C) $a_n = n^2 - 4$", "D) $a_n = \\frac{4}{n}$"], "correct_answer": "A) $a_n = a_{n-1} + 4$", "solution_steps": "Es la única que hace referencia a un término anterior ($a_{n-1}$) dentro de su fórmula.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COMPEXR-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si queremos calcular el término número $1.000$ de una sucesión, nos resulta mucho más rápido utilizar la fórmula de recurrencia que el término general explícito?", "choices": [], "correct_answer": "Falso", "solution_steps": "Totalmente falso. La recurrencia obligaría a calcular 999 pasos previos. La explícita nos lleva directo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COMPEXR-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una sucesión tiene como regla recursiva $a_1 = 3$ y $a_n = a_{{n-1}} + 3$. Al inspeccionar los números generados, un profesor pide a sus estudiantes crear la fórmula explícita equivalente (el término general en función de '$n$'). ¿Cuál de las siguientes propuestas es la correcta? (v{i})", "choices": ["A) $a_n = 3n$", "B) $a_n = n + 3$", "C) $a_n = 3^n$", "D) $a_n = 3n + 3$"], "correct_answer": "A) $a_n = 3n$", "solution_steps": "La recurrencia genera $3, 6, 9, 12\\dots$ Esta lista es la tabla del 3. La fórmula que multiplica la posición por 3 es $3n$.", "paes_style": True})

# 5. DEFINICION_PROG_ARITMETICA
sid5 = "MAT.NUM.PROG_ARITMETICA.DEFINICION"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Reconocer las Progresiones Aritméticas (P.A.) como sucesiones donde la diferencia entre términos consecutivos es constante.",
    "introduccion": "Imagina una escalera donde todos los peldaños miden exactamente lo mismo. Subes a un ritmo perfectamente constante. En matemáticas, esa escalera tan predecible y ordenada tiene nombre y apellido: Progresión Aritmética.",
    "resumen": "Una Progresión Aritmética (P.A.) es un tipo especial de sucesión. Su regla inquebrantable es que se suma (o se resta) exactamente la misma cantidad para pasar de un término al siguiente. Ese número fijo se llama 'Diferencia' ($d$).",
    "explicacion": "De todas las sucesiones numéricas posibles, la **Progresión Aritmética** es la más sencilla de todas. Corresponde a crecimientos lineales.\n\n- **La Prueba de Ácido:** Para saber si una sucesión es aritmética, debes restar cualquier número con su vecino anterior (Ej: $a_2 - a_1$). Si repites esto en toda la lista y **siempre te da el mismo resultado**, ¡es una P.A.!\n- **La Diferencia ($d$):** Ese número constante que siempre se suma o se resta. \n  - Si $d > 0$, la progresión es *Creciente* (Ej: $2, 5, 8, 11\\dots$ aquí $d=3$).\n  - Si $d < 0$, la progresión es *Decreciente* (Ej: $20, 15, 10, 5\\dots$ aquí $d=-5$).\n  - Si $d = 0$, la progresión es *Constante* (Ej: $7, 7, 7, 7\\dots$).",
    "procedimiento": ["Paso 1: Toma el segundo término y réstale el primero ($a_2 - a_1$). Anota el resultado.", "Paso 2: Toma el tercer término y réstale el segundo ($a_3 - a_2$). Anota el resultado.", "Paso 3: Si ambos resultados son idénticos, es altamente probable que sea una Progresión Aritmética de diferencia 'd' igual a tu resultado."],
    "ejemplos": [
        {"titulo": "Comprobando la escalera", "enunciado": "¿Es la secuencia 10, 14, 18, 22 una progresión aritmética? Si es así, ¿cuál es su diferencia 'd'?", "solucion_pasos": ["Restamos: $14 - 10 = 4$.", "Restamos: $18 - 14 = 4$.", "Restamos: $22 - 18 = 4$.", "La resta siempre da lo mismo. Sí es una P.A. y su diferencia es $d = 4$."]}
    ],
    "errores_frecuentes": ["Restar al revés (restar el primer término menos el segundo), lo cual da un signo equivocado a la diferencia 'd'. ¡Siempre es el de la derecha menos el de la izquierda!", "Creer que la sucesión $2, 4, 8, 16$ es aritmética (¡No lo es! $4-2=2$, pero $8-4=4$. Esa es geométrica)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPA-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué condición matemática obligatoria debe cumplir una sucesión numérica para ser clasificada como 'Progresión Aritmética' (P.A.)? (v{i})", "choices": ["A) La resta entre cualquier término y su término inmediatamente anterior debe dar un valor constante 'd'.", "B) La división entre un término y su anterior debe ser siempre constante.", "C) Todos sus términos deben ser números primos positivos.", "D) El primer término debe ser siempre cero o uno."], "correct_answer": "A) La resta entre cualquier término y su término inmediatamente anterior debe dar un valor constante 'd'.", "solution_steps": "Esa resta constante se conoce como la 'Diferencia' (d) de la progresión.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEFPA-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en una progresión aritmética se descubre que su diferencia '$d$' es un número negativo (ejemplo $d = -2$), entonces se clasifica como una progresión:", "choices": ["A) Decreciente.", "B) Creciente.", "C) Constante.", "D) Alternada."], "correct_answer": "A) Decreciente.", "solution_steps": "Si a cada paso le sumas un negativo (le restas 2), los números irán bajando.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPA-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La secuencia de números $100, 90, 80, 70\\dots$ es una progresión aritmética cuya diferencia '$d$' vale $10$?", "choices": [], "correct_answer": "Falso", "solution_steps": "La resta es $90 - 100 = -10$. La diferencia 'd' vale $-10$, no $10$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFPA-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"De las siguientes opciones, ¿cuál representa una auténtica Progresión Aritmética? (v{i})", "choices": ["A) $5, 2, -1, -4, -7\\dots$", "B) $1, 2, 4, 8, 16\\dots$", "C) $1, 4, 9, 16, 25\\dots$", "D) $-2, 4, -8, 16, -32\\dots$"], "correct_answer": "A) $5, 2, -1, -4, -7\\dots$", "solution_steps": "Revisamos restas: $2-5 = -3$. $-1-2 = -3$. $-4 - (-1) = -3$. Se mantiene la diferencia $d=-3$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 2 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 2 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-2", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-2.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
