# scratch/build_b0206_t7.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. CONDICION_CONVERGENCIA
sid1 = "MAT.NUM.SERIE_GEOMETRICA.CONDICION_CONVERGENCIA"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Evaluar si una serie geométrica dada cumple las condiciones matemáticas para ser sumada hasta el infinito.",
    "introduccion": "Antes de lanzarte a usar la fórmula del infinito, tienes que pedirle permiso a las matemáticas. Como un portero de discoteca, la 'Condición de Convergencia' revisa tu razón 'r' y te dice si pasas o rebotas.",
    "resumen": "La única condición para que una serie geométrica converja a un número real al sumarla infinitamente es que **su razón '$r$' esté estrictamente entre $-1$ y $1$ (sin incluirlos)**. Matemáticamente: $|r| < 1$.",
    "explicacion": "Si te saltas este control de seguridad, la fórmula te mentirá.\n\nEjemplo de desastre: Serie $1 + 2 + 4 + 8 + 16 \\dots$ (Aquí $r = 2$).\n- Claramente la suma va hacia el infinito positivo.\n- ¡Pero la fórmula $S = \\frac{a_1}{1 - r}$ te dejaría usarla! Te daría $\\frac{1}{1 - 2} = -1$.\n- ¿Sumar números positivos infinitamente te dará $-1$? ¡ABSURDO!\n\nPor eso el portero existe:\n- ¿$r = 0.5$? PASE.\n- ¿$r = -1/3$? PASE.\n- ¿$r = -0.99$? PASE.\n- ¿$r = 1.01$? ¡RECHAZADO! (La suma explota).\n- ¿$r = -1$? ¡RECHAZADO! (La suma alterna infinitamente entre dos valores sin decidirse).",
    "procedimiento": ["Paso 1: Calcula la razón 'r' dividiendo el 2do término por el 1ro.", "Paso 2: Quítale el signo (toma su valor absoluto).", "Paso 3: Pregúntate: ¿Es estrictamente menor que 1?", "Paso 4: Si es Sí, la serie converge y puedes usar la fórmula. Si es No, la serie diverge (su suma es infinito o no existe)."],
    "ejemplos": [
        {"titulo": "El portero matemático", "enunciado": "Determina si la serie infinita 5 - 10 + 20 - 40... se puede sumar con la fórmula.", "solucion_pasos": ["Calculamos r: -10 / 5 = -2.", "Valor absoluto de r es 2.", "Como 2 es mayor que 1, el portero la rechaza.", "Respuesta: NO converge, no se puede calcular un total fijo."]}
    ],
    "errores_frecuentes": ["Creer que si la razón es negativa, automáticamente la serie diverge (Las razones negativas pequeñas como -0.5 convergen perfectamente).", "Forzar la fórmula con $r > 1$ y entregar ciegamente el resultado negativo como respuesta válida."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCONV-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes condiciones matemáticas expresa correctamente la exigencia que debe cumplir la razón '$r$' para garantizar que una serie geométrica infinita converja? (v{i})", "choices": ["A) $|r| < 1$", "B) $r > 1$", "C) $|r| = 1$", "D) $r \\neq 0$"], "correct_answer": "A) $|r| < 1$", "solution_steps": "El valor absoluto de la razón debe ser estrictamente menor que 1 (es decir, $-1 < r < 1$).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CCONV-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál de las siguientes progresiones geométricas NO se puede sumar hasta el infinito mediante la fórmula $S_\\infty = \\frac{{a_1}}{{1-r}}$?", "choices": ["A) Una progresión de razón $r = -1.2$", "B) Una progresión de razón $r = 0.99$", "C) Una progresión de razón $r = -0.5$", "D) Una progresión de razón $r = 1/4$"], "correct_answer": "A) Una progresión de razón $r = -1.2$", "solution_steps": "El valor de $-1.2$ está fuera del rango permitido ($-1, 1$). Su valor absoluto es mayor que 1, por lo que diverge.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCONV-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La serie infinita de la progresión $\\frac{1}{2}, 1, 2, 4, 8, \\dots$ converge y por lo tanto puede calcularse usando la fórmula?", "choices": [], "correct_answer": "Falso", "solution_steps": "La razón es 2 ($1 / 0.5 = 2$). Como 2 > 1, la serie no converge y NO se puede usar la fórmula.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CCONV-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una empresa ofrece un plan de referidos perpetuo. Pagará a sus promotores sumas decrecientes al infinito, formando una serie geométrica. El Ministerio de Economía solo autoriza estos planes si el total a pagar converge a un número finito. Si las razones '$r$' propuestas por la empresa son las siguientes, ¿qué plan es el ÚNICO que recibirá la aprobación ministerial? (v{i})", "choices": ["A) El plan con razón $r = 0.85$", "B) El plan con razón $r = 1.05$", "C) El plan con razón $r = 1.00$", "D) El plan con razón $r = -1.15$"], "correct_answer": "A) El plan con razón $r = 0.85$", "solution_steps": "Solo el 0.85 cumple la condición $-1 < r < 1$. Las otras razones harán que la suma explote y la empresa quiebre.", "paes_style": True})

# 2. SUMA_INFINITA
sid2 = "MAT.NUM.SERIE_GEOMETRICA.SUMA_INFINITA"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Calcular con precisión la suma total de una serie geométrica infinita convergente.",
    "introduccion": "Ya pasaste el control del portero. La razón es una fracción válida. Ahora, es el momento de aplicar la fórmula más limpia y satisfactoria de todas las progresiones.",
    "resumen": "Si $|r| < 1$, la suma infinita se calcula resolviendo la fracción **$S_{\\infty} = \\frac{a_1}{1 - r}$**. Solo necesitas dos números: el de inicio y la razón.",
    "explicacion": "Fórmula: $$S_{\\infty} = \\frac{a_1}{1 - r}$$\n\nNo te dejes engañar por la simplicidad. El peligro está en el manejo de los signos y las fracciones en el denominador.\n\nEjemplo con fracciones: Serie infinita de $18, 6, 2, 2/3 \\dots$\n- $a_1 = 18$.\n- $r = 6/18 = 1/3$.\n- Aplicamos fórmula: $S_{\\infty} = \\frac{18}{1 - 1/3}$\n- Truco para el denominador: $1$ es lo mismo que $3/3$. Así que $3/3 - 1/3 = 2/3$.\n- Nos queda: $S_{\\infty} = \\frac{18}{2/3}$\n- Dividir por una fracción es multiplicar por ella invertida: $18 \\cdot \\frac{3}{2} = \\frac{54}{2} = 27$.\n\n¡La suma de todos esos infinitos números da clavado 27!",
    "procedimiento": ["Paso 1: Detecta $a_1$ y 'r'.", "Paso 2: Resta la razón a 1 ($1 - r$). Ten cuidado si 'r' es negativa.", "Paso 3: Si el denominador es fracción, conviértelo (1 = 4/4, 1 = 5/5, etc.).", "Paso 4: Divide $a_1$ por el resultado del denominador (regla de la herradura)."],
    "ejemplos": [
        {"titulo": "Cuidado con los signos", "enunciado": "Calcula la suma infinita de 10 - 5 + 2.5 - 1.25 ...", "solucion_pasos": ["a1 = 10. r = -5 / 10 = -0.5.", "Fórmula: S = 10 / (1 - (-0.5))", "Denominador: 1 + 0.5 = 1.5", "S = 10 / 1.5 = 100 / 15 = 20 / 3.", "La suma da exactamente 20/3 (aprox 6.66)."]}
    ],
    "errores_frecuentes": ["Olvidar la regla de los signos en el denominador cuando $r$ es negativa: calcular $(1 - 0.5)$ en lugar de $(1 - (-0.5))$.", "Enredarse en la división final cuando el denominador es una fracción (hacer mal la regla de la oreja o herradura)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SINF-CALC-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al usar la fórmula $S_\\infty = \\frac{{a_1}}{{1-r}}$, si la razón '$r$' de la sucesión resulta ser un número negativo como $-1/4$, la operación matemática correcta que ocurre en el denominador de la fórmula es: (v{i})", "choices": ["A) Una suma, transformándose en $1 + 1/4$.", "B) Una resta directa, quedando $1 - 1/4$.", "C) Una multiplicación, quedando $1 \\cdot (-1/4)$.", "D) El denominador se vuelve cero."], "correct_answer": "A) Una suma, transformándose en $1 + 1/4$.", "solution_steps": "La fórmula es $(1 - r)$. Al ser r negativo, es $1 - (-1/4)$, lo cual es $1 + 1/4$ (regla de signos).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SINF-CALC-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Para realizar la división final $\\frac{10}{2/5}$ que resulta al aplicar la fórmula de la serie infinita, la operación equivalente más rápida es:", "choices": ["A) Multiplicar $10$ por $5/2$.", "B) Dividir $10$ entre $5$ y multiplicar por $2$.", "C) Multiplicar $10$ por $2$ y dividir por $5$.", "D) Restar $2/5$ a $10$."], "correct_answer": "A) Multiplicar $10$ por $5/2$.", "solution_steps": "Dividir por una fracción es matemáticamente idéntico a multiplicar por esa fracción invertida.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SINF-CALC-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La suma infinita de la progresión geométrica donde $a_1=50$ y $r=0.5$ resulta ser exactamente $100$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "S = 50 / (1 - 0.5) = 50 / 0.5 = 100. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SINF-CALC-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Una pelota de goma se deja caer desde una altura inicial de $30$ metros. Tras chocar con el suelo, rebota alcanzando exactamente $\\frac{{2}}{{3}}$ de su altura anterior en cada nuevo bote. Si sumamos TODAS las distancias verticales que la pelota recorre (ignorando el rebote de subida y contando solo las bajadas) hasta que finalmente queda en reposo, ¿qué distancia total habrá recorrido de bajada? (v{i})", "choices": ["A) $90$ metros.", "B) $60$ metros.", "C) $30$ metros.", "D) $50$ metros."], "correct_answer": "A) $90$ metros.", "solution_steps": "Es la serie infinita de bajadas. a1 = 30, r = 2/3. S = 30 / (1 - 2/3) = 30 / (1/3) = 30 * 3 = 90 metros.", "paes_style": True})

# 3. INTERPRETACION_LIMITE
sid3 = "MAT.NUM.SERIE_GEOMETRICA.INTERPRETACION_LIMITE"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Interpretar el valor de una serie geométrica infinita no como un número a alcanzar, sino como un límite teórico (asíntota) del proceso.",
    "introduccion": "En la vida real, nadie puede sumar 'infinitas' veces. La paradoja de Zenón decía que Aquiles nunca alcanzaría a la tortuga porque siempre habría una distancia a la mitad que recorrer. Las matemáticas lo resolvieron con el concepto de 'Límite'.",
    "resumen": "El valor $S_{\\infty}$ es un **Límite Teórico** (una Asíntota). Esto significa que la suma acumulada de los números reales jamás superará (ni tocará exactamente) ese valor en la realidad, pero se acercará a él microscópicamente tanto como quieras.",
    "explicacion": "Imagina que tienes una torta. El primer día comes la mitad (1/2). El segundo día comes la mitad de lo que quedó (1/4). El tercero la mitad de eso (1/8)....\n- Serie: $1/2 + 1/4 + 1/8 \\dots$\n- Cálculo: $S = \\frac{1/2}{1 - 1/2} = \\frac{1/2}{1/2} = 1$.\n\nLa fórmula dice que el total es '1 torta entera'.\n- ¿Te la comerás toda alguna vez en la realidad? **NO.** Siempre quedará una miguita que partirás a la mitad al día siguiente.\n- Entonces, ¿qué significa ese '1'? Es tu **Techo Insuperable**. Significa que jamás necesitarás ir a comprar una segunda torta, no importa cuántos días repitas el proceso.\n\nEn PAES, las preguntas no siempre te pedirán calcular, sino interpretar qué significa ese techo en el contexto del problema (capacidad máxima de un estanque, distancia límite, etc).",
    "procedimiento": ["Paso 1: Calcula el valor de la serie infinita.", "Paso 2: Acompáñalo verbalmente con palabras clave como 'límite', 'techo', 'no se superará', o 'tiende a'.", "Paso 3: Aplica esta idea al contexto (Ej: 'La población de abejas no superará los 1000 ejemplares')."],
    "ejemplos": [
        {"titulo": "El estanque de químicos", "enunciado": "A un estanque se le vierten 100L de químico, luego 50L, luego 25L, al infinito. Si el estanque hace 200L, ¿se rebalsará?", "solucion_pasos": ["Calculamos S = 100 / (1 - 0.5) = 200.", "La serie infinita da 200.", "Interpretación: Al infinito, el volumen tenderá a 200L. Pero jamás los superará. No se rebalsará."]}
    ],
    "errores_frecuentes": ["Creer que en algún paso específico 'n' se alcanza el valor de la serie infinita (Nunca se alcanza en un paso 'n' finito).", "Interpretar el límite como un promedio o un valor constante, en vez de entenderlo como el 'acumulado tope'."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INLIM-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde una perspectiva conceptual, cuando decimos que la serie infinita $\\frac{1}{2} + \\frac{1}{4} + \\frac{1}{8} + \\dots$ es igual a $1$, estamos declarando rigurosamente que: (v{i})", "choices": ["A) A medida que vamos agregando más y más términos a la suma, el valor acumulado se acerca cada vez más a $1$, usándolo como un techo o límite matemático que nunca se supera.", "B) Exactamente en el último paso de la serie, el valor se vuelve un $1$ sólido.", "C) La suma de los dos primeros términos da $1$.", "D) El promedio de todos los números es $1$."], "correct_answer": "A) A medida que vamos agregando más y más términos a la suma, el valor acumulado se acerca cada vez más a $1$, usándolo como un techo o límite matemático que nunca se supera.", "solution_steps": "La serie infinita representa una asíntota, el valor al que 'tiende' el total pero que nunca se alcanza en una cantidad finita de pasos.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INLIM-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Un ingeniero diseña una batería que en su primer ciclo de recarga almacena $1000$ mAh, y en cada recarga sucesiva almacena el $50\\%$ de la recarga anterior. La suma infinita da $2000$ mAh. ¿Qué palabra clave utilizarías en un informe para interpretar correctamente este número?", "choices": ["A) El 'límite' máximo de capacidad teórica acumulada.", "B) El 'promedio' de carga por ciclo.", "C) La 'velocidad' de recarga.", "D) El 'porcentaje' de vida útil."], "correct_answer": "A) El 'límite' máximo de capacidad teórica acumulada.", "solution_steps": "El total de una serie infinita actúa como el límite asintótico.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INLIM-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si el límite teórico de la dosis total acumulada de un fármaco (calculado como serie infinita) es $50$ mg, significa que es matemáticamente imposible que el paciente supere alguna vez esa dosis en su cuerpo bajo este tratamiento?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El límite de la serie es el techo supremo e insuperable. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INLIM-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un grifo defectuoso gotea agua en un recipiente de vidrio. En la primera hora gotea $500$ ml. En la segunda hora gotea $250$ ml, en la tercera $125$ ml, y así sucesivamente reduciendo el goteo a la mitad. Si el recipiente de vidrio tiene una capacidad total máxima de $1$ litro ($1000$ ml) antes de desbordarse, ¿qué ocurrirá si dejamos el recipiente bajo el grifo de forma permanente? (v{i})", "choices": ["A) El recipiente jamás se desbordará, porque el volumen total acumulado tenderá a $1000$ ml como su límite máximo insuperable.", "B) El recipiente se desbordará en exactamente 4 horas.", "C) El recipiente se desbordará al cabo de infinitas horas.", "D) El recipiente jamás superará los $500$ ml de volumen acumulado."], "correct_answer": "A) El recipiente jamás se desbordará, porque el volumen total acumulado tenderá a $1000$ ml como su límite máximo insuperable.", "solution_steps": "La serie infinita es $S = 500 / (1 - 0.5) = 500 / 0.5 = 1000$ ml. El agua acumulada tenderá a este valor pero nunca lo sobrepasará (y por tanto, no se rebalsará).", "paes_style": True})

# 4. PA_VS_PG
sid4 = "MAT.NUM.PROGRESIONES_COMPARACION.PA_VS_PG"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Distinguir entre una progresión aritmética (P.A.) y una geométrica (P.G.) analizando el comportamiento de sus términos.",
    "introduccion": "En el examen PAES, casi nunca te dicen 'hola, soy una progresión aritmética'. Te entregan un problema con números crudos. Si te equivocas al clasificarlos, aplicarás la fórmula equivocada. Es vital saber qué bestia enfrentamos.",
    "resumen": "Si la diferencia (resta) entre términos vecinos es constante, es una **Progresión Aritmética (P.A.)**. Si el cociente (división) entre términos vecinos es constante, es una **Progresión Geométrica (P.G.)**.",
    "explicacion": "El test de paternidad de las sucesiones:\nTe dan la lista: $3, 12, 21, 30$\n- **Prueba A (Restar):** $12-3=9$. $21-12=9$. $30-21=9$. \n- ¡Bingo! Pasa la prueba aritmética. Su diferencia es $d=9$.\n\nTe dan la lista: $3, 12, 48, 192$\n- **Prueba A (Restar):** $12-3=9$. $48-12=36$. \n- ¡Fallo! No es aritmética. Vamos al plan B.\n- **Prueba B (Dividir):** $12/3=4$. $48/12=4$. $192/48=4$.\n- ¡Bingo! Es una geométrica con razón $r=4$.\n\nCuidado con las 'trampas PAES': Secuencias como $1, 4, 9, 16, 25$. Si haces la prueba de restar da $3, 5, 7, 9$. Si haces la de dividir da $4, 2.25, 1.77$. ¡No pasa ninguna! No te asustes, no todo en la vida es P.A. o P.G. (estas son los cuadrados perfectos).",
    "procedimiento": ["Paso 1: Toma el 2do y 1er término. Réstalos. Luego divide el 2do entre el 1ro.", "Paso 2: Haz lo mismo con el 3er y 2do término.", "Paso 3: Si las RESTAS dieron igual, usa fórmulas de P.A.", "Paso 4: Si las DIVISIONES dieron igual, usa fórmulas de P.G.", "Paso 5: Si ninguna da igual, detente, el problema se resuelve con otra lógica."],
    "ejemplos": [
        {"titulo": "Clasificando la deuda", "enunciado": "Tus cuotas a pagar son: mes 1 = $500, mes 2 = $550, mes 3 = $605, mes 4 = $665.5. ¿Qué tipo de sucesión es?", "solucion_pasos": ["Prueba A: 550 - 500 = 50. 605 - 550 = 55. Fallo, no es Aritmética.", "Prueba B: 550 / 500 = 1.1. 605 / 550 = 1.1. 665.5 / 605 = 1.1.", "Conclusión: Es Geométrica (aumenta un 10% mensual)."]}
    ],
    "errores_frecuentes": ["Detener la verificación en el segundo término asumiendo que el patrón se mantiene (Ej: $2, 4, 8, 10$ parece geométrica al principio porque $4/2=2$ y $8/4=2$, pero el 10 la arruina).", "Confundir P.A. con P.G. al trabajar con fracciones."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PAPG-COMP-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la prueba analítica definitiva para confirmar que una sucesión de números pertenece exclusivamente a la familia de las Progresiones Aritméticas (P.A.) y descartar que sea Geométrica? (v{i})", "choices": ["A) Comprobar que la resta (diferencia) entre cualquier término y su predecesor es un número constante a lo largo de toda la secuencia.", "B) Comprobar que la división entre cualquier término y su predecesor es constante.", "C) Verificar que los números vayan aumentando.", "D) Sumar todos los números y ver si el resultado es par."], "correct_answer": "A) Comprobar que la resta (diferencia) entre cualquier término y su predecesor es un número constante a lo largo de toda la secuencia.", "solution_steps": "Restas iguales = P.A. (Diferencia común). Divisiones iguales = P.G. (Razón).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PAPG-COMP-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Dada la secuencia de números $50, 45, 40, 35, 30$, al aplicar las pruebas de clasificación determinamos que:", "choices": ["A) Es una Progresión Aritmética porque la diferencia es constante ($d = -5$).", "B) Es una Progresión Geométrica porque la razón es constante.", "C) Es ambas cosas a la vez.", "D) No es ni Aritmética ni Geométrica."], "correct_answer": "A) Es una Progresión Aritmética porque la diferencia es constante ($d = -5$).", "solution_steps": "Prueba de resta: $45 - 50 = -5$. $40 - 45 = -5$. Las restas son constantes.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PAPG-COMP-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La sucesión de números negativos $-2, -4, -8, -16$ es una Progresión Aritmética con diferencia $d = -2$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Prueba de resta: $-4 - (-2) = -2$. $-8 - (-4) = -4$. Falló la resta. Es Geométrica (razón 2).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PAPG-COMP-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un investigador tiene cuatro muestras de datos correspondientes al crecimiento semanal de distintas colonias de bacterias bajo diferentes dietas. ¿Cuál de los siguientes registros de datos debe ser analizado utilizando las fórmulas de una Progresión Geométrica? (v{i})", "choices": ["A) Muestra Alfa: $10, 30, 90, 270$", "B) Muestra Beta: $10, 20, 30, 40$", "C) Muestra Gamma: $10, 15, 20, 25$", "D) Muestra Delta: $10, 12, 16, 22$"], "correct_answer": "A) Muestra Alfa: $10, 30, 90, 270$", "solution_steps": "La muestra Alfa tiene un cociente constante: $30/10=3; 90/30=3; 270/90=3$. Es la única geométrica.", "paes_style": True})

# 5. CAMBIO_ADITIVO_MULTIPLICATIVO
sid5 = "MAT.NUM.PROGRESIONES_COMPARACION.CAMBIO_ADITIVO_MULTIPLICATIVO"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Diferenciar entre situaciones reales que presentan cambio aditivo (lineal) y cambio multiplicativo (exponencial).",
    "introduccion": "¿Tu sueldo crece de la misma manera que una infección viral? Afortunadamente no (o lamentablemente, dependiendo cómo lo mires). El universo matemático tiene dos engranajes principales: el que suma y el que multiplica.",
    "resumen": "El **cambio aditivo** (P.A.) suma o resta cantidades fijas (ej: $+ $\$1000$ diarios$). El **cambio multiplicativo** (P.G.) multiplica por factores fijos, generalmente descritos como porcentajes o palabras de proporción (ej: aumenta un $10\\%$, o se *triplica*).",
    "explicacion": "Lee atentamente los enunciados. Tienes que ser un detective de palabras clave:\n\n**Señales de Cambio Aditivo (Usa Progresión Aritmética):**\n- 'Aumenta en 5 litros por minuto'\n- 'Suma $\$500$ cada día'\n- 'Pierde 3 puntos por cada error'\n- Características: La gráfica de este crecimiento es una línea recta (Función Lineal).\n\n**Señales de Cambio Multiplicativo (Usa Progresión Geométrica):**\n- 'Aumenta un $5\\%$ mensual' (Porcentajes = Siempre P.G.)\n- 'Se duplica, se triplica, se reduce a la mitad'\n- 'Por cada hora, crece a un factor de 1.5'\n- Características: La gráfica es una curva que despega violentamente o cae en picada (Función Exponencial).",
    "procedimiento": ["Paso 1: Busca la palabra que describe cómo ocurre el cambio en el tiempo.", "Paso 2: Si el cambio se expresa en unidades directas (metros, pesos, litros), el modelo es Aditivo (P.A.).", "Paso 3: Si el cambio se expresa en multiplicadores ('el doble') o porcentajes ('15%'), el modelo es Multiplicativo (P.G.)."],
    "ejemplos": [
        {"titulo": "Contrato A vs Contrato B", "enunciado": "Contrato A: Sueldo inicial 1 millón, sube $50.000 cada año. Contrato B: Sueldo inicial 1 millón, sube 5% cada año. Clasifícalos.", "solucion_pasos": ["Contrato A: Sube una cantidad en pesos directos (50.000). Es un cambio Aditivo (Progresión Aritmética).", "Contrato B: Sube en base a un porcentaje (5%). Es un cambio Multiplicativo (Progresión Geométrica).", "Al principio son parecidos, pero a largo plazo el Contrato B ganará por goleada exponencial."]}
    ],
    "errores_frecuentes": ["Confundir un porcentaje fijo con un cambio aditivo (Ej: 'Si sube 10% cada año, es una suma constante'. No, porque ese 10% se calcula sobre montos cada vez más grandes, es multiplicativo).", "Asumir que si la cantidad restada es muy grande, debe ser exponencial."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ADIMULT-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde el punto de vista del modelamiento matemático, ¿cuál de las siguientes expresiones verbales describe inequívocamente un proceso de crecimiento de naturaleza 'multiplicativa' (geométrica)? (v{i})", "choices": ["A) 'El valor de la acción bursátil aumenta en un $3\\%$ al finalizar cada día hábil'.", "B) 'La tarifa de gas cobra un recargo fijo de $\$500$ por cada metro cúbico extra consumido'.", "C) 'El taxímetro suma $\$100$ por cada semáforo en rojo'.", "D) 'El balde de agua pierde $2$ litros cada media hora'."], "correct_answer": "A) 'El valor de la acción bursátil aumenta en un $3\\%$ al finalizar cada día hábil'.", "solution_steps": "Los porcentajes implican multiplicar el total anterior por un factor (ej: 1.03), por lo que definen siempre un cambio multiplicativo/exponencial.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ADIMULT-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en un experimento de física se describe que 'la temperatura del motor aumenta a razón de $5°C$ constantes por cada minuto en funcionamiento', el modelo matemático pertinente a usar es:", "choices": ["A) Un modelo Aditivo (Progresión Aritmética).", "B) Un modelo Multiplicativo (Progresión Geométrica).", "C) Un modelo Logarítmico.", "D) Una Serie Infinita."], "correct_answer": "A) Un modelo Aditivo (Progresión Aritmética).", "solution_steps": "Añadir una cantidad física absoluta (como 5 grados) de forma constante es el sello distintivo del cambio aditivo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ADIMULT-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Un préstamo bancario donde la deuda crece aplicando un 'interés del $4\\%$ compuesto mensual' se modela utilizando una Progresión Aritmética?", "choices": [], "correct_answer": "Falso", "solution_steps": "El interés compuesto es el ejemplo clásico de crecimiento porcentual continuo, el cual es de naturaleza multiplicativa (Geométrica), no aritmética.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ADIMULT-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Dos ciudades, X e Y, buscan predecir su crisis hídrica para el año $2030$. Los informes hidrológicos señalan lo siguiente: \n- Informe Ciudad X: 'Las reservas de agua dulce disminuyen en un $10\\%$ respecto al año inmediatamente anterior'.\n- Informe Ciudad Y: 'Las reservas de agua dulce disminuyen en $1.500.000$ de litros todos los años'.\n¿Qué tipo de progresiones matemáticas modelan el comportamiento de las reservas en la Ciudad X y la Ciudad Y, respectivamente? (v{i})", "choices": ["A) Ciudad X: Progresión Geométrica / Ciudad Y: Progresión Aritmética.", "B) Ciudad X: Progresión Aritmética / Ciudad Y: Progresión Geométrica.", "C) Ambas se modelan con Progresión Aritmética.", "D) Ambas se modelan con Progresión Geométrica."], "correct_answer": "A) Ciudad X: Progresión Geométrica / Ciudad Y: Progresión Aritmética.", "solution_steps": "Ciudad X usa porcentajes (cambio multiplicativo = Geométrica). Ciudad Y usa resta directa de litros fijos (cambio aditivo = Aritmética).", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 7 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 7 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-7", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-7.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
