# scratch/build_b0206_t5.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. RECONOCIMIENTO P.G.
sid1 = "MAT.NUM.PROG_GEOMETRICA.RECONOCIMIENTO"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Auditar una lista de números para determinar rápidamente si califica o no como progresión geométrica.",
    "introduccion": "No todo lo que crece rápido es una progresión geométrica. Algunas sucesiones tienen trampas. Así como en las aritméticas comprobábamos restando, aquí seremos los inspectores de la multiplicación.",
    "resumen": "Para confirmar que una secuencia es Progresión Geométrica (P.G.), debes verificar que al **dividir** cualquier término por su antecesor, el resultado ('$r$') sea siempre idéntico para todos los pares consecutivos entregados.",
    "explicacion": "Una secuencia sospechosa: $2, 6, 18, 36$.\nVamos a auditarla paso a paso:\n1. $6 / 2 = 3$\n2. $18 / 6 = 3$\n3. $36 / 18 = 2$ $\\rightarrow$ **¡Fallo!** Aunque empezó bien multiplicando por 3, al final se multiplicó por 2. No es una P.G.\n\nTambién puedes toparte con secuencias alternadas como $5, -10, 20, -40$.\n1. $-10 / 5 = -2$\n2. $20 / -10 = -2$\n3. $-40 / 20 = -2$\n¡Éxito! Todas las divisiones dan $-2$. Es una P.G. perfectamente válida.",
    "procedimiento": ["Paso 1: Toma el segundo número y divídelo por el primero.", "Paso 2: Toma el tercer número y divídelo por el segundo.", "Paso 3: Sigue así con todos los números que te hayan dado.", "Paso 4: Si todas las divisiones dan el mismo resultado exacto, es una P.G. Si una sola falla, la rechazas."],
    "ejemplos": [
        {"titulo": "Desenmascarando al impostor", "enunciado": "¿La secuencia $1, 4, 9, 16$ es una progresión geométrica?", "solucion_pasos": ["Dividimos 4/1 = 4.", "Dividimos 9/4 = 2.25.", "Como 4 y 2.25 son distintos, no necesitamos seguir. NO es geométrica. (En realidad, son los cuadrados perfectos)."]}
    ],
    "errores_frecuentes": ["Comprobar solo los primeros dos números y dar por hecho que la regla se cumple para el resto.", "Creer que si tiene números negativos o fracciones no puede ser geométrica. Las progresiones con razón fraccionaria o negativa son las favoritas en la PAES."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPG-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Para demostrar irrefutablemente que una lista de $4$ números ($a_1, a_2, a_3, a_4$) conforma una progresión geométrica, ¿qué debes comprobar? (v{i})", "choices": [r"A) Que las tres divisiones $\frac{{a_2}}{{a_1}}, \frac{{a_3}}{{a_2}}$ y $\frac{{a_4}}{{a_3}}$ den el mismo resultado.", r"B) Que la división $\frac{{a_2}}{{a_1}}$ dé un número entero.", r"C) Que las restas entre los términos sean constantes.", r"D) Que al multiplicar todos los números el resultado sea par."], "correct_answer": r"A) Que las tres divisiones $\frac{{a_2}}{{a_1}}, \frac{{a_3}}{{a_2}}$ y $\frac{{a_4}}{{a_3}}$ den el mismo resultado.", "solution_steps": "Debes probar cada par de vecinos dividiendo el posterior entre el anterior.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"RECPG-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál de las siguientes sucesiones verbales describe de forma pura una progresión geométrica?", "choices": ["A) La cantidad de bacterias en una herida se triplica cada dos horas.", "B) Cada mes guardo $5.000$ pesos en mi cuenta.", "C) La temperatura sube $1$ grado cada minuto.", "D) El taxi cobra $200$ pesos por cuadra."], "correct_answer": "A) La cantidad de bacterias en una herida se triplica cada dos horas.", "solution_steps": "Triplicarse significa multiplicar por 3 en cada intervalo de tiempo. Crecimiento multiplicativo = Geométrica.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPG-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La sucesión de números $100, 50, 25, 12.5$ es una Progresión Geométrica verdadera?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "50/100 = 0.5. 25/50 = 0.5. 12.5/25 = 0.5. Como todos dan el mismo cociente, es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"RECPG-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En un laboratorio se registran los tamaños (en mm) de un cultivo de hongos durante $4$ días consecutivos, obteniendo los siguientes cuatro grupos de datos. ¿Cuál de estos registros representa un crecimiento puramente geométrico? (v{i})", "choices": ["A) $3, 12, 48, 192$", "B) $2, 4, 6, 8$", "C) $5, 25, 50, 100$", "D) $10, 30, 60, 180$"], "correct_answer": "A) $3, 12, 48, 192$", "solution_steps": "A) $12/3=4; 48/12=4; 192/48=4$. Todas dan 4. La C y D fallan en la segunda división.", "paes_style": True})

# 2. TERMINO_GENERAL P.G.
sid2 = "MAT.NUM.PROG_GEOMETRICA.TERMINO_GENERAL"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Aplicar la fórmula del término general de una progresión geométrica para encontrar cualquier valor en la secuencia.",
    "introduccion": "Si un rumor empieza contigo y se lo cuentas a 3 personas, y cada uno a otras 3... ¿cuántos sabrán el rumor en el paso 10? No puedes sumar. Aquí los saltos son exponentes. Bienvenido al término general geométrico.",
    "resumen": "La fórmula maestra para hallar cualquier término en una P.G. es: $a_n = a_1 \\cdot r^{(n - 1)}$. Necesitas el primer término ($a_1$), la razón ($r$) y la posición que buscas ($n$).",
    "explicacion": "Anatomía de la fórmula: **$a_n = a_1 \\cdot r^{(n - 1)}$**\n- **$a_n$**: Es el número gigante o pequeñito que quieres descubrir.\n- **$a_1$**: Es tu punto de inicio.\n- **$r$**: Es el multiplicador (la razón).\n- **$(n - 1)$**: Es la cantidad de saltos que darás. Como empezamos en el salto cero (la posición 1), el exponente siempre es uno menos que la posición.\n\nEjemplo: Tienes la progresión $2, 6, 18\\dots$ y te piden el término 5.\n- $a_1 = 2$\n- $r = 3$ (porque $6/2=3$)\n- $n = 5$\nFórmula: $a_5 = 2 \\cdot 3^{(5 - 1)} \\rightarrow 2 \\cdot 3^4 \\rightarrow 2 \\cdot 81 = 162$.",
    "procedimiento": ["Paso 1: Extrae a1 (el primer término).", "Paso 2: Calcula la razón 'r' dividiendo el 2do por el 1ro.", "Paso 3: Identifica la posición 'n'.", "Paso 4: Eleva 'r' a la potencia $(n-1)$.", "Paso 5: Multiplica ese resultado por $a_1$."],
    "ejemplos": [
        {"titulo": "Plegando el papel", "enunciado": "Doblas una hoja de papel por la mitad. Luego otra vez. El grosor inicial es 0.1 mm y se duplica en cada doblez. ¿Cuál será el grosor en el doblez número 7?", "solucion_pasos": ["a1 = 0.1 mm. r = 2. n = 7.", "Fórmula: a7 = 0.1 * 2^(7-1)", "a7 = 0.1 * 2^6", "2^6 = 64.", "a7 = 0.1 * 64 = 6.4 mm."]}
    ],
    "errores_frecuentes": ["Multiplicar $a_1$ por '$r$' ANTES de elevar al exponente. Por ejemplo, en $2 \\cdot 3^4$, multiplicar $6^4$ (incorrecto) en vez de $2 \\cdot 81$ (correcto). ¡Papomudas: potencias primero!", "Olvidar restar 1 al exponente (usar $r^n$ en lugar de $r^{n-1}$)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPG-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al utilizar la fórmula $a_n = a_1 \\cdot r^{{(n-1)}}$, ¿por qué la razón '$r$' se eleva a un exponente en lugar de multiplicarse por '$n$' como en las progresiones aritméticas? (v{i})", "choices": ["A) Porque en una progresión geométrica el avance se realiza multiplicando sucesivamente por '$r$', y las multiplicaciones repetidas se abrevian como potencias.", "B) Porque la fórmula fue diseñada para números muy grandes.", "C) Porque la razón siempre es un número mayor que 1.", "D) Porque '$n$' representa una raíz cuadrada oculta."], "correct_answer": "A) Porque en una progresión geométrica el avance se realiza multiplicando sucesivamente por '$r$', y las multiplicaciones repetidas se abrevian como potencias.", "solution_steps": "Multiplicar por 'r' cinco veces es $r \\cdot r \\cdot r \\cdot r \\cdot r$, que es lo mismo que $r^5$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TGENPG-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Según la jerarquía de operaciones, al resolver la expresión $5 \\cdot 2^3$ para encontrar un término geométrico, el primer paso obligatorio es:", "choices": ["A) Elevar $2$ al cubo ($2^3 = 8$).", "B) Multiplicar $5$ por $2$ ($10$) y luego elevar al cubo.", "C) Sumar $5$ más $2$.", "D) Multiplicar $5$ por $3$."], "correct_answer": "A) Elevar $2$ al cubo ($2^3 = 8$).", "solution_steps": "Las potencias siempre se resuelven antes que las multiplicaciones. $5 \\cdot 8 = 40$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPG-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El cuarto término ($a_4$) de una progresión geométrica que empieza en $3$ y tiene razón $2$, es exactamente $24$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$a_4 = 3 \\cdot 2^{4-1} = 3 \\cdot 2^3 = 3 \\cdot 8 = 24$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENPG-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una plataforma de videos online se vuelve viral. El día 1 tuvo $1.000$ visitas. Los expertos en análisis de datos notan que cada día que pasa, las visitas diarias se triplican respecto al día anterior ($r=3$). Según este modelo, ¿cuántas visitas exactas tendrá la plataforma durante el día 5? (v{i})", "choices": ["A) $81.000$ visitas.", "B) $243.000$ visitas.", "C) $15.000$ visitas.", "D) $9.000$ visitas."], "correct_answer": "A) $81.000$ visitas.", "solution_steps": "a1 = 1000, r = 3, n = 5. Fórmula: a5 = 1000 * 3^(5-1) = 1000 * 3^4 = 1000 * 81 = 81.000.", "paes_style": True})

# 3. CALCULO_PRIMER_TERMINO P.G.
sid3 = "MAT.NUM.PROG_GEOMETRICA.CALCULO_PRIMER_TERMINO"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Despejar y calcular el primer término ($a_1$) de una P.G. conociendo un término cualquiera y la razón.",
    "introduccion": "Imagina que entras a la cocina y ves un pan gigante que triplicó su tamaño tres veces seguidas. ¿De qué tamaño era la bolita de masa original? Tenemos que rebobinar la película usando divisiones.",
    "resumen": "Para hallar el término inicial ($a_1$) conociendo un término lejano ($a_n$), debes despejar la fórmula general pasando la potencia dividiendo: $a_1 = \\frac{a_n}{r^{(n - 1)}}$.",
    "explicacion": "Sabemos que $a_n = a_1 \\cdot r^{(n-1)}$.\nSi la incógnita es $a_1$, el bloque multiplicativo de la razón $r^{(n-1)}$ debe cruzar al otro lado haciendo la operación contraria (dividiendo).\n\n**Fórmula despejada:**\n$$a_1 = \\frac{a_n}{r^{(n - 1)}}$$\n\nLógica: 'Tomo el número gigante de la posición $n$ y lo divido todas las veces que fue multiplicado para encogerlo de vuelta a su tamaño original'.\n\nEjemplo: Sabemos que el término 4 vale 54 ($a_4=54$) y la razón es 3 ($r=3$).\n- $a_1 = \\frac{54}{3^{(4-1)}}$\n- $a_1 = \\frac{54}{3^3}$\n- $a_1 = \\frac{54}{27} = 2$. \n¡La bolita original valía 2!",
    "procedimiento": ["Paso 1: Identifica tu término de destino ($a_n$) y su posición ($n$).", "Paso 2: Identifica la razón geométrica ($r$).", "Paso 3: Eleva la razón al exponente $(n-1)$ para saber cuál fue el factor total de multiplicación.", "Paso 4: Divide el término de destino ($a_n$) por ese factor."],
    "ejemplos": [
        {"titulo": "Desinflando el número", "enunciado": "El 5to término de una progresión geométrica es 160. Su razón es 2. Halla el primer término.", "solucion_pasos": ["Datos: a5 = 160, r = 2, n = 5.", "Factor total: 2^(5-1) = 2^4 = 16.", "Despejamos a1: 160 / 16.", "a1 = 10."]}
    ],
    "errores_frecuentes": ["Olvidar elevar a la potencia $(n-1)$ y dividir simplemente $a_n / r$ (lo cual solo te retrocedería una posición, en vez de volver hasta el inicio).", "Equivocarse en el cálculo de la potencia en el denominador (ej. decir que $2^4 = 8$ en vez de 16)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CINI-PG-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al despejar matemáticamente el primer término '$a_1$' de la ecuación $a_n = a_1 \\cdot r^{{(n-1)}}$, la expresión final correcta es: (v{i})", "choices": [r"A) $a_1 = \frac{{a_n}}{{r^{(n-1)}}}$", r"B) $a_1 = a_n \cdot r^{(n-1)}$", r"C) $a_1 = a_n - r^{(n-1)}$", r"D) $a_1 = \frac{{r^{(n-1)}}}{{a_n}}$"], "correct_answer": r"A) $a_1 = \frac{{a_n}}{{r^{(n-1)}}}$", "solution_steps": "La potencia completa pasa al otro lado dividiendo al término $a_n$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CINI-PG-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Desde un enfoque lógico, si un término ha sido multiplicado por la razón '$r$' un total de $3$ veces para llegar a su tamaño actual, ¿qué debes hacer para regresarlo a su tamaño original?", "choices": ["A) Dividirlo entre $r^3$.", "B) Restarle $3r$.", "C) Dividirlo entre $3r$.", "D) Multiplicarlo por $r^{-1}$."], "correct_answer": "A) Dividirlo entre $r^3$.", "solution_steps": "Si multiplicas por 'r' tres veces, el factor es $r^3$. Lo opuesto es dividir por $r^3$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CINI-PG-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si el tercer término de una progresión geométrica es $100$ y la razón es $10$, entonces su primer término ($a_1$) vale $1$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "a1 = 100 / (10^(3-1)) = 100 / 10^2 = 100 / 100 = 1. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CINI-PG-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un inversionista revisa su cuenta en un fondo mutuo agresivo. Nota que su capital se ha estado duplicando matemáticamente cada año ($r=2$). En el año número $6$ de su inversión (posición $6$), el saldo de su cuenta es de $\$640.000$. ¿Cuánto dinero depositó originalmente en el año $1$ para iniciar este fondo? (v{i})", "choices": ["A) $\$20.000$", "B) $\$10.000$", "C) $\$32.000$", "D) $\$5.000$"], "correct_answer": "A) $\$20.000$", "solution_steps": "a6 = 640.000, n = 6, r = 2. a1 = 640.000 / 2^(6-1) = 640.000 / 2^5 = 640.000 / 32 = 20.000.", "paes_style": True})

# 4. CALCULO_INDICE P.G.
sid4 = "MAT.NUM.PROG_GEOMETRICA.CALCULO_INDICE"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Despejar y calcular la posición (n) de un número en una P.G. utilizando bases iguales o logaritmos simples.",
    "introduccion": "Empiezas con 2 bacterias. Se duplican cada hora. De pronto, tienes 1.024 bacterias. ¿Cuántas horas han pasado? Encontrar la incógnita en el exponente es el reto de este recurso.",
    "resumen": "Para encontrar la posición '$n$', la ecuación queda como $r^{(n-1)} = \\frac{a_n}{a_1}$. Debes igualar las bases a ambos lados para descubrir el exponente, y luego sumarle 1.",
    "explicacion": "En el mundo de las progresiones aritméticas, despejábamos '$n$' dividiendo. Aquí '$n$' está escondida en un exponente. ¡Estamos lidiando con una **Ecuación Exponencial**!\n\nProcedimiento de despeje:\n1. $a_n = a_1 \\cdot r^{(n-1)}$\n2. Pasamos $a_1$ dividiendo: $\\frac{a_n}{a_1} = r^{(n-1)}$\n3. Ahora debemos expresar el número de la izquierda como una potencia que tenga la misma base '$r$'.\n\nEjemplo: $a_1 = 5, r = 2$. ¿Qué posición ocupa el número 160?\n- $\\frac{160}{5} = 2^{(n-1)}$\n- $32 = 2^{(n-1)}$\n- Expresamos 32 como potencia de 2: sabemos que $32 = 2^5$.\n- Entonces: $2^5 = 2^{(n-1)}$\n- Igualamos exponentes: $5 = n - 1 \\rightarrow n = 6$.\n¡El número 160 está en la posición 6!",
    "procedimiento": ["Paso 1: Divide el término final por el término inicial ($a_n / a_1$).", "Paso 2: Escribe ese resultado como una potencia usando como base a tu razón 'r'.", "Paso 3: Iguala los exponentes.", "Paso 4: Despeja 'n' (normalmente sumando 1 al otro lado)."],
    "ejemplos": [
        {"titulo": "El salto cuántico", "enunciado": "La P.G. es 3, 9, 27... ¿En qué posición está el número 243?", "solucion_pasos": ["a1 = 3, r = 3.", "243 = 3 * 3^(n-1)", "243 / 3 = 81", "81 = 3^(n-1)", "Sabemos que 81 = 3^4.", "4 = n - 1 -> n = 5."]}
    ],
    "errores_frecuentes": ["Olvidar sumar el '+1' al final, entregando solo el número de saltos como respuesta.", "No saber transformar el resultado de la división en una potencia de igual base."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CIND-PG-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al intentar encontrar la posición '$n$' en la ecuación $64 = 2^{{(n-1)}}$, el método algebraico para resolver esta incógnita en el exponente se basa en el principio de: (v{i})", "choices": ["A) Igualación de bases, convirtiendo el $64$ a una potencia de base $2$.", "B) División simple, dividiendo $64$ entre $2$.", "C) Sacar la raíz cuadrada de $64$.", "D) Multiplicar $64$ por $2$."], "correct_answer": "A) Igualación de bases, convirtiendo el $64$ a una potencia de base $2$.", "solution_steps": "El principio de las ecuaciones exponenciales básicas es tener la misma base en ambos lados ($2^6 = 2^{n-1}$).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CIND-PG-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en medio de un problema de progresión geométrica llegas a la expresión $3^4 = 3^{(n-1)}$, ¿qué ecuación lineal simple debes resolver a continuación para terminar?", "choices": ["A) $4 = n - 1$", "B) $3 = n - 1$", "C) $4 = 3n$", "D) $n = 4 - 1$"], "correct_answer": "A) $4 = n - 1$", "solution_steps": "Al tener la misma base, simplemente se igualan los exponentes.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CIND-PG-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El número $1.000.000$ ocupa la posición $n=7$ en la progresión que parte de $1$ y tiene una razón constante de $10$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$1.000.000 / 1 = 10^{(n-1)}$. Sabemos que un millón es $10^6$. Por lo tanto $6 = n - 1$, lo que da $n = 7$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CIND-PG-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un correo electrónico de fraude (phishing) es reenviado de tal manera que el número de nuevas víctimas se quintuplica ($r=5$) en cada ronda de envíos. Si en la primera ronda ($n=1$) cayeron $2$ víctimas, ¿en qué ronda caerán exactamente $250$ nuevas víctimas en un solo envío? (v{i})", "choices": ["A) En la ronda $4$.", "B) En la ronda $3$.", "C) En la ronda $5$.", "D) En la ronda $125$."], "correct_answer": "A) En la ronda $4$.", "solution_steps": "a1 = 2, r = 5. Buscamos n para an=250. 250 / 2 = 125. Ecuación: 125 = 5^(n-1). Como 125 = 5^3, entonces 3 = n - 1 -> n = 4.", "paes_style": True})

# 5. SUMA_FINITA P.G.
sid5 = "MAT.NUM.PROG_GEOMETRICA.SUMA_FINITA"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Calcular la suma total acumulada de los primeros 'n' términos de una progresión geométrica.",
    "introduccion": "El inventor del ajedrez le pidió al rey 1 grano de trigo por la primera casilla, 2 por la segunda, 4 por la tercera... El rey pensó que era barato. No sabía que sumar progresiones geométricas arroja números monumentales. Descubramos cómo calcular ese total.",
    "resumen": "La suma de los primeros '$n$' términos de una P.G. (con $r \\neq 1$) se calcula con la fórmula: $S_n = \\frac{a_1 \\cdot (r^n - 1)}{r - 1}$. Aquí '$n$' SÍ actúa como exponente directo de '$r$'.",
    "explicacion": "Sumar una P.G. a mano es muy agotador. Usaremos una fórmula cerrada:\n$$S_n = \\frac{a_1 \\cdot (r^n - 1)}{r - 1}$$\n\nAnalicemos sus partes:\n- **$S_n$**: La suma total de todo lo acumulado en esos '$n$' casilleros.\n- **$a_1$**: Lo que había en el primer casillero.\n- **$r^n$**: La razón elevada a la cantidad de términos que sumarás. **¡ALERTA!** En esta fórmula SÍ elevamos a '$n$', NO a '$(n-1)$'. Este es el error número uno en las pruebas.\n\nEjemplo: Suma los 4 primeros términos de la serie $5, 15, 45, 135$. (Sabemos que suman 200).\n- $a_1 = 5, r = 3, n = 4$.\n- $S_4 = \\frac{5 \\cdot (3^4 - 1)}{3 - 1}$\n- $S_4 = \\frac{5 \\cdot (81 - 1)}{2}$\n- $S_4 = \\frac{5 \\cdot 80}{2} = \\frac{400}{2} = 200$.",
    "procedimiento": ["Paso 1: Identifica $a_1, r$ y la cantidad de términos a sumar ($n$).", "Paso 2: Calcula la potencia $r^n$.", "Paso 3: Resta 1 a ese resultado en el numerador.", "Paso 4: Multiplica el numerador por $a_1$.", "Paso 5: Divide todo por $(r - 1)$."],
    "ejemplos": [
        {"titulo": "Ahorros multiplicados", "enunciado": "Ahorras $2 el primer día y cada día duplicas lo del día anterior. ¿Cuánto sumarás en total luego de 5 días?", "solucion_pasos": ["a1 = 2, r = 2, n = 5.", "Fórmula: S5 = 2 * (2^5 - 1) / (2 - 1)", "S5 = 2 * (32 - 1) / 1", "S5 = 2 * 31 = 62.", "Suman 62 en total."]}
    ],
    "errores_frecuentes": ["Elevar '$r$' a la '$(n-1)$' en vez de '$n$' por inercia o confusión con la fórmula del término general.", "Dividir por $(r-1)$ antes de multiplicar el numerador completo."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SFIN-PG-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al comparar la fórmula del término general ($a_n$) con la fórmula de la suma finita ($S_n$) de una Progresión Geométrica, una diferencia estructural clave en el exponente de la razón '$r$' es que: (v{i})", "choices": ["A) En la suma finita el exponente es exactamente '$n$', mientras que en el término general es '$(n-1)$'.", "B) En la suma finita el exponente siempre es cuadrado.", "C) En la suma finita no se usa la razón como base.", "D) Ambas fórmulas usan rigurosamente el exponente '$(n-1)$'."], "correct_answer": "A) En la suma finita el exponente es exactamente '$n$', mientras que en el término general es '$(n-1)$'.", "solution_steps": "Es crucial no confundirlas. El término general necesita $(n-1)$ saltos. La suma suma $n$ términos, usa exponente $n$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SFIN-PG-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en la fórmula de suma $S_n = \\frac{{a_1(r^n - 1)}}{{r - 1}}$ nos encontramos con que la razón es exactamente $r = 1$, ¿qué problema matemático grave ocurre en la fórmula?", "choices": ["A) El denominador se vuelve cero, lo cual es matemáticamente indefinido.", "B) El resultado siempre dará números negativos.", "C) El numerador se vuelve infinito.", "D) La fórmula sigue funcionando pero da cero absoluto."], "correct_answer": "A) El denominador se vuelve cero, lo cual es matemáticamente indefinido.", "solution_steps": "Si $r=1$, $(1-1) = 0$ en el divisor. Por eso la fórmula exige $r \\neq 1$. (Si r=1, es solo sumar el mismo número $n$ veces, ej: $2+2+2$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SFIN-PG-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La suma de los $3$ primeros términos de la progresión que arranca en $4$ ($a_1=4$) con razón $3$ ($r=3$) da como total final $52$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$S_3 = \\frac{4 \\cdot (3^3 - 1)}{3 - 1} = \\frac{4 \\cdot (27 - 1)}{2} = \\frac{4 \\cdot 26}{2} = 2 \\cdot 26 = 52$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SFIN-PG-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un donante anónimo aporta dinero a una fundación benéfica en cuotas mensuales. El primer mes dona $\$10.000$, el segundo mes dona $\$20.000$, el tercer mes $\$40.000$, y así sucesivamente, duplicando la donación anterior. Si mantiene este patrón durante exactamente $5$ meses, ¿cuánto dinero en total (la suma de todos los aportes) habrá recibido la fundación? (v{i})", "choices": ["A) $\$310.000$", "B) $\$160.000$", "C) $\$320.000$", "D) $\$150.000$"], "correct_answer": "A) $\$310.000$", "solution_steps": "a1=10.000, r=2, n=5. S5 = 10000 * (2^5 - 1) / (2 - 1) = 10000 * (32 - 1) / 1 = 10000 * 31 = 310.000.", "paes_style": True})


def generate_all():
    print("Escribiendo YAMLs Tanda 5 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 5 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-5", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-5.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
