# scratch/build_alg_b0301_t3.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 11. GRADO_ABSOLUTO_TERMINO
sid11 = "MAT.ALG.TERMINO.GRADO_ABSOLUTO_TERMINO"
RECURSOS.append({
    "semantic_id": sid11, "objetivo": "Calcular el grado absoluto de un término algebraico sumando los exponentes de sus variables.",
    "introduccion": "¿Qué tan 'pesado' matemáticamente es un vagón de tren algebraico? El Grado Absoluto es como pesar el término completo en una balanza: metemos todas las letras y sumamos su potencia total.",
    "resumen": "El **Grado Absoluto** de un término algebraico es la **suma de los exponentes de TODAS sus letras** (variables). \n- Si el término no tiene letras (es un número puro), su grado absoluto es cero.",
    "explicacion": "Para encontrar el grado absoluto, ignoramos completamente al coeficiente numérico y nos concentramos solo en la parte literal.\nEjemplo 1: Termino $4x^3$.\n- Tiene solo una letra ($x$) con exponente $3$. Su grado absoluto es $3$.\n\nEjemplo 2: Término $-5a^2b^3c$.\n- Exponente de $a$ = $2$.\n- Exponente de $b$ = $3$.\n- Exponente de $c$ = $1$ (el uno invisible).\n- Grado absoluto = $2 + 3 + 1 = 6$. Es un término de sexto grado.\n\nEjemplo 3: Término $8$.\n- No hay letras. Matemáticamente es $8x^0$. Su grado absoluto es $0$.",
    "procedimiento": ["Paso 1: Olvida el número grande (el coeficiente) y su signo. No participan.", "Paso 2: Haz una lista de todas las letras presentes.", "Paso 3: Identifica el exponente de cada letra (pon un '1' si no hay número escrito).", "Paso 4: Suma todos esos exponentes. El total es el grado absoluto."],
    "ejemplos": [
        {"titulo": "Pesando el término", "enunciado": "Calcula el grado absoluto de la expresión 12m^4n^2p.", "solucion_pasos": ["Ignoramos el 12.", "Exponente de m = 4. Exponente de n = 2. Exponente de p = 1.", "Suma: 4 + 2 + 1 = 7.", "El grado absoluto es 7 (séptimo grado)."]}
    ],
    "errores_frecuentes": ["Olvidar sumar el '1' invisible de las letras que no tienen exponente escrito (ej. decir que el grado de $xy^3$ es 3, cuando en realidad es $1+3=4$).", "Sumar también el coeficiente numérico a la mezcla (ej. en $2x^3$ decir que el grado es $2+3=5$. El coeficiente jamás se suma)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GABST-CONC-{i}", "semantic_id": sid11, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cómo se define matemáticamente el 'Grado Absoluto' de un término algebraico? (v{i})", "choices": ["A) Como el resultado de la suma aritmética de los exponentes de todas sus letras o variables.", "B) Como el valor del mayor exponente que se encuentre en el término.", "C) Como la suma de todos los exponentes más el coeficiente numérico.", "D) Como el exponente de la primera letra en orden alfabético."], "correct_answer": "A) Como el resultado de la suma aritmética de los exponentes de todas sus letras o variables.", "solution_steps": "El grado absoluto es una medida global del término, sumando todas las potencias literales presentes.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"GABST-REC-1", "semantic_id": sid11, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Calcula el grado absoluto del siguiente término algebraico: $-15x^3y^2z$.", "choices": ["A) $6$", "B) $5$", "C) $3$", "D) $-9$"], "correct_answer": "A) $6$", "solution_steps": "Exponentes: x(3) + y(2) + z(1 invisible) = 6.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GABST-PROC-{i}", "semantic_id": sid11, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El grado absoluto del término independiente $45$ (un número sin letras) es cero?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Al no tener letras visibles, se asume $x^0$, por lo que la suma de exponentes es efectivamente 0.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GABST-PAES-{i}", "semantic_id": sid11, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un software de física pide ingresar fórmulas categorizadas por su 'grado dimensional' (grado absoluto). Un estudiante ingresa el término de aceleración $4\\pi \\cdot r^2 \\cdot t^3$. Si $\\pi$ es el número Pi, ¿de qué grado absoluto es realmente el término ingresado? (v{i})", "choices": ["A) Quinto grado ($5$).", "B) Sexto grado ($6$).", "C) Noveno grado ($9$).", "D) Cuarto grado ($4$)."], "correct_answer": "A) Quinto grado ($5$).", "solution_steps": "Pi es una constante numérica, no aporta al grado. Solo suman r(2) y t(3). 2 + 3 = 5.", "paes_style": True})

# 12. GRADO_RELATIVO_TERMINO
sid12 = "MAT.ALG.TERMINO.GRADO_RELATIVO_TERMINO"
RECURSOS.append({
    "semantic_id": sid12, "objetivo": "Calcular el grado relativo de un término algebraico respecto a una variable específica.",
    "introduccion": "Ya vimos el peso total de la caja (grado absoluto). Pero a veces solo nos interesa saber el peso de las manzanas ignorando las peras. Ese enfoque individualizado se llama Grado Relativo.",
    "resumen": "El **Grado Relativo** de un término se calcula **respecto a una letra en específico**. Es simplemente el **exponente que tiene esa letra particular** en el término.",
    "explicacion": "No hay que hacer ninguna suma. Es una búsqueda y captura directa.\nTérmino de estudio: $-8x^4y^2z$\n\n- ¿Cuál es el grado relativo con respecto a la $x$? Miras la $x$, su exponente es 4. El grado relativo respecto a $x$ es 4.\n- ¿Cuál es el grado relativo con respecto a la $y$? Miras la $y$, su exponente es 2. El grado es 2.\n- ¿Cuál es el grado relativo con respecto a la $z$? Miras la $z$, tiene el uno invisible. El grado es 1.\n- ¿Cuál es el grado relativo con respecto a la $w$? Como la letra $w$ no está en el término, su grado relativo es 0.\n\nEs una herramienta vital para cuando ordenamos polinomios alfabéticamente.",
    "procedimiento": ["Paso 1: Te deben especificar la letra (variable) a analizar.", "Paso 2: Busca esa letra en el término.", "Paso 3: Si está, su exponente es el grado relativo.", "Paso 4: Si la letra no está, el grado relativo respecto a esa letra es cero."],
    "ejemplos": [
        {"titulo": "Análisis por letra", "enunciado": "En el término 5a^3b, ¿cuál es el grado relativo respecto a 'b' y respecto a 'c'?", "solucion_pasos": ["Respecto a 'b': Buscamos la b. No tiene exponente visible, por lo que es 1. Grado relativo a b = 1.", "Respecto a 'c': Buscamos la c. No existe en el término. Grado relativo a c = 0."]}
    ],
    "errores_frecuentes": ["Confundir Grado Relativo con Grado Absoluto y terminar sumando todos los exponentes inútilmente.", "Al pedir el grado relativo de una letra sin exponente escrito, decir que es 0 en vez de 1."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GRELT-CONC-{i}", "semantic_id": sid12, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cómo se define el 'Grado Relativo' de un término algebraico con respecto a una variable específica? (v{i})", "choices": ["A) Es exactamente el exponente que acompaña a dicha variable en el término.", "B) Es la suma de los exponentes de todas las demás variables menos esa.", "C) Es la resta entre el grado absoluto y el exponente de esa letra.", "D) Es el coeficiente numérico multiplicado por el exponente de esa letra."], "correct_answer": "A) Es exactamente el exponente que acompaña a dicha variable en el término.", "solution_steps": "El grado relativo no requiere cálculos, es una observación directa del exponente de la letra solicitada.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"GRELT-REC-1", "semantic_id": sid12, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Dado el término algebraico $14a^5b^3c$, ¿cuál es su grado relativo con respecto a la letra '$b$'?", "choices": ["A) $3$", "B) $5$", "C) $9$", "D) $1$"], "correct_answer": "A) $3$", "solution_steps": "Observamos la letra b. Su exponente explícito es 3. Ese es su grado relativo.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GRELT-PROC-{i}", "semantic_id": sid12, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El grado relativo respecto a la variable '$w$' en el término algebraico $5x^2y^3$ es igual a cero?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "La letra 'w' no aparece en el término, lo que equivale matemáticamente a que está elevada a cero ($w^0 = 1$). Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"GRELT-PAES-{i}", "semantic_id": sid12, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Una tarea de cálculo matricial pide identificar el término con mayor 'Grado Relativo respecto a $y$' entre las siguientes opciones. ¿Cuál término debes elegir para tener la respuesta correcta? (v{i})", "choices": ["A) $-10x^8y^4$", "B) $15y^3z^{10}$", "C) $100x^{20}y$", "D) $45y^2$"], "correct_answer": "A) $-10x^8y^4$", "solution_steps": "Revisamos solo los exponentes de y: A tiene 4. B tiene 3. C tiene 1. D tiene 2. El mayor es 4 (Opción A).", "paes_style": True})

# 13. DEFINICION_EXPRESION
sid13 = "MAT.ALG.EXPRESIONES.DEFINICION_EXPRESION"
RECURSOS.append({
    "semantic_id": sid13, "objetivo": "Comprender la definición de Expresión Algebraica como una combinación de términos vinculados por sumas y restas.",
    "introduccion": "Ya conocemos los vagones individuales (términos). Ahora es el momento de engancharlos para formar trenes matemáticos completos. Un tren puede tener un vagón o cien vagones.",
    "resumen": "Una **Expresión Algebraica** es la representación de un símbolo algebraico o de **una o más operaciones algebraicas**. Básicamente, es cualquier conjunto válido de números y letras (términos) unidos por los signos de adición o sustracción.",
    "explicacion": "Cualquier trozo de matemáticas que escribas siguiendo las reglas es una expresión algebraica.\n- Ejemplos de expresiones de 1 término: $5x$, $-y^2$, $\\frac{a}{b}$.\n- Ejemplos de expresiones de 2 términos: $x + y$, $a^2 - b^2$.\n- Ejemplos de expresiones de 3 términos: $a + b + c$, $x^2 + 5x + 6$.\n\nLa expresión algebraica es el concepto general, el 'paraguas'. Luego, dependiendo de cuántos términos la compongan, la clasificaremos con nombres específicos (Monomios, Binomios, Polinomios).",
    "procedimiento": ["Paso 1: Observa el conjunto de números, letras y operaciones matemáticas.", "Paso 2: Si no hay un signo igual (=) o de desigualdad (<, >), es una expresión pura.", "Paso 3: Si tiene un igual, se convierte en una ecuación (una igualdad entre dos expresiones)."],
    "ejemplos": [
        {"titulo": "Todo cabe en el paraguas", "enunciado": "¿Es '(x^2 + y) / 2' una expresión algebraica?", "solucion_pasos": ["Tiene variables (x, y).", "Tiene operaciones (potencia, suma, división).", "Cumple la sintaxis matemática. Sí, es una expresión algebraica válida."]}
    ],
    "errores_frecuentes": ["Confundir una 'expresión' con una 'ecuación'. Una expresión (ej. $2x + 1$) no se 'resuelve' ni se 'despeja', solo se evalúa o simplifica. La ecuación ($2x + 1 = 5$) sí se resuelve porque tiene un signo igual.", "Creer que si tiene solo un término no es una 'expresión'. Las expresiones pueden tener desde 1 hasta infinitos términos."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFEX-CONC-{i}", "semantic_id": sid13, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes definiciones describe con mayor exactitud el concepto de 'Expresión Algebraica'? (v{i})", "choices": ["A) Un conjunto válido de números y variables combinados mediante operaciones aritméticas básicas.", "B) Una igualdad condicional entre dos polinomios que debe ser despejada.", "C) Una operación que solo involucra letras, sin incluir números o exponentes.", "D) El resultado final de una multiplicación."], "correct_answer": "A) Un conjunto válido de números y variables combinados mediante operaciones aritméticas básicas.", "solution_steps": "La expresión es el lenguaje, la combinación sintácticamente válida de símbolos y operaciones, sin necesidad de ser una ecuación.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"DEFEX-REC-1", "semantic_id": sid13, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cuál de las siguientes alternativas NO es una simple expresión algebraica, sino una ecuación o desigualdad?", "choices": ["A) $3x + 4 = 10$", "B) $3x + 4$", "C) $a^2 + b^2 - 5c$", "D) $\\frac{x - y}{2}$"], "correct_answer": "A) $3x + 4 = 10$", "solution_steps": "La opción A contiene un signo igual (=), por lo que dejó de ser una expresión suelta para convertirse en una proposición de igualdad (ecuación).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFEX-PROC-{i}", "semantic_id": sid13, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Es posible afirmar que la letra suelta '$x$' por sí sola constituye una expresión algebraica legítima?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Una expresión puede constar de un solo símbolo. '$x$' es una expresión de un solo término (monomio).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"DEFEX-PAES-{i}", "semantic_id": sid13, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una prueba, se pide a los estudiantes escribir una expresión algebraica que represente el perímetro de un rectángulo. Juan escribe $2a + 2b$. Pedro escribe $P = 2a + 2b$. Según el rigor del lenguaje algebraico, ¿quién cumplió estrictamente la instrucción de escribir SOLO una 'expresión'? (v{i})", "choices": ["A) Solo Juan, porque escribió un conjunto de operaciones sin formular una igualdad.", "B) Solo Pedro, porque toda expresión requiere una letra que indique el resultado total.", "C) Ambos, porque significan matemáticamente lo mismo.", "D) Ninguno de los dos."], "correct_answer": "A) Solo Juan, porque escribió un conjunto de operaciones sin formular una igualdad.", "solution_steps": "Juan escribió la expresión. Pedro, al agregar 'P =', construyó una ecuación o fórmula, excediendo la definición de simple expresión.", "paes_style": True})

# 14. IDENTIFICACION_MONOMIO
sid14 = "MAT.ALG.EXPRESIONES.IDENTIFICACION_MONOMIO"
RECURSOS.append({
    "semantic_id": sid14, "objetivo": "Identificar y clasificar expresiones algebraicas compuestas por un solo término (Monomios).",
    "introduccion": "En el lenguaje cotidiano, 'mono' significa uno (monociclo, monolito, monopolio). En álgebra ocurre exactamente lo mismo.",
    "resumen": "Un **Monomio** es una expresión algebraica que consta de **un solo término**. En un monomio, no existen signos de suma ($+$) o resta ($-$) que separen bloques; todas sus letras y números están fusionados mediante multiplicación o división.",
    "explicacion": "Para saber si estás frente a un monomio, busca los signos + y -.\n- $5x$: Es un monomio (no hay sumas ni restas sueltas).\n- $-3a^2b$: Es un monomio. ¡Espera! ¿No hay un signo menos ahí? Sí, pero ese signo le pertenece al coeficiente numérico ($-3$), no está *separando* a la $a$ de la $b$. Es un solo bloque sólido.\n- $\\frac{x^2y}{4z}$: Es un monomio (el bloque es gigante, pero está todo pegado por divisiones y multiplicaciones).\n- $a + b$: ¡ALERTA! Hay un signo + libre en el medio. Son dos vagones separados. Esto NO es un monomio.",
    "procedimiento": ["Paso 1: Revisa la expresión completa de izquierda a derecha.", "Paso 2: Si detectas un '+' o '-' en medio de variables, actuando como puente o enganche, descártalo: no es monomio.", "Paso 3: Si toda la expresión es un bloque sólido ininterrumpido (aunque tenga signo negativo al inicio), es un monomio."],
    "ejemplos": [
        {"titulo": "El bloque solitario", "enunciado": "Clasifica la expresión -7x^4y^5.", "solucion_pasos": ["Analizamos la expresión en busca de sumas o restas intermedias.", "No hay puentes '+' ni '-' entre la x y la y.", "Toda la estructura es sólida. Por tanto, es un Monomio."]}
    ],
    "errores_frecuentes": ["Descartar a los términos negativos (ej. $-4x$) creyendo que el signo menos rompe la regla de 'no tener restas'. El menos inicial es de identidad, no de separación operativa.", "Creer que $\\frac{x}{y}$ son dos términos (numerador y denominador). Las divisiones fusionan, no separan."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONOM-CONC-{i}", "semantic_id": sid14, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Según la nomenclatura algebraica formal, la palabra 'Monomio' designa específicamente a una expresión que: (v{i})", "choices": ["A) Consta de un solo y único término matemático, sin sumas ni restas que separen componentes.", "B) Tiene como máximo una sola letra (variable).", "C) Su coeficiente numérico es exactamente igual a uno.", "D) Solo posee operaciones de adición en su estructura."], "correct_answer": "A) Consta de un solo y único término matemático, sin sumas ni restas que separen componentes.", "solution_steps": "Mono significa uno. Un monomio es un bloque de un solo término (sin + ni - como separadores).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MONOM-REC-1", "semantic_id": sid14, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "De la siguiente lista de expresiones algebraicas, identifica la ÚNICA que cumple estrictamente con ser un Monomio.", "choices": ["A) $-8a^3b^2c$", "B) $-8a^3 + b^2c$", "C) $8a - 3b$", "D) $a + b + c$"], "correct_answer": "A) $-8a^3b^2c$", "solution_steps": "La alternativa A es un solo bloque indivisible. Las demás tienen signos de suma o resta operando como separadores.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONOM-PROC-{i}", "semantic_id": sid14, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La expresión $\\frac{x}{4}$ se considera un Binomio porque contiene dos componentes visibles: el numerador $x$ y el denominador $4$?", "choices": [], "correct_answer": "Falso", "solution_steps": "La división no separa en términos diferentes, fusiona los componentes matemáticos. Es un Monomio fraccionario.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MONOM-PAES-{i}", "semantic_id": sid14, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una tarea de programación, se solicita crear una variable de código que reciba y procese exclusivamente 'monomios'. El estudiante prueba su código con los siguientes inputs de texto. ¿Cuál de ellos será validado exitosamente por el programa? (v{i})", "choices": ["A) '-45x^2y^3'", "B) 'x^2 - y^2'", "C) '3x + 1'", "D) 'a - b'"], "correct_answer": "A) '-45x^2y^3'", "solution_steps": "El programa solo acepta 1 término. La opción A es la única que no posee operadores separadores (+ o -) entre sus letras.", "paes_style": True})

# 15. IDENTIFICACION_POLINOMIO
sid15 = "MAT.ALG.EXPRESIONES.IDENTIFICACION_POLINOMIO"
RECURSOS.append({
    "semantic_id": sid15, "objetivo": "Identificar y clasificar expresiones algebraicas compuestas por más de un término (Polinomios), incluyendo binomios y trinomios.",
    "introduccion": "Cuando enganchas varios vagones formas un tren. En álgebra, la palabra 'Poli' significa muchos. Si una expresión tiene sumas o restas intermedias, ya cruzaste la frontera del monomio y entraste a la ciudad de los Polinomios.",
    "resumen": "Un **Polinomio** es una expresión algebraica que consta de **más de un término**. \nExisten nombres especiales para los más pequeños:\n- **Binomio:** Polinomio de exactamente dos términos (ej. $a + b$).\n- **Trinomio:** Polinomio de exactamente tres términos (ej. $x^2 + 5x + 6$).\nSi tiene cuatro o más, se le llama simplemente polinomio.",
    "explicacion": "Contar términos es el primer paso para dominar el álgebra operativa.\n- Expresión: $4a - 5b$. ¿Hay un signo en medio actuando de puente? Sí, el menos. Hay dos bloques. Es un **Binomio**.\n- Expresión: $x^2 - 3x + 2$. Hay dos puentes (- y +). Por ende hay tres bloques. Es un **Trinomio**.\n- Expresión: $m^3 + m^2 - m + 1$. Tres puentes, cuatro bloques. Le llamamos Polinomio (de 4 términos).\n\n*Nota vital:* Para contar limpiamente, asegúrate de que los términos no se puedan sumar entre ellos. Por ejemplo, $2x + 3x$ parece un binomio, pero como son peras con peras, en realidad es un monomio disfrazado ($5x$).",
    "procedimiento": ["Paso 1: Simplifica la expresión si es posible (junta términos semejantes).", "Paso 2: Cuenta cuántos 'puentes' libres de suma o resta (+, -) existen.", "Paso 3: El número de bloques resultantes te da la clasificación: 2 (binomio), 3 (trinomio), 4+ (polinomio genérico)."],
    "ejemplos": [
        {"titulo": "Clasificando el tren", "enunciado": "Clasifica la expresión: 5x^2 - 4y + z/2", "solucion_pasos": ["Separador 1: el menos antes del 4y.", "Separador 2: el más antes de z/2.", "Bloques totales: 3.", "Conclusión: Es un Trinomio (y por ende, también pertenece a la familia general de los polinomios)."]}
    ],
    "errores_frecuentes": ["Contar variables en vez de términos (ej. en $a+b+c$ hay tres términos, pero en $abc$ hay un solo término con tres letras).", "Pensar que un binomio NO es un polinomio. 'Polinomio' es la familia de todo lo que tenga 2 o más. El binomio es solo un sub-tipo de polinomio."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLIN-CONC-{i}", "semantic_id": sid15, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes es la definición correcta de un 'Trinomio' en el marco teórico del álgebra polinomial? (v{i})", "choices": ["A) Es un tipo específico de polinomio constituido por exactamente tres términos vinculados por sumas o restas.", "B) Es un monomio que contiene exactamente tres variables distintas (letras).", "C) Es un término cuyo grado absoluto es igual a tres.", "D) Es un polinomio elevado a la tercera potencia."], "correct_answer": "A) Es un tipo específico de polinomio constituido por exactamente tres términos vinculados por sumas o restas.", "solution_steps": "Tri = tres; nomio = término. Un trinomio agrupa tres bloques o vagones separados por operaciones de adición/sustracción.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"POLIN-REC-1", "semantic_id": sid15, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Clasifica apropiadamente la siguiente expresión matemática según su cantidad de términos irreductibles: $8x^3 - 27y^3$.", "choices": ["A) Binomio.", "B) Monomio.", "C) Trinomio.", "D) Ecuación."], "correct_answer": "A) Binomio.", "solution_steps": "La expresión tiene un solo puente '-' que separa dos bloques indivisibles. Posee dos términos, luego es un Binomio.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLIN-PROC-{i}", "semantic_id": sid15, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $5x + 2x$ debe clasificarse formalmente como un Binomio porque presenta dos términos separados por un signo más?", "choices": [], "correct_answer": "Falso", "solution_steps": "Antes de clasificar, se debe reducir si es posible. $5x + 2x = 7x$. Al ser simplificable a un único término, en esencia es un Monomio.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"POLIN-PAES-{i}", "semantic_id": sid15, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"La base de la pirámide central del museo depende de una ecuación de diseño definida como $P(x) = x^2 + 5x + 6$. Para encargar el software de corte, el ingeniero debe seleccionar el módulo matemático adecuado. ¿Qué módulo específico debe usar para procesar $P(x)$? (v{i})", "choices": ["A) Módulo de Trinomios Cuadráticos.", "B) Módulo de Binomios.", "C) Módulo de Monomios Multivariables.", "D) Módulo de Polinomios de cuatro términos."], "correct_answer": "A) Módulo de Trinomios Cuadráticos.", "solution_steps": "La expresión $x^2 + 5x + 6$ tiene tres términos inmiscibles separados por signos +. Su forma estructural clasifica directamente como Trinomio.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 3 (MAT.ALG.B0301)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 3 (MAT.ALG.B0301)...")
    append_jsonl("mat-alg-nomenclatura-banco-gen-3", EJERCICIOS)
    print("Creado mat-alg-nomenclatura-banco-gen-3.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
