# scratch/build_b0206_t6.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. MODELO_CRECIMIENTO_PORCENTUAL
sid1 = "MAT.NUM.PROG_GEOMETRICA.MODELO_CRECIMIENTO_PORCENTUAL"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Modelar situaciones de crecimiento o decrecimiento porcentual constante mediante el uso de progresiones geométricas.",
    "introduccion": "Si tu dinero crece un 5% cada año, no está creciendo sumando la misma cantidad, está creciendo sumando un porcentaje del nuevo total. Esta es la magia del interés compuesto, y es una Progresión Geométrica en estado puro.",
    "resumen": "Todo cambio porcentual constante (como un aumento del $10\\%$ mensual) se modela multiplicando por un factor decimal llamado 'Índice de Variación', que actúa como la razón geométrica: $r = (1 \\pm \\frac{p}{100})$.",
    "explicacion": "Cuando algo aumenta o disminuye en un porcentaje fijo, no es una progresión aritmética (lineal), sino geométrica (exponencial).\n\nPara hallar la Razón Geométrica ($r$) a partir de un porcentaje:\n1. **Aumento porcentual ($+p\\%$):** Tu nuevo total es el $100\\%$ original MÁS el $p\\%$. En decimales, esto es $r = 1 + \\frac{p}{100}$.\n   - *Ejemplo:* Si aumenta un $15\\%$ anual, la razón es $r = 1 + 0.15 = 1.15$.\n2. **Disminución porcentual ($-p\\%$):** Tu nuevo total es el $100\\%$ MENOS el $p\\%$. En decimales, esto es $r = 1 - \\frac{p}{100}$.\n   - *Ejemplo:* Si un auto pierde un $20\\%$ de su valor anual, la razón es $r = 1 - 0.20 = 0.80$.\n\nLa fórmula general queda: $Capital_{final} = Capital_{inicial} \\cdot r^n$ (Nota: en finanzas suele usarse exponente '$n$' directo porque se cuenta desde el periodo cero, a diferencia de la P.G. estricta que empieza en 1).",
    "procedimiento": ["Paso 1: Identifica si el problema habla de un aumento (interés, crecimiento) o disminución (descuento, depreciación) porcentual.", "Paso 2: Convierte ese porcentaje a decimal dividiéndolo por 100.", "Paso 3: Si es aumento, suma 1 (ej: 1 + 0.05 = 1.05). Si es disminución, réstaselo a 1 (ej: 1 - 0.05 = 0.95). Ese número es tu razón 'r'.", "Paso 4: Aplica la fórmula de progresión geométrica multiplicando el valor inicial por $r^n$."],
    "ejemplos": [
        {"titulo": "El auto que pierde valor", "enunciado": "Un auto cuesta $10.000.000 y se deprecia un 10% cada año. ¿Cuál será su valor tras 3 años?", "solucion_pasos": ["Es disminución del 10%. Razón r = 1 - (10/100) = 1 - 0.10 = 0.90.", "Valor inicial = 10.000.000.", "Valor tras 3 años = 10.000.000 * (0.90)^3", "0.90^3 = 0.729.", "10.000.000 * 0.729 = $7.290.000."]}
    ],
    "errores_frecuentes": ["Creer que si algo aumenta un 10% cada año por 3 años, aumenta un 30% en total (Falso, los porcentajes se aplican sobre el nuevo monto acumulado cada año).", "Usar el porcentaje directo como razón (ej: multiplicar por 0.10 en vez de por 1.10 para un aumento)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CRECPO-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si un artículo sufre una inflación constante de manera que su precio aumenta un $8\\%$ todos los meses, ¿cuál es el valor matemático exacto de la razón geométrica '$r$' que modela esta situación? (v{i})", "choices": ["A) $1.08$", "B) $0.08$", "C) $1.8$", "D) $8.0$"], "correct_answer": "A) $1.08$", "solution_steps": "Aumentar un $8\\%$ significa quedar con el $108\\%$. En decimal es $1.08$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CRECPO-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al modelar la pérdida de eficiencia de un panel solar que disminuye su capacidad de generar energía en un $5\\%$ cada año, la razón geométrica a emplear debe ser:", "choices": ["A) $0.95$", "B) $1.05$", "C) $0.05$", "D) $-0.05$"], "correct_answer": "A) $0.95$", "solution_steps": "Perder un $5\\%$ significa retener un $95\\%$ del valor anterior. En decimal es $0.95$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CRECPO-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si inviertes $\$1.000$ a un interés compuesto del $10\\%$ anual, al cabo de $2$ años tendrás exactamente $\$1.200$?", "choices": [], "correct_answer": "Falso", "solution_steps": "El primer año tienes 1100. El segundo año se aplica el $10\\%$ sobre 1100, ganando 110. Total = 1210. (No 1200).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CRECPO-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Una empresa pronostica que sus ventas decaerán a una tasa constante del $20\\%$ anual debido a la obsolescencia de su producto estrella. Si este año vendieron $\$50.000.000$, ¿qué expresión matemática representa correctamente las ventas esperadas transcurridos '$t$' años bajo este mismo modelo de caída libre? (v{i})", "choices": [r"A) $50.000.000 \cdot (0.80)^t$", r"B) $50.000.000 \cdot (1.20)^t$", r"C) $50.000.000 - (0.20 \cdot t)$", r"D) $50.000.000 \cdot (-0.20)^t$"], "correct_answer": r"A) $50.000.000 \cdot (0.80)^t$", "solution_steps": "Caída del 20% significa retener el 80% (r=0.80). Modelo multiplicativo: $Valor \cdot (0.80)^t$.", "paes_style": True})

# 2. INTERPRETACION_RAZON_CONTEXTO
sid2 = "MAT.NUM.PROG_GEOMETRICA.INTERPRETACION_RAZON_CONTEXTO"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Interpretar el significado práctico de la razón geométrica (r) en contextos aplicados a la vida real.",
    "introduccion": "Si lees que la fórmula de una pandemia es $Infectados = 100 \\cdot (2.5)^t$, el número 2.5 no es un adorno matemático, es una alerta roja. Descubramos qué nos grita la razón geométrica sobre el comportamiento del mundo.",
    "resumen": "La razón '$r$' en un contexto real indica el **factor multiplicativo de cambio**. Si $r > 1$, la situación explota o crece (intereses, poblaciones). Si $0 < r < 1$, la situación se desintegra o decae (depreciación, material radiactivo).",
    "explicacion": "Cada vez que en la prueba aparezca un modelo del tipo $A \\cdot (b)^t$, concéntrate en la base de la potencia '$b$' (que es nuestra razón '$r$').\n\n1. **¿Qué nos dice si $r = 3$?** Significa que la cantidad (de bacterias, de dinero, de rumores) se está **triplicando** en cada unidad de tiempo. Es un crecimiento del $200\\%$.\n2. **¿Qué nos dice si $r = 1.04$?** Significa que por cada paso, la cantidad retiene su $100\\%$ (el número 1) y suma un $0.04$ extra. Es decir, crece un **$4\\%$ por periodo**.\n3. **¿Qué nos dice si $r = 0.85$?** Significa que por cada paso solo retiene el $85\\%$ de lo que tenía antes. Por ende, está perdiendo un **$15\\%$ por periodo**.\n\nEn conclusión: la razón 'r' te da la 'velocidad y dirección' del crecimiento exponencial.",
    "procedimiento": ["Paso 1: Localiza el número que está siendo elevado al exponente (la base de la potencia).", "Paso 2: Compáralo con 1. Si es mayor a 1, hay crecimiento. Si es menor a 1, hay decrecimiento.", "Paso 3: Resta el número a 1 (o viceversa) para descubrir el porcentaje exacto de cambio oculto."],
    "ejemplos": [
        {"titulo": "Desentrañando la fórmula", "enunciado": "La masa de un medicamento en la sangre se modela como M(t) = 500 * (0.6)^t. ¿Qué significa el 0.6?", "solucion_pasos": ["El 0.6 es la razón geométrica.", "Al ser menor que 1, la masa está disminuyendo.", "En porcentaje, 0.6 es el 60%.", "Significa que en cada unidad de tiempo 't', el paciente solo conserva el 60% del medicamento en su sangre (o sea, elimina un 40%)."]}
    ],
    "errores_frecuentes": ["Interpretar $r = 1.20$ como 'crece un 120%' (Falso, el 1 representa la conservación del total original; el crecimiento neto es solo el 0.20, es decir 20%).", "Interpretar $r = 0.30$ como 'pierde un 30%' (Falso, 0.30 es lo que CONSERVA. Por lo tanto, pierde un 70%)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTRZG-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si en un modelo de población forestal la ecuación proyectiva está regida por la expresión $P(t) = 15.000 \cdot (1.025)^t$, ¿cuál es la interpretación real del factor $1.025$? (v{i})", "choices": ["A) Indica que la población de árboles está experimentando un crecimiento neto del $2.5\\%$ cada año.", "B) Indica que se plantan $1.025$ árboles nuevos cada año.", "C) Indica que la población crece un $102.5\\%$ extra cada año.", "D) Indica que la cantidad inicial de árboles se dividirá por $1.025$."], "correct_answer": "A) Indica que la población de árboles está experimentando un crecimiento neto del $2.5\\%$ cada año.", "solution_steps": "1.025 descompuesto es $1 + 0.025$. El 1 es la base y el 0.025 es el aumento, que equivale al 2.5%.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTRZG-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En una fórmula de decaimiento radiactivo $M = 200 \cdot (0.8)^t$, la afirmación más precisa respecto a la pérdida de masa por cada unidad de tiempo es:", "choices": ["A) El material pierde exactamente el $20\\%$ de su masa en cada periodo.", "B) El material pierde el $80\\%$ de su masa en cada periodo.", "C) El material pierde $0.8$ gramos en cada periodo.", "D) El material pierde $20$ gramos en cada periodo."], "correct_answer": "A) El material pierde exactamente el $20\\%$ de su masa en cada periodo.", "solution_steps": "Si la razón multiplicativa es 0.8, significa que CONSERVA el 80%. Si conserva el 80%, la pérdida neta es del 20%.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTRZG-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si un modelo financiero está dado por $C = 50.000 \cdot (3.0)^t$, significa que la ganancia es del $300\\%$ por período?", "choices": [], "correct_answer": "Falso", "solution_steps": "La base 3.0 se descompone en 1 (el 100% que ya tenías) + 2.0. El crecimiento o ganancia neta es de 2.0, lo que equivale a un 200%.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTRZG-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un ecólogo usa el modelo $P(m) = 5.000 \cdot (0.91)^m$ para predecir la cantidad de abejas en una colmena infectada por un ácaro al cabo de '$m$' meses. ¿Qué enunciado describe mejor la crisis que sufre la colmena basándose únicamente en la estructura de este modelo? (v{i})", "choices": ["A) La colmena está perdiendo un $9\\%$ del total de su población restante cada mes que transcurre.", "B) La colmena está perdiendo un $91\\%$ del total de su población restante cada mes.", "C) Mueren exactamente $91$ abejas cada mes.", "D) La población se reducirá a cero en exactamente 9 meses."], "correct_answer": "A) La colmena está perdiendo un $9\\%$ del total de su población restante cada mes que transcurre.", "solution_steps": "El factor 0.91 indica que sobrevive el 91%. Por lo tanto, la tasa de mortalidad (pérdida) es del 9% mensual (1 - 0.91 = 0.09).", "paes_style": True})

# 3. CONCEPTO_SERIE
sid3 = "MAT.NUM.SERIE_GEOMETRICA.CONCEPTO_SERIE"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Diferenciar formalmente el concepto de 'Sucesión' (lista de números) del concepto de 'Serie' (suma de esa lista).",
    "introduccion": "En el lenguaje cotidiano, 'sucesión' y 'serie' parecen sinónimos (como una 'serie de televisión' con episodios sucesivos). Pero en matemáticas, son dos animales completamente distintos. No cometas el error de confundirlos en la prueba.",
    "resumen": "Una **Sucesión** es una LISTA ordenada de números separados por comas ($a_1, a_2, a_3\\dots$). Una **Serie** es el resultado de SUMAR todos los números de una sucesión ($a_1 + a_2 + a_3\\dots$).",
    "explicacion": "Visualicemos la diferencia:\n\n- **La Sucesión:** Es como mirar tu cuenta corriente mes a mes.\n  - Mes 1: $\$10.000$\n  - Mes 2: $\$20.000$\n  - Mes 3: $\$40.000$\n  - Sucesión (lista): $10.000, 20.000, 40.000$.\n\n- **La Serie:** Es como meter todo ese dinero en una gran alcancía y contar el total.\n  - Total = $10.000 + 20.000 + 40.000 = $\$70.000$.\n  - Serie (suma): $70.000$.\n\nCuando veas la palabra 'Serie' en un problema de matemáticas, tu cerebro debe encender una alerta de neón que diga: **'¡TENGO QUE SUMAR, VOY A USAR LA FÓRMULA DE $S_n$!'**",
    "procedimiento": ["Paso 1: Lee el enunciado. Si te piden encontrar un número específico en una posición, trabajas con una SUCESIÓN (fórmula de a_n).", "Paso 2: Si el problema habla de 'acumulado', 'total', 'recorrido completo' o dice literalmente 'SERIE', entonces es una SUMA (fórmula de S_n)."],
    "ejemplos": [
        {"titulo": "Aclarando el vocabulario", "enunciado": "La P.G. es 2, 4, 8, 16. ¿Cuál es el valor del 4to término de la sucesión, y cuál es el valor de la serie finita de 4 términos?", "solucion_pasos": ["Sucesión: Buscamos el elemento en la posición 4. Miramos la lista: es el 16.", "Serie: Buscamos la suma de los 4 elementos. 2 + 4 + 8 + 16 = 30."]}
    ],
    "errores_frecuentes": ["Entregar el valor del término $a_n$ cuando el problema pedía calcular 'la serie'.", "Entregar el total acumulado cuando el problema solo pedía 'el valor del término de la sucesión'."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSERIE-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Desde el punto de vista del rigor matemático formal, ¿cuál es la diferencia exacta entre una sucesión geométrica y una serie geométrica? (v{i})", "choices": ["A) La sucesión es el conjunto listado de los términos, y la serie es la suma de todos esos términos.", "B) La serie utiliza multiplicaciones, mientras que la sucesión usa sumas.", "C) La sucesión puede ser finita o infinita, pero la serie siempre es finita.", "D) Son exactamente el mismo concepto y se usan como sinónimos en las fórmulas."], "correct_answer": "A) La sucesión es el conjunto listado de los términos, y la serie es la suma de todos esos términos.", "solution_steps": "Sucesión = Lista de elementos (separados por comas). Serie = La suma total (+).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CSERIE-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si en un control de matemáticas te preguntan '¿Cuál es el valor de la serie de los primeros $5$ términos de $3, 6, 12...$?', la fórmula que deberás emplear obligatoriamente es:", "choices": [r"A) La fórmula de suma $S_n$.", r"B) La fórmula del término general $a_n$.", r"C) La fórmula de la razón $r$.", r"D) La fórmula del promedio simple."], "correct_answer": r"A) La fórmula de suma $S_n$.", "solution_steps": "La palabra 'serie' equivale al concepto de suma acumulada ($S_n$).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSERIE-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Para la lista $1, 2, 4, 8, 16$, el quinto término de la sucesión es $16$, y el valor de la serie asociada a esos 5 términos es $31$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Término posición 5 es 16. Serie = $1+2+4+8+16 = 31$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CSERIE-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un concurso de televisión lanza monedas al aire. En la ronda 1 regalan $\$1.000$, en la ronda 2 regalan $\$2.000$, en la 3 regalan $\$4.000$ (potencias de $2$). El animador anuncia: '¡Y ahora el participante se llevará el premio equivalente a la SERIE de las primeras 4 rondas!'. ¿Cuánto dinero se lleva el participante en ese maletín? (v{i})", "choices": ["A) $\$15.000$", "B) $\$8.000$", "C) $\$4.000$", "D) $\$16.000$"], "correct_answer": "A) $\$15.000$", "solution_steps": "Serie = Suma de las 4 rondas. $1000 + 2000 + 4000 + 8000 = 15.000$.", "paes_style": True})

# 4. SERIE_FINITA
sid4 = "MAT.NUM.SERIE_GEOMETRICA.SERIE_FINITA"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Calcular matemáticamente el valor de una serie geométrica finita aplicando la fórmula de suma parcial.",
    "introduccion": "Ya conoces la diferencia entre lista y suma. Ahora, vamos a los fierros. Cuando la lista es de 30 términos, no puedes sumar a mano. Sacaremos nuestra fórmula mágica para devorar grandes sumas geométricas en un segundo.",
    "resumen": "Para calcular una serie finita (suma de 'n' términos) usamos la fórmula ya conocida: $S_n = \\frac{a_1(r^n - 1)}{r - 1}$. Recuerda que el exponente es '$n$' entero, no '$(n-1)$'.",
    "explicacion": "Repasemos la mecánica de la fórmula con un ejemplo donde los errores abundan.\n\nFórmula: $$S_n = \\frac{a_1(r^n - 1)}{r - 1}$$\n\nSi queremos la serie de los primeros 6 términos de $10, 20, 40\\dots$\n- $a_1 = 10$, $r = 2$, $n = 6$.\n\nReemplazo cuidadoso:\n1. Arriba: $10 \\cdot (2^6 - 1)$\n   - Primero la potencia: $2^6 = 64$\n   - Luego la resta: $64 - 1 = 63$\n   - Luego multiplicamos: $10 \\cdot 63 = 630$.\n2. Abajo: $2 - 1 = 1$.\n3. División final: $630 / 1 = 630$.\n\nLa serie vale 630. Cuidado con el paso 1: jamás debes hacer $10 \\cdot 2$ primero y luego elevar a la sexta (eso daría un absurdo $20^6$).",
    "procedimiento": ["Paso 1: Detecta $a_1, r, n$.", "Paso 2: Evalúa la potencia $r^n$.", "Paso 3: Resta 1 a la potencia.", "Paso 4: Multiplica por $a_1$ (esto completa el numerador).", "Paso 5: Divide por $(r-1)$ (el denominador)."],
    "ejemplos": [
        {"titulo": "Números fríos", "enunciado": "Halla el valor de la serie de los 4 primeros términos de la sucesión que empieza en 100 con razón -2.", "solucion_pasos": ["a1=100, r=-2, n=4.", "Potencia: (-2)^4 = +16.", "Resta: 16 - 1 = 15.", "Multiplica a1: 100 * 15 = 1500.", "Denominador: r - 1 = -2 - 1 = -3.", "División final: 1500 / -3 = -500.", "La serie da -500."]}
    ],
    "errores_frecuentes": ["Romper la jerarquía de operaciones multiplicando $a_1$ por la base $r$ antes de aplicar el exponente (Ej: resolver $3(2^4)$ como $6^4$).", "Olvidar los paréntesis al evaluar una razón negativa elevada a potencia par, como escribir $-2^4 = -16$ en vez de $(-2)^4 = +16$."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERFIN-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Si aplicamos la fórmula de la serie finita $S_n = \\frac{{a_1(r^n - 1)}}{{r - 1}}$ para una progresión geométrica donde la razón es $r = 10$, el denominador de la fracción final quedará siempre convertido en un: (v{i})", "choices": ["A) $9$", "B) $10$", "C) $11$", "D) $1$"], "correct_answer": "A) $9$", "solution_steps": "El denominador es $(r - 1)$. Si $r = 10$, entonces $10 - 1 = 9$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SERFIN-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al calcular el valor del bloque $a_1(r^n - 1)$ para $a_1 = 2$, $r = 5$, y $n = 3$, el paso inicial correcto según Papomudas es:", "choices": ["A) Calcular primero el valor de $5^3$.", "B) Multiplicar $2 \cdot 5$ para obtener $10$.", "C) Restar $5 - 1$ y elevar a la tercera.", "D) Restar $3 - 1$ para cambiar el exponente a 2."], "correct_answer": "A) Calcular primero el valor de $5^3$.", "solution_steps": "Potencias primero: $5^3 = 125$. Luego $125 - 1 = 124$. Luego $2 \cdot 124$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERFIN-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El valor de la serie de los primeros $5$ términos de la progresión de $a_1=2$ y $r=-1$ es exactamente $2$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Lista: $2, -2, 2, -2, 2$. La suma es $2 - 2 + 2 - 2 + 2 = 2$. Por fórmula: $S_5 = 2((-1)^5 - 1) / (-1 - 1) = 2(-1 - 1) / -2 = 2(-2)/-2 = 2$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERFIN-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un esquema de comisiones piramidal asegura que una persona invita a $3$ vendedores el primer mes ($a_1=3$). Al segundo mes, esos $3$ invitan a otros $3$ cada uno ($9$ nuevos), y así sucesivamente. ¿Cuántos vendedores NUEVOS habrán ingresado en TOTAL al cumplirse exactamente el mes número $4$ de la pirámide? (v{i})", "choices": ["A) $120$ vendedores.", "B) $81$ vendedores.", "C) $40$ vendedores.", "D) $121$ vendedores."], "correct_answer": "A) $120$ vendedores.", "solution_steps": "Serie finita. a1=3, r=3, n=4. S4 = 3 * (3^4 - 1) / (3 - 1) = 3 * (81 - 1) / 2 = 3 * 80 / 2 = 240 / 2 = 120.", "paes_style": True})

# 5. SERIE_INFINITA_CONCEPTO
sid5 = "MAT.NUM.SERIE_GEOMETRICA.SERIE_INFINITA_CONCEPTO"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Comprender la convergencia y calcular el límite de una serie geométrica infinita decreciente.",
    "introduccion": "Si sumas números positivos para siempre, el resultado debería ser infinito, ¿verdad? ¡Sorpresa matemática! Si los números se achican lo suficientemente rápido, sumar infinitos números te dará un total pequeño y cerrado. Rompamos la mente con el infinito.",
    "resumen": "Una serie geométrica se puede sumar hasta el INFINITO solo si su razón es una fracción estricta ($-1 < r < 1$). La suma total de infinitos términos converge a una simple fórmula mágica: $S_{\\infty} = \\frac{a_1}{1 - r}$.",
    "explicacion": "Imagina que caminas hacia la pared. Primero avanzas 1 metro, luego medio metro, luego un cuarto de metro, luego un octavo... Si haces esto infinitas veces, ¡nunca superarás los 2 metros totales! Te estancarás (convergerás) en 2 metros exactos.\n\nPara que la magia del infinito funcione:\n1. La razón debe ser **menor a 1 y mayor a -1** (Ej: $r = 1/2, r = -0.3, r = 2/3$). Si $r=2$, los números crecen y la suma sí explota al infinito.\n2. La fórmula de suma infinita colapsa a la mínima expresión matemática:\n$$S_{\\infty} = \\frac{a_1}{1 - r}$$\n\nEs tan simple porque el término enorme $(r^n)$ de la fórmula antigua, al ser 'r' una fracción minúscula elevada al infinito, se vuelve prácticamente CERO, desapareciendo de la ecuación.",
    "procedimiento": ["Paso 1: Revisa que la razón 'r' esté entre -1 y 1 (obligatorio).", "Paso 2: Identifica el primer término ($a_1$).", "Paso 3: Resta (1 - r) para el denominador.", "Paso 4: Divide $a_1$ por ese denominador. El resultado es el techo máximo al que llegará la suma infinita."],
    "ejemplos": [
        {"titulo": "Sumando polvo de estrellas", "enunciado": "Calcula el total de la suma infinita de 100 + 50 + 25 + 12.5 + ...", "solucion_pasos": ["a1 = 100. La razón es 0.5 (o 1/2).", "Como 0.5 está entre -1 y 1, SÍ se puede calcular.", "S_inf = 100 / (1 - 0.5)", "S_inf = 100 / 0.5", "S_inf = 200.", "Sumar infinitos términos de esta secuencia dará exactamente 200."]}
    ],
    "errores_frecuentes": ["Intentar aplicar la fórmula del infinito a una progresión creciente donde $r>1$ (esto te dará un número negativo absurdo, cuando en realidad la suma es matemáticamente 'Infinito').", "Equivocarse en la resta del denominador cuando $r$ es negativa, olvidando la regla de signos: $1 - (-0.5) = 1.5$."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERINF-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la condición matemática ineludible que debe cumplir la razón '$r$' de una progresión geométrica para que su serie infinita pueda ser calculada (converja a un número real)? (v{i})", "choices": ["A) El valor absoluto de la razón debe ser menor a 1 (es decir, $-1 < r < 1$).", "B) La razón debe ser siempre un número entero positivo mayor a 1.", "C) La razón debe ser obligatoriamente un número negativo.", "D) El primer término debe ser cero."], "correct_answer": "A) El valor absoluto de la razón debe ser menor a 1 (es decir, $-1 < r < 1$).", "solution_steps": "Para que la suma se detenga, los términos deben ir encogiéndose hacia cero. Esto solo ocurre si se multiplica por fracciones propias.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SERINF-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si intentas usar la fórmula de la serie infinita $S_\\infty = \\frac{{a_1}}{{1-r}}$ en una progresión donde $r = 3$ y $a_1 = 10$, el resultado algebraico te dará $-5$. ¿Qué significa realmente ese $-5$?", "choices": ["A) Es un error matemático conceptual, porque al ser $r=3$ la serie diverge al infinito, y la fórmula no tiene validez aquí.", "B) Significa que la suma infinita da realmente un resultado negativo.", "C) Significa que debes sumar 5 a la respuesta.", "D) Significa que la progresión se mueve hacia atrás."], "correct_answer": "A) Es un error matemático conceptual, porque al ser $r=3$ la serie diverge al infinito, y la fórmula no tiene validez aquí.", "solution_steps": "No puedes usar la fórmula si $|r| \geq 1$. Aplicarla a ciegas da un falso negativo (un absurdo).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERINF-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La suma infinita de la serie geométrica cuyas potencias son $1 + \frac{1}{3} + \frac{1}{9} + \frac{1}{27} + \dots$ converge exactamente al número $1.5$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "a1=1, r=1/3. S = 1 / (1 - 1/3) = 1 / (2/3) = 3/2 = 1.5. Es totalmente verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SERINF-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un péndulo es soltado desde cierta altura. En su primer balanceo recorre un arco de $20$ cm. Debido a la fricción, en cada balanceo subsiguiente recorre el $80\\%$ de la distancia del balanceo anterior. Si se deja oscilar infinitamente hasta que se detenga por completo, ¿cuál es la distancia total acumulada que habrá recorrido la punta del péndulo? (v{i})", "choices": ["A) $100$ cm.", "B) $20$ cm.", "C) $80$ cm.", "D) Infinitos centímetros."], "correct_answer": "A) $100$ cm.", "solution_steps": "Serie infinita. a1 = 20, r = 0.8. S_inf = 20 / (1 - 0.8) = 20 / 0.2 = 100 cm.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 6 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 6 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-6", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-6.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
