# scratch/build_b0206_t1.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. DEFINICION (Sucesiones Numéricas)
sid1 = "MAT.NUM.SUCESIONES_BASE.DEFINICION"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Comprender qué es una sucesión numérica y distinguirla de un simple conjunto de números.",
    "introduccion": "¿Has notado que los años bisiestos ocurren cada 4 años? 2020, 2024, 2028... Estás frente a una sucesión. A diferencia de un grupo de números al azar, aquí el orden y el patrón lo son todo.",
    "resumen": "Una sucesión numérica es una lista ORDENADA de números. Cada número ocupa una posición específica y suele existir una regla matemática (o lógica) que conecta un término con el siguiente.",
    "explicacion": "Imagina una fila de personas esperando entrar a un concierto. Cada persona tiene un número de llegada: el primero, el segundo, el tercero. Una **sucesión numérica** es exactamente eso: una fila de números.\n\n- **Orden:** Es la característica principal. El conjunto $\\{2, 4, 6\\}$ tiene los mismos números que la sucesión $6, 4, 2$, pero como sucesiones son totalmente distintas porque el orden cambió.\n- **Términos:** Cada número dentro de la sucesión se llama 'término'.\n- **Patrón:** Casi todas las sucesiones que estudiarás tienen una regla matemática que predice el futuro (ej. 'sumar 3 al anterior').\n\nEjemplo: $5, 10, 15, 20, \\dots$ es una sucesión donde cada término es múltiplo de 5, ordenados de menor a mayor.",
    "procedimiento": ["Paso 1: Observa una lista de números.", "Paso 2: Verifica si el orden importa (si cambiar los números de posición altera el sentido de la lista).", "Paso 3: Identifica si es una sucesión finita (termina) o infinita (tiene puntos suspensivos...)."],
    "ejemplos": [
        {"titulo": "El orden importa", "enunciado": "¿Es lo mismo la sucesión 1, 2, 3 que la sucesión 3, 2, 1?", "solucion_pasos": ["Ambas tienen los mismos elementos matemáticos.", "Sin embargo, el primer término de la primera es 1, y el de la segunda es 3.", "Al ser el orden distinto, son sucesiones diferentes."]}
    ],
    "errores_frecuentes": ["Confundir una 'sucesión' con un 'conjunto'. (En los conjuntos el orden no importa, en las sucesiones sí).", "Pensar que las sucesiones solo pueden ir en aumento (pueden decrecer, alternar signos o incluso ser constantes como 3, 3, 3...)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCDEF-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la característica principal que diferencia a una sucesión de un simple conjunto matemático de números? (v{i})", "choices": ["A) En una sucesión, el orden de los números es estrictamente relevante.", "B) Las sucesiones solo pueden contener números enteros positivos.", "C) Un conjunto siempre tiene infinitos elementos, la sucesión no.", "D) Las sucesiones no permiten repetir el mismo número."], "correct_answer": "A) En una sucesión, el orden de los números es estrictamente relevante.", "solution_steps": "Una sucesión es, por definición, una lista ordenada.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SUCDEF-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Los números individuales que forman parte de una sucesión numérica reciben el nombre matemático de:", "choices": ["A) Términos.", "B) Índices.", "C) Exponentes.", "D) Coeficientes."], "correct_answer": "A) Términos.", "solution_steps": "Cada elemento en la fila es un 'término' de la sucesión.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCDEF-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿La sucesión formada por los números $2, 4, 6$ es considerada exactamente la misma sucesión que $6, 4, 2$?", "choices": [], "correct_answer": "Falso", "solution_steps": "Al cambiar el orden, se transforma en una sucesión diferente.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUCDEF-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un estudiante anota las edades de sus $4$ hermanos desde el menor hasta el mayor, obteniendo la lista: $5, 8, 12, 15$. Su profesor le pide formar una nueva sucesión invirtiendo el orden. ¿Qué afirmación es correcta respecto a estas dos listas? (v{i})", "choices": ["A) Representan sucesiones distintas, a pesar de contener los mismos elementos.", "B) Representan exactamente la misma sucesión, pues los elementos son idénticos.", "C) La segunda lista no puede ser considerada una sucesión porque los números van disminuyendo.", "D) La suma de los elementos de la segunda sucesión será distinta a la de la primera."], "correct_answer": "A) Representan sucesiones distintas, a pesar de contener los mismos elementos.", "solution_steps": "El orden define a la sucesión. Si el orden cambia, la sucesión cambia.", "paes_style": True})

# 2. ORDEN_TERMINOS
sid2 = "MAT.NUM.SUCESIONES_BASE.ORDEN_TERMINOS"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Identificar y verbalizar la posición que ocupa cada término en una sucesión.",
    "introduccion": "En una carrera de atletismo, no solo importa quiénes corrieron, sino quién llegó primero, segundo y tercero. En las sucesiones, cada número tiene una 'medalla' que indica su posición.",
    "resumen": "Cada número en una sucesión ocupa una posición ordinal: primer término, segundo término, tercer término, etc. La posición se denota habitualmente con la letra '$n$' y siempre es un número natural ($1, 2, 3, \\dots$).",
    "explicacion": "Para no perdernos en la fila de números, asignamos una etiqueta a la posición de cada uno, usando los números de contar (los Naturales: $1, 2, 3, 4\\dots$).\n\nDada la sucesión: $10, 20, 30, 40, \\dots$\n- El número $10$ está en la **posición 1** (es el primer término).\n- El número $20$ está en la **posición 2**.\n- El número $40$ está en la **posición 4**.\n\nEs fundamental **NO confundir el valor del número con su posición**. En el ejemplo, el valor es $40$, pero su posición es $4$. La letra '$n$' se utiliza casi universalmente en matemáticas para representar esta posición.",
    "procedimiento": ["Paso 1: Lee la sucesión de izquierda a derecha.", "Paso 2: Asigna el número 1 al primer valor que leas, el 2 al segundo, etc.", "Paso 3: Si te preguntan por la posición 'n=3', busca el tercer número escrito."],
    "ejemplos": [
        {"titulo": "Ubicando al infiltrado", "enunciado": "En la sucesión: 2, 4, 8, 16, 32... ¿qué valor ocupa la cuarta posición (n=4)?", "solucion_pasos": ["Posición 1: 2", "Posición 2: 4", "Posición 3: 8", "Posición 4: 16.", "El valor en la cuarta posición es 16."]}
    ],
    "errores_frecuentes": ["Confundir el valor del término con el número de su posición (Ej. decir que el término en la posición 16 es el número 4, leyendo al revés).", "Pensar que existe la posición 'cero' o posiciones negativas (las posiciones empiezan siempre en 1)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDTER-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el estudio de las sucesiones, la letra minúscula '$n$' se utiliza habitualmente para representar: (v{i})", "choices": ["A) La posición o lugar que ocupa un término dentro de la sucesión.", "B) El valor numérico más grande de toda la sucesión.", "C) La suma de todos los términos.", "D) El número que siempre va al final."], "correct_answer": "A) La posición o lugar que ocupa un término dentro de la sucesión.", "solution_steps": "La 'n' indica el índice u orden (1°, 2°, 3°...).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"ORDTER-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Dado que indican posiciones en una fila, los valores que puede tomar '$n$' en una sucesión tradicional siempre pertenecen al conjunto de los números:", "choices": ["A) Naturales ($1, 2, 3\\dots$).", "B) Reales (con decimales).", "C) Enteros negativos ($-1, -2\\dots$).", "D) Irracionales."], "correct_answer": "A) Naturales ($1, 2, 3\\dots$).", "solution_steps": "Contamos posiciones como 1ro, 2do, 3ro... sin decimales ni negativos.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDTER-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿En la sucesión $5, 10, 15, 20, 25$, el número $20$ ocupa la posición $n=4$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Contando desde la izquierda, el 20 es el cuarto elemento.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"ORDTER-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Dada la siguiente sucesión de números impares: $1, 3, 5, 7, 9, 11, 13\\dots$ Si un estudiante afirma que 'el número $11$ es $n=6$', ¿qué significa exactamente esta afirmación? (v{i})", "choices": ["A) Que el valor $11$ ocupa el sexto lugar en la lista ordenada.", "B) Que se debe multiplicar $11$ por $6$.", "C) Que en la posición $11$ se encuentra el número $6$.", "D) Que el número $11$ es el último término de la sucesión."], "correct_answer": "A) Que el valor $11$ ocupa el sexto lugar en la lista ordenada.", "solution_steps": "La letra n indica la posición. $n=6$ significa sexta posición. El sexto elemento es el 11.", "paes_style": True})

# 3. NOTACION_SUBINDICE
sid3 = "MAT.NUM.SUCESIONES_BASE.NOTACION_SUBINDICE"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Utilizar e interpretar la notación algebraica con subíndices ($a_n$) en sucesiones.",
    "introduccion": "Los matemáticos son perezosos para escribir. En lugar de anotar 'el quinto número de la fila A es 20', inventaron un símbolo corto y elegante: $a_5 = 20$. Conocer este idioma te ahorrará mucha lectura.",
    "resumen": "Para referirnos a un término específico usamos una letra minúscula seguida de un subíndice. $a_1$ es el primer término, $a_2$ es el segundo, y $a_n$ se refiere al término genérico en la posición '$n$'.",
    "explicacion": "En vez de escribir frases largas, usamos la **notación de subíndice**:\n- Se elige una letra para nombrar a la sucesión completa (casi siempre **$a$**, a veces $b$, $c$, etc.).\n- Se le añade un número pequeñito abajo a la derecha (**el subíndice**), que indica la posición.\n\nEjemplo en la sucesión $a$: $7, 14, 21, 28, \\dots$\n- **$a_1 = 7$** (Se lee 'a sub uno es igual a siete').\n- **$a_2 = 14$**\n- **$a_4 = 28$**\n\nEl símbolo mágico es **$a_n$**, que significa 'un término cualquiera que está en la posición $n$'. Te permite hablar de las reglas de la sucesión de manera universal sin referirte a un número específico.",
    "procedimiento": ["Paso 1: Identifica la letra base (por ejemplo 'a') que nombra la lista.", "Paso 2: Mira el número chiquito (subíndice). Ese es la posición 'n'.", "Paso 3: Busca en la lista el valor numérico que está en esa posición."],
    "ejemplos": [
        {"titulo": "Traduciendo el subíndice", "enunciado": "Dada la sucesión b: 100, 90, 80, 70, 60... ¿Cuánto vale la suma de $b_2 + b_5$?", "solucion_pasos": ["El subíndice indica la posición.", "$b_2$ es el segundo término, que vale 90.", "$b_5$ es el quinto término, que vale 60.", "La suma es 90 + 60 = 150."]}
    ],
    "errores_frecuentes": ["Creer que el subíndice multiplica a la letra (pensar que $a_3$ significa 'a multiplicado por 3').", "Confundir el subíndice (posición) con el exponente (potencia). ¡Van escritos abajo, no arriba!"],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUBIND-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En la expresión algebraica $a_7 = 40$ referida a una sucesión numérica, ¿qué información nos entrega el número $7$? (v{i})", "choices": ["A) Indica la posición ordinal que ocupa el valor 40 en la lista.", "B) Indica que el número 40 debe multiplicarse por 7.", "C) Indica el valor del séptimo término, que es 7.", "D) Indica que la sucesión tiene un total de 7 elementos."], "correct_answer": "A) Indica la posición ordinal que ocupa el valor 40 en la lista.", "solution_steps": "El subíndice (el 7) siempre indica el índice o posición del término en la fila.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"SUBIND-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "¿Cómo se lee correctamente la expresión genérica $a_n$ en el contexto de sucesiones?", "choices": ["A) El término enésimo (o de posición n).", "B) 'a' elevado a 'n'.", "C) 'a' multiplicado por 'n'.", "D) 'n' dividido por 'a'."], "correct_answer": "A) El término enésimo (o de posición n).", "solution_steps": "Al referirse a la posición 'n' de forma general, se le llama el término 'enésimo'.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUBIND-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿En la sucesión $3, 6, 9, 12, 15$, es correcto afirmar que $a_3 = 9$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "$a_3$ se refiere al tercer elemento de la sucesión, el cual efectivamente es 9.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"SUBIND-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Se tiene la sucesión $c$: $2, 4, 8, 16, 32, 64$. Un estudiante debe calcular el resultado de la expresión: $(c_4 - c_2) \\cdot c_1$. ¿Cuál es el resultado correcto de esta operación? (v{i})", "choices": ["A) $24$", "B) $8$", "C) $16$", "D) $4$"], "correct_answer": "A) $24$", "solution_steps": "Identificamos términos: $c_4 = 16$, $c_2 = 4$, $c_1 = 2$. Reemplazamos: $(16 - 4) \\cdot 2 = 12 \\cdot 2 = 24$.", "paes_style": True})

# 4. TERMINO_GENERAL_CONCEPTO
sid4 = "MAT.NUM.SUCESIONES_BASE.TERMINO_GENERAL_CONCEPTO"
RECURSOS.append({
    "semantic_id": sid4, "objetivo": "Comprender qué es el término general de una sucesión y cómo funciona como una máquina o fórmula productora de números.",
    "introduccion": "Si te doy los números 2, 4, 6... es fácil adivinar el que sigue. Pero si te pido el término que está en la posición un millón, ¿vas a sumar de a 2 un millón de veces? ¡Para eso inventamos el Término General!",
    "resumen": "El **Término General ($a_n$)** es una fórmula algebraica que genera cualquier valor de la sucesión simplemente reemplazando la '$n$' por la posición que deseas descubrir.",
    "explicacion": "Imagina que una sucesión es una fábrica de hacer números. El **término general** es la 'receta secreta' de la máquina.\n\nEs una expresión algebraica que siempre lleva la letra '$n$' (la posición).\nPor ejemplo, si la fórmula de la máquina es **$a_n = 3n$**, significa que la máquina toma el número de posición que tú le digas y lo multiplica por 3.\n\n- Si quieres fabricar al que va primero ($n=1$): $3 \\cdot 1 = 3$.\n- Si quieres fabricar al segundo ($n=2$): $3 \\cdot 2 = 6$.\n- Si quieres descubrir quién está en la posición número cien ($n=100$): $3 \\cdot 100 = 300$.\n\nEl término general te da el superpoder de 'teletransportarte' a cualquier lugar de la fila sin tener que calcular todos los números anteriores.",
    "procedimiento": ["Paso 1: Entiende que '$a_n = \\dots$' es una fórmula matemática.", "Paso 2: Reconoce que la '$n$' de la fórmula representa el número de la posición.", "Paso 3: Para descubrir el valor de un término, se reemplaza la 'n' por la posición deseada y se resuelve la operatoria."],
    "ejemplos": [
        {"titulo": "La fábrica de impares", "enunciado": "La fórmula general de los números impares es $a_n = 2n - 1$. Sin sumar desde el principio, ¿cuál es el 50° número impar?", "solucion_pasos": ["Quiero la posición 50, así que $n = 50$.", "Tomo la fórmula: $2 \\cdot (50) - 1$.", "Multiplico: $100 - 1 = 99$.", "El número impar número 50 de la fila es el 99."]}
    ],
    "errores_frecuentes": ["Creer que la letra 'n' en la fórmula representa el valor del número en sí, en lugar de su posición.", "Pensar que todas las sucesiones tienen una fórmula simple (algunas sucesiones reales son muy caóticas y difíciles de modelar con una sola fórmula)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENCON-GEN-CONC-{i}", "semantic_id": sid4, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es la utilidad principal de tener el 'Término General' ($a_n$) de una sucesión numérica? (v{i})", "choices": ["A) Permite calcular el valor de cualquier término de la sucesión directamente, conociendo solo su posición.", "B) Permite saber cuál es el último número exacto de cualquier sucesión infinita.", "C) Sirve para ordenar los números de mayor a menor.", "D) Es el nombre que se le da al término más grande de la sucesión."], "correct_answer": "A) Permite calcular el valor de cualquier término de la sucesión directamente, conociendo solo su posición.", "solution_steps": "Actúa como una fórmula o 'máquina' para generar cualquier elemento de la fila instantáneamente.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"TGENCON-GEN-REC-1", "semantic_id": sid4, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "En la fórmula del término general $a_n = 5n + 2$, la variable '$n$' debe ser reemplazada por:", "choices": ["A) El número de la posición que se desea calcular.", "B) El valor del término anterior.", "C) La suma de todos los términos.", "D) Un número decimal al azar."], "correct_answer": "A) El número de la posición que se desea calcular.", "solution_steps": "La 'n' representa la posición o índice ordinal.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENCON-GEN-PROC-{i}", "semantic_id": sid4, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si el término general de una sucesión es $a_n = n^2$, entonces la sucesión generada corresponde a los cuadrados perfectos: $1, 4, 9, 16\\dots$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Si $n=1, 1^2=1$. Si $n=2, 2^2=4$. Si $n=3, 3^2=9$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"TGENCON-GEN-PAES-{i}", "semantic_id": sid4, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"La sucesión de los números pares positivos es $2, 4, 6, 8, 10\\dots$ Un estudiante propone que la fórmula general para esta sucesión es $a_n = n + 2$. ¿Es correcta esta afirmación? (v{i})", "choices": ["A) No, porque al evaluar $n=1$ arroja $3$, pero el primer par es $2$.", "B) Sí, porque si evaluamos $n=2$ arroja $4$, que es un número par.", "C) No, porque las sucesiones de números pares no tienen fórmula general.", "D) Sí, porque siempre suma $2$ al término anterior."], "correct_answer": "A) No, porque al evaluar $n=1$ arroja $3$, pero el primer par es $2$.", "solution_steps": "El término general debe cumplir para TODOS los términos desde $n=1$. Si evaluamos $a_1 = 1 + 2 = 3$. Falla inmediatamente.", "paes_style": True})

# 5. CALCULO_TERMINOS_GENERAL
sid5 = "MAT.NUM.SUCESIONES_BASE.CALCULO_TERMINOS_GENERAL"
RECURSOS.append({
    "semantic_id": sid5, "objetivo": "Calcular los primeros términos o un término específico de una sucesión a partir de su fórmula general.",
    "introduccion": "Ya conocemos la máquina que fabrica números. ¡Ahora aprendamos a usarla! Conecta los cables, engrasa las piezas, introduce el número de posición y veamos qué sale por el otro lado de la fórmula.",
    "resumen": "Para construir la sucesión a partir de $a_n$, se reemplaza la $n$ por $1$ para el primer término, por $2$ para el segundo, por $3$ para el tercero, y así sucesivamente, respetando la jerarquía de las operaciones matemáticas.",
    "explicacion": "Construir una sucesión desde su fórmula general es un simple ejercicio de **evaluación algebraica**.\n\nReglas importantes:\n1. Sustituye la letra $n$ por el número de la posición.\n2. Respeta el **PAPOMUDAS** (Paréntesis, Potencias, Multiplicación/División, Adición/Sustracción).\n3. Cuidado con los signos negativos y las fracciones.\n\nEjemplo: Generar los 3 primeros términos de la sucesión $a_n = n^2 - 1$.\n- Para $n=1$: $\\rightarrow (1)^2 - 1 \\rightarrow 1 - 1 = 0$\n- Para $n=2$: $\\rightarrow (2)^2 - 1 \\rightarrow 4 - 1 = 3$\n- Para $n=3$: $\\rightarrow (3)^2 - 1 \\rightarrow 9 - 1 = 8$\nLa sucesión comienza así: $0, 3, 8, \\dots$",
    "procedimiento": ["Paso 1: Escribe la fórmula general.", "Paso 2: Haz una lista con las posiciones 'n' que te piden (ej. $n=1, n=2, n=3$).", "Paso 3: Sustituye la 'n' en la fórmula por cada número de la lista y resuelve paso a paso."],
    "ejemplos": [
        {"titulo": "Alternancia de signos", "enunciado": "Calcula el primer y el segundo término de la sucesión con fórmula $a_n = (-1)^n \\cdot 5$.", "solucion_pasos": ["Para n=1: $(-1)^1 \\cdot 5 = (-1) \\cdot 5 = -5$.", "Para n=2: $(-1)^2 \\cdot 5 = (+1) \\cdot 5 = 5$.", "La sucesión empieza alternando: -5, 5..."]}
    ],
    "errores_frecuentes": ["Olvidar que $3n$ significa '3 multiplicado por n' y no '3 sumado a n'.", "Cometer errores de signos al elevar a potencias, especialmente cuando $n$ acompaña a bases negativas (ej. $(-1)^n$)."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCGEN-GEN-CONC-{i}", "semantic_id": sid5, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al usar la fórmula del término general $a_n = 4n - 1$ para calcular el tercer término de la sucesión, el procedimiento correcto implica: (v{i})", "choices": ["A) Multiplicar $4$ por $3$ y luego restarle $1$.", "B) Restarle $1$ a $4$ y el resultado multiplicarlo por $3$.", "C) Sumar $3$ cuatro veces y restar $1$.", "D) Reemplazar la '$n$' por el número del término anterior."], "correct_answer": "A) Multiplicar $4$ por $3$ y luego restarle $1$.", "solution_steps": "El tercer término corresponde a $n=3$. Al evaluar, por jerarquía primero va la multiplicación $4 \\cdot 3$, luego la resta.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"CALCGEN-GEN-REC-1", "semantic_id": sid5, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si se te pide 'obtener los $4$ primeros términos' de una sucesión con término general $a_n$, debes evaluar la fórmula en los valores de '$n$':", "choices": ["A) $1, 2, 3$ y $4$.", "B) $0, 1, 2$ y $3$.", "C) $2, 4, 6$ y $8$.", "D) Solamente en $n=4$."], "correct_answer": "A) $1, 2, 3$ y $4$.", "solution_steps": "Los primeros términos corresponden a las posiciones desde la 1 hasta la 4.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCGEN-GEN-PROC-{i}", "semantic_id": sid5, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿El quinto término de la sucesión definida por la fórmula $a_n = n^2 + 2$ es $27$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Si $n=5$, evaluamos $5^2 + 2 = 25 + 2 = 27$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"CALCGEN-GEN-PAES-{i}", "semantic_id": sid5, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": r"Una sucesión está definida matemáticamente por el término general $a_n = \frac{2n - 1}{n}$. ¿Cuáles son los tres primeros términos de esta sucesión en orden? (v" + str(i) + ")", "choices": [r"A) $1$, $\frac{3}{2}$, $\frac{5}{3}$", r"B) $1$, $2$, $3$", r"C) $0$, $\frac{1}{2}$, $\frac{2}{3}$", r"D) $\frac{1}{2}$, $\frac{3}{4}$, $\frac{5}{6}$"], "correct_answer": r"A) $1$, $\frac{3}{2}$, $\frac{5}{3}$", "solution_steps": r"$n=1 \rightarrow (2(1)-1)/1 = 1/1 = 1$. $n=2 \rightarrow (2(2)-1)/2 = 3/2$. $n=3 \rightarrow (2(3)-1)/3 = 5/3$.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 1 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 1 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-1", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-1.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
