# scratch/build_b0206_t8.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 1. ELECCION_MODELO
sid1 = "MAT.NUM.PROGRESIONES_COMPARACION.ELECCION_MODELO"
RECURSOS.append({
    "semantic_id": sid1, "objetivo": "Justificar la elección correcta entre un modelo aritmético o uno geométrico para representar un problema real.",
    "introduccion": "Imagina que eres un analista financiero. Tienes que proyectar las ganancias de una empresa. Si usas la herramienta equivocada, predecirás la quiebra cuando en realidad se volverán millonarios. Elegir el modelo es el 90% del trabajo.",
    "resumen": "La elección del modelo depende exclusivamente de la **naturaleza de la tasa de cambio**. Si el problema describe cuotas fijas o aportes absolutos (peso por peso), eliges el **Modelo Aritmético**. Si describe tasas de interés, replicación biológica o inflación, eliges el **Modelo Geométrico**.",
    "explicacion": "A la hora de leer un problema complejo, subraya las palabras que denotan cómo avanza el tiempo:\n\n1. **Palabras clave para Modelo Aritmético:** 'Bono fijo', 'cuota mensual plana', 'caída de $5$ grados por hora', 'depreciación lineal'. \n   - Justificación: La diferencia 'd' entre periodos es un valor constante independiente del total acumulado.\n\n2. **Palabras clave para Modelo Geométrico:** 'Interés compuesto', 'crecimiento poblacional', 'depreciación porcentual', 'se divide a la mitad', 'tasa de inflación'.\n   - Justificación: El aumento o disminución se calcula sobre el nuevo saldo de cada periodo, creando un efecto de bola de nieve (razón 'r').\n\n*Nota PAES:* Te presentarán dos opciones de inversión o cobro y te preguntarán cuál conviene más a largo plazo. Recuerda que la progresión geométrica (si $r > 1$) SIEMPRE terminará superando a la aritmética, sin importar la ventaja inicial que tenga la aritmética.",
    "procedimiento": ["Paso 1: Identifica qué está cambiando en la historia.", "Paso 2: Evalúa si el cambio en el paso 2 depende del tamaño del paso 1 (Ej: ganar el 10% de 100 no es lo mismo que el 10% de 1000). Si depende del tamaño previo, es Geométrico.", "Paso 3: Si el cambio siempre es el mismo número rígido (Ej: ganar siempre $1000), es Aritmético."],
    "ejemplos": [
        {"titulo": "Eligiendo el plan de celular", "enunciado": "Plan A: Pagas $10.000 más $50 por cada minuto. Plan B: El primer minuto cuesta $10 y cada minuto extra cuesta el doble del anterior. ¿Qué modelos son?", "solucion_pasos": ["Plan A: Suma $50 por unidad. Es Aditivo -> Modelo Aritmético.", "Plan B: Multiplica por 2 por unidad ('el doble'). Es Multiplicativo -> Modelo Geométrico.", "Si hablas 10 minutos, el Plan B te arruinará exponencialmente."]}
    ],
    "errores_frecuentes": ["Elegir el modelo basándose en los números iniciales (Ej: si los números son grandes, creer que es geométrica).", "Olvidar que el 'interés simple' es Aritmético, mientras que el 'interés compuesto' es Geométrico."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EMOD-GEN-CONC-{i}", "semantic_id": sid1, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál de las siguientes situaciones financieras exige rigurosamente el uso de un modelo matemático Geométrico en lugar de uno Aritmético para proyectar su valor a futuro? (v{i})", "choices": ["A) Una inversión en un depósito a plazo con interés compuesto anual.", "B) Un crédito donde se paga una cuota fija de $\$50.000$ todos los meses.", "C) Una alcancía donde se inserta una moneda de $\$500$ diariamente.", "D) El pago del peaje de una autopista donde se cobra $\$1.000$ por cada pórtico cruzado."], "correct_answer": "A) Una inversión en un depósito a plazo con interés compuesto anual.", "solution_steps": "El interés compuesto se calcula sobre el capital acumulado anterior, generando un efecto multiplicativo (Geométrico).", "paes_style": False})
EJERCICIOS.append({"stable_id": f"EMOD-GEN-REC-1", "semantic_id": sid1, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Al modelar la pérdida de temperatura de un café recién servido que se enfría según la Ley de Enfriamiento de Newton (su temperatura decae un porcentaje fijo de la diferencia térmica cada minuto), la elección teórica correcta recae sobre:", "choices": ["A) Un Modelo Geométrico (o exponencial).", "B) Un Modelo Aritmético (o lineal).", "C) Un Modelo Cuadrático.", "D) Una Serie Infinita."], "correct_answer": "A) Un Modelo Geométrico (o exponencial).", "solution_steps": "Al decaer un 'porcentaje fijo' respecto a la cantidad anterior, es una razón de decaimiento multiplicativa.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EMOD-GEN-PROC-{i}", "semantic_id": sid1, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si un contrato de arriendo estipula que el valor a pagar subirá en $\$20.000$ fijos cada mes de enero, este contrato sigue estrictamente un modelo de Progresión Aritmética?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Se suma una constante absoluta (d = 20.000). Es un modelo Aditivo, es decir, Aritmético.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"EMOD-GEN-PAES-{i}", "semantic_id": sid1, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Una empresa minera contrata a un ingeniero para evaluar dos maquinarias (Opción X y Opción Y). La Opción X pierde $\$500.000$ de valor de reventa cada año de uso continuado. La Opción Y pierde el $10\\%$ de su valor de reventa del año inmediatamente anterior. ¿Qué recomendación técnica y modelamiento es correcto presentarle a la gerencia? (v{i})", "choices": ["A) La Opción X se modela con Progresión Aritmética y la Opción Y con Progresión Geométrica.", "B) Ambas opciones siguen modelos Aritméticos de depreciación.", "C) La Opción X se modela con Progresión Geométrica y la Opción Y con Progresión Aritmética.", "D) Ambas opciones siguen modelos Geométricos de depreciación."], "correct_answer": "A) La Opción X se modela con Progresión Aritmética y la Opción Y con Progresión Geométrica.", "solution_steps": "X resta un monto fijo ('d' negativo = Aritmética). Y resta un porcentaje (multiplica por 0.90 = Geométrica).", "paes_style": True})

# 2. INTERPOLACION_ARITMETICA
sid2 = "MAT.NUM.PROGRESIONES_COMPARACION.INTERPOLACION_ARITMETICA"
RECURSOS.append({
    "semantic_id": sid2, "objetivo": "Interpolar (insertar) medios aritméticos (números faltantes) entre dos extremos conocidos para completar una Progresión Aritmética.",
    "introduccion": "Alguien borró los números del medio en una lista. Tienes el primero y el último, y sabes que era una progresión aritmética. Tu misión es construir el puente de escalones perfectos entre esos dos extremos. A esto le llamamos 'Interpolar'.",
    "resumen": "Para interpolar '$k$' medios aritméticos entre un número '$A$' y un número '$B$', debes calcular la diferencia constante '$d$' usando la fórmula de los saltos: **$d = \\frac{B - A}{k + 1}$**. Luego, vas sumando '$d$' desde '$A$' hasta llegar a '$B$'.",
    "explicacion": "Visualiza el problema:\nTe dan el número 5 y el número 17. Te piden **interpolar 3 números** en el medio para que formen una P.A.\n- La lista se vería así: $5, \\_ , \\_ , \\_ , 17$.\n- Cuentas los saltos: Para pasar del 5 al 17 a través de 3 espacios vacíos, debes dar **4 saltos** (siempre es $k+1$ saltos, donde '$k$' es la cantidad de huecos).\n\nCálculo de la diferencia 'd':\n1. Distancia total = $17 - 5 = 12$.\n2. Cantidad de saltos = $3 + 1 = 4$.\n3. Tamaño de cada salto ($d$) = Distancia Total / Saltos = $12 / 4 = 3$.\n\nLlenamos los huecos sumando de a 3:\n- $5 + 3 = 8$\n- $8 + 3 = 11$\n- $11 + 3 = 14$\n- ¡Y comprobamos! $14 + 3 = 17$. El puente encaja perfectamente. Los 'medios aritméticos' son $8, 11$ y $14$.",
    "procedimiento": ["Paso 1: Resta el extremo final menos el extremo inicial ($B - A$).", "Paso 2: A la cantidad de números a interpolar ($k$), súmale 1 ($k + 1$).", "Paso 3: Divide el resultado del Paso 1 entre el resultado del Paso 2. Esta es tu diferencia 'd'.", "Paso 4: Suma 'd' repetidamente partiendo desde 'A'."],
    "ejemplos": [
        {"titulo": "Construyendo la escalera", "enunciado": "Interpolar 4 medios aritméticos entre 10 y 40.", "solucion_pasos": ["A = 10, B = 40. k = 4.", "Distancia total = 40 - 10 = 30.", "Número de saltos = 4 + 1 = 5.", "d = 30 / 5 = 6.", "Interpolar: 10 (+6)-> 16 (+6)-> 22 (+6)-> 28 (+6)-> 34 (+6)-> 40.", "Los medios son: 16, 22, 28, 34."]}
    ],
    "errores_frecuentes": ["Dividir la distancia total simplemente por '$k$' (la cantidad de huecos) en lugar de '$k+1$' (los saltos). ¡Si hay 3 huecos, hay 4 espacios/saltos que los conectan!", "Confundirse y restar al revés ($A - B$) obteniendo una diferencia con el signo cambiado."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTARI-GEN-CONC-{i}", "semantic_id": sid2, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al usar la fórmula $d = \\frac{{B - A}}{{k + 1}}$ para interpolar medios aritméticos, ¿qué representa físicamente el valor del denominador '$(k + 1)$' dentro del modelo de la progresión? (v{i})", "choices": ["A) Representa la cantidad total de 'saltos' o intervalos que existen entre el primer término y el último.", "B) Representa la cantidad total de números en la progresión, incluyendo los extremos.", "C) Representa la suma de todos los términos faltantes.", "D) Representa la posición del número más grande."], "correct_answer": "A) Representa la cantidad total de 'saltos' o intervalos que existen entre el primer término y el último.", "solution_steps": "Si metes 'k' números entre dos extremos, generas 'k+1' espacios o transiciones (saltos) para cruzar de lado a lado.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTARI-GEN-REC-1", "semantic_id": sid2, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si te piden interpolar $5$ medios aritméticos entre los números $12$ y $60$, la ecuación correcta para calcular la diferencia constante '$d$' es:", "choices": [r"A) $d = \frac{60 - 12}{6}$", r"B) $d = \frac{60 - 12}{5}$", r"C) $d = \frac{60 + 12}{6}$", r"D) $d = \frac{12 - 60}{5}$"], "correct_answer": r"A) $d = \frac{60 - 12}{6}$", "solution_steps": "Es $(B - A) / (k + 1)$. Si $k=5$, el denominador es $5+1=6$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTARI-GEN-PROC-{i}", "semantic_id": sid2, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si interpolamos un único ($1$) medio aritmético entre los números $10$ y $20$, ese número central será exactamente $15$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "k=1. Saltos = 2. d = (20-10)/2 = 10/2 = 5. Medio = 10+5 = 15. Es el promedio simple.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTARI-GEN-PAES-{i}", "semantic_id": sid2, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un arquitecto diseña una escalera recta. El primer peldaño está a $15$ cm del suelo y la plataforma final descansa a $135$ cm del suelo. Si el arquitecto necesita colocar $3$ peldaños intermedios entre el primero y la plataforma, asegurando que todos tengan la misma altura (diferencia constante), ¿a qué altura exacta respecto del suelo debe estar el segundo peldaño de la escalera (el primero de los intermedios)? (v{i})", "choices": ["A) $45$ cm.", "B) $30$ cm.", "C) $55$ cm.", "D) $75$ cm."], "correct_answer": "A) $45$ cm.", "solution_steps": "Interpolar k=3 entre A=15 y B=135. Saltos = 4. d = (135 - 15) / 4 = 120 / 4 = 30 cm. El 1er intermedio estará a 15 + 30 = 45 cm.", "paes_style": True})

# 3. INTERPOLACION_GEOMETRICA
sid3 = "MAT.NUM.PROGRESIONES_COMPARACION.INTERPOLACION_GEOMETRICA"
RECURSOS.append({
    "semantic_id": sid3, "objetivo": "Interpolar (insertar) medios geométricos (números faltantes) entre dos extremos conocidos calculando la razón a través de raíces.",
    "introduccion": "Ya rellenamos huecos sumando. Ahora rellenaremos huecos multiplicando. Cuando la brecha entre el primer y último número es explosiva (ejemplo: de 2 a 162 en pocos pasos), sabes que estás en territorio geométrico. Las raíces serán tus mejores amigas aquí.",
    "resumen": "Para interpolar '$k$' medios geométricos entre '$A$' y '$B$', debes calcular la razón multiplicativa '$r$' usando la fórmula de raíces: **$r = \\sqrt[k+1]{\\frac{B}{A}}$**. Luego, vas multiplicando repetidamente por '$r$' desde '$A$'.",
    "explicacion": "Visualicemos: Interpolar **2 medios geométricos** entre el número 3 y el número 192.\n- La lista: $3, \\_ , \\_ , 192$.\n- Hay 2 huecos, lo que significa que daremos **3 saltos multiplicativos**. (Multiplicaremos por '$r$' tres veces seguidas).\n\nPara hallar 'r', hacemos el camino inverso a la potencia (la raíz):\n1. Cociente total = $192 / 3 = 64$.\n2. Cantidad de saltos = $k + 1 = 2 + 1 = 3$.\n3. Extraer la raíz: $r = \\sqrt[3]{64}$. \n4. Buscamos qué número multiplicado por sí mismo 3 veces da 64. ¡Es el 4!\n5. La razón $r = 4$.\n\nLlenamos los huecos multiplicando:\n- $3 \\cdot 4 = 12$\n- $12 \\cdot 4 = 48$\n- Comprobamos el puente: $48 \\cdot 4 = 192$. ¡Encaje perfecto! Los medios son 12 y 48.",
    "procedimiento": ["Paso 1: Divide el término final entre el término inicial ($B / A$).", "Paso 2: A la cantidad de números a interpolar ($k$) súmale 1 ($k + 1$). Este será el índice de tu raíz.", "Paso 3: Saca la raíz de índice '$(k+1)$' al resultado de la división. Esa es tu razón 'r'.", "Paso 4: Multiplica por 'r' repetidamente partiendo desde 'A' para llenar los espacios."],
    "ejemplos": [
        {"titulo": "El eslabón perdido", "enunciado": "Interpolar 1 medio geométrico entre 5 y 125.", "solucion_pasos": ["A = 5, B = 125, k = 1.", "Índice de la raíz = 1 + 1 = 2 (raíz cuadrada).", "Cociente = 125 / 5 = 25.", "r = Raíz Cuadrada de 25 = 5.", "Interpolar: 5 * 5 = 25. Compruebo: 25 * 5 = 125.", "El medio geométrico es 25."]}
    ],
    "errores_frecuentes": ["Olvidar que si la cantidad de saltos ($k+1$) es un número PAR (ej: raíz cuadrada o cuarta), la razón 'r' podría ser un número negativo (Ej: $\\sqrt{25}$ puede ser 5 o -5), abriendo la puerta a dos sucesiones posibles.", "Aplicar la fórmula de interpolación aritmética por error, terminando con sumas raras en vez de raíces."],
    "fuente": "Currículum Nacional MINEDUC.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGEO-GEN-CONC-{i}", "semantic_id": sid3, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al usar la fórmula $r = \\sqrt[k+1]{{\\frac{{B}}{{A}}}}$ para encontrar la razón en una interpolación geométrica, ¿por qué utilizamos específicamente una operación de Raíz (radical)? (v{i})", "choices": ["A) Porque para ir del número A al B tuvimos que multiplicar por la razón varias veces (creando una potencia $r^{k+1}$), y la raíz es la operación inversa que anula esa potencia para despejar la razón aislada.", "B) Porque la fórmula general de todas las progresiones requiere raíces cuadradas por convención.", "C) Porque los números geométricos son irracionales.", "D) Porque es la única forma de volver negativos a los números positivos."], "correct_answer": "A) Porque para ir del número A al B tuvimos que multiplicar por la razón varias veces (creando una potencia $r^{k+1}$), y la raíz es la operación inversa que anula esa potencia para despejar la razón aislada.", "solution_steps": "Despejamos de la ecuación general. $B = A \\cdot r^{k+1}$. El camino inverso exige usar la raíz de índice $k+1$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"INTGEO-GEN-REC-1", "semantic_id": sid3, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Si debes interpolar $2$ medios geométricos entre los números $2$ y $54$, ¿cuál de las siguientes expresiones algebraicas te entregará directamente el valor de la razón '$r$'?", "choices": [r"A) $r = \sqrt[3]{\frac{54}{2}}$", r"B) $r = \sqrt[2]{\frac{54}{2}}$", r"C) $r = \frac{54 - 2}{3}$", r"D) $r = \sqrt[3]{54 \cdot 2}$"], "correct_answer": r"A) $r = \sqrt[3]{\frac{54}{2}}$", "solution_steps": "Se divide el final entre el inicio ($54/2$) y se saca raíz de índice $k+1$. Como $k=2$, el índice es 3 (raíz cúbica).", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGEO-GEN-PROC-{i}", "semantic_id": sid3, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "basica", "competencia": "M1", "prompt": "¿Si se interpola un ($1$) único medio geométrico POSITIVO entre los números $4$ y $36$, ese número central resultará ser el $12$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "r = RaizCuadrada(36/4) = RaizCuadrada(9) = 3 (positivo). El medio es $4 \\cdot 3 = 12$. Es verdadero.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"INTGEO-GEN-PAES-{i}", "semantic_id": sid3, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M2", "prompt": f"Un equipo de biólogos registra el número de células en un cultivo cerrado. En la hora cero hay $10$ células. Tras la hora tres de incubación, el contador marca $80$ células. Sabiendo que el crecimiento sigue un modelo de progresión geométrica estricta, ¿cuántas células marcaba exactamente el contador en la hora número dos? (v{i})", "choices": ["A) $40$ células.", "B) $30$ células.", "C) $60$ células.", "D) $45$ células."], "correct_answer": "A) $40$ células.", "solution_steps": "Hay que interpolar 2 datos (hora 1 y hora 2) entre el 10 y el 80. Saltos (k+1) = 3. RaizCúbica(80/10) = RaizCúbica(8) = 2. La razón es 2. Hora 1: 10*2=20. Hora 2: 20*2=40.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 8 (B0206)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 8 (B0206)...")
    append_jsonl("mat-num-sucesiones-banco-gen-8", EJERCICIOS)
    print("Creado mat-num-sucesiones-banco-gen-8.jsonl con 30 ejercicios.")

if __name__ == "__main__":
    generate_all()
