# scratch/build_alg_b0302_t2.py
import json
import yaml
from pathlib import Path

CONTENT_DIR = Path("docs/conocimiento/contenido")
EJERCICIOS_DIR = Path("docs/conocimiento/ejercicios")

def write_yaml(filename, data):
    with open(CONTENT_DIR / f"{filename}.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

def append_jsonl(filename, items):
    with open(EJERCICIOS_DIR / f"{filename}.jsonl", "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

RECURSOS = []
EJERCICIOS = []

# 6. PRODUCTO_NUMEROS
sid6 = "MAT.ALG.LENGUAJE_OPERACIONES.PRODUCTO_NUMEROS"
RECURSOS.append({
    "semantic_id": sid6, "objetivo": "Traducir el producto o multiplicación entre dos o más cantidades desconocidas.",
    "introduccion": "Cuando varias fuerzas actúan en conjunto multiplicando sus efectos, hablamos de producto. En el lenguaje de las letras, la multiplicación es la operación más silenciosa y unida de todas.",
    "resumen": "El **Producto de Cantidades** se traduce utilizando la multiplicación. Por convención algebraica, **se omite el signo de multiplicar** cuando se unen letras entre sí o números con letras (multiplicación implícita).",
    "explicacion": "Palabras clave:\n- El producto de\n- Multiplicado por\n- Veces\n- El área de (en contextos rectangulares)\n\nEjemplos:\n- 'El producto de dos números distintos': $xy$\n- 'Un número multiplicado por otro número': $ab$\n- 'La base multiplicada por la altura': $bh$\n\nNo es necesario escribir $x \\cdot y$ ni $x \\times y$, aunque no es un error formal. La norma es escribirlos juntos: $xy$.",
    "procedimiento": ["Paso 1: Identifica los factores (las entidades que se están multiplicando).", "Paso 2: Asígnales variables distintas si son entidades desconocidas diferentes.", "Paso 3: Escribe las letras juntas, una al lado de la otra, para denotar su multiplicación."],
    "ejemplos": [
        {"titulo": "El factor invisible", "enunciado": "Traduce algebraicamente: 'El producto del precio de costo por el margen de ganancia'.", "solucion_pasos": ["Precio de costo es C.", "Margen de ganancia es M.", "La palabra producto exige multiplicar.", "Traducción: CM."]}
    ],
    "errores_frecuentes": ["Traducir usando el signo de suma. (Ej: pensar que 'el producto' es una adición).", "Usar la misma letra para ambas cantidades, escribiendo $x^2$ cuando el enunciado dice 'el producto de *dos* números' (deben ser diferentes, $xy$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PROD-CONC-{i}", "semantic_id": sid6, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Qué convención sintáctica se utiliza predominantemente en el álgebra para representar la traducción de 'el producto de dos variables distintas'? (v{i})", "choices": ["A) La yuxtaposición de las variables, escribiéndolas juntas sin ningún símbolo de operación entre ellas (ej. $xy$).", "B) La separación de las variables mediante un signo más (ej. $x+y$).", "C) La colocación de la letra 'P' antes de las variables (ej. $P(x,y)$).", "D) El uso obligatorio de un asterisco entre las letras."], "correct_answer": "A) La yuxtaposición de las variables, escribiéndolas juntas sin ningún símbolo de operación entre ellas (ej. $xy$).", "solution_steps": "La multiplicación implícita (letras juntas) es el estándar de la notación algebraica.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PROD-REC-1", "semantic_id": sid6, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica la traducción correcta al lenguaje algebraico del enunciado: 'El producto de tres cantidades cualesquiera'.", "choices": ["A) $abc$", "B) $3a$", "C) $a^3$", "D) $a+b+c$"], "correct_answer": "A) $abc$", "solution_steps": "Tres cantidades distintas multiplicadas entre sí se expresan como tres letras unidas: $abc$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PROD-PROC-{i}", "semantic_id": sid6, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿Si el enunciado indica 'el área de un rectángulo de lados desconocidos', la traducción algebraica que modela esta situación asumiendo que los lados son diferentes es $b \\cdot h$ (o $bh$)?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "El área de un rectángulo se define como el producto de sus dos lados distintos (base y altura). Por tanto, modela una multiplicación de dos variables.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PROD-PAES-{i}", "semantic_id": sid6, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Una plataforma calcula el impuesto aduanero a pagar. La regla dice: 'El impuesto final es el producto entre la tasa de riesgo aduanero (variable) y el costo declarado del envío'. Si la tasa es $T$ y el costo es $C$, ¿cuál es el modelo correcto? (v{i})", "choices": ["A) Impuesto $= TC$", "B) Impuesto $= T + C$", "C) Impuesto $= T / C$", "D) Impuesto $= C^T$"], "correct_answer": "A) Impuesto $= TC$", "solution_steps": "La palabra 'producto' exige multiplicar ambas variables: T por C, quedando TC.", "paes_style": True})

# 7. MULTIPLO_NUMERO
sid7 = "MAT.ALG.LENGUAJE_OPERACIONES.MULTIPLO_NUMERO"
RECURSOS.append({
    "semantic_id": sid7, "objetivo": "Traducir múltiplos explícitos de un número (doble, triple, cuádruple).",
    "introduccion": "No es lo mismo decir 'tengo dos amigos' que 'tengo el doble de amigos que tú'. Los múltiplos escalan cantidades desconocidas como si usáramos una fotocopiadora matemática.",
    "resumen": "Un **Múltiplo de un Número** se traduce multiplicando una constante (el factor de multiplicidad) por la variable. **El número constante siempre se escribe a la izquierda de la variable**.",
    "explicacion": "Palabras clave y su traducción directa:\n- El doble de un número: $2x$\n- El triple de una cantidad: $3a$\n- El cuádruple de la ganancia: $4G$\n- Cinco veces un valor: $5v$\n\n*La regla de oro:* El coeficiente (el número fijo) siempre, siempre, va antes de la letra. Escribir $x2$ en vez de $2x$ es un error de sintaxis gravísimo en álgebra formal.",
    "procedimiento": ["Paso 1: Identifica la palabra que indica multiplicidad (doble, triple, veces).", "Paso 2: Conviértela a su número correspondiente (2, 3, etc). Escríbelo primero.", "Paso 3: Identifica de quién estamos calculando ese múltiplo y asigna una variable.", "Paso 4: Escribe la variable inmediatamente a la derecha del número."],
    "ejemplos": [
        {"titulo": "Clonando variables", "enunciado": "Traduce algebraicamente: 'Siete veces la edad del capitán'.", "solucion_pasos": ["La expresión 'Siete veces' nos da la constante multiplicadora: 7.", "La 'edad del capitán' es el objeto a multiplicar: C.", "Se escribe constante seguida de variable: 7C."]}
    ],
    "errores_frecuentes": ["Escribir $x^2$ (x al cuadrado) para expresar 'el doble'. El doble es una multiplicación ($2x$), no una potencia.", "Escribir $x2$ violando la regla del coeficiente a la izquierda."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MULT-CONC-{i}", "semantic_id": sid7, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"¿Cuál es el error conceptual más común que se comete al traducir algebraicamente la frase 'el doble de un número'? (v{i})", "choices": ["A) Traducirla como una potencia, es decir, escribir $x^2$ en lugar de $2x$.", "B) Traducirla como $2+x$.", "C) Traducirla usando el número $3$.", "D) Traducirla como una fracción, $\\frac{x}{2}$."], "correct_answer": "A) Traducirla como una potencia, es decir, escribir $x^2$ en lugar de $2x$.", "solution_steps": "El 'doble' es multiplicar por 2 ($2x$). Elevar al cuadrado ($x^2$) es multiplicar el número por sí mismo, un concepto totalmente distinto.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"MULT-REC-1", "semantic_id": sid7, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica la traducción algebraica formalmente correcta de la frase: 'El triple de una cantidad desconocida'.", "choices": ["A) $3x$", "B) $x3$", "C) $x^3$", "D) $3+x$"], "correct_answer": "A) $3x$", "solution_steps": "El triple implica multiplicar por 3. El coeficiente debe ir a la izquierda de la variable.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MULT-PROC-{i}", "semantic_id": sid7, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión 'ocho veces la altura de la torre' se traduce algebraicamente como $h^8$, asumiendo que $h$ es la altura?", "choices": [], "correct_answer": "Falso", "solution_steps": "La palabra 'veces' es una multiplicación directa, no una potencia. La traducción correcta es $8h$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"MULT-PAES-{i}", "semantic_id": sid7, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"En una fábrica, la meta de producción de este mes exige fabricar 'el cuádruple de lo fabricado el mes anterior'. Si la producción del mes anterior está guardada en la variable $P$, ¿cómo debe escribirse el algoritmo que define la meta actual? (v{i})", "choices": ["A) $Meta = 4P$", "B) $Meta = P^4$", "C) $Meta = P / 4$", "D) $Meta = 4 + P$"], "correct_answer": "A) $Meta = 4P$", "solution_steps": "El cuádruple significa multiplicar por cuatro. Se escribe el coeficiente 4 seguido de la variable P.", "paes_style": True})

# 8. COCIENTE_NUMEROS
sid8 = "MAT.ALG.LENGUAJE_OPERACIONES.COCIENTE_NUMEROS"
RECURSOS.append({
    "semantic_id": sid8, "objetivo": "Traducir el cociente o división entre dos cantidades algebraicas.",
    "introduccion": "A veces hay que repartir en partes iguales. Cuando necesitamos expresar un reparto entre dos variables desconocidas, llamamos al cociente.",
    "resumen": "El **Cociente de Cantidades** se traduce utilizando la división, la cual se representa preferentemente en **formato de fracción** $\\frac{x}{y}$, donde la primera cantidad mencionada es el numerador y la segunda el denominador.",
    "explicacion": "Palabras clave:\n- El cociente entre\n- La división de\n- La razón entre\n- Repartido entre\n\nEjemplos:\n- 'El cociente entre un número y otro número distinto': $\\frac{a}{b}$\n- 'La fortuna de un millonario dividida entre la cantidad de herederos': $\\frac{F}{H}$\n\nIgual que en la resta, **el orden es crítico**. En 'El cociente entre A y B', A debe ir arriba (numerador) y B abajo (denominador).",
    "procedimiento": ["Paso 1: Detecta que se trata de una división (cociente). Dibuja una línea fraccionaria.", "Paso 2: Identifica cuál es la primera cantidad mencionada. Escríbela en la parte de arriba (numerador).", "Paso 3: Identifica la segunda cantidad mencionada. Escríbela en la parte de abajo (denominador)."],
    "ejemplos": [
        {"titulo": "El orden del reparto", "enunciado": "Traduce algebraicamente: 'El cociente entre la velocidad y el tiempo'.", "solucion_pasos": ["La operación es una división.", "La 'velocidad' (v) se nombra primero. Va arriba.", "El 'tiempo' (t) se nombra segundo. Va abajo.", "Traducción: v / t."]}
    ],
    "errores_frecuentes": ["Invertir el orden de las variables. Escribir $\\frac{y}{x}$ cuando el enunciado dijo 'el cociente entre x e y'.", "Usar el símbolo de porcentaje o multiplicación. (Ej. confundir 'repartir' con 'multiplicar')."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COCI-CONC-{i}", "semantic_id": sid8, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"Al traducir el enunciado 'el cociente entre la cantidad $A$ y la cantidad $B$', ¿qué regla determina la posición de las variables en la fracción resultante? (v{i})", "choices": ["A) La cantidad mencionada primero ($A$) asume la posición de dividendo o numerador (arriba), y la mencionada en segundo lugar ($B$) será el divisor o denominador (abajo).", "B) La letra que vaya antes en el abecedario debe ir en el numerador.", "C) La variable que represente la cantidad mayor debe ir siempre en el numerador.", "D) El orden es irrelevante, $\\frac{A}{B}$ y $\\frac{B}{A}$ representan la misma traducción matemática."], "correct_answer": "A) La cantidad mencionada primero ($A$) asume la posición de dividendo o numerador (arriba), y la mencionada en segundo lugar ($B$) será el divisor o denominador (abajo).", "solution_steps": "La división no es conmutativa. El estricto orden de lectura verbal define quién es partido y quién parte.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"COCI-REC-1", "semantic_id": sid8, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Selecciona la expresión algebraica correcta para: 'La división de una longitud desconocida entre una temperatura variable'.", "choices": ["A) $\\frac{L}{T}$", "B) $\\frac{T}{L}$", "C) $L - T$", "D) $LT$"], "correct_answer": "A) $\\frac{L}{T}$", "solution_steps": "Longitud (L) va primero, temperatura (T) va después. El cociente es L sobre T.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COCI-PROC-{i}", "semantic_id": sid8, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La frase 'el cociente entre el doble de un número y el número original' se traduce matemáticamente como $\\frac{2x}{x}$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Primera cantidad es 'el doble de un número' ($2x$). La segunda es 'el número' ($x$). El cociente exacto es $\\frac{2x}{x}$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"COCI-PAES-{i}", "semantic_id": sid8, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un estudio sociológico necesita calcular el 'Índice de Densidad' de varias ciudades. La regla teórica establece que dicho índice es 'el cociente entre la cantidad de habitantes y la superficie territorial en kilómetros cuadrados'. Si Habitantes es $H$ y Superficie es $S$, ¿qué fórmula debe implementar la base de datos? (v{i})", "choices": ["A) $I = \\frac{H}{S}$", "B) $I = \\frac{S}{H}$", "C) $I = H \\cdot S$", "D) $I = H - S$"], "correct_answer": "A) $I = \\frac{H}{S}$", "solution_steps": "La palabra cociente indica fracción. Habitantes se nombra primero (numerador). Superficie se nombra segundo (denominador). Resultado: H/S.", "paes_style": True})

# 9. FRACCION_OPERADOR
sid9 = "MAT.ALG.LENGUAJE_OPERACIONES.FRACCION_OPERADOR"
RECURSOS.append({
    "semantic_id": sid9, "objetivo": "Traducir fracciones que actúan como operadores directos sobre variables o enunciados.",
    "introduccion": "¿Qué ocurre si no quiero la cantidad entera, sino solo un pedazo proporcional de ella? Cuando operamos con partes o rebanadas de variables, las fracciones entran a dominar el juego.",
    "resumen": "Las expresiones como 'la mitad', 'la tercera parte' o 'los dos quintos' se traducen **multiplicando la fracción numérica por la variable**, o bien, colocando la variable directamente en el numerador.",
    "explicacion": "Palabras clave:\n- La mitad de: $\\frac{1}{2}x$ o $\\frac{x}{2}$\n- La tercera parte de: $\\frac{1}{3}y$ o $\\frac{y}{3}$\n- La cuarta parte de: $\\frac{z}{4}$\n- Los dos tercios de: $\\frac{2}{3}x$ o $\\frac{2x}{3}$\n\nLa palabra **DE** en matemáticas de proporciones significa **multiplicación**. \n'Los tres cuartos DE un número' es $\\frac{3}{4} \\cdot x$. Que por regla de fracciones se fusiona hermosamente en $\\frac{3x}{4}$.",
    "procedimiento": ["Paso 1: Identifica la fracción mencionada en palabras (mitad = 1/2, tercio = 1/3, quintos = /5).", "Paso 2: Identifica la variable objetivo (la cantidad de la que se está sacando la fracción).", "Paso 3: Multiplica la fracción por la variable, lo que resulta en colocar el número superior multiplicando a la letra, y el número inferior dividiendo."],
    "ejemplos": [
        {"titulo": "Las tres quintas partes", "enunciado": "Traduce algebraicamente: 'Las tres quintas partes del salario'.", "solucion_pasos": ["Fracción mencionada: 3/5.", "Variable: S (salario).", "La palabra 'del' implica multiplicar 3/5 por S.", "Resultado final: (3S) / 5."]}
    ],
    "errores_frecuentes": ["Traducir 'la mitad de un número' como $x - 2$. (La mitad implica dividir en 2, no restar 2).", "Escribir mal fracciones compuestas (ej. 'dos tercios de x' traducirlo como $\\frac{x}{2/3}$ en lugar de $\\frac{2x}{3}$)."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"FROP-CONC-{i}", "semantic_id": sid9, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": f"En el contexto de la traducción de fracciones como operadores, ¿qué operación matemática fundamental se esconde detrás de la preposición 'de' o 'del' en frases como 'los tres cuartos de un número'? (v{i})", "choices": ["A) Una multiplicación entre la fracción descrita y la variable involucrada.", "B) Una suma entre el numerador y la variable.", "C) Una resta entre el denominador y la variable.", "D) Una igualación entre la fracción y la variable."], "correct_answer": "A) Una multiplicación entre la fracción descrita y la variable involucrada.", "solution_steps": "Sacarle la proporción a algo (el 'DE' algo) es multiplicarlo por esa fracción. $\\frac{3}{4}$ 'de' $x$ es $\\frac{3}{4} \\cdot x$.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"FROP-REC-1", "semantic_id": sid9, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica la traducción algebraica más exacta para el enunciado: 'Las dos séptimas partes del inventario inicial'. (Usa $I$ para inventario).", "choices": ["A) $\\frac{2I}{7}$", "B) $2 + \\frac{I}{7}$", "C) $\\frac{7I}{2}$", "D) $2I - 7$"], "correct_answer": "A) $\\frac{2I}{7}$", "solution_steps": "Dos séptimas partes es la fracción 2/7. Multiplicada por I, nos da 2I/7.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"FROP-PROC-{i}", "semantic_id": sid9, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La frase 'la quinta parte de un número' se puede expresar de forma indistinta y equivalente como $\\frac{1}{5}x$ o como $\\frac{x}{5}$?", "choices": [], "correct_answer": "Verdadero", "solution_steps": "Multiplicar 1/5 por x es matemáticamente idéntico a poner la x directamente en el numerador sobre el 5. Ambas formas son correctas.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"FROP-PAES-{i}", "semantic_id": sid9, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"Un contrato de sociedad establece la distribución de utilidades. Dice literalmente: 'El socio capitalista retirará como ganancia los cuatro novenos de las utilidades totales del mes'. Si la utilidad del mes se designa con la letra $U$, ¿qué expresión debe programar el banco para ejecutar la transferencia al socio capitalista? (v{i})", "choices": ["A) $\\frac{4U}{9}$", "B) $\\frac{9U}{4}$", "C) $4U - 9$", "D) $\\frac{4}{9U}$"], "correct_answer": "A) $\\frac{4U}{9}$", "solution_steps": "Los cuatro novenos son 4/9. El 'de' implica multiplicar por U. El 4 (numerador) multiplica a U, quedando 4U todo sobre 9.", "paes_style": True})

# 10. PARTE_NUMERO
sid10 = "MAT.ALG.LENGUAJE_OPERACIONES.PARTE_NUMERO"
RECURSOS.append({
    "semantic_id": sid10, "objetivo": "Diferenciar la traducción del recíproco respecto del múltiplo, evitando ambigüedades.",
    "introduccion": "En español existe una diferencia sutil pero catastrófica entre 'El doble' y 'La mitad'. Uno te hace rico, el otro te quita dinero. El lenguaje algebraico debe captar estas sutilezas sin margen de error.",
    "resumen": "La **'parte' de un número** se refiere a **fracciones unitarias (recíprocas)** y siempre ubica al número de la división en el denominador. Esto contrasta frontalmente con los múltiplos, donde el número va multiplicando.",
    "explicacion": "Análisis comparativo para no morir en el intento:\n- 'Doble' $\\rightarrow$ Multiplica por 2 ($2x$). \n- 'Mitad' o 'media parte' $\\rightarrow$ Divide por 2 ($\\frac{x}{2}$).\n\n- 'Tercero' o 'El triple' $\\rightarrow$ Multiplica por 3 ($3x$).\n- 'Tercera parte' $\\rightarrow$ Divide por 3 ($\\frac{x}{3}$).\n\n- 'Cuádruple' $\\rightarrow$ Multiplica por 4 ($4x$).\n- 'Cuarta parte' $\\rightarrow$ Divide por 4 ($\\frac{x}{4}$).\n\nLa palabra mágica que indica que la constante va al sótano (al denominador) es la palabra **'parte'**.",
    "procedimiento": ["Paso 1: Lee el enunciado buscando el sufijo multiplicador (triple, cuádruple) o el sustantivo fraccionario (tercera parte, cuarta parte).", "Paso 2: Si es multiplicador, el número va como coeficiente (arriba, a la izquierda de la variable).", "Paso 3: Si dice 'parte', el número va automáticamente como denominador debajo de una fracción (y la variable arriba)."],
    "ejemplos": [
        {"titulo": "El abismo del lenguaje", "enunciado": "Traduce: 'La quinta parte de un número sumada al quíntuple del mismo número'.", "solucion_pasos": ["La quinta parte de un número: x/5.", "El quíntuple del mismo número: 5x.", "Sumados entre sí: x/5 + 5x."]}
    ],
    "errores_frecuentes": ["Leer 'tercera parte' y por ansiedad traducirlo como $3x$.", "Leer 'cuádruple' y traducirlo como $\\frac{x}{4}$."],
    "fuente": "Álgebra de Baldor.", "estado": "publicado"
})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUM-CONC-{i}", "semantic_id": sid10, "item_group": "conceptuales", "format": "multiple_choice", "difficulty": "media", "competencia": "M1", "prompt": f"¿Cuál es el efecto algebraico crítico que provoca la palabra 'parte' (como en 'la cuarta parte') en comparación con su prefijo multiplicativo ('el cuádruple')? (v{i})", "choices": ["A) Envía la constante numérica al denominador provocando una división, en lugar de ubicarla como coeficiente multiplicador lineal.", "B) Provoca que la expresión requiera una raíz cuadrada.", "C) Obliga a que la variable asuma un valor negativo.", "D) Ambas palabras significan matemáticamente lo mismo, solo es una diferencia de estilo."], "correct_answer": "A) Envía la constante numérica al denominador provocando una división, en lugar de ubicarla como coeficiente multiplicador lineal.", "solution_steps": "La palabra 'parte' invoca un fraccionamiento, una división de la entidad.", "paes_style": False})
EJERCICIOS.append({"stable_id": f"PNUM-REC-1", "semantic_id": sid10, "item_group": "reconocimiento", "format": "multiple_choice", "difficulty": "basica", "competencia": "M1", "prompt": "Identifica cuál de las siguientes opciones traduce fielmente la frase: 'La octava parte del ahorro'.", "choices": ["A) $\\frac{A}{8}$", "B) $8A$", "C) $A - 8$", "D) $\\frac{8}{A}$"], "correct_answer": "A) $\\frac{A}{8}$", "solution_steps": "La 'octava parte' es el ahorro dividido entre 8. Es decir, A sobre 8.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUM-PROC-{i}", "semantic_id": sid10, "item_group": "procedimiento_basico", "format": "true_false", "difficulty": "media", "competencia": "M1", "prompt": "¿La expresión $10x$ es la traducción correcta y recomendada para el enunciado 'la décima parte de la población'? (Asumiendo $x$ como población)", "choices": [], "correct_answer": "Falso", "solution_steps": "Esa traducción representa el decúplo (10 veces la población). La décima 'parte' se traduce como división: $\\frac{x}{10}$.", "paes_style": False})
for i in range(1, 4): EJERCICIOS.append({"stable_id": f"PNUM-PAES-{i}", "semantic_id": sid10, "item_group": "tipo_paes", "format": "multiple_choice", "difficulty": "alta", "competencia": "M1", "prompt": f"Un problema de control de calidad indica: 'El margen de error del lote debe ser la sexta parte de los productos defectuosos admitidos en el lote anterior'. Un técnico novato modela esto como $Error = 6 \\cdot Defectuosos$. ¿Qué impacto técnico tiene este error de traducción en la producción de la empresa? (v{i})", "choices": ["A) El técnico está permitiendo 36 veces más error del solicitado, ya que multiplicó por 6 en lugar de dividir por 6.", "B) El técnico está reduciendo el error, porque 6 es un número par.", "C) Ningún impacto, ambas operaciones son equivalentes si se evalúan en cero.", "D) Está exigiendo que el error sea la mitad."], "correct_answer": "A) El técnico está permitiendo 36 veces más error del solicitado, ya que multiplicó por 6 en lugar de dividir por 6.", "solution_steps": "La sexta parte requería dividir entre 6 ($\\frac{x}{6}$). Al multiplicar ($6x$), multiplicó el impacto en un factor global inmenso en comparación con dividirlo.", "paes_style": True})

def generate_all():
    print("Escribiendo YAMLs Tanda 2 (MAT.ALG.B0302)...")
    for r in RECURSOS:
        filename = r["semantic_id"].lower().replace(".", "-").replace("_", "-")
        write_yaml(filename, r)
        print(f"Creado {filename}.yaml")

    print("Escribiendo JSONL Tanda 2 (MAT.ALG.B0302)...")
    append_jsonl("mat-alg-lenguaje-banco-gen-2", EJERCICIOS)
    print("Creado mat-alg-lenguaje-banco-gen-2.jsonl con 50 ejercicios.")

if __name__ == "__main__":
    generate_all()
