from __future__ import annotations

import os
import sys
from pathlib import Path

import django

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
django.setup()

from apps.content.models import KnowledgeNode  # noqa: E402
from scratch import finalize_mat_num_b0203 as base  # noqa: E402


SPECS: dict[str, dict] = {}


def A(sid, definition, example, fact, hook, goal, steps):
    SPECS[sid] = {
        "definition": definition,
        "example": example,
        "fact": fact,
        "hook": hook,
        "goal": goal,
        "steps": steps,
    }


def build_content(sid: str, title: str) -> dict:
    s = SPECS[sid]
    definition = base._without_trailing_period(s["definition"])
    example = base._without_example_prefix(s["example"])
    fact = base._without_trailing_period(s["fact"])
    prepare, execute, verify = s["steps"]
    lower_title = title[:1].lower() + title[1:]
    explanation = base._variant(
        sid,
        "b0204-explanation",
        [
            f"{base._upper_initial(definition)}.\n\nEn el caso “{example}” esta idea se hace visible: {fact}",
            f"{base._upper_initial(definition)}.\n\nEl cálculo “{example}” muestra por qué {fact[0].lower() + fact[1:]}",
            f"{base._upper_initial(definition)}.\n\nAl analizar “{example}” conviene observar la conexión siguiente: {fact}",
            f"{base._upper_initial(definition)}.\n\nLa situación “{example}” permite comprobar, y no solo memorizar, que {fact[0].lower() + fact[1:]}",
        ],
    )
    return {
        "semantic_id": sid,
        "objetivo": base._objective_for(sid, title, s["goal"], fact),
        "introduccion": s["hook"],
        "resumen": f"{base._upper_initial(definition)}. {base._upper_initial(fact)}.",
        "explicacion": explanation,
        "procedimiento": [f"Paso 1: {prepare}", f"Paso 2: {execute}", f"Paso 3: {verify}"],
        "ejemplos": base._examples_for(
            sid, title, definition, example, fact, prepare, execute, verify
        ),
        "errores_frecuentes": [
            f"Confundir {lower_title} con otro concepto y omitir este inicio: {prepare}",
            f"Aplicar mecánicamente “{execute}” sin revisar las condiciones de la definición.",
            f"Tomar “{example}” como una igualdad aislada, sin explicar por qué es válida.",
            f"Aceptar una respuesta que contradice la idea clave “{fact}”.",
            f"Terminar el desarrollo sin realizar este control: {verify}",
        ],
        "fuente": "Currículum Nacional MINEDUC — Matemática, números reales, potencias, raíces, logaritmos y complejos.",
        "estado": "publicado",
    }


# Irracionales y reales
A("MAT.NUM.IRRACIONALES.DEFINICION", "un número irracional es un real que no puede escribirse como cociente de dos enteros", "\\(\\sqrt{2}\\) no admite una fracción exacta y su decimal \\(1.4142\\ldots\\) no termina ni presenta período", "los irracionales completan los puntos de la recta que no cubre \\(\\mathbb{Q}\\)", "La diagonal de un cuadrado de lado 1 mide \\(\\sqrt{2}\\): una longitud perfectamente concreta que ninguna fracción representa exactamente. Esa tensión entre geometría y aritmética motiva los números irracionales.", "reconocer un irracional a partir de su representación", ["Descarta primero que el número sea un decimal finito o periódico.", "Comprueba si existe una representación exacta como cociente de enteros.", "Clasifica como irracional solo cuando esa representación racional no existe."])
A("MAT.NUM.IRRACIONALES.DECIMAL_INFINITO_NO_PERIODICO", "la expansión decimal de un irracional es infinita y no repite indefinidamente ningún bloque fijo", "\\(0.101001000100001\\ldots\\) intercala cada vez más ceros y no forma un período", "ser infinito no basta: \\(0.333\\ldots\\) es periódico y, por tanto, racional", "Dos decimales pueden continuar para siempre y pertenecer a conjuntos distintos. La pregunta decisiva no es dónde terminan, sino si sus cifras entran en un ciclo repetitivo.", "distinguir un decimal irracional de uno periódico", ["Observa una porción suficientemente larga de la expansión decimal.", "Busca un bloque fijo que se repita desde algún punto en adelante.", "Si la escritura es infinita y no periódica, concluye que representa un irracional."])
A("MAT.NUM.IRRACIONALES.RAIZ_NO_EXACTA", "la raíz de un entero positivo que no es potencia perfecta suele ser irracional", "como \\(4<7<9\\), se tiene \\(2<\\sqrt{7}<3\\), pero no existe una fracción decimal finita que sea su valor exacto", "una aproximación de la raíz no convierte el valor exacto en racional", "La calculadora muestra \\(\\sqrt{7}\\approx2.6458\\), pero esos dígitos son solo una aproximación. El símbolo radical conserva un valor exacto que no cabe en una expansión decimal finita.", "decidir si una raíz entera no exacta es irracional", ["Compara el radicando con potencias perfectas consecutivas.", "Verifica que ninguna potencia entera produzca exactamente el radicando.", "Conserva el radical como valor exacto y usa decimales únicamente para aproximar."])
A("MAT.NUM.IRRACIONALES.PI", "\\(\\pi\\) es la razón constante entre la longitud de una circunferencia y su diámetro", "si un círculo tiene diámetro \\(10\\text{ cm}\\), su longitud es exactamente \\(10\\pi\\text{ cm}\\), no \\(31.4\\text{ cm}\\)", "\\(\\pi\\) es irracional y su decimal no termina ni se vuelve periódico", "Medir objetos circulares siempre conduce al mismo número, sin importar el tamaño del círculo. Esa constante geométrica es exacta, aunque solo podamos escribir aproximaciones de sus infinitas cifras.", "usar \\(\\pi\\) como valor exacto y distinguirlo de sus aproximaciones", ["Identifica la magnitud circular y la fórmula que contiene \\(\\pi\\).", "Sustituye los datos manteniendo \\(\\pi\\) durante el cálculo exacto.", "Aproxima al final solo si el problema solicita una cantidad decimal."])
A("MAT.NUM.IRRACIONALES.EULER", "el número \\(e\\) es la base natural del crecimiento continuo y vale aproximadamente \\(2.71828\\)", "la sucesión \\(\\left(1+\\frac1n\\right)^n\\) se acerca a \\(e\\) cuando \\(n\\) aumenta", "\\(e\\) es irracional y aparece de forma natural en exponenciales, logaritmos y tasas instantáneas", "Cuando el crecimiento se capitaliza cada vez con mayor frecuencia, los resultados se acercan a una constante. Esa frontera no depende de una tabla financiera: es el número \\(e\\).", "interpretar \\(e\\) como constante exacta de crecimiento continuo", ["Reconoce una situación de cambio continuo o un logaritmo natural.", "Mantén \\(e\\) de forma simbólica mientras transformas la expresión.", "Usa \\(e\\approx2.71828\\) únicamente para obtener una aproximación numérica final."])
A("MAT.NUM.IRRACIONALES.NUMERO_AUREO", "el número áureo es \\(\\varphi=\\frac{1+\\sqrt5}{2}\\)", "\\(\\varphi^2=\\varphi+1\\), propiedad que se verifica a partir de su forma radical", "\\(\\varphi\\) es irracional porque contiene la raíz no exacta \\(\\sqrt5\\)", "Una proporción es áurea cuando la razón entre el total y la parte mayor coincide con la razón entre la parte mayor y la menor. Esa condición conduce a una ecuación cuadrática y al valor \\(\\varphi\\).", "reconocer y utilizar la forma exacta del número áureo", ["Parte de \\(\\varphi=(1+\\sqrt5)/2\\) o de la ecuación \\(x^2=x+1\\).", "Opera manteniendo \\(\\sqrt5\\) para no perder exactitud.", "Comprueba la identidad \\(\\varphi^2=\\varphi+1\\) o aproxima solo al final."])

A("MAT.NUM.REALES.DEFINICION", "los números reales reúnen todos los racionales y todos los irracionales", "\\(-3\\), \\(\\frac25\\), \\(\\sqrt2\\) y \\(\\pi\\) son reales", "cada número real corresponde a un punto de la recta numérica", "Las mediciones exigen tanto fracciones como raíces no exactas. El conjunto \\(\\mathbb{R}\\) ofrece un mismo espacio para trabajar con ambas clases de números.", "identificar si un número pertenece a \\(\\mathbb{R}\\)", ["Determina si el número es racional o irracional.", "Verifica que no dependa de una raíz par de un negativo ni de una división por cero.", "Ubícalo dentro de \\(\\mathbb{R}\\) indicando, si es posible, el subconjunto más específico."])
A("MAT.NUM.REALES.UNION_RACIONALES_IRRACIONALES", "\\(\\mathbb{R}=\\mathbb{Q}\\cup(\\mathbb{R}\\setminus\\mathbb{Q})\\)", "\\(0.75\\) pertenece a \\(\\mathbb{Q}\\) y \\(\\sqrt3\\) al conjunto irracional; ambos pertenecen a \\(\\mathbb{R}\\)", "ningún número es simultáneamente racional e irracional", "Una recta sin huecos necesita dos familias disjuntas: números expresables como fracción y números que no lo son. Su unión forma los reales.", "clasificar reales separando racionales e irracionales", ["Intenta expresar el número como cociente de enteros o decimal finito/periódico.", "Si no es posible y el valor existe en la recta, clasifícalo como irracional.", "Concluye su pertenencia a \\(\\mathbb{R}\\) y evita asignarlo a ambas familias."])
A("MAT.NUM.REALES.INCLUSION_CONJUNTOS_NUMERICOS", "los conjuntos numéricos cumplen \\(\\mathbb{N}\\subset\\mathbb{Z}\\subset\\mathbb{Q}\\subset\\mathbb{R}\\)", "\\(-4\\) es entero, racional porque \\(-4=-4/1\\), y también real", "pertenecer a un conjunto pequeño implica pertenecer a todos los conjuntos que lo contienen", "Clasificar un número no significa elegir una sola etiqueta. Un natural también es entero, racional y real; la jerarquía permite registrar toda esa información sin contradicción.", "ubicar un número en la cadena de inclusión más precisa", ["Identifica el conjunto más pequeño al que pertenece el número.", "Recorre hacia afuera la cadena de inclusiones sin saltar relaciones.", "Distingue pertenencia \\(\\in\\) de inclusión \\(\\subset\\) al escribir la conclusión."])
A("MAT.NUM.REALES.RECTA_NUMERICA", "cada real se representa mediante un único punto de la recta numérica", "\\(\\sqrt2\\approx1.414\\) se ubica entre \\(1.4\\) y \\(1.5\\), a la derecha de \\(1\\)", "la posición expresa simultáneamente orden y distancia respecto de cero", "Aunque un irracional tenga infinitas cifras, ocupa una posición exacta. Aproximaciones sucesivas permiten encerrarlo en intervalos cada vez más pequeños de la recta.", "ubicar racionales e irracionales en la recta", ["Obtén una aproximación suficiente o encierra el número entre valores conocidos.", "Localiza el intervalo entre enteros y subdivídelo según la precisión requerida.", "Marca el punto y verifica su orden respecto de los números vecinos."])
A("MAT.NUM.REALES.ORDEN", "dos números reales distintos siempre pueden compararse mediante \\(<\\) o \\(>\\)", "como \\(1.41^2<2<1.42^2\\), se concluye \\(1.41<\\sqrt2<1.42\\)", "comparar aproximaciones exige suficiente precisión para que los intervalos no se superpongan", "Ordenar raíces, fracciones y decimales obliga a llevarlos a una referencia común. La recta y las cotas permiten comparar sin fingir que una aproximación es el valor exacto.", "comparar números reales escritos de formas distintas", ["Transforma los números a decimales controlados o establece cotas exactas.", "Compara signos, partes enteras y luego las cifras o límites necesarios.", "Escribe la desigualdad y comprueba que la precisión usada permite decidirla."])
A("MAT.NUM.REALES.OPERACIONES", "las operaciones con reales combinan las reglas de racionales, radicales y potencias respetando sus dominios", "\\(2+\\sqrt3\\) es real y exacto, mientras que \\(\\sqrt{-3}\\) no es real", "la suma y el producto de reales son reales, pero dividir por cero o extraer una raíz par negativa sale del dominio real", "Trabajar en \\(\\mathbb{R}\\) amplía las expresiones disponibles, pero no elimina las restricciones. Antes de calcular hay que comprobar que cada operación produzca un valor real.", "operar reales sin perder exactitud ni violar el dominio", ["Revisa denominadores, índices de raíces y bases antes de operar.", "Agrupa términos compatibles y conserva radicales o constantes exactas.", "Comprueba que el resultado pertenezca al dominio real y aproxima solo si se pide."])

# Potencias: significado y casos especiales
A("MAT.NUM.POTENCIAS_CONCEPTO.DEFINICION", "una potencia \\(a^n\\) abrevia el producto de \\(n\\) factores iguales a \\(a\\) cuando \\(n\\) es natural", "\\(3^4=3\\cdot3\\cdot3\\cdot3=81\\)", "la base es el factor repetido y el exponente indica cuántas veces aparece", "Escribir una multiplicación larga oculta su estructura repetitiva. La notación de potencia la concentra en dos datos: qué número se repite y cuántas copias se multiplican.", "interpretar y calcular una potencia desde su significado", ["Identifica la base y el exponente de la expresión.", "Expande como producto repetido cuando el exponente sea natural.", "Multiplica los factores y revisa que la cantidad coincida con el exponente."])
A("MAT.NUM.POTENCIAS_CONCEPTO.BASE_IDENTIFICACION", "la base es la cantidad que se eleva y constituye el factor repetido", "en \\((-5)^3\\), la base completa es \\(-5\\) porque el signo está dentro de los paréntesis", "los paréntesis determinan si un signo forma parte de la base", "En una potencia negativa, un par de paréntesis puede cambiar el resultado. Antes de aplicar cualquier propiedad hay que decidir con exactitud qué expresión está siendo elevada.", "identificar la base completa de una potencia", ["Localiza el exponente y observa qué expresión queda directamente bajo él.", "Incluye signos, fracciones o paréntesis que pertenezcan a esa expresión.", "Expande un caso pequeño para comprobar que elegiste la base correcta."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_IDENTIFICACION", "el exponente señala la operación o cantidad de factores aplicada a la base", "en \\(2^6\\), el exponente \\(6\\) indica seis factores iguales a \\(2\\)", "un exponente no es un factor que se multiplica por la base", "Confundir \\(2^6\\) con \\(2\\cdot6\\) borra la idea de crecimiento multiplicativo. Leer el exponente correctamente evita ese error desde el comienzo.", "leer e interpretar el exponente de una potencia", ["Ubica el número o expresión escrita en posición superior.", "Relaciona su valor natural con la cantidad de factores iguales.", "Contrasta la expansión con una multiplicación base por exponente para no confundirlas."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_NATURAL", "para \\(n\\in\\mathbb{N}\\), \\(a^n\\) es el producto de \\(n\\) factores iguales a \\(a\\)", "\\((-2)^5=(-2)(-2)(-2)(-2)(-2)=-32\\)", "la paridad del exponente controla el signo cuando la base es negativa", "Los exponentes naturales construyen potencias mediante repetición. Esa lectura permite calcular y, a la vez, anticipar el signo sin depender de una calculadora.", "evaluar potencias con exponente natural", ["Escribe la base completa tantas veces como indique el exponente.", "Determina primero el signo contando factores negativos.", "Multiplica los valores absolutos y combina el signo previsto."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_UNO", "toda base conserva su valor al elevarse a uno: \\(a^1=a\\)", "\\((-7)^1=-7\\)", "un solo factor no modifica la base", "El exponente uno suele quedar invisible en el álgebra, pero explica por qué una letra sin exponente representa su primera potencia.", "simplificar potencias de exponente uno", ["Comprueba que el exponente sea exactamente \\(1\\).", "Conserva íntegra la base, incluidos su signo y sus paréntesis.", "Verifica interpretando la potencia como un producto de un único factor."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_CERO", "para toda base no nula, \\(a^0=1\\)", "\\(5^0=1\\) y \\((-3/4)^0=1\\)", "la condición \\(a\\neq0\\) evita confundir esta regla con el caso \\(0^0\\)", "La regla del exponente cero no proviene de multiplicar cero factores de manera informal: se fuerza al mantener coherente la división de potencias. Su restricción es tan importante como el resultado.", "aplicar el exponente cero comprobando la base", ["Identifica la base completa y verifica que no sea cero.", "Sustituye la potencia por \\(1\\) sin conservar el signo exterior como si perteneciera a la base.", "Distingue expresamente el caso excluido \\(0^0\\)."])
A("MAT.NUM.POTENCIAS_CONCEPTO.BASE_CERO_EXPONENTE_POSITIVO", "cero elevado a cualquier exponente positivo vale cero", "\\(0^7=0\\)", "el producto contiene únicamente factores cero y por eso no puede ser distinto de cero", "Multiplicar cero muchas veces no genera una cantidad nueva. El exponente cambia cuántos factores aparecen, pero todos anulan el producto.", "evaluar potencias de base cero y exponente positivo", ["Comprueba que la base sea \\(0\\) y que el exponente sea estrictamente positivo.", "Interpreta la expresión como un producto de factores cero.", "Concluye \\(0\\) y evita extender la regla al exponente cero."])
A("MAT.NUM.POTENCIAS_CONCEPTO.CERO_ELEVADO_A_CERO", "\\(0^0\\) es una forma indeterminada o no definida según el contexto y no se evalúa con las reglas elementales", "la regla \\(a^0=1\\) exige \\(a\\neq0\\), mientras que \\(0^n=0\\) exige \\(n>0\\); ninguna cubre \\(0^0\\)", "dos patrones válidos llegan a conclusiones incompatibles al intentar prolongarlos hasta \\(0^0\\)", "El símbolo \\(0^0\\) está justo en el límite de dos reglas distintas. Aplicar cualquiera sin revisar sus hipótesis produce una respuesta aparente, no una justificación.", "reconocer por qué \\(0^0\\) requiere tratamiento especial", ["Escribe las condiciones de las reglas de base cero y exponente cero.", "Comprueba que \\(0^0\\) viola una condición en cada regla.", "Declara el caso indeterminado o no definido según el marco, sin asignar automáticamente \\(0\\) o \\(1\\)."])
A("MAT.NUM.POTENCIAS_CONCEPTO.BASE_NEGATIVA_PARENTESIS", "una base negativa debe encerrarse entre paréntesis para que el signo quede elevado", "\\((-2)^4=16\\), pero \\(-2^4=-(2^4)=-16\\)", "sin paréntesis, la potenciación se ejecuta antes que el signo menos exterio", "Dos expresiones visualmente parecidas pueden tener signos opuestos. Los paréntesis indican si el menos participa como factor o actúa después de calcular la potencia.", "distinguir una base negativa de un signo exterio", ["Observa si el signo menos está dentro o fuera de los paréntesis de la base.", "Calcula primero la potencia de acuerdo con la jerarquía de operaciones.", "Aplica el signo exterior, si existe, y compara ambas escrituras."])
A("MAT.NUM.POTENCIAS_CONCEPTO.SIGNO_BASE_NEGATIVA_EXPONENTE_PAR", "una base negativa elevada a exponente par produce un resultado positivo", "\\((-3)^4=81\\)", "los factores negativos se agrupan en pares de producto positivo", "El signo de una potencia negativa se puede anticipar antes de multiplicar. Un exponente par garantiza que no quede ningún factor negativo sin pareja.", "predecir el signo con base negativa y exponente pa", ["Confirma que el signo menos pertenezca a la base.", "Clasifica el exponente como par y empareja los factores negativos.", "Calcula la potencia del valor absoluto y asigna signo positivo."])
A("MAT.NUM.POTENCIAS_CONCEPTO.SIGNO_BASE_NEGATIVA_EXPONENTE_IMPAR", "una base negativa elevada a exponente impar produce un resultado negativo", "\\((-2)^5=-32\\)", "después de formar pares positivos queda un factor negativo", "Con exponente impar, la multiplicación conserva un signo menos. La paridad permite saberlo incluso antes de calcular el valor absoluto.", "predecir el signo con base negativa y exponente impa", ["Verifica que la base incluya el signo negativo.", "Reconoce que el exponente impar deja un factor negativo sin pareja.", "Calcula el valor absoluto y coloca signo negativo al resultado."])
A("MAT.NUM.POTENCIAS_CONCEPTO.BASE_RACIONAL", "una fracción elevada a una potencia aplica el exponente a numerador y denominado", "\\(\\left(-\\frac23\\right)^3=-\\frac8{27}\\)", "el denominador debe ser distinto de cero y los paréntesis conservan la base completa", "Elevar una fracción no significa multiplicar solo su numerador. La barra agrupa un cociente completo y la potencia actúa sobre ambos términos.", "calcular potencias cuya base es racional", ["Encierra la fracción completa e identifica el signo de la base.", "Eleva por separado numerador y denominador al mismo exponente.", "Simplifica el resultado y comprueba el signo mediante la paridad."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_ENTERO_NEGATIVO", "para \\(a\\neq0\\), \\(a^{-n}=1/a^n\\)", "\\(2^{-3}=1/2^3=1/8\\)", "un exponente negativo produce el recíproco; no vuelve negativo el valor por sí mismo", "El signo del exponente describe una inversión, no el signo del resultado. Leerlo así conecta las potencias negativas con los recíprocos.", "transformar y calcular potencias de exponente negativo", ["Comprueba que la base sea distinta de cero.", "Invierte la base y cambia el exponente a su opuesto positivo.", "Calcula la potencia positiva y verifica multiplicando por la potencia opuesta."])
A("MAT.NUM.POTENCIAS_CONCEPTO.EXPONENTE_RACIONAL", "para condiciones reales adecuadas, \\(a^{m/n}=\\sqrt[n]{a^m}\\)", "\\(8^{2/3}=\\sqrt[3]{8^2}=4\\)", "el denominador del exponente indica el índice de la raíz y el numerador indica la potencia", "Los exponentes fraccionarios enlazan dos notaciones: potencia y radical. Esa equivalencia permite elegir la forma más fácil sin cambiar el valor.", "convertir exponentes racionales en radicales y evaluarlos", ["Reduce la fracción del exponente e identifica numerador y denominador.", "Usa el denominador como índice y el numerador como potencia.", "Revisa las condiciones reales cuando el índice sea par y simplifica en el orden conveniente."])

# Propiedades de potencias
A("MAT.NUM.POTENCIAS_PROPIEDADES.MULTIPLICACION_IGUAL_BASE", "al multiplicar potencias de igual base se suman los exponentes: \\(a^m a^n=a^{m+n}\\)", "\\(2^3\\cdot2^5=2^8=256\\)", "la propiedad reúne en una sola potencia todos los factores iguales", "Dos potencias con la misma base son dos grupos del mismo factor repetido. Al juntar los grupos, la cantidad total de factores se suma.", "simplificar productos de potencias con base común", ["Verifica que las bases sean exactamente iguales, incluidos signos y paréntesis.", "Suma los exponentes y conserva la base sin multiplicarla por sí misma.", "Comprueba expandiendo un caso pequeño o evaluando ambos miembros."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.DIVISION_IGUAL_BASE", "al dividir potencias de igual base no nula se restan los exponentes: \\(a^m/a^n=a^{m-n}\\)", "\\(5^6/5^2=5^4=625\\)", "la resta cuenta los factores de la base que no se cancelan", "En un cociente de potencias iguales, cada factor del denominador cancela uno del numerador. Los factores restantes quedan registrados por la diferencia de exponentes.", "reducir cocientes de potencias con la misma base", ["Comprueba que las bases coincidan y que la base no sea cero.", "Resta exponente del denominador al del numerador.", "Interpreta un exponente negativo como recíproco y verifica las cancelaciones."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.POTENCIA_DE_POTENCIA", "al elevar una potencia a otra potencia se multiplican los exponentes: \\((a^m)^n=a^{mn}\\)", "\\((3^2)^4=3^8\\)", "cada una de las \\(n\\) copias aporta \\(m\\) factores de la base", "Una potencia de potencia repite un bloque que ya contiene factores iguales. Multiplicar los exponentes cuenta cuántos factores hay en total.", "simplificar una potencia elevada a otra potencia", ["Identifica con los paréntesis la potencia interior completa.", "Multiplica los exponentes y conserva la base original.", "Evita sumar exponentes: compara con la expansión de dos bloques para verificar."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.POTENCIA_DE_PRODUCTO", "la potencia de un producto se distribuye a cada factor: \\((ab)^n=a^n b^n\\)", "\\((2\\cdot3)^4=2^4\\cdot3^4=1296\\)", "cada repetición del producto contiene una copia de todos sus factores", "Elevar un producto repite el bloque completo, no solo uno de sus componentes. Reordenar los factores permite agrupar las copias de cada uno.", "distribuir una potencia sobre un producto", ["Comprueba que toda la multiplicación esté dentro de la base.", "Eleva cada factor al mismo exponente exterior.", "Multiplica los resultados y verifica frente a la potencia del producto original."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.POTENCIA_DE_COCIENTE", "la potencia de un cociente se aplica al numerador y al denominador: \\((a/b)^n=a^n/b^n\\)", "\\(\\left(\\frac34\\right)^2=\\frac9{16}\\)", "el denominador debe ser no nulo y recibe el mismo exponente que el numerado", "La barra de fracción agrupa dos cantidades en una sola base. Al repetir ese cociente, numeradores y denominadores forman productos paralelos.", "distribuir una potencia sobre un cociente", ["Verifica que el denominador sea distinto de cero y que la fracción completa sea la base.", "Eleva numerador y denominador al exponente exterior.", "Simplifica la fracción y contrasta con la multiplicación repetida del cociente."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.MULTIPLICACION_IGUAL_EXPONENTE", "potencias con igual exponente pueden reunirse multiplicando sus bases: \\(a^n b^n=(ab)^n\\)", "\\(2^3\\cdot5^3=(2\\cdot5)^3=10^3\\)", "la propiedad funciona por igualdad de exponentes, aunque las bases sean distintas", "A veces conviene mirar los exponentes en lugar de las bases. Si coinciden, cada posición del producto repetido puede agrupar una base de cada potencia.", "combinar productos de potencias con exponente común", ["Comprueba que los exponentes sean iguales.", "Multiplica las bases y conserva el exponente común.", "Elige la forma que simplifique el cálculo y verifica evaluando ambos lados."])
A("MAT.NUM.POTENCIAS_PROPIEDADES.DIVISION_IGUAL_EXPONENTE", "potencias con igual exponente pueden reunirse dividiendo sus bases: \\(a^n/b^n=(a/b)^n\\)", "\\(12^2/3^2=(12/3)^2=16\\)", "el divisor y su potencia deben ser distintos de cero", "Un cociente de potencias puede esconder una división sencilla entre bases. Reconocer el exponente común evita calcular números grandes innecesariamente.", "combinar cocientes de potencias con exponente común", ["Verifica que ambos exponentes coincidan y que la base divisora no sea cero.", "Divide las bases y conserva el exponente.", "Simplifica antes de elevar y comprueba con el cociente original."])

# Notación científica
A("MAT.NUM.NOTACION_CIENTIFICA.CONCEPTO", "la notación científica escribe un número como \\(a\\times10^n\\), con \\(1\\le |a|<10\\)", "\\(6300000=6.3\\times10^6\\)", "el coeficiente contiene las cifras significativas y la potencia de diez fija la escala", "Las distancias astronómicas y los tamaños microscópicos son difíciles de leer con largas filas de ceros. La notación científica separa precisión y orden de magnitud.", "reconocer una escritura científica normalizada", ["Localiza la primera cifra no nula y coloca la coma después de ella.", "Cuenta los lugares desplazados y asigna el signo del exponente.", "Comprueba que el coeficiente tenga valor absoluto entre \\(1\\) y \\(10\\)."])
A("MAT.NUM.NOTACION_CIENTIFICA.ESCRITURA_NUMERO_GRANDE", "un número grande usa exponente positivo en notación científica", "\\(482000000=4.82\\times10^8\\)", "el exponente positivo cuenta los lugares que la coma debe volver hacia la derecha", "Mover la coma hacia la izquierda produce un coeficiente manejable; la potencia positiva registra cuánta escala se retiró del número original.", "convertir números grandes a notación científica", ["Desplaza la coma a la izquierda hasta dejar una cifra no nula delante.", "Cuenta los desplazamientos y úsalo como exponente positivo.", "Reconstruye el número moviendo la coma a la derecha para verificar."])
A("MAT.NUM.NOTACION_CIENTIFICA.ESCRITURA_NUMERO_PEQUENO", "un número entre cero y uno usa exponente negativo en notación científica", "\\(0.000072=7.2\\times10^{-5}\\)", "el exponente negativo indica cuántos lugares debe moverse la coma hacia la izquierda al reconstrui", "Los ceros iniciales no aportan cifras significativas, pero sí indican escala. Un exponente negativo conserva esa información de forma compacta.", "convertir números pequeños a notación científica", ["Mueve la coma a la derecha hasta obtener un coeficiente entre \\(1\\) y \\(10\\).", "Cuenta los lugares y escribe el exponente con signo negativo.", "Devuelve la coma hacia la izquierda para confirmar el valor original."])
A("MAT.NUM.NOTACION_CIENTIFICA.CONVERSION_A_DECIMAL", "convertir desde notación científica consiste en escalar el coeficiente por la potencia de diez", "\\(3.07\\times10^{-4}=0.000307\\)", "un exponente positivo mueve la coma a la derecha y uno negativo a la izquierda", "La potencia de diez contiene una instrucción de escala. Leer su signo y magnitud permite reconstruir el decimal sin contar ceros a ciegas.", "pasar una escritura científica a decimal", ["Lee el signo y el valor absoluto del exponente.", "Desplaza la coma del coeficiente en la dirección y cantidad indicadas.", "Completa posiciones con ceros y verifica el orden de magnitud."])
A("MAT.NUM.NOTACION_CIENTIFICA.MULTIPLICACION", "para multiplicar notación científica se multiplican coeficientes y se suman exponentes", "\\((2\\times10^3)(4\\times10^5)=8\\times10^8\\)", "el resultado debe normalizarse si el nuevo coeficiente queda fuera de \\([1,10)\\)", "El producto separa dos tareas independientes: operar las cifras significativas y combinar las escalas. Al final ambas partes vuelven a reunirse.", "multiplicar números expresados científicamente", ["Multiplica los coeficientes y suma los exponentes de diez.", "Normaliza el coeficiente moviendo la coma si es necesario.", "Compensa cada movimiento en el exponente y estima el orden de magnitud."])
A("MAT.NUM.NOTACION_CIENTIFICA.DIVISION", "para dividir notación científica se dividen coeficientes y se restan exponentes", "\\((9\\times10^7)/(3\\times10^2)=3\\times10^5\\)", "la normalización final conserva un coeficiente de valor absoluto entre \\(1\\) y \\(10\\)", "En una división, la escala del divisor se resta de la del dividendo. Esta operación evita desplegar números enormes antes de simplificarlos.", "dividir números en notación científica", ["Divide los coeficientes comprobando que el divisor no sea cero.", "Resta el exponente del divisor al del dividendo.", "Normaliza el coeficiente y verifica el orden mediante una estimación."])
A("MAT.NUM.NOTACION_CIENTIFICA.ADICION_SUSTRACCION", "solo se suman o restan directamente coeficientes cuando las potencias de diez tienen el mismo exponente", "\\(3.2\\times10^5+1.7\\times10^5=4.9\\times10^5\\)", "si los exponentes difieren, primero hay que reescribir uno de los términos con la misma escala", "Sumar magnitudes de escalas distintas exige expresar ambas en la misma unidad posicional. La potencia de diez cumple el papel de esa unidad común.", "sumar y restar cantidades en notación científica", ["Compara los exponentes y elige una potencia de diez común.", "Reescribe los coeficientes sin cambiar el valor de cada término.", "Opera los coeficientes, conserva el exponente común y normaliza el resultado."])

# Raíces: significado, dominio y representación
A("MAT.NUM.RAICES_CONCEPTO.DEFINICION_RAIZ_ENESIMA", "\\(\\sqrt[n]{a}=b\\) significa que \\(b^n=a\\)", "\\(\\sqrt[3]{64}=4\\) porque \\(4^3=64\\)", "el índice indica qué potencia debe deshacerse", "Una raíz responde una pregunta inversa: ¿qué número, elevado cierto número de veces, produce el radicando? Leerla así evita tratar el símbolo como una división.", "interpretar y calcular una raíz enésima", ["Identifica el índice y el radicando.", "Busca un número cuya potencia con ese índice reproduzca el radicando.", "Eleva el resultado para verificar la igualdad original."])
A("MAT.NUM.RAICES_CONCEPTO.RAIZ_COMO_INVERSA_POTENCIA", "la raíz enésima deshace una potencia de exponente \\(n\\) dentro de las condiciones de su dominio", "\\(\\sqrt[5]{3^5}=3\\)", "para índice par la raíz principal es no negativa, por lo que \\(\\sqrt{x^2}=|x|\\)", "Potenciar y extraer raíz parecen operaciones opuestas, pero el dominio y la raíz principal introducen matices. La verificación debe considerar signos, no solo exponentes.", "usar raíces como inversas de potencias", ["Reconoce la potencia y compara su exponente con el índice radical.", "Simplifica respetando la raíz principal y el signo del valor.", "Comprueba elevando el resultado y revisando las restricciones del dominio."])
A("MAT.NUM.RAICES_CONCEPTO.INDICE_IDENTIFICACION", "el índice de un radical indica la potencia inversa que se está aplicando", "en \\(\\sqrt[5]{32}\\), el índice es \\(5\\)", "cuando no se escribe índice se entiende \\(2\\)", "El pequeño número situado en el radical decide qué operación inversa se busca. Omitirlo cambia una raíz cúbica, quinta o cuadrada en problemas diferentes.", "identificar e interpretar el índice de una raíz", ["Localiza el número pequeño escrito en la abertura del radical.", "Si no aparece, asigna índice \\(2\\) por convención.", "Relaciona el índice con la potencia que debe reproducir el radicando."])
A("MAT.NUM.RAICES_CONCEPTO.RADICANDO_IDENTIFICACION", "el radicando es la expresión situada bajo el signo radical", "en \\(\\sqrt[3]{x+7}\\), el radicando completo es \\(x+7\\)", "la barra del radical agrupa todos los términos que cubre", "En expresiones algebraicas, confundir una parte con el radicando completo altera el dominio y el resultado. La extensión de la barra funciona como un paréntesis.", "identificar el radicando completo", ["Observa hasta dónde se extiende la barra horizontal del radical.", "Agrupa todos los términos cubiertos como una sola expresión.", "Sustituye un valor sencillo para comprobar que respetaste la agrupación."])
A("MAT.NUM.RAICES_CONCEPTO.RAIZ_CUADRADA_PRINCIPAL", "\\(\\sqrt{a}\\) denota la raíz cuadrada no negativa de \\(a\\ge0\\)", "\\(\\sqrt{25}=5\\), no \\(\\pm5\\)", "el símbolo radical representa un valor principal; el signo \\(\\pm\\) aparece al resolver ecuaciones como \\(x^2=25\\)", "El número \\(-5\\) también tiene cuadrado 25, pero no es el valor del símbolo \\(\\sqrt{25}\\). Distinguir raíz principal de soluciones de una ecuación evita duplicar respuestas.", "calcular y reconocer la raíz cuadrada principal", ["Comprueba que el radicando sea no negativo.", "Busca el número no negativo cuyo cuadrado sea el radicando.", "Diferencia el valor del radical de las dos soluciones posibles de una ecuación cuadrática."])
A("MAT.NUM.RAICES_CONCEPTO.EXISTENCIA_INDICE_PAR", "una raíz de índice par tiene valor real solo cuando el radicando es no negativo", "\\(\\sqrt[4]{16}=2\\), mientras que \\(\\sqrt[4]{-16}\\) no existe en \\(\\mathbb{R}\\)", "ninguna potencia par de un real puede producir un número negativo", "Antes de simplificar una raíz par hay que mirar el signo interior. Esa revisión de dominio puede detener un cálculo que, de otro modo, parecería rutinario.", "determinar el dominio real de una raíz pa", ["Identifica que el índice sea par.", "Exige que el radicando sea mayor o igual que cero.", "Resuelve la restricción y solo después calcula o simplifica el radical."])
A("MAT.NUM.RAICES_CONCEPTO.EXISTENCIA_INDICE_IMPAR", "una raíz de índice impar admite cualquier radicando real", "\\(\\sqrt[3]{-125}=-5\\)", "las potencias impares conservan el signo y cubren todos los valores reales", "A diferencia de una raíz cuadrada, una raíz cúbica puede atravesar valores negativos sin abandonar los reales. El signo del resultado sigue al del radicando.", "calcular raíces impares de radicandos positivos o negativos", ["Reconoce que el índice sea impar.", "Busca un número con el mismo signo cuyo exponente reproduzca el radicando.", "Eleva el resultado al índice para verificar tanto magnitud como signo."])
A("MAT.NUM.RAICES_CONCEPTO.RAIZ_EXACTA", "una raíz es exacta cuando su radicando es una potencia perfecta del índice", "\\(\\sqrt[3]{216}=6\\) porque \\(216=6^3\\)", "el resultado exacto no requiere aproximación decimal", "Reconocer potencias perfectas transforma un radical en un número entero o racional sin pérdida. La factorización permite descubrirlas cuando no son evidentes.", "reconocer y calcular raíces exactas", ["Compara el radicando con potencias conocidas o factorízalo.", "Agrupa los factores en conjuntos del tamaño indicado por el índice.", "Extrae cada grupo completo y verifica elevando el resultado."])
A("MAT.NUM.RAICES_CONCEPTO.RAIZ_NO_EXACTA", "una raíz no exacta no produce un entero o racional simple y suele conservarse en forma radical", "\\(\\sqrt{13}\\) está entre \\(3\\) y \\(4\\) y vale aproximadamente \\(3.606\\)", "la forma \\(\\sqrt{13}\\) es exacta, mientras que \\(3.606\\) es una aproximación", "Una calculadora entrega cifras útiles para ubicar una raíz, pero no reemplaza su valor exacto. Elegir entre radical y decimal depende de lo que pida el problema.", "distinguir valor exacto y aproximación de una raíz", ["Ubica el radicando entre potencias perfectas consecutivas.", "Conserva el radical si se requiere una respuesta exacta.", "Si aproximas, indica precisión y comprueba elevando las cotas vecinas."])
A("MAT.NUM.RAICES_CONCEPTO.EXPONENTE_FRACCIONARIO", "\\(\\sqrt[n]{a^m}=a^{m/n}\\) cuando la expresión está definida en los reales", "\\(\\sqrt[4]{16^3}=16^{3/4}=8\\)", "radical y exponente racional son dos escrituras del mismo valo", "Cambiar de radical a potencia puede revelar propiedades que la notación original oculta. La fracción del exponente conserva por separado potencia e índice.", "traducir entre radicales y exponentes fraccionarios", ["Lee el índice como denominador y la potencia del radicando como numerador.", "Escribe la potencia racional y simplifica la fracción del exponente si corresponde.", "Revisa el dominio real y verifica regresando a la notación radical."])

# Propiedades y operatoria con radicales
A("MAT.NUM.RAICES_PROPIEDADES.MULTIPLICACION_IGUAL_INDICE", "raíces de igual índice pueden multiplicarse dentro de un solo radical: \\(\\sqrt[n]{a}\\sqrt[n]{b}=\\sqrt[n]{ab}\\)", "\\(\\sqrt3\\sqrt{12}=\\sqrt{36}=6\\)", "la identidad exige compatibilidad de índices y condiciones reales de los radicandos", "Dos radicales del mismo tipo pueden reunir sus radicandos. Esta transformación suele revelar una potencia perfecta que no aparecía por separado.", "multiplicar y simplificar raíces con índice común", ["Comprueba que los índices coincidan y que cada radical exista en \\(\\mathbb{R}\\).", "Multiplica los radicandos bajo un único radical.", "Busca potencias perfectas y verifica el resultado por aproximación o potencia."])
A("MAT.NUM.RAICES_PROPIEDADES.DIVISION_IGUAL_INDICE", "raíces de igual índice pueden dividirse como \\(\\sqrt[n]{a}/\\sqrt[n]{b}=\\sqrt[n]{a/b}\\), con divisor no nulo", "\\(\\sqrt{72}/\\sqrt2=\\sqrt{36}=6\\)", "la propiedad puede simplificar el cociente antes de calcular raíces por separado", "Un cociente de radicales puede esconder una división exacta entre radicandos. Revisar el denominador antes de reunirlos evita crear una expresión inválida.", "dividir raíces de igual índice", ["Verifica índices iguales y que el radical divisor sea distinto de cero.", "Forma el cociente de radicandos dentro de una sola raíz.", "Simplifica el cociente y comprueba que se mantenga el dominio original."])
A("MAT.NUM.RAICES_PROPIEDADES.RAIZ_DE_RAIZ", "una raíz aplicada a otra multiplica sus índices: \\(\\sqrt[m]{\\sqrt[n]{a}}=\\sqrt[mn]{a}\\)", "\\(\\sqrt{\\sqrt[3]{64}}=\\sqrt[6]{64}=2\\)", "en exponentes, \\((a^{1/n})^{1/m}=a^{1/(mn)}\\)", "Cada radical divide un exponente; aplicar dos divisiones sucesivas equivale a dividir por el producto de los índices.", "simplificar raíces anidadas", ["Identifica el índice de cada radical, incluyendo el \\(2\\) implícito.", "Multiplica los índices y conserva el radicando.", "Revisa el dominio y eleva el resultado al índice combinado para verificar."])
A("MAT.NUM.RAICES_PROPIEDADES.RAIZ_DE_POTENCIA", "una raíz puede simplificar una potencia cuando su índice y el exponente comparten factores", "\\(\\sqrt[3]{x^6}=x^2\\) para todo real \\(x\\)", "con índice par puede aparecer valor absoluto, como \\(\\sqrt{x^2}=|x|\\)", "Cancelar índice y exponente sin mirar la paridad puede perder el signo correcto. La raíz principal obliga a tratar con cuidado las potencias pares.", "simplificar raíces de potencias respetando signos", ["Compara el exponente del radicando con el índice y calcula su máximo común divisor.", "Reduce ambos valores o extrae grupos completos del tamaño del índice.", "Introduce valor absoluto cuando la raíz principal par lo requiera y verifica con valores negativos."])
A("MAT.NUM.RAICES_PROPIEDADES.EXTRACCION_FACTOR_SUBRADICAL", "un factor que forma una potencia perfecta puede salir del radical", "\\(\\sqrt{72}=\\sqrt{36\\cdot2}=6\\sqrt2\\)", "solo salen grupos completos de tantos factores como indique el índice", "Simplificar un radical consiste en separar dentro del radicando la mayor potencia perfecta posible. El factor extraído conserva la exactitud.", "extraer factores perfectos desde un radical", ["Factoriza el radicando y forma grupos según el índice.", "Extrae un factor por cada grupo completo y deja los restantes dentro.", "Eleva o vuelve a ingresar el factor para comprobar que recuperas el radicando."])
A("MAT.NUM.RAICES_PROPIEDADES.INGRESO_FACTOR_SUBRADICAL", "un factor exterior entra a una raíz elevado al índice: \\(a\\sqrt[n]{b}=\\sqrt[n]{a^n b}\\)", "\\(3\\sqrt2=\\sqrt{3^2\\cdot2}=\\sqrt{18}\\)", "para índices pares y factores negativos debe controlarse el signo antes de ingresa", "Ingresar un factor es la operación inversa de extraerlo. La potencia aplicada al factor compensa exactamente el índice radical.", "introducir un factor dentro de un radical", ["Identifica el índice y comprueba el signo del factor exterior.", "Eleva el factor al índice y multiplícalo por el radicando.", "Extrae nuevamente la potencia perfecta para verificar la equivalencia."])
A("MAT.NUM.RAICES_PROPIEDADES.DESCOMPOSICION_RADICANDO", "factorizar el radicando permite separar potencias perfectas y simplificar la raíz", "\\(\\sqrt[3]{54}=\\sqrt[3]{27\\cdot2}=3\\sqrt[3]2\\)", "la descomposición útil depende del índice del radical", "No cualquier factorización simplifica una raíz. Hay que buscar grupos cuadrados, cúbicos o de orden superior según el índice presente.", "descomponer un radicando con propósito de simplificación", ["Factoriza el radicando, preferentemente en primos.", "Agrupa factores en conjuntos del tamaño del índice.", "Extrae los grupos completos y confirma que el radicando residual ya no contiene otra potencia perfecta."])
A("MAT.NUM.RAICES_PROPIEDADES.RADICALES_SEMEJANTES", "dos radicales son semejantes si, tras simplificar, tienen el mismo índice y el mismo radicando", "\\(2\\sqrt3\\) y \\(-5\\sqrt3\\) son semejantes, pero \\(\\sqrt2\\) y \\(\\sqrt3\\) no", "los coeficientes pueden ser distintos sin romper la semejanza", "Antes de sumar radicales hay que mirar su parte radical simplificada, del mismo modo que en álgebra se comparan partes literales.", "reconocer radicales que pueden combinarse", ["Simplifica cada radical extrayendo potencias perfectas.", "Compara índices y radicandos de las formas resultantes.", "Declara semejanza solo si ambas partes radicales coinciden exactamente."])
A("MAT.NUM.RAICES_PROPIEDADES.ADICION_RADICALES_SEMEJANTES", "los radicales semejantes se suman operando sus coeficientes", "\\(3\\sqrt5+2\\sqrt5=5\\sqrt5\\)", "la parte radical común se conserva como un facto", "Sumar radicales semejantes funciona como sumar términos algebraicos semejantes. La raíz no se suma consigo misma; se factoriza mientras cambian los coeficientes.", "sumar expresiones con radical común", ["Simplifica los radicales y confirma que sean semejantes.", "Suma únicamente los coeficientes y conserva la parte radical.", "Distribuye el resultado para verificar que reproduce los términos iniciales."])
A("MAT.NUM.RAICES_PROPIEDADES.SUSTRACCION_RADICALES_SEMEJANTES", "los radicales semejantes se restan operando sus coeficientes", "\\(7\\sqrt2-3\\sqrt2=4\\sqrt2\\)", "restar radicandos entre sí no es una propiedad válida", "La resta actúa sobre las cantidades de una misma unidad radical. Si las raíces no son semejantes, la expresión no se combina de esta manera.", "restar términos con la misma parte radical", ["Reduce cada radical y verifica que índice y radicando coincidan.", "Resta los coeficientes respetando sus signos.", "Conserva el radical común y comprueba expandiendo el factor."])

# Racionalización
A("MAT.NUM.RACIONALIZACION.DENOMINADOR_MONOMIO_RAIZ_CUADRADA", "racionalizar un denominador \\(\\sqrt a\\) consiste en multiplicar por \\(\\sqrt a/\\sqrt a\\)", "\\(\\frac3{\\sqrt5}=\\frac{3\\sqrt5}{5}\\)", "el valor no cambia porque se multiplica por uno", "Una fracción puede ser correcta y aun así tener un radical incómodo en el denominador. Multiplicar por una forma de uno traslada ese radical al numerador.", "racionalizar un monomio con raíz cuadrada", ["Identifica el radical del denominador y comprueba que no sea cero.", "Multiplica numerador y denominador por la misma raíz.", "Simplifica el cuadrado del radical y reduce la fracción final."])
A("MAT.NUM.RACIONALIZACION.DENOMINADOR_MONOMIO_RAIZ_ENESIMA", "para racionalizar \\(\\sqrt[n]{a^k}\\) se completa en el denominador una potencia múltiplo de \\(n\\)", "\\(1/\\sqrt[3]{2}\\) se multiplica por \\(\\sqrt[3]{4}/\\sqrt[3]{4}\\) y queda \\(\\sqrt[3]{4}/2\\)", "el factor racionalizante depende de cuánto falta para completar el exponente del índice", "En raíces de índice mayor no basta repetir el mismo radical. El objetivo es completar grupos exactos del tamaño del índice en el denominador.", "elegir el factor que racionaliza una raíz enésima", ["Expresa los factores del radicando con sus exponentes.", "Completa cada exponente hasta el siguiente múltiplo del índice.", "Multiplica por el radical complementario y simplifica la potencia exacta del denominador."])
A("MAT.NUM.RACIONALIZACION.DENOMINADOR_BINOMIO_CONJUGADO", "un binomio con radical se racionaliza multiplicando por su conjugado", "\\(\\frac1{2+\\sqrt3}\\cdot\\frac{2-\\sqrt3}{2-\\sqrt3}=2-\\sqrt3\\)", "el producto de conjugados usa \\((a+b)(a-b)=a^2-b^2\\) y elimina los términos radicales cruzados", "Cuando el denominador es una suma, multiplicar solo por la raíz no elimina todos los radicales. El conjugado aprovecha una diferencia de cuadrados.", "racionalizar un denominador binomial", ["Forma el conjugado cambiando únicamente el signo entre los términos.", "Multiplica numerador y denominador por ese conjugado.", "Aplica diferencia de cuadrados y simplifica, verificando que el denominador original no sea cero."])

# Logaritmos: significado, notación y dominio
A("MAT.NUM.LOGARITMOS_CONCEPTO.DEFINICION", "\\(\\log_b a=c\\) significa que \\(b^c=a\\), con \\(b>0\\), \\(b\\neq1\\) y \\(a>0\\)", "\\(\\log_2 32=5\\) porque \\(2^5=32\\)", "un logaritmo responde qué exponente necesita la base para producir el argumento", "El resultado de un logaritmo no es una potencia ni una base: es un exponente. Traducir la pregunta a forma exponencial vuelve visible ese significado.", "calcular logaritmos desde su definición", ["Identifica base, argumento y exponente desconocido.", "Reescribe la igualdad en forma exponencial.", "Comprueba las restricciones y eleva la base al resultado obtenido."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.RELACION_CON_POTENCIA", "logaritmos y potencias expresan la misma relación entre base, exponente y resultado", "\\(3^4=81\\) equivale a \\(\\log_3 81=4\\)", "la base se conserva, el resultado de la potencia pasa a argumento y el exponente pasa a ser el logaritmo", "Una igualdad exponencial y una logarítmica pueden contar exactamente la misma historia. Cambiar de forma permite elegir la operación que deja visible la incógnita.", "conectar una potencia con su logaritmo equivalente", ["Señala base, exponente y resultado en la igualdad inicial.", "Reubica cada elemento según la definición logarítmica o exponencial.", "Regresa a la forma original para verificar que no intercambiaste argumento y exponente."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.FORMA_LOGARITMICA_A_EXPONENCIAL", "de \\(\\log_b a=c\\) se obtiene la forma exponencial \\(b^c=a\\)", "\\(\\log_5 125=3\\) se transforma en \\(5^3=125\\)", "la conversión conserva la base y hace explícita la potencia que define el logaritmo", "La forma logarítmica puede parecer abstracta hasta que se vuelve potencia. Esa traducción es también una herramienta de comprobación inmediata.", "convertir una igualdad logarítmica a exponencial", ["Ubica la base como número inferior del logaritmo.", "Usa el valor del logaritmo como exponente y el argumento como resultado.", "Evalúa la potencia para comprobar la igualdad y el dominio."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.FORMA_EXPONENCIAL_A_LOGARITMICA", "de \\(b^c=a\\) se obtiene \\(\\log_b a=c\\)", "\\(10^{-3}=0.001\\) equivale a \\(\\log_{10}0.001=-3\\)", "el exponente de la potencia se convierte en el valor del logaritmo", "Pasar una potencia a logaritmo permite expresar exponentes desconocidos y escalas muy grandes o pequeñas. La posición de cada término determina el significado.", "convertir una igualdad exponencial a logarítmica", ["Identifica base, exponente y resultado de la potencia.", "Coloca el resultado como argumento y el exponente después del signo igual.", "Verifica que la base sea válida y recupera la potencia para controlar la conversión."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.RESTRICCION_BASE_POSITIVA", "la base de un logaritmo real debe ser positiva", "\\(\\log_{-2}8\\) no define un logaritmo real", "una base negativa no produce una función exponencial real definida para todos los exponentes", "No toda potencia con base negativa puede invertirse de manera continua en los reales. Por eso el logaritmo exige una base estrictamente positiva.", "descartar logaritmos con base no positiva", ["Identifica la base antes de calcular.", "Impone la desigualdad \\(b>0\\).", "Si la condición falla, declara que la expresión no está definida en \\(\\mathbb{R}\\)."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.RESTRICCION_BASE_DISTINTA_UNO", "la base logarítmica no puede ser \\(1\\)", "\\(\\log_1 7\\) no existe porque ninguna potencia de \\(1\\) produce \\(7\\)", "la función \\(1^x\\) es constante y no tiene inversa", "Una base válida debe cambiar al variar el exponente. Como todas las potencias de uno valen uno, no es posible recuperar un exponente único.", "reconocer por qué la base uno está excluida", ["Comprueba si la base es exactamente \\(1\\).", "Analiza la ecuación equivalente \\(1^x=a\\).", "Concluye que no hay logaritmo único y rechaza la expresión."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.RESTRICCION_ARGUMENTO_POSITIVO", "el argumento de un logaritmo real debe ser mayor que cero", "\\(\\log_3(-9)\\) y \\(\\log_3 0\\) no existen en \\(\\mathbb{R}\\)", "una base positiva elevada a cualquier exponente real siempre produce un valor positivo", "El argumento es el resultado de una potencia de base positiva. Como esa potencia nunca llega a cero ni a valores negativos, esos argumentos quedan fuera del dominio.", "determinar el dominio mediante la positividad del argumento", ["Aísla la expresión completa que actúa como argumento.", "Plantea la condición argumento \\(>0\\) y resuélvela si contiene variables.", "Conserva solo los valores que satisfacen la desigualdad antes de operar."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.LOGARITMO_DE_UNO", "para toda base válida, \\(\\log_b1=0\\)", "\\(\\log_7 1=0\\) porque \\(7^0=1\\)", "la propiedad proviene directamente del exponente cero", "El número uno ocupa una posición especial en todas las escalas logarítmicas: corresponde al exponente cero, sin importar qué base válida se use.", "evaluar el logaritmo de uno", ["Comprueba que la base sea positiva y distinta de uno.", "Pregunta qué exponente de la base produce \\(1\\).", "Usa \\(b^0=1\\) para concluir y verificar el valor cero."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.LOGARITMO_DE_LA_BASE", "para toda base válida, \\(\\log_b b=1\\)", "\\(\\log_4 4=1\\) porque \\(4^1=4\\)", "una base elevada a uno se conserva", "Cuando argumento y base coinciden, el exponente buscado está a la vista. Esta identidad simplifica expresiones antes de aplicar propiedades más largas.", "reconocer el logaritmo de la propia base", ["Verifica que base y argumento sean exactamente iguales.", "Comprueba que la base cumpla las restricciones logarítmicas.", "Aplica \\(b^1=b\\) y concluye que el logaritmo vale \\(1\\)."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.LOGARITMO_DECIMAL", "\\(\\log x\\) suele denotar \\(\\log_{10}x\\)", "\\(\\log 10000=4\\) porque \\(10^4=10000\\)", "el logaritmo decimal mide órdenes de magnitud en potencias de diez", "Las escalas de pH, decibeles y magnitud aprovechan una base alineada con nuestro sistema decimal. La base diez suele omitirse por convenio.", "interpretar y calcular logaritmos de base diez", ["Reconoce la ausencia de base escrita como base \\(10\\) según el contexto.", "Expresa el argumento como potencia de diez cuando sea posible.", "Lee el exponente y verifica elevando \\(10\\) a ese valor."])
A("MAT.NUM.LOGARITMOS_CONCEPTO.LOGARITMO_NATURAL", "\\(\\ln x\\) denota el logaritmo de base \\(e\\)", "\\(\\ln(e^3)=3\\)", "el logaritmo natural es la operación inversa de la exponencial \\(e^x\\)", "Los procesos continuos se describen naturalmente con potencias de \\(e\\). El símbolo \\(\\ln\\) permite recuperar el tiempo o exponente escondido en ese crecimiento.", "interpretar y calcular logaritmos naturales", ["Traduce \\(\\ln x\\) como \\(\\log_e x\\).", "Busca una potencia de \\(e\\) equivalente al argumento.", "Comprueba el dominio positivo y verifica con la exponencial."])

# Propiedades de logaritmos
A("MAT.NUM.LOGARITMOS_PROPIEDADES.PRODUCTO", "\\(\\log_b(xy)=\\log_bx+\\log_by\\) para argumentos positivos", "\\(\\log_2(8\\cdot4)=\\log_2 8+\\log_2 4=5\\)", "un producto dentro del argumento se convierte en suma de logaritmos", "Multiplicar potencias de la misma base suma exponentes; la propiedad del producto es esa misma idea expresada mediante logaritmos.", "expandir o condensar el logaritmo de un producto", ["Verifica que cada factor sea positivo.", "Separa el producto en una suma de logaritmos con la misma base.", "Evalúa o vuelve a condensar para comprobar la igualdad."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.COCIENTE", "\\(\\log_b(x/y)=\\log_bx-\\log_by\\) para \\(x,y>0\\)", "\\(\\log_3(81/9)=\\log_3 81-\\log_3 9=2\\)", "dividir potencias resta exponentes y por eso aparece una diferencia de logaritmos", "El cociente transforma una razón multiplicativa en una diferencia. El orden es importante: invertirlo cambia el signo del resultado.", "aplicar la propiedad logarítmica del cociente", ["Comprueba positividad de numerador y denominador.", "Escribe logaritmo del numerador menos logaritmo del denominador.", "Mantén la base común y verifica condensando la diferencia."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.POTENCIA", "\\(\\log_b(x^k)=k\\log_bx\\) para \\(x>0\\)", "\\(\\log_2(8^4)=4\\log_2 8=12\\)", "el exponente del argumento pasa a multiplicar el logaritmo", "Una potencia repite un factor y el logaritmo convierte esa repetición multiplicativa en un coeficiente.", "extraer exponentes desde un argumento logarítmico", ["Confirma que el argumento base de la potencia sea positivo.", "Baja el exponente como factor delante del logaritmo.", "Evalúa ambos lados o vuelve a introducir el factor para verificar."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.RAIZ", "\\(\\log_b\\sqrt[n]{x}=\\frac1n\\log_bx\\) para \\(x>0\\)", "\\(\\log_3\\sqrt{81}=\\frac12\\log_3 81=2\\)", "la raíz actúa como una potencia de exponente \\(1/n\\)", "La propiedad de la raíz no es una regla nueva aislada: nace al escribir el radical como exponente fraccionario.", "transformar el logaritmo de una raíz", ["Escribe la raíz como potencia \\(x^{1/n}\\).", "Aplica la propiedad de potencia y extrae \\(1/n\\) como coeficiente.", "Comprueba el dominio y evalúa el radical cuando sea exacto."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.CAMBIO_BASE", "\\(\\log_b a=\\frac{\\log_c a}{\\log_c b}\\) para bases válidas", "\\(\\log_2 7=\\ln7/\\ln2\\)", "el cociente permite calcular cualquier base usando una base disponible en la calculadora", "Una calculadora suele ofrecer solo \\(\\log\\) y \\(\\ln\\), pero el cambio de base reconstruye cualquier otra escala a partir de ellas.", "calcular un logaritmo mediante otra base", ["Elige una nueva base válida y úsala en numerador y denominador.", "Coloca el argumento original arriba y la base original abajo.", "Evalúa el cociente y verifica elevando la base original al resultado aproximado."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.POTENCIA_DE_BASE_LOGARITMICA", "\\(b^{\\log_b x}=x\\) para \\(x>0\\)", "\\(5^{\\log_5 12}=12\\)", "la exponencial de base \\(b\\) cancela a su logaritmo por ser funciones inversas", "Base y logaritmo coincidentes forman una pareja de operaciones inversas. Reconocerla evita desarrollar un cálculo que ya está resuelto por estructura.", "simplificar una potencia cuyo exponente es un logaritmo de la misma base", ["Comprueba que la base de la potencia coincida con la del logaritmo.", "Verifica que el argumento del logaritmo sea positivo.", "Cancela las operaciones inversas y conserva el argumento."])
A("MAT.NUM.LOGARITMOS_PROPIEDADES.LOGARITMO_DE_POTENCIA_MISMA_BASE", "\\(\\log_b(b^x)=x\\) para una base logarítmica válida", "\\(\\log_7(7^{-2})=-2\\)", "el logaritmo recupera el exponente de una potencia con la misma base", "La composición inversa también funciona en el otro orden: aplicar logaritmo a una potencia de la misma base devuelve el exponente.", "simplificar el logaritmo de una potencia con base coincidente", ["Compara la base del logaritmo con la base de la potencia interior.", "Comprueba que la base sea positiva y distinta de uno.", "Elimina las operaciones inversas y conserva el exponente completo."])

# Imaginarios y complejos
A("MAT.NUM.IMAGINARIOS.UNIDAD_IMAGINARIA", "la unidad imaginaria \\(i\\) se define por la relación \\(i^2=-1\\)", "\\(\\sqrt{-9}=3i\\)", "introducir \\(i\\) permite extender los reales para representar raíces de números negativos", "La ecuación \\(x^2+1=0\\) no tiene solución real, pero sí puede resolverse al ampliar el sistema numérico con una nueva unidad.", "usar la unidad imaginaria para expresar raíces negativas", ["Separa el signo negativo del valor absoluto bajo la raíz.", "Sustituye \\(\\sqrt{-1}\\) por \\(i\\).", "Simplifica la raíz positiva restante y verifica usando \\(i^2=-1\\)."])
A("MAT.NUM.IMAGINARIOS.I_CUADRADO", "por definición, \\(i^2=-1\\)", "\\(5i^2=-5\\)", "cada par de factores \\(i\\) puede reemplazarse por \\(-1\\)", "La propiedad \\(i^2=-1\\) es la regla de reducción fundamental de los números imaginarios. Permite convertir potencias y productos en formas más simples.", "simplificar expresiones que contienen \\(i^2\\)", ["Agrupa los factores imaginarios de dos en dos.", "Reemplaza cada \\(i^2\\) por \\(-1\\).", "Combina signos y coeficientes reales para comprobar la forma final."])
A("MAT.NUM.IMAGINARIOS.RAIZ_DE_MENOS_UNO", "\\(i\\) representa una raíz cuadrada de \\(-1\\)", "\\(i^2=-1\\), por lo que \\(i\\) satisface \\(x^2=-1\\)", "las dos soluciones de \\(x^2=-1\\) son \\(i\\) y \\(-i\\)", "El símbolo \\(i\\) no es una variable desconocida cualquiera: nombra una cantidad cuyo cuadrado es negativo y abre la puerta al plano complejo.", "interpretar \\(i\\) al resolver una raíz o ecuación negativa", ["Reescribe la raíz negativa separando \\(-1\\).", "Usa \\(\\sqrt{-1}=i\\) para la raíz principal elegida por convenio.", "Si resuelves una ecuación cuadrática, incluye ambas soluciones \\(\\pm i\\)."])
A("MAT.NUM.IMAGINARIOS.POTENCIAS_DE_I", "las potencias de \\(i\\) se repiten en un ciclo de cuatro: \\(i,-1,-i,1\\)", "\\(i^{23}=i^{4\\cdot5+3}=i^3=-i\\)", "el resto al dividir el exponente por \\(4\\) determina el valo", "Calcular una potencia enorme de \\(i\\) factor por factor sería inútil. La periodicidad convierte el exponente en un problema de división con resto.", "reducir cualquier potencia entera de \\(i\\)", ["Divide el exponente por \\(4\\) y conserva el resto.", "Asocia los restos \\(0,1,2,3\\) con \\(1,i,-1,-i\\).", "Comprueba el signo recorriendo un ciclo cercano si existe duda."])

A("MAT.NUM.COMPLEJOS.DEFINICION", "un número complejo tiene la forma \\(a+bi\\), con \\(a,b\\in\\mathbb{R}\\)", "\\(3-2i\\) es complejo con parte real \\(3\\) y parte imaginaria \\(-2\\)", "los reales están contenidos en los complejos tomando \\(b=0\\)", "La extensión compleja reúne una componente horizontal real y una vertical imaginaria. Juntas permiten representar soluciones que no caben en la recta real.", "reconocer un número complejo y sus componentes", ["Ordena la expresión en la forma \\(a+bi\\).", "Identifica los coeficientes reales \\(a\\) y \\(b\\).", "Verifica casos especiales: \\(b=0\\) produce un real y \\(a=0\\) un imaginario puro."])
A("MAT.NUM.COMPLEJOS.FORMA_BINOMIAL", "la forma binomial estándar de un complejo es \\(z=a+bi\\)", "\\(4i-7\\) se ordena como \\(-7+4i\\)", "escribir primero la parte real facilita comparar y operar complejos", "El orden estándar no cambia el valor, pero vuelve visibles las dos componentes. Esa organización es esencial al sumar términos semejantes.", "escribir expresiones complejas en forma binomial", ["Reduce potencias de \\(i\\) y agrupa términos reales.", "Agrupa por separado los términos que contienen \\(i\\).", "Escribe el resultado como parte real más coeficiente imaginario por \\(i\\)."])
A("MAT.NUM.COMPLEJOS.PARTE_REAL", "en \\(z=a+bi\\), la parte real es \\(\\operatorname{Re}(z)=a\\)", "si \\(z=-5+8i\\), entonces \\(\\operatorname{Re}(z)=-5\\)", "la parte real no incluye el término imaginario ni su coeficiente", "Leer un complejo exige separar dos coordenadas. La parte real es la que sobreviviría al hacer cero el componente imaginario.", "identificar la parte real de un complejo", ["Ordena el número en forma \\(a+bi\\).", "Localiza el término que no contiene \\(i\\).", "Entrega su valor con signo y comprueba que sea un número real."])
A("MAT.NUM.COMPLEJOS.PARTE_IMAGINARIA", "en \\(z=a+bi\\), la parte imaginaria es el coeficiente real \\(b\\)", "si \\(z=6-3i\\), entonces \\(\\operatorname{Im}(z)=-3\\)", "la parte imaginaria es \\(-3\\), no el término \\(-3i\\)", "La palabra “parte” puede inducir a copiar todo el término con \\(i\\). En notación matemática, \\(\\operatorname{Im}(z)\\) devuelve únicamente su coeficiente real.", "identificar correctamente la parte imaginaria", ["Escribe el complejo como \\(a+bi\\).", "Lee el coeficiente de \\(i\\), incluyendo su signo.", "Distingue el coeficiente \\(b\\) del término imaginario completo \\(bi\\)."])
A("MAT.NUM.COMPLEJOS.REPRESENTACION_CARTESIANA", "el complejo \\(a+bi\\) se representa por el par ordenado \\((a,b)\\)", "\\(-2+5i\\) corresponde al punto \\((-2,5)\\)", "la coordenada horizontal es la parte real y la vertical es la parte imaginaria", "Un complejo puede verse como un punto o vector del plano. La forma cartesiana traduce directamente sus dos componentes en coordenadas.", "convertir entre forma binomial y par cartesiano", ["Identifica \\(a\\) y \\(b\\) en la forma \\(a+bi\\).", "Escribe el par \\((a,b)\\) respetando orden y signos.", "Reconstruye \\(a+bi\\) desde el par para verificar la correspondencia."])
A("MAT.NUM.COMPLEJOS.PLANO_COMPLEJO", "el plano complejo usa el eje horizontal para la parte real y el vertical para la imaginaria", "\\(2-3i\\) se ubica tres unidades bajo el punto \\(2\\) del eje real", "cada complejo corresponde a un único punto del plano de Argand", "La recta numérica no tiene espacio para una segunda componente. El plano complejo añade un eje perpendicular y convierte cada número en una ubicación bidimensional.", "ubicar números complejos en el plano", ["Extrae las coordenadas \\((a,b)\\) del complejo.", "Desplázate \\(a\\) unidades en el eje real y \\(b\\) en el imaginario.", "Marca el punto y comprueba el cuadrante según los signos."])
A("MAT.NUM.COMPLEJOS.CONJUGADO", "el conjugado de \\(z=a+bi\\) es \\(\\overline z=a-bi\\)", "si \\(z=4-7i\\), entonces \\(\\overline z=4+7i\\)", "el conjugado refleja el punto respecto del eje real y cumple \\(z\\overline z=a^2+b^2\\)", "Cambiar el signo imaginario produce una simetría geométrica y, al multiplicar, elimina la componente con \\(i\\). Ambas lecturas explican la utilidad del conjugado.", "obtener y verificar el conjugado de un complejo", ["Conserva la parte real sin cambios.", "Cambia únicamente el signo del coeficiente imaginario.", "Multiplica por el original o refleja el punto para comprobar el resultado."])
A("MAT.NUM.COMPLEJOS.MODULO", "el módulo de \\(z=a+bi\\) es \\(|z|=\\sqrt{a^2+b^2}\\)", "\\(|3-4i|=\\sqrt{3^2+(-4)^2}=5\\)", "el módulo es la distancia desde el origen al punto complejo y siempre es no negativo", "Las partes real e imaginaria forman los catetos de un triángulo rectángulo. El módulo es su hipotenusa y mide el tamaño del complejo en el plano.", "calcular e interpretar el módulo de un complejo", ["Identifica las componentes \\(a\\) y \\(b\\).", "Suma sus cuadrados y extrae la raíz cuadrada principal.", "Comprueba que el resultado sea no negativo y coincida con la distancia al origen."])


def main() -> None:
    nodes = list(
        KnowledgeNode.objects.filter(
            node_type="recurso",
            parent__parent__semantic_id="MAT.NUM.B0204",
        ).order_by("parent__order", "order", "semantic_id")
    )
    ids = [node.semantic_id for node in nodes]
    missing = set(ids) - set(SPECS)
    extra = set(SPECS) - set(ids)
    if len(nodes) != 93 or missing or extra:
        raise RuntimeError(
            f"B0204 inconsistente: nodes={len(nodes)} missing={missing} extra={extra}"
        )

    for node in nodes:
        base.safe_write_yaml(
            base.CONTENT_DIR / base.yaml_filename(node.semantic_id),
            build_content(node.semantic_id, node.name),
        )

    all_meta = {
        sid: {
            "definition": SPECS[sid]["definition"],
            "example": SPECS[sid]["example"],
            "fact": SPECS[sid]["fact"],
        }
        for sid in ids
    }
    groups = [ids[i : i + 5] for i in range(0, len(ids), 5)]
    for index, group in enumerate(groups, start=1):
        rows = []
        for sid in group:
            node = next(n for n in nodes if n.semantic_id == sid)
            rows.extend(
                base.make_exercises(sid, node.name, node.competencia, all_meta)
            )
        base.write_jsonl(
            base.EXERCISES_DIR / f"mat-num-reales-banco-gen-{index}.jsonl", rows
        )
    print(f"B0204 generado: {len(nodes)} YAML y {len(groups)} JSONL.")


if __name__ == "__main__":
    main()
