import re
import os

new_explanations = {
    # FRACCIONES MULT (Tanda 3)
    "MAT.ALG.FRACCIONES_MULT.PRODUCTO_DIRECTO": "Multiplicar fracciones algebraicas es paradójicamente mucho más sencillo que sumarlas, porque no necesitas buscar denominadores comunes (MCM).\n\nLa regla es el ataque directo:\n- **Numerador por Numerador (Piso de arriba se multiplica con piso de arriba)**\n- **Denominador por Denominador (Piso de abajo se multiplica con piso de abajo)**\n\nFórmula general: $\\frac{A}{B} \\cdot \\frac{C}{D} = \\frac{A \\cdot C}{B \\cdot D}$\n\nPor ejemplo: $\\frac{2x}{3y} \\cdot \\frac{4x^2}{5} = \\frac{2x \\cdot 4x^2}{3y \\cdot 5} = \\frac{8x^3}{15y}$.\n\nSimplemente aplicas las leyes de los exponentes (bases iguales suman exponentes) y multiplicas los números libremente. Es rápido y directo.",
    "MAT.ALG.FRACCIONES_MULT.FACTORIZACION_PREVIA": "Si te lanzas a multiplicar directamente polinomios gigantes (ej: $(x^2 - 4) \\cdot (x^2 + 5x + 6)$), vas a terminar con un monstruo polinómico de grado 4 que será casi imposible de simplificar al final.\n\nLa ley de oro antes de multiplicar cualquier fracción compleja es **FACTORIZAR TODO PRIMERO**.\nDebes desarmar cada numerador y cada denominador en pequeños paréntesis (factores).\n\n¿Por qué? Porque al multiplicar, esos pequeños paréntesis quedarán todos juntos, pegados por multiplicaciones, en una sola gran fracción. Y como están multiplicando, ¡te será muy fácil tachar (simplificar) los paréntesis idénticos de arriba con los de abajo antes de calcular nada grande!",
    "MAT.ALG.FRACCIONES_MULT.SIMPLIFICACION_CRUZADA": "La simplificación cruzada es tu mejor amiga para evitar cálculos gigantes. Se basa en una propiedad mágica de la multiplicación de fracciones: como todos los numeradores terminan multiplicándose juntos arriba y los denominadores abajo, **puedes tachar cualquier factor de arriba con cualquier factor igual de abajo**, sin importar si estaban originalmente en la misma fracción o en fracciones cruzadas.\n\nEjemplo:\nTienes $\\frac{(x-2)}{x+1} \\cdot \\frac{x+1}{(x-2)(x+3)}$.\n\nEn lugar de multiplicar todo, observa:\n- Tienes un $(x-2)$ arriba (en la 1ra) y uno abajo (en la 2da). ¡Se tachan!\n- Tienes un $(x+1)$ abajo (en la 1ra) y uno arriba (en la 2da). ¡Se tachan!\n\n¿Qué sobrevivió a la masacre? Arriba se canceló todo (queda un 1). Abajo sobrevivió $(x+3)$.\nResultado final inmediato: $\\frac{1}{x+3}$.",
    "MAT.ALG.FRACCIONES_MULT.PRODUCTO_RESULTANTE": "Una vez que has factorizado, simplificado en cruz y tachado todo lo tachablemente posible, llega el momento de recoger los escombros y armar tu respuesta final.\n\nEl producto resultante es simplemente la multiplicación de los factores 'supervivientes' en el numerador y los 'supervivientes' en el denominador.\n\nRegla de estilo matemático: Es perfectamente válido, y muchas veces preferible, dejar el resultado expresado como multiplicaciones indicadas de factores primos en lugar de desarrollar la multiplicación. Es decir, dejar la respuesta como $\\frac{(x-5)}{(x+2)(x-3)}$ suele ser mejor (y más útil para ver el dominio) que expandirlo a $\\frac{x-5}{x^2-x-6}$. Sigue la instrucción de la prueba o de tu profesor.",

    # FRACCIONES DIV
    "MAT.ALG.FRACCIONES_DIV.INVERSO_MULTIPLICATIVO": "El 'inverso multiplicativo' (o recíproco) de una fracción es simplemente darla vuelta. Si tienes $\\frac{A}{B}$, su inverso es $\\frac{B}{A}$.\n\n¿Por qué importa esto? Porque en álgebra (y en matemáticas en general), **la división de fracciones no existe como operación nativa**. \nDividir por una fracción es exactamente lo mismo que multiplicar por el inverso de esa fracción.\n\nPor ejemplo, dividir por $1/2$ (la mitad) es matemáticamente idéntico a multiplicar por $2$. Dividir por $\\frac{x}{y}$ es lo mismo que multiplicar por $\\frac{y}{x}$.\nEl inverso multiplicativo es la llave maestra que transforma el feo problema de la división en un amigable problema de multiplicación.",
    "MAT.ALG.FRACCIONES_DIV.PRODUCTO_RECIPROCO": "La regla universal para dividir fracciones algebraicas se resume en el mantra de tres pasos de la escuela: 'Mantener, Cambiar, Voltear' (Keep, Change, Flip).\n\nSi tienes: $\\frac{A}{B} \\div \\frac{C}{D}$\n\n1. **Mantener:** La primera fracción ($\\frac{A}{B}$) se queda exactamente igual. No la toques.\n2. **Cambiar:** El signo de división ($\\div$) se convierte en multiplicación ($\\cdot$).\n3. **Voltear:** Inviertes (das vuelta) la segunda fracción. El numerador pasa a ser denominador y viceversa. ($\\frac{C}{D}$ se convierte en $\\frac{D}{C}$).\n\nOperación resultante: $\\frac{A}{B} \\cdot \\frac{D}{C}$.\n\nA partir de aquí, el problema es una simple multiplicación de fracciones. Factorizas, simplificas cruzado y resuelves.",
    "MAT.ALG.FRACCIONES_DIV.FACTORIZACION_PREVIA": "Al igual que en la multiplicación, lanzarse a multiplicar el resultado del 'producto recíproco' sin factorizar es un suicidio algebraico.\n\nEl orden estricto de ejecución para divisiones complejas es:\n1. Aplica la regla 'Mantener, Cambiar, Voltear' para transformar la división en multiplicación.\n2. Inmediatamente después, **factoriza absolutamente todos** los numeradores y denominadores resultantes.\n3. Ahora que todo son puros factores (paréntesis) multiplicándose, busca paréntesis idénticos arriba y abajo para simplificarlos (tacharlos).\n\nSi te saltas el paso 2 y multiplicas primero, crearás polinomios masivos que te harán perder el tiempo en exámenes.",
    "MAT.ALG.FRACCIONES_DIV.SIMPLIFICACION_RESULTADO": "Este es el paso de limpieza final. Después de haber convertido la división en multiplicación, haber factorizado y haber simplificado, debes presentar el resultado de forma limpia.\n\nUn detalle crucial sobre las restricciones (el dominio) al simplificar el resultado de una división:\nEn una multiplicación normal, las restricciones vienen de los denominadores. Pero en una división, $\\frac{A}{B} \\div \\frac{C}{D}$, fíjate que la $C$ estaba originalmente arriba, pero al voltear la fracción, ¡quedó abajo!\nPor lo tanto, la expresión original explota si $B=0$, si $D=0$ (por los denominadores originales) Y TAMBIÉN si $C=0$ (porque terminarás dividiendo por cero la fracción volteada).\nLleva cuidado con eso si te piden el dominio en niveles avanzados.",
    "MAT.ALG.FRACCIONES_DIV.ERROR_RECIPROCO": "El error más doloroso e imperdonable al dividir fracciones es confundirse de fracción y voltear la primera en lugar de la segunda.\n\nEjemplo del horror:\n$\\frac{x}{y} \\div \\frac{2}{3}$\n- Estudiante confundido: Voltea la primera $\\rightarrow \\frac{y}{x} \\cdot \\frac{2}{3} = \\frac{2y}{3x}$.\n- Estudiante maestro: Voltea la SEGUNDA $\\rightarrow \\frac{x}{y} \\cdot \\frac{3}{2} = \\frac{3x}{2y}$.\n\n¿Ves la diferencia? El resultado es completamente distinto. La división no es conmutativa (dividir 10 entre 2 no es lo mismo que dividir 2 entre 10).\n\n**REGLA:** El signo de división SOLO afecta a la fracción que está a su INMEDIATA DERECHA. Esa es la única que tiene permiso para voltearse.",

    # FRACCIONES SUMA
    "MAT.ALG.FRACCIONES_SUMA.IGUAL_DENOMINADOR": "¡Alegría, alegría! Sumar fracciones con el mismo denominador es el escenario más fácil posible.\n\nLa regla fundamental de las fracciones dice que solo puedes sumar pedazos si son del mismo tamaño (es decir, tienen el mismo denominador).\n\nSi los denominadores ya son iguales, la operación es directa:\n1. Conservas el denominador intacto (¡No los sumes! El tamaño del pedazo no cambia).\n2. Sumas matemáticamente los numeradores (la cantidad de pedazos).\n\nEjemplo algebraico:\n$\\frac{3x}{x+1} + \\frac{5}{x+1}$\n- Mantén el piso de abajo: $x+1$.\n- Junta el techo con una suma: $3x + 5$.\n- Resultado: $\\frac{3x + 5}{x+1}$.\nTan sencillo como sumar 2 manzanas más 3 manzanas.",
    "MAT.ALG.FRACCIONES_SUMA.DISTINTO_DENOMINADOR": "Este es el verdadero desafío del álgebra de fracciones. No puedes sumar fracciones con distintos denominadores directamente, porque estarías intentando sumar manzanas con limones.\n\nAntes de juntar los numeradores, debes forzar a que ambos denominadores sean idénticos. Este proceso se llama 'hallar el Mínimo Común Denominador (MCM)'.\n\nSi tienes $\\frac{1}{x} + \\frac{1}{y}$:\n1. El MCM de $x$ e $y$ es $xy$.\n2. Amplificas la primera fracción: le falta la 'y' abajo, así que multiplicas arriba y abajo por 'y' $\\rightarrow \\frac{y}{xy}$.\n3. Amplificas la segunda fracción: le falta la 'x' abajo, multiplicas arriba y abajo por 'x' $\\rightarrow \\frac{x}{xy}$.\n4. ¡Ahora ambas tienen $xy$ abajo! Puedes juntar los techos.\nResultado: $\\frac{y+x}{xy}$.",
    "MAT.ALG.FRACCIONES_SUMA.USO_MCM": "Para denominadores grandes que son polinomios completos, hallar el MCM requiere cirugía de precisión.\n\n**Algoritmo maestro para sumar fracciones difíciles:**\n1. Factoriza por completo TODOS los denominadores de las fracciones. (No toques los numeradores aún).\n2. Construye tu super-denominador (el MCM). Toma todos los paréntesis distintos que aparecieron abajo, a su mayor exponente.\n3. Amplificación selectiva: Para cada fracción, compara su denominador viejo con el super-denominador. Identifica qué paréntesis le faltan para volverse el super-denominador.\n4. Multiplica el numerador de esa fracción por los paréntesis exactos que le faltaban abajo.\n5. Expande los numeradores resultantes y suma o reduce los términos semejantes.\n\nSin este procedimiento ordenado, el problema se convertirá en un monstruo imparable.",
    "MAT.ALG.FRACCIONES_SUMA.REDUCCION_NUMERADOR": "Una vez que has logrado construir tu súper fracción con el denominador común, tienes un numerador gigante lleno de sumas y (frecuentemente) multiplicaciones sin resolver.\n\nEl siguiente paso es limpiar ese numerador gigante.\n1. Desarrolla las multiplicaciones distribuyendo los factores. (Ej: $x(x+2)$ se vuelve $x^2 + 2x$).\n2. Identifica los términos semejantes (las $x^2$ con las $x^2$, las $x$ con las $x$, los números con los números).\n3. Suma y resta esos términos para reducir el polinomio a su mínima expresión.\n\nCuidado letal: Durante todo este proceso de orden, **NO TOQUES EL DENOMINADOR**. Déjalo factorizado, porque es mucho más útil así para el paso final de simplificación.",
    "MAT.ALG.FRACCIONES_SUMA.SIMPLIFICACION_FINAL": "Has trabajado duro, igualaste denominadores, sumaste numeradores, y reduciste todo. ¡Ya terminaste! Bueno, casi.\n\nEl protocolo de buena etiqueta matemática exige que el resultado final de toda fracción esté simplificado al máximo.\n\nPara revisar si se puede simplificar más:\n1. Toma tu numerador recién reducido (tu respuesta).\n2. Factorízalo si es posible. (Saca factor común, trinomio, etc.).\n3. Observa el denominador (que sabiamente habías dejado factorizado desde el paso del MCM).\n4. ¿Hay algún paréntesis arriba idéntico a alguno de abajo? Si es así, táchalos.\n\nSi no se puede factorizar el numerador, o no hay coincidencias con el denominador, entonces tu fracción es irreductible y has llegado al final real del problema.",

    # FRACCIONES RESTA
    "MAT.ALG.FRACCIONES_RESTA.IGUAL_DENOMINADOR": "La resta con igual denominador opera exactamente igual que la suma con igual denominador: mantienes el piso intacto y restas los techos.\n\nEjemplo: $\\frac{5x}{2a} - \\frac{3x}{2a}$\n1. Se conserva el denominador: $2a$.\n2. Restas los numeradores: $5x - 3x = 2x$.\n3. Tienes el resultado base: $\\frac{2x}{2a}$.\n4. (Paso de limpieza): Tacha el 2 con el 2. Respuesta final: $\\frac{x}{a}$.\n\nPero, mucho ojo: esta tranquilidad es peligrosa. Si el segundo numerador (el que está siendo restado) fuera un polinomio entero (ej: $3x + 1$), el signo menos va a intentar atacarlo completo. Veremos ese peligro en el siguiente tema.",
    "MAT.ALG.FRACCIONES_RESTA.DISTINTO_DENOMINADOR": "Restar fracciones con denominadores distintos te obliga a seguir la misma ruta ceremonial que la suma: Factorizar, encontrar el MCM, amplificar y unir los numeradores.\n\nSupongamos: $\\frac{2}{x-1} - \\frac{1}{x+1}$.\n1. Denominador común (MCM): $(x-1)(x+1)$.\n2. A la primera fracción le falta $(x+1)$ abajo. Multiplicamos su techo por eso: $2(x+1)$.\n3. A la segunda fracción le falta $(x-1)$ abajo. Multiplicamos su techo por eso: $1(x-1)$.\n4. Juntamos con la resta en medio: $\\frac{2(x+1) - 1(x-1)}{(x-1)(x+1)}$.\n\nAquí es donde la resta se pone agresiva: ese menos en medio va a afectar los signos del segundo bloque. Debes desarrollar con sumo cuidado.",
    "MAT.ALG.FRACCIONES_RESTA.PARENTESIS_NUMERADOR": "Cuando juntas dos fracciones con una resta, debes activar una alarma roja de emergencia en tu cerebro.\n\nEl signo menos ($-$) que estaba entre las fracciones, ahora se va a aplicar al segundo numerador. La regla estricta es: **Coloca paréntesis invisibles a todo el segundo numerador** antes de aplicarle el menos.\n\nEjemplo visual de la trampa:\n$\\frac{3x}{5} - \\frac{x - 2}{5}$\n- Forma incorrecta: Conservas el 5 y escribes $3x - x - 2$. (El menos solo afectó a la x). Resultado erróneo: $2x-2$.\n- Forma magistral: Conservas el 5 y escribes $3x - (x - 2)$. El menos afecta a TODOS los términos dentro del paréntesis.\n  Queda: $3x - x + 2$ (el -2 se vuelve +2 por la regla de signos).\n  Resultado correcto: $\\frac{2x + 2}{5}$.\n\nEl 90% de los errores en las pruebas al restar fracciones ocurren exactamente aquí.",
    "MAT.ALG.FRACCIONES_RESTA.USO_MCM": "El uso del MCM en la resta es idéntico a la suma, pero la presión aumenta al momento de armar el gran numerador final por culpa de los signos negativos.\n\nAl construir el numerador unificado:\n$\\frac{ \\text{Num1}(\\text{lo que faltaba}) - \\text{Num2}(\\text{lo que faltaba}) }{ \\text{MCM} }$\n\nEse signo menos intermedio multiplicará al desarrollo de $\\text{Num2}(\\text{lo que faltaba})$.\n\n**Recomendación de oro:** Desarrolla la multiplicación de $\\text{Num2}(\\text{lo que faltaba})$ manteniendo un gran corchete de seguridad, y solo cuando hayas terminado de multiplicar los paréntesis internos, distribuye el signo negativo externo para invertir todos los signos resultantes de golpe.",
    "MAT.ALG.FRACCIONES_RESTA.CAMBIO_SIGNOS_NUMERADOR": "La mecánica del cambio de signos es tu escudo protector al operar el numerador de una resta.\n\nVeámoslo en cámara lenta:\nTienes la expresión en el numerador: $x^2 - 3x - (2x^2 - 5x + 1)$.\n\nEl signo menos actúa como un 'inversor universal' multiplicando por $-1$.\n- El $2x^2$ positivo se voltea a $-2x^2$.\n- El $-5x$ negativo se voltea a $+5x$.\n- El $+1$ positivo se voltea a $-1$.\n\nEl numerador sin paréntesis queda: $x^2 - 3x - 2x^2 + 5x - 1$.\nAhora puedes reducir términos semejantes tranquilo. Si dominas esto sistemáticamente sin saltarte pasos, serás invulnerable en las restas algebraicas.",
    "MAT.ALG.FRACCIONES_RESTA.ERROR_PARENTESIS": "Vamos a analizar el asesino de notas más letal del álgebra de fracciones: 'El Síndrome del Signo Perdido'.\n\nOcurre al restar un numerador polinomial:\nRestar $\\frac{x^2 - 4x + 1}{D}$.\n\nEl estudiante apresurado une la fracción con un menos y escribe: $-x^2 - 4x + 1$.\n¿Qué pasó? Le cambió el signo al primer término ($x^2$), pero por la prisa, copió el resto igual. Ignoró que el menos debía golpear al $-4x$ (volviéndolo $+4x$) y al $+1$ (volviéndolo $-1$).\n\n**Cura definitiva:** Cada vez que veas un signo menos enlazando fracciones, escribe físicamente un paréntesis gigante al juntarlas, ej: $- (x^2 - 4x + 1)$. Toma un segundo escribirlo y te salvará de perder todo el puntaje del ejercicio.",
    "MAT.ALG.FRACCIONES_RESTA.SIMPLIFICACION_FINAL": "La etapa de cierre de la resta es idéntica a la suma. Has domado los signos, distribuido, y reducido tu numerador gigante a algo compacto.\n\nAntes de cantar victoria, la revisión de estilo es obligatoria:\n1. Toma tu numerador compactado y obsérvalo. ¿Se puede factorizar? (Busca factor común o fíjate si es un trinomio factorizable).\n2. Si se factoriza, colócalo en paréntesis.\n3. Si alguno de esos nuevos paréntesis del numerador es exactamente igual a los paréntesis que dejaste descansando pacíficamente en el denominador, aplícales la simplificación asesina (táchalos).\n\nEl resultado sobreviviente, con sus restricciones de dominio heredadas, es tu respuesta gloriosa final.",

    # FRACCIONES COMPLEJAS
    "MAT.ALG.FRACCIONES_COMPLEJAS.DEFINICION": "Una fracción compleja (o compuesta) parece una pesadilla arquitectónica: es una fracción principal enorme que tiene otras fracciones más pequeñas anidadas adentro de su numerador, de su denominador, ¡o en ambos!\n\nTiene la estructura:\n$\\frac{\\frac{A}{B}}{\\frac{C}{D}}$\n\nNo debes entrar en pánico. Una fracción es fundamentalmente un símbolo de división gigante.\nEsa pesadilla visual se puede leer en español simple como: '(Numerador Grande) dividido entre (Denominador Grande)'.\n\nEl método general más seguro para resolverlas se llama 'Aplanar los pisos'. Consiste en trabajar solo el piso de arriba hasta convertirlo en UNA sola fracción normal, luego trabajar solo el piso de abajo hasta que sea UNA sola fracción normal, y finalmente usar la regla de la taza de café (multiplicar extremos con extremos, medios con medios) para colapsarlas en una sola.",
    "MAT.ALG.FRACCIONES_COMPLEJAS.SEGUNDO_NIVEL": "El famoso truco para resolver la fracción compleja en el último paso, una vez que lograste aplanar ambos pisos a formas simples, se conoce de múltiples formas: regla del sándwich, ley de la oreja, o multiplicación de extremos por medios.\n\nTienes la estructura purificada: $\\frac{\\frac{A}{B}}{\\frac{C}{D}}$\n\nEsto es equivalente a $\\frac{A}{B} \\div \\frac{C}{D}$.\nSi recuerdas la regla de división (Mantener, Cambiar, Voltear), esto se vuelve $\\frac{A}{B} \\cdot \\frac{D}{C} = \\frac{AD}{BC}$.\n\n**La Regla del Sándwich visualizada:**\n1. Multiplicas los elementos de afuera (los tapas del pan): El de más arriba ($A$) y el de más abajo ($D$). Ellos forman el nuevo Numerador ($AD$).\n2. Multiplicas los elementos del medio (el relleno): Los que están cerca de la línea gruesa central ($B$ y $C$). Ellos forman el nuevo Denominador ($BC$).\n\nResultado final en un paso: $\\frac{AD}{BC}$. Rápido y sin dolor.",
    "MAT.ALG.FRACCIONES_COMPLEJAS.DENOMINADOR_COMPUESTO": "A menudo, el 'piso de arriba' o el 'piso de abajo' no son fracciones simples listas para la regla del sándwich, sino una ensalada de fracciones sumándose o restándose. Por ejemplo, el denominador principal es $(1 + \\frac{1}{x})$.\n\nAntes de intentar la ley del sándwich, **tienes la obligación de convertir esa ensalada en una única fracción compacta**.\n\nPara el ejemplo $(1 + \\frac{1}{x})$:\n1. Imagina que el 1 es una fracción: $\\frac{1}{1}$.\n2. Súmala a $\\frac{1}{x}$ usando el MCM (que es 'x').\n3. Amplifica la primera: $\\frac{x}{x} + \\frac{1}{x}$.\n4. Suma los numeradores: $\\frac{x+1}{x}$.\n\n¡Listo! Tu piso rebelde ha sido compactado en una hermosa fracción. Haz lo mismo con el otro piso y ahora sí podrás aplicar la ley del sándwich sin problemas.",
    "MAT.ALG.FRACCIONES_COMPLEJAS.FRACCION_CONTINUA_FINITA": "Las fracciones continuas parecen infinitamente profundas, como escaleras que descienden en cascada: $\\frac{1}{1 + \\frac{1}{1 + x}}$.\n\nLa estrategia para resolver este puzzle no es de arriba hacia abajo, sino de **abajo hacia arriba**. Imagina que estás construyendo una pirámide invertida; debes consolidar la punta (la parte más baja) para poder subir al siguiente nivel.\n\n**Estrategia 'Bottom-Up':**\n1. Ve al rincón más profundo de la fracción (en el ejemplo, el nivel del denominador inferior: $1 + x$).\n2. Resuelve la mini-fracción compleja de ese piso. Si tienes $\\frac{1}{(algo)}$, recuerda que dividir 1 entre una fracción simplemente voltea la fracción.\n3. Una vez consolidado ese nivel, subirás un peldaño y enfrentarás una nueva suma. Resuélvela.\n4. Continúa este proceso de 'colapso' secuencial piso por piso, hasta llegar al tope.\n\nEs un proceso mecánico, de pura paciencia, donde saltarte un escalón es tropezar y caer.",
    "MAT.ALG.FRACCIONES_COMPLEJAS.FRACCION_CONTINUA_INFINITA": "Una fracción continua infinita es una estructura fascinante, como un espejo frente a otro espejo: $x = 1 + \\frac{1}{1 + \\frac{1}{1 + ...}}$. Sigue para siempre.\n\nParece imposible de resolver, pero utiliza uno de los trucos lógicos más hermosos de la matemática matemática pura: **la auto-similitud fractal**.\n\nComo la fracción sigue infinitamente hacia abajo con el mismo patrón exacto, si tapas la primera capa, el trozo infinito que sobra abajo ¡es matemáticamente idéntico a la fracción original completa ($x$)!\n\n**Truco Maestro:**\n1. Observa el patrón infinito bajo el primer término.\n2. Reemplaza todo ese infinito bloque con la misma letra original $x$.\n3. Tu problema infinito se colapsa instantáneamente a una ecuación finita simple: $x = 1 + \\frac{1}{x}$.\n4. Multiplicas todo por $x$ para deshacerte del denominador: $x^2 = x + 1$.\n5. Obtienes $x^2 - x - 1 = 0$, que es una ecuación cuadrática clásica. ¡Y la resuelves! (Dato curioso: el resultado positivo de esta específica ecuación da vida al sagrado 'Número de Oro' o Proporción Áurea, $\\frac{1+\\sqrt{5}}{2}$)."
}

def process_files(file_dict):
    success = 0
    pattern = re.compile(r'(explicacion:\s*\|)(.*?)(?=\nprocedimiento:)', re.DOTALL)
    for sid, new_expl in file_dict.items():
        filename = f"docs/conocimiento/contenido/{sid.lower().replace('.', '-').replace('_', '-')}.yaml"
        if not os.path.exists(filename):
            print(f"Error: {filename} no encontrado.")
            continue

        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()

        formatted_expl = "\n  " + "\n  ".join(new_expl.strip().split("\n")) + "\n"

        new_content, count = pattern.subn(lambda m: m.group(1) + formatted_expl, content)

        if count > 0:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(new_content)
            success += 1
            print(f"Actualizado: {filename}")
        else:
            print(f"Fallo regex en: {filename}")
    return success

if __name__ == "__main__":
    s = process_files(new_explanations)
    print(f"Total actualizados Tandas 3, 4 y 5: {s}/{len(new_explanations)}")
