import re
import os

new_explanations = {
    # MCD
    "MAT.ALG.MCD_ALGEBRAICO.CONCEPTO_MCD": "El Máximo Común Divisor (MCD) en álgebra es como buscar el 'ADN compartido' más grande entre varias expresiones matemáticas. Es la expresión más grande que divide a todas las demás sin dejar residuo (es decir, de manera exacta).\n\nImagina que tienes tres bolsas con dulces, y quieres armar paquetes idénticos sin que sobre nada. El tamaño del paquete más grande posible es tu MCD.\n\nEn álgebra, el MCD se forma tomando los elementos comunes que se repiten en TODOS los términos, pero eligiendo siempre el que tiene el **menor exponente** (el eslabón más débil, porque es el único que cabe en todos). Si un término tiene $x^3$ y otro tiene $x^2$, el MCD solo puede incluir $x^2$.",
    "MAT.ALG.MCD_ALGEBRAICO.COEFICIENTE_MONOMIOS": "Para los coeficientes numéricos (los números grandes al inicio de cada término), el MCD se calcula exactamente igual que en aritmética básica.\n\nDebes buscar el número más grande que divida a todos los coeficientes a la vez.\n\nPor ejemplo, para los términos $12x$, $18y$ y $24z$:\n- Los divisores de 12 son: 1, 2, 3, 4, 6, 12.\n- Los divisores de 18 son: 1, 2, 3, 6, 9, 18.\n- Los divisores de 24 son: 1, 2, 3, 4, 6, 8, 12, 24.\n\nEl número más grande que aparece en las tres listas es el **6**. Por lo tanto, el MCD de los coeficientes es 6. Es fundamental calcular esto correctamente porque es el primer paso (y la mitad del trabajo) para factorizar por factor común.",
    "MAT.ALG.MCD_ALGEBRAICO.PARTE_LITERAL_MONOMIOS": "La parte literal (las letras) es donde el álgebra brilla. Para encontrar el MCD de las letras, debes seguir una regla de oro estricta:\n\n**Regla del MCD Literal:** Selecciona ÚNICAMENTE las bases (letras) que se repiten en TODOS los monomios, y asígnales el MENOR exponente con el que aparecen.\n\nVeamos un ejemplo paso a paso. Tenemos $A = x^3 y^2$ y $B = x^2 y^4 z$.\n- **Paso 1 (Letras comunes):** ¿Qué letras están en A y en B? La $x$ y la $y$. (La $z$ solo está en B, así que la descartamos. No es común).\n- **Paso 2 (Menor exponente para $x$):** En A tenemos $x^3$ y en B tenemos $x^2$. El menor es 2. Tomamos $x^2$.\n- **Paso 3 (Menor exponente para $y$):** En A tenemos $y^2$ y en B tenemos $y^4$. El menor es 2. Tomamos $y^2$.\n\nResultado: El MCD es $x^2 y^2$.",
    "MAT.ALG.MCD_ALGEBRAICO.MCD_MONOMIOS": "El MCD completo de un grupo de monomios es simplemente la combinación (multiplicación) del MCD de sus números y el MCD de sus letras.\n\n**Fórmula de ensamblaje:**\nMCD(Total) = MCD(Coeficientes) $\\cdot$ MCD(Parte Literal)\n\nTomemos un ejemplo integrado: $15a^3 b^2$ y $20a^2 b^3 c$.\n\n1. **Coeficientes (15 y 20):** El número más grande que divide a 15 y 20 es **5**.\n2. **Letras comunes:** La '$a$' y la '$b$'. (La '$c$' queda fuera).\n3. **Exponentes menores:** Para la '$a$', entre 3 y 2, el menor es **2** ($a^2$). Para la '$b$', entre 2 y 3, el menor es **2** ($b^2$).\n\nJuntando todo: El MCD es **$5a^2b^2$**. Este término es el mayor 'bloque de construcción' que cabe perfectamente dentro de ambos monomios iniciales.",
    "MAT.ALG.MCD_ALGEBRAICO.FACTORIZACION_POLINOMIOS": "Cuando las expresiones ya no son simples monomios, sino polinomios completos (sumas y restas), el proceso tiene un paso inicial obligatorio: **Factorizar cada polinomio al máximo**.\n\nNo puedes hallar el MCD de polinomios mirándolos directamente. Debes descomponerlos en sus 'ladrillos' fundamentales (factores).\n\nEjemplo:\n- Polinomio 1: $x^2 - 4$. Su factorización (diferencia de cuadrados) es $(x-2)(x+2)$.\n- Polinomio 2: $x^2 - 4x + 4$. Su factorización (cuadrado de binomio) es $(x-2)^2$.\n\nAhora aplicamos la regla de oro del MCD a los paréntesis como si fueran letras simples:\n1. **Factor común:** El único paréntesis que se repite en ambos es $(x-2)$.\n2. **Menor exponente:** En el P1 está elevado a 1. En el P2 está elevado a 2. El menor es 1.\n\nEl MCD de estos dos polinomios es **$(x-2)$**.",
    "MAT.ALG.MCD_ALGEBRAICO.ALGORITMO_EUCLIDES": "El Algoritmo de Euclides es un método legendario y avanzado para encontrar el MCD entre dos polinomios que son muy difíciles de factorizar a simple vista. Se basa en divisiones sucesivas.\n\nLa lógica detrás de Euclides es simple: Si un término divide a $A$ y a $B$, también debe dividir al resto (residuo) de la división entre $A$ y $B$.\n\n**Pasos del algoritmo:**\n1. Se divide el polinomio de mayor grado ($P_1$) por el de menor grado ($P_2$).\n2. Si el residuo es cero, el MCD es $P_2$.\n3. Si hay un residuo ($R_1$), se divide $P_2$ por $R_1$.\n4. Se repite el proceso (dividiendo el divisor anterior por el residuo actual) hasta que el residuo sea cero.\n5. El **último divisor no nulo** es el MCD.\n\nEste método es muy mecánico, pero requiere dominar a la perfección la división larga de polinomios.",

    # MCM
    "MAT.ALG.MCM_ALGEBRAICO.CONCEPTO_MCM": "El Mínimo Común Múltiplo (MCM) en álgebra es el concepto opuesto al MCD. Aquí no buscamos el bloque más pequeño que cabe en ellos, sino el 'recipiente más pequeño' en el que quepan TODAS las expresiones originales sin que sobre espacio.\n\nEs la expresión algebraica más pequeña que puede ser dividida de forma exacta por todas las demás.\n\nPara formar este 'super-recipiente', debes tomar absolutamente todos los elementos presentes (tanto los comunes como los no comunes), pero esta vez, si un elemento se repite, debes elegir el que tiene el **mayor exponente** (para garantizar que las versiones más grandes de ese elemento quepan sin problema).",
    "MAT.ALG.MCM_ALGEBRAICO.COEFICIENTE_MONOMIOS": "Al igual que con el MCD, el MCM de los coeficientes numéricos se calcula usando aritmética tradicional. Buscamos el número más pequeño que sea múltiplo de todos los coeficientes a la vez.\n\nPor ejemplo, para los términos $4x$, $6y$ y $8z$:\n- Múltiplos de 4: 4, 8, 12, 16, 20, 24, 28...\n- Múltiplos de 6: 6, 12, 18, 24, 30...\n- Múltiplos de 8: 8, 16, 24, 32...\n\nEl primer número (el menor) en el que las tres listas coinciden es el **24**. Por lo tanto, el MCM de los coeficientes es 24.\n\nOtra forma más rápida es descomponer los números en factores primos ($4 = 2^2$, $6 = 2 \\cdot 3$, $8 = 2^3$) y tomar todos los factores distintos con su mayor exponente ($2^3 \\cdot 3 = 8 \\cdot 3 = 24$).",
    "MAT.ALG.MCM_ALGEBRAICO.PARTE_LITERAL_MONOMIOS": "La construcción de la parte literal del MCM requiere ser generoso, al contrario del MCD que era estricto.\n\n**Regla del MCM Literal:** Se toman TODAS las bases (letras) que aparezcan, ya sea que se repitan o no, y a cada una se le asigna el MAYOR exponente con el que aparezca.\n\nEjemplo: Tenemos $A = x^3 y^2$ y $B = x^2 y^4 z$.\n- **Paso 1 (Todas las letras):** ¿Qué letras existen en total? Tenemos $x$, $y$, y $z$. Tomamos las tres.\n- **Paso 2 (Mayor exponente):**\n  - Para $x$: Aparece como $x^3$ y $x^2$. El mayor es 3. Tomamos $x^3$.\n  - Para $y$: Aparece como $y^2$ y $y^4$. El mayor es 4. Tomamos $y^4$.\n  - Para $z$: Solo aparece como $z^1$. Tomamos $z^1$.\n\nResultado: El MCM es $x^3 y^4 z$. Fíjate cómo tanto A como B 'caben' perfectamente dentro de este resultado.",
    "MAT.ALG.MCM_ALGEBRAICO.MCM_MONOMIOS": "El MCM definitivo de un grupo de monomios se ensambla multiplicando el MCM de sus números y el MCM de sus letras.\n\n**Fórmula de ensamblaje:**\nMCM(Total) = MCM(Coeficientes) $\\cdot$ MCM(Parte Literal)\n\nTomemos un ejemplo: $12a^4 b$ y $18a^2 b^3 c^2$.\n\n1. **Coeficientes (12 y 18):** El menor múltiplo común entre 12 y 18 es **36** (ya que 36/12=3 y 36/18=2).\n2. **Letras (Todas):** Aparecen '$a$', '$b$', y '$c$'.\n3. **Exponentes mayores:** \n   - Para '$a$': entre 4 y 2, tomamos **4** ($a^4$).\n   - Para '$b$': entre 1 y 3, tomamos **3** ($b^3$).\n   - Para '$c$': solo está elevada a 2, tomamos **2** ($c^2$).\n\nJuntando todo: El MCM es **$36a^4 b^3 c^2$**. Este super-término es divisible exactamente tanto por $12a^4 b$ como por $18a^2 b^3 c^2$.",
    "MAT.ALG.MCM_ALGEBRAICO.FACTORIZACION_POLINOMIOS": "Para hallar el MCM de expresiones polinómicas complejas, el primer paso irrenunciable es **Factorizar cada polinomio completamente**. \n\nUna vez que tienes los polinomios expresados como multiplicaciones de paréntesis, aplicas la regla general del MCM: Tomas TODOS los factores distintos (comunes y no comunes), con su MAYOR exponente.\n\nEjemplo:\n- Polinomio 1: $x^2 - 1$. Factorizado es $(x-1)(x+1)$.\n- Polinomio 2: $x^2 - 2x + 1$. Factorizado es $(x-1)^2$.\n\nAplicamos la regla del MCM:\n1. **Todos los factores:** Aparecen los paréntesis $(x-1)$ y $(x+1)$. Debemos incluirlos ambos.\n2. **Mayor exponente:** \n   - El $(x-1)$ aparece elevado a 1 en P1 y elevado a 2 en P2. Tomamos la versión más grande: $(x-1)^2$.\n   - El $(x+1)$ solo aparece elevado a 1. Lo tomamos tal cual.\n\nEl MCM es **$(x-1)^2(x+1)$**. Dominar esto es vital para sumar fracciones algebraicas.",
    "MAT.ALG.MCM_ALGEBRAICO.DENOMINADOR_COMUN": "La utilidad principal del MCM en el álgebra no es un mero ejercicio teórico, sino su aplicación directa como **Mínimo Común Denominador (MCDn)** al sumar o restar fracciones algebraicas.\n\nCuando tienes fracciones con denominadores distintos, no puedes sumarlas directamente. Debes 'amplificarlas' para que tengan el mismo denominador. ¿Y cuál es el mejor denominador posible? ¡El MCM de todos los denominadores originales!\n\nPor ejemplo, para sumar $\\frac{1}{x} + \\frac{1}{x^2}$:\n1. Calculas el MCM de los denominadores ($x$ y $x^2$). El MCM es $x^2$.\n2. Amplificas la primera fracción para que su denominador sea $x^2$ (multiplicando arriba y abajo por $x$). Queda $\\frac{x}{x^2}$.\n3. La segunda fracción ya tiene $x^2$, así que queda igual: $\\frac{1}{x^2}$.\n4. Ahora que tienen el mismo denominador, las sumas directamente: $\\frac{x + 1}{x^2}$.\n\nSin el MCM, la suma de fracciones algebraicas sería caótica y llevaría a expresiones gigantes e inmanejables.",

    # FRACCIONES BASE
    "MAT.ALG.FRACCIONES_BASE.DEFINICION_FRACCION": "Una fracción algebraica es simplemente la división indicada de dos polinomios. Funciona exactamente con las mismas reglas lógicas que una fracción numérica tradicional (como 3/4), pero en lugar de números, sus 'pisos' están ocupados por letras y expresiones algebraicas.\n\nTiene dos partes fundamentales:\n- **El Numerador (Piso superior):** Es la expresión algebraica que está siendo dividida. Representa la 'cantidad que tienes'.\n- **El Denominador (Piso inferior):** Es la expresión algebraica que divide. Representa 'en cuántas partes estás dividiendo'.\n\nPor ejemplo: $\\frac{P(x)}{Q(x)}$.\nEl hecho de que sean polinomios no cambia las leyes matemáticas subyacentes. Las fracciones algebraicas se simplifican, se amplifican, se suman, restan, multiplican y dividen siguiendo exactamente los mismos protocolos que usabas en la escuela primaria con fracciones numéricas.",
    "MAT.ALG.FRACCIONES_BASE.DENOMINADOR_NO_NULO": "En el universo de las matemáticas, hay un pecado capital que destruye la realidad misma: **dividir por cero**. Es una operación matemáticamente indefinida (no existe respuesta).\n\nDado que una fracción algebraica es una división disfrazada, el denominador (la parte de abajo) jamás puede ser igual a cero. Si el denominador llega a valer cero, la fracción 'explota' y deja de existir.\n\nPor ejemplo, en la fracción $\\frac{x+5}{x-2}$:\nSi la $x$ toma el valor mágico de $2$, el denominador se vuelve $(2 - 2) = 0$. La fracción quedaría $\\frac{7}{0}$, lo cual es un absurdo matemático. Por lo tanto, debes declarar inmediatamente que para esta fracción, **$x$ no puede ser 2** ($x \\neq 2$).\n\nA esto se le llama calcular el 'dominio' o las 'restricciones' de la fracción.",
    "MAT.ALG.FRACCIONES_BASE.RESTRICCIONES_DOMINIO": "Para encontrar todas las restricciones (valores prohibidos) de una fracción algebraica, debes realizar una 'interrogación' rigurosa a su denominador.\n\nEl procedimiento es sistemático:\n1. **Toma solo el denominador:** Ignora por completo el numerador (el numerador sí puede ser cero, no hay problema con eso).\n2. **Plantea una ecuación:** Iguala el denominador a cero. Ej: $x^2 - 9 = 0$.\n3. **Resuelve la ecuación:** Factoriza y despeja la incógnita. En este caso: $(x-3)(x+3) = 0$, por lo que $x=3$ y $x=-3$.\n4. **Declara las restricciones:** Los números que encontraste son la 'lista negra'. Debes indicar explícitamente que la fracción existe para todos los números reales **excepto** esos valores. Se anota: $x \\neq 3$ y $x \\neq -3$.\n\nSi no indicas las restricciones al simplificar, estás mintiendo matemáticamente, ya que la expresión original no era válida para esos números.",
    "MAT.ALG.FRACCIONES_BASE.SIGNO_FRACCION": "Toda fracción posee tres posiciones donde se puede colocar un signo (positivo o negativo):\n1. El signo del Numerador.\n2. El signo del Denominador.\n3. El signo Global (delante de la línea fraccionaria).\n\nLa regla de oro de los signos en fracciones dicta que **puedes cambiar dos signos simultáneamente** sin alterar el valor real de la fracción (porque menos por menos da más).\n\nPor ejemplo, la fracción $-\\frac{A}{B}$ es exactamente igual a $\\frac{-A}{B}$ (signo al numerador) y también es igual a $\\frac{A}{-B}$ (signo al denominador).\n\nSin embargo, por pura estética y convención matemática mundial, los matemáticos odian tener signos negativos en el denominador o colgando solos. El estándar de oro es **subir el signo negativo al numerador**, o **dejarlo justo al nivel de la línea de fracción**.",
    "MAT.ALG.FRACCIONES_BASE.SIGNO_NUMERADOR": "Cuando decides asignar un signo negativo global hacia el numerador (la parte de arriba), debes tener un cuidado extremo si el numerador es un polinomio completo (tiene sumas o restas).\n\nEl signo negativo no solo afecta al primer término que vea, sino que **afecta a TODOS los términos del numerador**, actuando exactamente como si hubiera un paréntesis invisible protegiéndolo.\n\nEjemplo de lo correcto y lo incorrecto:\nTienes la fracción: $-\\frac{x - 5}{y}$\n- **INCORRECTO:** $\\frac{-x - 5}{y}$ (El estudiante solo le cambió el signo a la 'x' y olvidó el -5).\n- **CORRECTO:** $\\frac{-(x - 5)}{y} = \\frac{-x + 5}{y}$ (El menos entró al paréntesis y cambió los signos de todo: la 'x' se volvió $-x$, y el $-5$ se volvió $+5$).\n\nEste es uno de los errores más mortales y comunes en las pruebas. ¡Usa siempre paréntesis mentales!",
    "MAT.ALG.FRACCIONES_BASE.SIGNO_DENOMINADOR": "Tener un signo negativo o múltiples signos negativos molestos en el denominador es visualmente confuso y propenso a generar errores en sumas y restas futuras.\n\nAfortunadamente, podemos 'limpiar' el denominador usando la regla de los signos: Puedes multiplicar tanto el numerador como el denominador por $-1$. Esto tiene el efecto mágico de invertir todos los signos de la fracción, manteniéndola matemáticamente equivalente.\n\nEjemplo: Tienes la fracción $\\frac{x - 2}{-y + 3}$. El denominador se ve horrible.\nSi multiplicas todo por $-1$ (cambias signos arriba y abajo):\n- Arriba: $(x - 2)$ se convierte en $(-x + 2)$ o $(2 - x)$.\n- Abajo: $(-y + 3)$ se convierte en $(y - 3)$.\n\nLa nueva fracción limpia es $\\frac{2 - x}{y - 3}$. ¡Mucho más elegante y fácil de trabajar!",
    "MAT.ALG.FRACCIONES_BASE.SIMPLIFICACION_MONOMIOS": "Simplificar una fracción compuesta solo por monomios (términos únicos sin sumas ni restas, ej: $\\frac{12x^3y}{8x^2y^2}$) es el proceso más directo. Se ataca en dos frentes simultáneos:\n\n1. **Frente Numérico (Coeficientes):** Trata los números grandes como una fracción básica de primaria. En $\\frac{12}{8}$, divides arriba y abajo por su MCD (que es 4), obteniendo $\\frac{3}{2}$.\n2. **Frente Literal (Letras):** Aplica la ley de exponentes para la división (se restan los exponentes de las bases iguales, conservando la base donde el exponente era mayor).\n   - Para las 'x': $\\frac{x^3}{x^2}$. Restas $3 - 2 = 1$. Queda una $x^1$ arriba.\n   - Para las 'y': $\\frac{y^1}{y^2}$. Restas $2 - 1 = 1$. Queda una $y^1$ abajo.\n\nEnsamblando el resultado final: $\\frac{3x}{2y}$. Es vital recordar que esto **solo** se puede hacer porque todo se está multiplicando (son factores puros).",
    "MAT.ALG.FRACCIONES_BASE.SIMPLIFICACION_FACTORIZACION": "El error más catastrófico en álgebra es tachar (simplificar) letras o números que están sumando o restando.\n\nSi tienes $\\frac{x^2 + 2x}{x}$, ¡ESTÁ PROHIBIDO tachar la 'x' de arriba con la de abajo!\n\n**Ley Universal de Simplificación:** SOLO puedes simplificar factores. Un factor es algo que está MULTIPLICANDO a todo lo demás. Los términos que suman o restan están blindados y no se pueden separar.\n\nPara poder simplificar, debes **Factorizar primero**. Transformar las sumas en multiplicaciones de paréntesis.\n- Paso 1: Toma el numerador $x^2 + 2x$ y extrae factor común 'x'. Queda: $x(x + 2)$.\n- Paso 2: Reescribe la fracción: $\\frac{x(x + 2)}{x}$.\n- Paso 3: ¡Ahora sí! Como la 'x' está multiplicando a todo el paréntesis, puedes tacharla con la 'x' que está multiplicando sola abajo.\n- Resultado final: $x + 2$.\n\nSi no hay multiplicaciones puras, no puedes simplificar.",
    "MAT.ALG.FRACCIONES_BASE.FACTORES_OPUESTOS": "En tu camino algebraico te encontrarás con una trampa visual muy común: los factores opuestos. Tienes un paréntesis arriba como $(a - b)$ y abajo tienes $(b - a)$.\n\nSe ven casi idénticos, pero están al revés debido a la resta. ¡No puedes tacharlos directamente! $(5 - 3)$ no es lo mismo que $(3 - 5)$.\n\nSin embargo, puedes aplicar un truco maestro de factorización:\n**Extracción del factor negativo (-1).**\n\nSi sacas un signo negativo fuera de un paréntesis, los signos internos se invierten.\n- Tienes $(b - a)$.\n- Sacas un $-1$: $-( -b + a )$.\n- Lo reordenas para que se vea bonito: $-(a - b)$.\n\n¡Magia! Ahora tienes el mismo paréntesis que arriba, pero con un signo menos adelante. Si tenías $\\frac{a - b}{b - a}$, esto se convierte en $\\frac{a - b}{-(a - b)}$. Ahora puedes tachar los paréntesis idénticos. El resultado no es 1, ¡es **$-1$**!",
    "MAT.ALG.FRACCIONES_BASE.ERROR_RESTRICCIONES": "Un error conceptual profundo es creer que al simplificar una fracción, sus restricciones originales desaparecen o ya no importan.\n\nAnaliza este caso: $\\frac{x^2 - 4}{x - 2}$.\n- Restricción inicial mirando el denominador: $x - 2 = 0 \\rightarrow x \\neq 2$. (Si x es 2, el universo explota).\n- Ahora simplificamos. Factorizamos arriba como diferencia de cuadrados: $\\frac{(x-2)(x+2)}{x-2}$.\n- Tachamos los $(x-2)$. El resultado es bellísimo y simple: $x + 2$.\n\n¡Pero cuidado! Aunque el resultado $x + 2$ no tenga denominador aparente, **hereda genéticamente la restricción original**. La respuesta matemáticamente rigurosa es: 'El resultado es $x+2$, pero con la condición de que $x \\neq 2$'.\n\nSi olvidas arrastrar las restricciones, estás diciendo que la función existe en $x=2$, lo cual contradice el problema original."
}

def process_files(file_dict):
    success = 0
    pattern = re.compile(r'(explicacion:\s*\|)(.*?)(?=\nprocedimiento:)', re.DOTALL)
    for sid, new_expl in file_dict.items():
        # Reconstruct filename
        filename = f"docs/conocimiento/contenido/{sid.lower().replace('.', '-').replace('_', '-')}.yaml"
        if not os.path.exists(filename):
            print(f"Error: {filename} no encontrado.")
            continue

        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()

        # Format the new explanation correctly with 2 spaces indent
        formatted_expl = "\n  " + "\n  ".join(new_expl.strip().split("\n")) + "\n"

        # Replace
        new_content, count = pattern.subn(lambda m: m.group(1) + formatted_expl, content)

        if count > 0:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(new_content)
            success += 1
            print(f"Actualizado: {filename}")
        else:
            print(f"Fallo regex en: {filename}")
    return success

if __name__ == "__main__":
    s = process_files(new_explanations)
    print(f"Total actualizados Tanda 1 y 2: {s}/{len(new_explanations)}")
